src/emulator/gxm/include/gxm/state.h
src/emulator/modules/SceGxm/src/SceGxm.cpp
src/emulator/modules/SceGxm/src/gxm.h

This commit adds:
- sceGxmSetCullMode implementation
- sceGxmTextureSetData implementation.
- sceGxmTextureSetWidth implementation.
- sceGxmTextureSetHeight implementation.
- Support for multitexturing (TEXUNIT1 and biggers support for fragment shaders)
- Support for almost all SceGxm primitives (except SCE_GXM_PRIMITIVE_TRIANGLE_EDGES)

Added several sceGxm implementations.

---

src/emulator/vpk.cpp

Restore cstring is needed for memset reference.

Fix UNIX Build

---

.gitmodules
src/emulator/audio/CMakeLists.txt
src/emulator/audio/include/audio/functions.h
src/emulator/audio/include/audio/state.h
src/emulator/audio/src/audio.cpp
src/emulator/cpu/src/cpu.cpp
src/emulator/host/CMakeLists.txt
src/emulator/host/src/host.cpp
src/emulator/io/CMakeLists.txt
src/emulator/io/src/io.cpp
src/emulator/load_self.cpp
src/emulator/main.cpp
src/emulator/mem/CMakeLists.txt
src/emulator/module/CMakeLists.txt
src/emulator/module/src/module.cpp
src/emulator/modules/SceGxm/src/SceGxm.cpp
src/emulator/nids/CMakeLists.txt
src/emulator/relocation.cpp
src/emulator/util/CMakeLists.txt
src/emulator/util/include/util/log.h
src/emulator/util/src/util.cpp
src/external/CMakeLists.txt

This improves logging using [spdlog](https://github.com/gabime/spdlog) and other than console output, it adds logging to a file (`vita3k.log` in the path of the executable) and Visual Studio's Output tab.
Existing logging code is ported to the new system.
**Copy from main commit:**
Defines `LOG_*` macros for different log levels, where * is either TRACE, DEBUG, INFO, WARN, ERROR or CRITICAL.
Additionally, it defines `LOG_*_IF` (same log levels), for conditional logging, with the first argument being the condition.
Resolves #34.
Console:
Similar output for the VS Output tab.
File output is the same (without color obviously).
As you can see I log the **time**, **log level** (also denoted by the color) and the **calling function name**.
---
Non-windows code path _should_ work, but is …

Better Logging (to file, console, VS Output)

---

.gitmodules
src/emulator/audio/CMakeLists.txt
src/emulator/audio/include/audio/functions.h
src/emulator/audio/include/audio/state.h
src/emulator/audio/src/audio.cpp
src/emulator/cpu/src/cpu.cpp
src/emulator/host/CMakeLists.txt
src/emulator/host/src/host.cpp
src/emulator/io/CMakeLists.txt
src/emulator/io/src/io.cpp
src/emulator/load_self.cpp
src/emulator/main.cpp
src/emulator/mem/CMakeLists.txt
src/emulator/module/CMakeLists.txt
src/emulator/module/src/module.cpp
src/emulator/modules/SceGxm/src/SceGxm.cpp
src/emulator/nids/CMakeLists.txt
src/emulator/relocation.cpp
src/emulator/util/CMakeLists.txt
src/emulator/util/include/util/log.h
src/emulator/util/src/util.cpp
src/external/CMakeLists.txt

*This is a duplicate of #36, it's re-opened because the first one was merged by mistake.*
This improves logging using [spdlog](https://github.com/gabime/spdlog) and other than console output, it adds logging to a file (`vita3k.log` in the path of the executable) and Visual Studio's Output tab.
Existing logging code is ported to the new system.
**Copy from main commit:**
Defines `LOG_*` macros for different log levels, where * is either TRACE, DEBUG, INFO, WARN, ERROR or CRITICAL.
Additionally, it defines `LOG_*_IF` (same log levels), for conditional logging, with the first argument being the condition.
Resolves #34.
Console:
Similar output for the VS Output tab.
File output is the same (without color obviously).
As you can see I log the **time**, **log level** (also denoted by the color) …

Better Logging (to file, console, VS Output) 

---

src/emulator/mem/src/mem.cpp

The last argument being `nullptr` was causing the function to fail.

[mem] Fix VirtualProtect call

---

src/emulator/host/include/host/rtc.h
src/emulator/modules/SceProcessmgr/SceProcessmgr.cpp

Allows **Vita Doom** to go in-game (still not playable because of other issues).
The `tzAddr` argument is unused, not even PPSSPP implements it apparently.

[sceKernel] Implement sceKernelLibcGettimeofday

---

src/emulator/modules/ScePower/ScePower.cpp

Probably doesn't fix any games, but this should at least help clean up the log of useless stuff. I did notice that the homebrew "FlppyBird" now correctly draws the battery icon instead of complaining in the log about an unimplemented function.
Before: 
After:
Again, nothing major here...

Stub some ScePower functions

---

src/emulator/gxm/include/gxm/functions.h
src/emulator/gxm/include/gxm/types.h
src/emulator/gxm/src/gxm.cpp
src/emulator/modules/SceGxm/SceGxm.cpp

When VitaGL creates fragment programs (`SceGxmFragmentProgram`), it passes fragment rather than vertex `SceGxmProgram`. Because of this, we can no longer maintain a logical connection between fragment and vertex programs, and store vertex program information in the fragment program structure.
As a result, the OpenGL program is only linkable (and able to be made current) when fragment and vertex shaders have _both_ been set, rather than just when the current fragment program is set.
Because of that, we can't rely on the current OpenGL program being the correct one when GXM uniforms are set. Instead we store uniform values in uniform buffers, and pass the values to OpenGL at the point of draw.
There is scope for caching and optimisation, but I think this is good enough for now.

More work on shaders and uniform buffers

---

src/emulator/gxm/include/gxm/functions.h
src/emulator/gxm/src/gxm.cpp
src/emulator/modules/SceGxm/SceGxm.cpp

Fixes VitaDoom (**doom.wad**, **doom2.wad**, and some other fan .wads work).
Runs at 35 fps for me, pretty playable. Only other issue at the moment is garbled audio.
From commit message:
- Extend current support of `SCE_GXM_TEXTURE_FORMAT_P8_ABGR` to the 15 more palleted formats.
- Only tested ones are `SCE_GXM_TEXTURE_FORMAT_P8_ABGR` and `SCE_GXM_TEXTURE_FORMAT_P8_1BGR`.
- A warning message is generated if one of the untested ones is used, just to be sure.
Can be removed in the future when more of them are tested.
---
I included a refactoring commit (VS does this automatically on Save for me and it was too anoying trying to separate the lines I wanted) so go [here](https://github.com/Vita3K/Vita3K/pull/105/commits/d754d9ce1a25327ab613640e0e8cd61a8d706608) to review main commit only, for …

Support all 16 paletted texture formats (fixes VitaDoom)

---

src/emulator/modules/SceNet/SceNet.cpp

sceNet returns SCE_NET_* errors instead of SCE_NET_ERROR_* (the second are probably kernel errors returned internally by called syscalls to perform net operations).

[sceNet] Using correct errorcode ranges.

---

src/emulator/modules/SceGxm/SceGxm.cpp

This fixes graphics in some homebrews (Happy Land for example) and stops homebrews from spamming on console for unimplemented mag/min filters translations.

Setting min/mag filters to linear filtering on init.

---

src/emulator/io/CMakeLists.txt
src/emulator/io/include/io/VitaPartition.def
src/emulator/io/include/io/io.h
src/emulator/io/src/io.cpp

- `VitaPartition` enum class
- Translation function instead of string compares
- Joined ux0/uma0 code paths
- Run clang-format
~~Just io.cpp changed.~~

IO refactoring

---

src/emulator/main.cpp
src/emulator/modules/SceGxm/SceGxm.cpp

This removes the (apparently) useless display thread spawned on main.cpp and properly renames the one created via sceGxmInitialize to sceGxmDisplayQueue like it would be on real hw.

[threads] Refactoring "display" threads.

---

src/emulator/gxm/src/gxm.cpp
src/emulator/modules/SceGxm/SceGxm.cpp

With this Flood It! works correctly.
What this PR does:
- Fixes some bad behaviours in set_uniform adding support for "float" uniforms.
- Fixes attrib location leak. Before we were using only glVertexAttribPointer with index 0,4,8,12,...; now we use 0,1,2,3,4... allowing us to use up to 16 vertex attributes like it should be.
This allows Flood It! to correctly work:

 [gxm] Attrib location and set_uniform fixes. 

---

src/emulator/gxm/src/gxm.cpp
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/shaders/7ab03ae7c55b085887bf61bc7dcc7bd403f36fd1be9b8d74783363a761a52aa9.vert

Change was actually fixing Flood It! but breaking more homebrews.
We should probably refactor the whole way uniforms work btw.
I left the added glUniform1fv code.

Reverting changes to set_uniform.

---

src/emulator/modules/SceGxm/SceGxm.cpp

This fixes ugly borders in some homebrews like Happy Land and HCL for textures and fixes Flood It! main menu background being "blurred".

[gxm] Using no filter as default for textures.

---

src/emulator/module/include/module/lay_out_args.h

emulator: Add missing include `tuple`

---

.travis.yml

split osx & linux parts and add linux specific actions
travis still use trusty and it's too old versions
custom parts:
- use gcc7 and g++7 of ubuntu-toolchain-r/test
- use unicorn engine and libsdl2 of archlinux
project requires unicorn-engine and >= libsdl 2.0.7
but could not find deb
- use static built cmake 3.10.3
this patch only test build process in linux system.

travis: Apply matrix for linux CI

---

src/emulator/kernel/include/kernel/thread_functions.h
src/emulator/kernel/src/thread.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp

Some games use status value as a way to call functions from the module

Fix status on loading modules

---

src/emulator/gxm/src/gxm.cpp

Many commercial games (and a few homebrew) use at least _some_ shaders with structs, which previously errored when compiling the OpenGL program, since we weren't parsing and generating the stubs correctly.
This should be fixed now.

Shader struct support

---

src/emulator/io/src/io.cpp

- Bug in open_file made so that the `if (!file)` check always failed cause file was declared two times.
- Bug in open_dir made so that emulator was unable to open directories in ux0 partition.

[io] Fixed two bugs causing io to fail when it shouldn't.

---

src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/functions.h
src/emulator/gui/include/gui/state.h
src/emulator/gui/src/ui_common_dialog.cpp
src/emulator/gui/src/ui_condvars_dialog.cpp
src/emulator/gui/src/ui_main.cpp
src/emulator/gui/src/ui_main_menubar.cpp
src/emulator/gxm/src/gxm.cpp
src/emulator/host/include/host/functions.h
src/emulator/host/src/app.cpp
src/emulator/host/src/host.cpp
src/emulator/io/src/io.cpp
src/emulator/kernel/include/kernel/state.h
src/emulator/kernel/include/kernel/thread/sync_primitives.h
src/emulator/kernel/include/kernel/types.h
src/emulator/kernel/src/load_self.cpp
src/emulator/kernel/src/thread/sync_primitives.cpp
src/emulator/kernel/src/thread/thread.cpp
src/emulator/main.cpp
src/emulator/module/tests/arg_layout_tests.cpp
src/emulator/modules/SceAppUtil/SceAppUtil.cpp
src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp
src/emulator/modules/SceNetCtl/SceNetCtl.cpp
src/emulator/modules/SceSysmem/SceSysmem.cpp

Also refactoring of mutex/semaphore code:
- Split some mutex functions to _impl functions because we need to run them from condvar code
- Change naming to have sync object name in the front
- Helper functions to reduce code duplication.
- Correct some returned erorrs
- Change `WaitingThreadData` to accomodate all current sync objects (and couple of future ones)
- Sync logging improvements
and a few other random fixes.

kernel: (Lightweight) Condition Variables

---

src/emulator/modules/SceNet/SceNet.cpp

Can't say why but using the correct values (SCE_NET_* errors) causes vitaQuake to softlock.
PSVita returns on real hardware SCE_NET_* errors and not SCE_NET_ERROR_* errors with those functions, source: https://github.com/Rinnegatamante/vitaQuakeIII/commit/f5db2245386513888a0bb1700c6dd4ed4daed2ce
Further investigations are required, for the moment i reverted errors to SCE_NET_ERROR_* and left a NOTE.

[net] Fixed a regression in vitaQuake

---

src/emulator/modules/SceSysmem/SceSysmem.cpp

Fixes crashes in vitaGL based homebrews running this specific code: https://github.com/Rinnegatamante/vitaGL/blob/master/source/vitaGL.c#L198-L201

[mem] Dividing the available pool equally.

---

src/emulator/cpu/src/cpu.cpp
src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/imgui_impl.h
src/emulator/gui/src/imgui_impl.cpp
src/emulator/gui/src/ui_eventflags_dialog.cpp
src/emulator/gui/src/ui_main.cpp
src/emulator/gui/src/ui_mutexes_dialog.cpp
src/emulator/gxm/src/gxm.cpp
src/emulator/host/include/host/app.h
src/emulator/host/include/host/functions.h
src/emulator/host/include/host/state.h
src/emulator/host/src/app.cpp
src/emulator/host/src/host.cpp
src/emulator/io/include/io/io.h
src/emulator/io/src/io.cpp
src/emulator/kernel/src/load_self.cpp
src/emulator/main.cpp
src/emulator/mem/src/mem.cpp
src/emulator/modules/SceCommonDialog/SceCommonDialog.cpp
src/emulator/modules/SceDisplay/SceDisplayUser.cpp
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp
src/emulator/modules/SceLibc/SceLibc.cpp
src/emulator/util/include/util/log.h

Some needed `main()`, `host` and `imgui` impl. refactoring and a few minor fixes.
Resolves #255.
Please use `log_hex()` to format hex strings from now on, with `{}` as the format string. It outputs unsigned hex strings in the format of `0xD34DB33F`, with `0` padding according to size of input type.
This is so that we finally have a standardized way to print them.

Μain refactoring & some random fixes

---

src/emulator/host/src/host.cpp

Games run on a background thread, so if vsync is disabled, the main thread spins like crazy and burns CPU time on systems with few cores.

Enable vsync for main OpenGL context.

---

src/emulator/cpu/include/cpu/functions.h
src/emulator/cpu/src/cpu.cpp
src/emulator/host/include/host/functions.h
src/emulator/host/include/host/import_fn.h
src/emulator/host/src/app.cpp
src/emulator/host/src/host.cpp
src/emulator/kernel/include/kernel/thread/thread_functions.h
src/emulator/kernel/src/thread/thread.cpp
src/emulator/module/include/module/bridge.h
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/modules/SceKernelThreadMgr/SceThreadmgrCoredumpTime.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp
src/emulator/modules/SceNetCtl/SceNetCtl.cpp

Pass `CPUState` through via `call_svc`, `call_import` rather than lock a mutex to look it up.

Eliminate lock per import call

---

src/emulator/modules/SceSysmem/SceSysmem.cpp

The parameter `SceKernelAllocMemBlockOpt` can be not null when used in `sceKernelAllocMemBlock`, see https://github.com/joshaxey/textquest/blob/3891bcb1cc13c27d599efe18aa34ba49ad62f000/src/graphics.c#L53-L61
This change allows the homebrew TextQuest to go further.
**Before**
```
SceUID export_sceKernelAllocMemBlock(HostState&, SceUID, const char*, const char*, SceKernelMemBlockType, int, emu::SceKernelAllocMemBlockOpt*): Assertion `optp == nullptr' failed.
```
**After**

sceKernelAllocMemBlock: remove assert for SceKernelAllocMemBlockOpt

---

src/emulator/gxm/include/gxm/functions.h
src/emulator/gxm/include/gxm/types.h
src/emulator/gxm/src/gxp.cpp
src/emulator/host/src/host.cpp
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/renderer/include/renderer/types.h
src/emulator/renderer/src/compile_program.cpp
src/emulator/renderer/src/sync_state.cpp
src/emulator/renderer/src/uniforms.cpp
src/emulator/shadergen/src/shadergen_spirv.cpp

Most notable are the SPIR-V/shader generation improvements.
As an example, a shader from the game "Alone With You" is generated like so (irrelevant stuff omitted):
```glsl
uniform mat4 gm_Matrices[5];
in vec4 input_aPosition;
in vec4 input_aColour;
in vec4 input_aTexCoord;
out vec4 spv_oPosition;
out vec4 spv_oColor0;
out vec2 spv_oTexcoord0;
out vec2 spv_oTexcoord1;
out vec2 spv_oPsize;
```
whereas previously, like so:
```glsl
struct input
{
vec4 aPosition;
vec4 aColour;
vec4 aTexCoord;
};
uniform vec4 gm_Matrices[20];
in input _input;
```
So you can see 3 improvements there:
1) **Vertex outputs** (all `spv_o*` declarations that were not previously there)
2) **Flattening of vertex input structs**
This needs to happen, previous method was wrong, the shader didn't compile. I didn't …

Shader generation, GXM and renderer improvements

---

src/emulator/gxm/include/gxm/types.h
src/emulator/io/include/io/state.h
src/emulator/io/src/io.cpp
src/emulator/kernel/src/thread/sync_primitives.cpp
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp
src/emulator/renderer/src/sync_state.cpp
src/emulator/shadergen/src/shadergen_spirv.cpp

- shadergen: Emit fragment output
- With hardcoded type and size (vec4)
- Add some structural comments
- Rename param_struct_t -> StructDeclContext
- shadergen: Write static color to fragment shader color output
- Like the GLSL transpiler used to, for debugging
- renderer: Ensure viewport dimensions are non-negative
- kernel/threadmgr: Stub 'callback check' functions
- io: Fix TTY for for read/write file descriptors 
- TTY fd's can be both read and write, previous code assumed either
one or the other.
- Persona 4's TTY output is visible with this.
- io: Don't print null terminator in TTY output
- io: Don't log twice if printing to TTY
- gxm: Don't hardcode uniform buffer container index

Shader gen, kernel, io and renderer improvements

---

CMakeLists.txt
src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp

- Windows build:
- Use multiple cores
- Disable C++17 deprecation warnings that are slowing down AppVeyor
- Builds 3-4 times faster on my quad-core CPU.
- Update ext-boost to include Boost.Optional
- A threadmgr race condition fix

Speed up Windows build & build hotfix

---

src/emulator/host/include/host/config.h
src/emulator/host/src/config.cpp
src/emulator/kernel/include/kernel/state.h
src/emulator/kernel/src/load_self.cpp
src/emulator/kernel/src/relocation.cpp
src/emulator/main.cpp
src/emulator/modules/SceSysmodule/SceSysmodule.cpp

Help message shows the following for the option:
```
-m [ --lle-modules ] arg         Load given (decrypted) OS modules from disk.
Separate by commas to specify multiple
modules (no spaces). Full path and extension
should not be included, the following are
assumed: vs0:sys/external/<name>.suprx
Example: --lle-modules libscemp4,libngs
```
See commits for the rest of the fixes.

LLE support for dumped modules

---

src/emulator/host/include/host/state.h
src/emulator/main.cpp
src/emulator/modules/SceDisplay/SceDisplay.cpp

Allows graphics debuggers like RenderDoc to pick up OpenGL calls from GXM emulation.
Graphics debugger support is still not perfect, since with this approach they also pick up OpenGL calls from the host (main) thread, which messes up captures.
For this to work perfectly we'd need to do all rendering from a single thread, which is not trivial to do.

Support syncing of host/guest rendering (for RenderDoc)

---

src/emulator/host/src/config.cpp

Addresses #342 by logging all current config settings during `config::init`.
Not sure if there's a better way to work with the lle_modules vector, I may have missed an existing utility somewhere to combine them into a comma-separated string.
Also not totally sure if INFO is the right logging level, I could see DEBUG being a good fit as well.
Thanks in advance for the review!
Sample log:
```
[20:30:46.738] |I| [config::init]:  input-installed-id: CRFT00001
[20:30:46.740] |I| [config::init]:  lle-modules: test,test,test,test
[20:30:46.741] |I| [config::init]:  log-level: 2
[20:30:46.741] |I| [config::init]:  log-imports: true
[20:30:46.742] |I| [config::init]:  log-exports: true
[20:30:46.742] |I| [config::init]:  log-active-shaders: true
[20:30:46.742] |I| [config::init]:  log-uniforms: …
```

host/config: Log config settings during init

---

src/emulator/renderer/src/texture_cache.cpp

Should speed up texture hashing by pretty much the amount of cores in the system.
*Note:* "Hashing" is a pretty loose term, since we're still just summing.

renderer/optimization: Multithreaded texture hashing

---

src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/functions.h
src/emulator/gui/include/gui/state.h
src/emulator/gui/src/ui_controls_dialog.cpp
src/emulator/gui/src/ui_main.cpp
src/emulator/gui/src/ui_main_menubar.cpp

Added an entry to MainMenuBar called "Help" with one entry "Controls", which simply displays the default key mappings.

gui: Provide controls information to the user

---

.travis.yml
.travis/linux/build.sh
.travis/linux/deploy.sh

Fixing the upload for linux again. This time it should work (method was borrowed from citra, copying the binary instead of try to change the permissions of the binary folder)

ci: Fix broken upload for linux

---

src/emulator/host/src/app.cpp
src/emulator/host/src/host.cpp

Fix #360 and display the title in one line in the log

gui/host: Replace EOL characters in game titles by spaces

---

src/emulator/ctrl/include/ctrl/state.h
src/emulator/main.cpp
src/emulator/modules/SceCtrl/SceCtrl.cpp

Added joystick rumbling support.
Tested with an XInput joystick with vitaQuake (to test it, you just have to wait till player gets damaged on demo playback).
Probably more testing is required with different kind of joysticks to see if the behaviour is correct.
Handles https://github.com/Vita3K/Vita3K/issues/33

Initial sceCtrlSetActuator implementation.

---

src/emulator/ctrl/include/ctrl/state.h
src/emulator/modules/SceCtrl/SceCtrl.cpp

Before this PR, controllers where not paired to a sceCtrl port resulting in weird behaviours when multiple joysticks where plugged in (or if an application using multiple controllers were used).
Now Vita3K will bind only max 4 controllers and pair them to a sceCtrl port so that a single controller will give input for a single port like it works on retail PSTV.

Properly implementing multiple controllers support.

---

src/emulator/modules/SceDisplay/SceDisplay.cpp
src/emulator/threads/include/threads/queue.h

Should fix #362 (with the changes at lines 112-114)
@VelocityRa Do you remember why the preprocessors were added in commit https://github.com/Vita3K/Vita3K/pull/146/commits/44ce9e2e98d819e64c70f024c698d75cee7adae0 (instead of deleting the lines)? Was it because you didn't want to change the behavior on other OS and/or you were only able to test on Windows?

display/queue: Remove [m]lock.release() for all OS

---

src/emulator/modules/SceSysmem/SceSysmem.cpp

(#368) returns true, so this should too.
[Here's ](https://github.com/caghandemir/vitaControllerTest) a test program if you want to test this behavior on real hardware.

Implement sceKernelIsPSVitaTV

---

src/emulator/CMakeLists.txt
src/external/CMakeLists.txt

Fix build issue on yaml-cpp after re generate cmake build, caused by issue on gslang with it change variable "CMAKE_INSTALL_PREFIX" with set force "install", causing broken yaml-cpp.
More info on gslang issue here https://github.com/KhronosGroup/glslang/issues/1015
For more understund how it works now with my fix, on first generate gslang set "install" value on "CMAKE_INSTALL_PREFIX" and after my code look if value is by default, and if not re set it with default value forced for can works after all time.
Separate .lib and .exp on lib folder bin folder show only .exe and bin file.
Update yaml-cpp submodule on last master

Fix buid for yaml-cpp on cmake

---

.gitmodules
src/emulator/cpu/src/cpu.cpp
src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/functions.h
src/emulator/gui/include/gui/state.h
src/emulator/gui/src/ui_allocations_dialog.cpp
src/emulator/gui/src/ui_main.cpp
src/emulator/gui/src/ui_main_menubar.cpp
src/emulator/mem/include/mem/mem.h
src/emulator/mem/src/mem.cpp
src/external/CMakeLists.txt

This pull request adds an allocation viewer to the debug menu of Vita3K. The allocation viewer allows a debugger to do a few things:
- View the allocation's generation and name.
- Tell the size of the allocation in pages and kilobytes.
- View where allocation starts and ends (as a hexadecimal address).
- View and edit the contents of the allocation using imgui_club's memory editor.

Added an allocation viewer

---

src/emulator/gui/include/gui/state.h

This merge prevents a crash when opening the memory allocation viewer. The code that draws the viewer relies on `memory_editor` being null when it should not be drawn, but it was not explicitly set to null.
This fix ensures that the memory editor is only drawn when it has been opened which prevents the crash.
Thanks to waterflame for pointing this out.

Allocation viewer crash fix

---

src/emulator/io/include/io/io.h
src/emulator/io/src/io.cpp

For example, the homebrew [pfba](http://vitadb.rinnegatamante.it/#/info/20) tries to create the directory `ux0:/data/pfba/roms` but failed because the directory `ux0:/data/pfba` does not exist.
```
[21:32:43.040] |T| [create_dir]:  sceIoMkdir: Removing dir ux0:/data/pfba/roms (ux0:/data/pfba/roms)
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
what():  filesystem error: cannot create directory: No such file or directory [/home/scribam/.local/share/Vita3K/Vita3K/ux0/data/pfba/roms]
```

io: Handle error cases when calling create_dir

---

gen-windows.bat
src/emulator/mem/CMakeLists.txt
src/emulator/net/CMakeLists.txt
src/emulator/nids/CMakeLists.txt
src/external/CMakeLists.txt

- **Commit "cmake: Cleanup link libraries"**
Fix the warning below (was it a typo in `src/emulator/nids/CMakeLists.txt`?) and remove unnecessary libraries link.
- **Commit "cmake: Do not build SPVRemapper"**
We don't use it so no reason to build it :slightly_smiling_face: 
- **Commit "cmake/ci: Generate "Release" Visual Studio solution only"**
Currently, on AppVeyor, we generate a solution file for the following four configurations but we only use "Release".
With this commit, one configuration will be used, the one defined in the configuration node of the `appveyor.yml`.

Cmake tweaks

---

src/emulator/gui/src/imgui_impl.cpp
src/emulator/io/src/io.cpp
src/emulator/kernel/src/load_self.cpp
src/emulator/util/include/util/fs.h

On macOS, util/fs.h doesn't have a definition of `fs::create_directory()` with two parameters. This causes a build error in io.cpp:
This pull request fixes this by changing util/fs.h to use boost/filesystem.hpp (which has both parameters available).

util: filesystem fix for macOS

---

src/emulator/modules/SceLibKernel/SceLibKernel.cpp

Signed-off-by: Francois Berder <fberder@outlook.fr>

modules: SceLibKernel: Fix memory leak if read_file fails in load_module

---

src/emulator/host/src/host.cpp
src/emulator/io/include/io/functions.h
src/emulator/io/src/io.cpp
src/emulator/modules/SceGxm/SceGxm.cpp
src/emulator/renderer/include/renderer/functions.h
src/emulator/renderer/src/functions.h
src/emulator/renderer/src/load_shaders.cpp
src/emulator/renderer/src/renderer.cpp

Shaders are now dumped in the main executable's directory, in `/shaderlog/<titleID>`.
Fixes #228.
Edit: Also, a reminder, these shaders are **not** read, just dumped, so don't modify them in-place. If you want to do that, move the ones you need to `/shaders` first.

renderer/io: Dump shaders to separate game specific directory

---

.travis/linux/deploy.sh

Travis buildscript for Linux keep failing deploying but we don't have enough info about why this happens.

travis: Logging git push execution

---

src/emulator/modules/SceTouch/SceTouch.cpp

This fixes touch coordinates for the SDL2 port ([SDL_vitatouch.c](https://github.com/rsn8887/SDL-Vita/blob/master/src/video/vita/SDL_vitatouch.c#L56)).

SceTouch: Implement sceTouchGetPanelInfo

---

src/emulator/host/include/host/config.h
src/emulator/host/src/app.cpp
src/emulator/host/src/config.cpp
src/emulator/util/include/util/log.h
src/emulator/util/include/util/string_utils.h
src/emulator/util/src/util.cpp

This PR fixes #402 
- it creates a copy of the log file with the game's name and title id as the file's name.
- the second log file sink is only added after the game has launched which omits the first few config system lines from logging
- it outputs to a new directory called `logs`
- added a config option to enable this from the command line using -A or --archive-log

util/config: config option to duplicate log with title id/game name as log name

---

src/emulator/ctrl/include/ctrl/state.h
src/emulator/modules/SceCtrl/SceCtrl.cpp
src/emulator/modules/SceTouch/SceTouch.cpp

- Moved input_mode and input_mode_ext to CtrlState.
- Made *Ext funcs in sceCtrl actually use input_mode_ext and not input_mode.
- Replaced some asserts in sceTouch with error handling.
- Implemented sceTouchSetSamplingState/sceTouchGetSamplingState.

input: sceCtrl and sceTouch improvements.

---

src/emulator/renderer/src/uniforms.cpp

Fix the biggest, most awful, most tragic event in Release history caused by a single evil commit I made: be144d77bc8510697501c29228dc1f477b4fca50

renderer/uniforms: Multiply vector index with component count

---

src/emulator/gxm/include/gxm/types.h
src/emulator/gxm/src/gxp.cpp
src/emulator/renderer/src/uniforms.cpp
src/emulator/shader/include/shader/usse_translator.h
src/emulator/shader/include/shader/usse_translator_types.h
src/emulator/shader/src/spirv_recompiler.cpp
src/emulator/shader/src/usse_translator.cpp

- Fix Flood It compile error: error C7011: implicit cast from "vec4" to "vec2", and some bugs in optimization and hacks
- A part of TODO: Correct secondary attribute (SECATTR) generation
- Add support for generating and access array types
- Implement VMIN, VMAX instructions
- Remove unroll
The reason for i say a part is: this doesn't not correct sampler SA offset. I don't know how they are generated yet.

Fixes and miscs

---

src/emulator/gui/src/allocations_dialog.cpp
src/emulator/gui/src/disassembly_dialog.cpp
src/emulator/gui/src/threads_dialog.cpp

I found some gui issues while debugging. This PR fixes the following bugs:
- The alignment for the stack pointer value on the thread screen was fixed.
Before:
After:
- Registers r13-r15 were hidden from the thread viewer screen. They're aliases for pc, lr and sp which are already shown anyway.
- Headers were added to certain files that were missing them.

gui: Fix Threading Information

---

src/emulator/glutil/src/shader.cpp

Some drivers seem to like to return a GL_INFO_LOG_LENGTH of 1 when compilation and linking succeeds. This causes Vita3K to crash when it really doesn't need to. The solution would be to check the compile/link status instead of the log length.

glutil: Fix shaders on platforms where GL_INFOLOG_LENGTH is 1

---

gen-linux.sh

This fixes the build on gentoo and specifically this issue https://github.com/Vita3K/Vita3K/issues/321#issuecomment-450370966
Since the idea is to build an independent copy of boost there's no reason to include the OS site-config

gen-linux.sh: Add ignore-site-config for boost

---

src/emulator/kernel/src/load_self.cpp

When there's a segment of non-PT_LOAD type (for example, `PT_SCE_COMMENT`), load_self would crash when it attempts to read a non-existent value from the std::map.
I've also taken the liberty to clean up the nearby code a little reducing the copypasta.
Repro: OrangeSunflower.vpk homebrew (or possibly any Unity homebrew). But it still crashes later, seemingly for a different reason.

kernel/load_self: Fix a crash when there's a non-PT_LOAD segment present

---

src/emulator/cpu/src/cpu.cpp

This allows us to gracefully handle invalid memory access by a game
instead of crashing the whole thing.

cpu: Don't map the NULL page into unicorn

---

src/emulator/audio/src/audio.cpp

`output` becomes invalidated after calling `pop()`

audio: Fix use after free in mix_out_port

---

src/emulator/kernel/include/kernel/types.h
src/emulator/kernel/src/load_self.cpp

As we only have up to 4 segments in the structure, don't attempt to place any more than that.

kernel/load_self: Add another check for when the segment shouldn't be loaded

---

.gitmodules
src/emulator/config.cpp
src/emulator/glutil/include/glutil/object.h
src/emulator/glutil/src/object.cpp
src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/state.h
src/emulator/gui/src/game_selector.cpp
src/emulator/gui/src/gui.cpp
src/emulator/host/include/host/config.h
src/external/CMakeLists.txt

As per request, config.yml accepts the `background-image` and `background-alpha` options.
`background-image` is an optional path to some picture on your hardrive. It changes your launch page's background for some nice tasty customization. It should stretch to fit your screen, just pretend that it is in the next screenshot.
`background-alpha` is an optional decimal that lets you see the image more or less. The higher the value, the harder it is to see. Kinda confusing imo but at least it works.

gui: Option To Add a Background Image

---

src/emulator/config.cpp
src/emulator/host/include/host/config.h
src/emulator/modules/SceAppUtil/SceAppUtil.cpp

- Add choice language inside config file.
Tested with few langue full working, here in french
Ingame here in spanich
List of Language available, first is 0 and last is 19
>	Japanese = 0
American English = 2 // Default value 
French = 2
Spanish = 3
German = 4
Italian = 5
Dutch = 6
Portugal Portuguese = 7
Russian = 8
Korean = 9
Traditional Chinese = 10
Simplified Chinese = 11
Finnish = 12
Swedish = 13
Danish = 14
Norwegian  = 15
Polish = 16
Brazil Portuguese = 17
British English = 18
Turkish = 19
so set in config 0 to 19 like you want used
- Important for user: All PSVita game not have all language, very lot gamer have only English.

System: Add choice console language in config.

---

src/emulator/config.cpp
src/emulator/gui/CMakeLists.txt
src/emulator/gui/include/gui/state.h
src/emulator/gui/src/game_selector.cpp
src/emulator/gui/src/gui.cpp
src/emulator/gui/src/main_menubar.cpp
src/emulator/gui/src/private.h
src/emulator/gui/src/settings_dialog.cpp
src/emulator/host/include/host/config.h
src/emulator/modules/SceAppUtil/SceAppUtil.cpp
src/emulator/modules/SceGxm/SceGxm.cpp

Thx @VelocityRa for have help me for found how save value inside config and for helping first with PopStyleColor and some other thing found.
Thx also @1whatleytay for have help me on get better description.
Thx too @pent0 for fix my color issue on Tab title.
- Add news Settings dialog with tabs category (System, Emulator , GUI, and Debug) for configure GUI hiden, Icon Size with news Slider, Background Alpha with slider, Console Language, Button Assign, Archive Log, texture Cache and Console mode and all Diferent Log in Debug . 
- Gui/system: Add Assign enter button selection.
- Setting: change color for checkbox and slider for better view.
- Setting: Add 3 tab color for get different color active/no active and hovered.
- Remove Optimizations Bar Menu for set Texture Cache option inside …

Settings/Gui: Add news settings dialog and misc things

---

.gitmodules
src/external/CMakeLists.txt
src/external/unicorn-build.sh

Spiritual successor of #277 by @muemart which was reverted in #278 because Windows builds were broken.
As no proper fix for the Windows build problems has been found, this interim solution of using a submodule on the platforms in which it works seemed better in my opinion.
As I only have access to Linux, building has not been tested in neither Windows nor macOS. Those ought to be unaffected by these changes though.

Use unicorn as submodule in Unix

---

.gitmodules
gen-windows.bat
src/emulator/init.cpp

- Add compatibility project on Visual studio 2019 and with fix compilation issue with link glbinding-aux on release build.
- Improve time on compilation appveyor and on VS, generate exe file take now only ~10 sec.
- Add choice script for user choice if wanted use 2017 or 2019 and using timmer for default value using
VS2017
For now, Visual studio 2019 require external install boost already build, 1.70 with msvc 14.2 version, but is exactly same with Dynarmic, also request external version for have all file needed, so need update it in future.
- Before :
- After :

Add support Visual Studio 2019 and improve time compile build.

---

src/emulator/modules/SceCtrl/SceCtrl.cpp

Some commercial games (eg: Sword Art Online: Lost Song) use multiple buffers for controls (Sword Art Online: Lost song actually uses sceCtrlReadBufferPositive with count = 64).

ctrl: Handling count parameter on peek_buffer.

---

src/emulator/shader/include/shader/usse_translator.h
src/emulator/shader/src/spirv_recompiler.cpp
src/emulator/shader/src/translator/utils.cpp
src/emulator/shader/src/usse_translator_entry.cpp

- Refactoring register cache: Move common, duplicated code to lambda, also added TEMP register cache.
- Remove static temp register creation in recompiler code. It's just wrong.
- Reorder VBW. The match string only requires 01 at the beginning, really vague, so put it at the end

shader: Fixes

---

src/emulator/audio/include/audio/state.h
src/emulator/audio/src/audio.cpp
src/emulator/modules/SceAudio/SceAudio.cpp

When a game attempts to output audio, I put it to the port's stream immediately rather than deferring that to the audio callback.
This avoids underflow when the game's thread doesn't wake up fast enough to output more audio.
Additionally, I only put the thread to sleep if the audio isn't going to finish playing in the next audio callback. This means the calling thread generally won't stop if submitting audio in small chunks.
I then increased the SDL chunk size, as it was popping a bit on my Mac.

Attempt to fix main audio underflow bug

---

src/emulator/gui/include/gui/state.h
src/emulator/gui/src/game_selector.cpp
src/emulator/gui/src/settings_dialog.cpp

- Add in settings dialog Core tab with lle module for select what you want in liste.
- Add reset button for reset all modules selected.
- Add button for apply log level change without reboot.
- Add search bar for search particular module wanted on list.
- Add check for show lle list only if found one llle file.
- Fix size list language for not set item outiside setting box

gui: add lle modules in setting dialog

---

src/emulator/renderer/src/draw.cpp

- Fixes RenderDoc output/replay (still not perfect). It was probably picking up the IB from imgui due to multithread sync issues)
- Could potentially fix graphical issues for buggy drivers

renderer: RenderDoc replay output fix

---

src/emulator/config.cpp
src/emulator/gui/src/game_selector.cpp
src/emulator/gui/src/settings_dialog.cpp
src/emulator/host/include/host/config.h
src/emulator/host/include/host/state.h
src/emulator/main.cpp
src/emulator/modules/SceDisplay/SceDisplay.cpp

- Get more easy to switch mode with sync rendering without re compile build.
- Fix render on few game if sync rendering is enable (like Dongaronpa).
- Restore id game on search game removed by mistake on my last pr. 
- Fix fps on few game for logo (get 60 fps and no eg: 250).
I have set (Sync Render) for get short name compared other option already here.

Gui/Modules: Add sync render option and fix showing render with this option

---

src/emulator/host/src/host.cpp
src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp

- Blacklist some commonly used NIDs that spam the log too much (debug-only feature, irrelevant to users)
- A potential perf improvement to import calling, though unlikely because of branch prediction.
- Linux build hotfix

Import call logging blacklist & optimization

---

src/emulator/gxm/include/gxm/types.h
src/emulator/host/src/host.cpp
src/emulator/renderer/include/renderer/texture_cache_state.h
src/emulator/shader/src/translator/alu.cpp
src/emulator/shader/src/translator/branch_cond.cpp
src/emulator/shader/src/translator/data.cpp
src/emulator/shader/src/translator/texture.cpp
src/emulator/shader/src/usse_utilities.cpp

- Add all spir-v check guard if shader value don't success loaded, prevent crashing, normally for lot case.
- Add log error for can debug it in futur and probably fix/improve render.
- Run clang format.

shader/translator: Add null spir-v check guards.

---

src/emulator/kernel/src/thread/sync_primitives.cpp

Fixes a regression in Danganronpa 2.

kernel: Allow calls with outBits set at NULL.

---

src/emulator/kernel/src/thread/sync_primitives.cpp
src/emulator/modules/SceAudio/SceAudio.cpp

Unicorn startup is slow, so better not stop it.
Improve framerate in debug build for Undertale on some places (like start screen). However the more glyph it draws, the more framerate it drop (to 6fps on my i5, and previously 2fps). I think it's fault somewhere in the rendering system?

Wait for lock instead of stop CPU and wait later

---

src/emulator/audio/src/audio.cpp

Fixes race condition where audio thread tries to access buffer before it is allocated.

audio: Start audio thread after temp buffer is allocated

---

src/emulator/app/include/app/functions.h
src/emulator/app/src/app_init.cpp
src/emulator/config/include/config/config.h
src/emulator/config/src/config.cpp
src/emulator/cpu/include/cpu/functions.h
src/emulator/cpu/src/cpu.cpp
src/emulator/gdbstub/src/gdb.cpp
src/emulator/main.cpp

This PR does a couple of things:
- Adds support for writing to registers or memory through GDB.
- Thread IDs are apparently hexes so the stub no longer interprets them as decimals.
- GDB *should* also catch unicorn errors now.
- Made the configuration option no longer optional for two reasons: 
- Everything else isn't optional anymore so it kinda looks ugly.
- I was editing the wrong config file and nothing was changing and I got scared and changed it.
- Makes a proper app:destroy() method to deinitialize the app.
- In my honest opinion, I think this is a good thing. It separates all the code that terminates stuff from main and gives it a nice cozy home.
- I understand if you think this shouldn't be included, either because it's not necessary or this isn't the pr to do it (or any other …

gdbstub: tune up

---

.travis.yml

Due to an issue with homebrew, ccache is not installed anymore on osx builds, resulting in increased compilation time for this system.
You can see the issue in travis logs by looking at the "Installing Homebrew Packages" part:
```
$ rvm $brew_ruby do brew bundle --verbose --global
/usr/local/bin/brew tap homebrew/bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 0 formulae (183 files, 250KB)
Error: Your Homebrew is outdated. Please run `brew update`.
Error: Kernel.exit
```
And in the CMake setup, we have:
```
-- Check for working CXX compiler: /Applications/Xcode-9.3.app/Contents/Developer/usr/bin/g++
-- Check for working CXX compiler: /Applications/Xcode-9.3.app/Contents/Developer/usr/bin/g++ -- works
```
This PR solves …

travis: Fix ccache homebrew installation

---

.gitmodules
src/emulator/gui/src/gui.cpp
src/emulator/host/CMakeLists.txt
src/emulator/interface.cpp
src/emulator/interface.h
src/emulator/io/CMakeLists.txt
src/emulator/io/include/io/VitaIoDevice.h
src/emulator/io/include/io/device.h
src/emulator/io/include/io/file.h
src/emulator/io/include/io/filesystem.h
src/emulator/io/include/io/functions.h
src/emulator/io/include/io/state.h
src/emulator/io/include/io/types.h
src/emulator/io/include/io/util.h
src/emulator/io/include/io/vfs.h
src/emulator/io/src/device.cpp
src/emulator/io/src/filesystem.cpp
src/emulator/io/src/io.cpp
src/emulator/io/src/state_functions.cpp
src/emulator/modules/SceAppUtil/SceAppUtil.cpp
src/emulator/modules/SceIofilemgr/SceIofilemgr.cpp
src/emulator/modules/SceLibKernel/SceLibKernel.cpp
src/emulator/modules/SceLibc/SceLibc.cpp
src/emulator/modules/SceProcessmgr/SceProcessmgr.cpp
src/emulator/modules/module_parent.cpp
src/emulator/np/src/trophy/context.cpp
src/emulator/np/src/trophy/trp_parser.cpp
src/emulator/util/include/util/string_utils.h
src/emulator/util/src/util.cpp
src/external/CMakeLists.txt

This PR implements ~~mark two of~~ io refactoring. `io` now uses two classes (one for directories and one for files) as the baseline for interacting with files, combined with [using Better Enums](https://github.com/aantron/better-enums) for manipulation of paths. As a result, *any* Vita path can now be constructed and translated.
~~This is a Work-in-Progress because directories still need to be refactored (traversing a directory WILL cause errors), but testing is needed.~~

io: Refactoring with Classes (#329)

---

src/emulator/modules/SceIofilemgr/SceIofilemgr.cpp

The recent io refactor (97183ffc1bbc1876afabeabf698e83ba7f9cc75b) mistakingly changed the offset type from int to SceOff which is defined as SceInt64 which causes issues when calling the 32 bit version of sceIoLseek32 but works fine on sceIoLseek (64 bit version).
Function prototype https://docs.vitasdk.org/group__SceFcntlUser.html#gaca489d7dcc95d9ee8f85248601c2102c

Fix sceIoLseek32

---

vita3k/renderer/src/gl/sync_state.cpp

Correct the viewport formula in flipped case. I think this is correct, if it đoesnt work with both steins gate and zero i will close

Nurses in Resident Evil

---

vita3k/gxm/include/gxm/types.h
vita3k/gxm/src/gxp.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp

I did some dual fixes for duals involving vec4, but the real meat comes from the stupid tex coord thingy.
Instead of making each TexCoord 2 bits and making each a size, peeps at sony decided to make it infinitely less clear. Now the bits work as following:
```
Bit 0: Enables TexCoord (.xy), Size + 2.
Bit 1: TexCoord .z, Size + 1
Bit 2: TexCoord .w, Size + 1
```

TexCoord shenanigans

---

vita3k/config/include/config/config.h
vita3k/config/src/config.cpp
vita3k/gui/CMakeLists.txt
vita3k/gui/include/gui/state.h
vita3k/gui/src/gui.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/private.h
vita3k/gui/src/profiles_manager_dialog.cpp
vita3k/interface.cpp
vita3k/io/include/io/functions.h
vita3k/io/include/io/state.h
vita3k/io/src/io.cpp
vita3k/modules/SceNpManager/SceNpManager.cpp
vita3k/np/src/trophy/context.cpp

- Add Profiles Manager for support multi user with user_id for savedata, and with online id.
- Add popup for confirm and ask if user wan delete folder with save/trophy corresponding user id. 
- Re works creation folder for Save Data.
- move tty log inside trace log level, before can get it on different file etc (improve perfomance if spaming)
- List user
- Both case for delete user popup ask user.
- Rename user

Gui/config/io: Add multi user support

---

.travis.yml

i noticed the last merge had some trouble deploying (macos specifically), and it's because we create a tag everytime we deploy without checking if the tag exists first, so hopefully this fixes it

Playing Tag

---

vita3k/gui/CMakeLists.txt
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/game_context_menu.cpp
vita3k/gui/src/game_selector.cpp

- Add context game menu in game selector.
- Possibility is: Copy Info game like ID, name or both/ Remove Game and shader log
- Delete game and remove it in list in a fly.
- Delete save data game.
thx @1whatleytay for get smart code for delete only one game inside game list.
- Main context menu
- Copy Game info  
- Remove part
- Remove game popup

Add game context menu.

---

gen-windows.bat

**To anyone compiling Vita3K on VS2019:**
You can now delete your large, system-wide boost installation, and run `gen-windows.bat` so that only our [subset](https://github.com/Vita3K/ext-boost) is compiled instead.
Just make sure to remove your environment variables (`BOOST_ROOT`, etc) too.
**To anyone compiling on VS2017:**
You can now switch to VS2019 easily.

Update Boost for VS2019

---

vita3k/modules/SceNet/SceNet.cpp

Second argument of `InetNtop` is of type `char *` in win 8.1 sdk. This causes an error when passing it a `const char *` variable. The 2 simple solutions to this is either what I've done in this PR or do an ifdef for windows 8.1 and only do `const_cast` there. The former seems like the better solution in terms of maintainability.

modules/SceNet: fix compatibility with win 8.1 sdk

---

vita3k/io/include/io/vfs.h
vita3k/io/src/io.cpp
vita3k/modules/SceAppUtil/SceAppUtil.cpp

Steins;Gate fails to check for available space to create the system data.
(credits to @Zangetsu38  for testing it and posting the log)
and it progresses to menu with this
---

sceAppUtil: implement sceAppUtilSaveDataGetQuota

---

README.md
vita3k/interface.cpp

In all scenarios when installing a game (success, bad zip, reinstall, vitamin-dump, etc) the application will unnecessarily lock the file you installed/tried to install.

Added file handle closing when installing a VPK to avoid locks

---

vita3k/renderer/src/gl/sync_state.cpp

Breaks hardware flip.
https://github.com/Vita3K/Vita3K/pull/619#issuecomment-565652849

Revert "renderer/gl: Correct viewport formula again"

---

vita3k/gui/CMakeLists.txt
vita3k/gui/include/gui/functions.h
vita3k/gui/src/game_context_menu.cpp
vita3k/gui/src/game_selector.cpp
vita3k/gui/src/gui.cpp

- Add Open folder for game and savedata
- Add Update History on game context menu.
- Add game information.
- Refactor order/name for have same real psvita hw (set real psvita element after emulate element).
- Context menu:
- Update history:
- Information:

game context menu: add misc things

---

vita3k/cpu/include/cpu/functions.h
vita3k/cpu/src/cpu.cpp
vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp

Stubs sceKernelGetThreadInfo with a basic implementation. There's a lot more stuff this function reports which we do not track, but this should be enough for simple uses. This PR in conjunction with #631 allows stardew valley to get even further.
[vita3k.log](https://github.com/Vita3K/Vita3K/files/4056733/vita3k.log)
I also moved `entry_point` from `CPUState` to `ThreadState`, let me know if I need to change anything there.

stub sceKernelGetThreadInfo

---

vita3k/kernel/src/thread/sync_primitives.cpp

When a thread waiting on a condition variable has been signaled, it needs to reacquire the associated mutex before returning to guest code. fixes fios/psarc hang in stardew valley and ratchet & clank 3.

sync_primitives: reaquire mutex on condvar wakeup

---

vita3k/io/src/device.cpp
vita3k/kernel/src/thread/sync_primitives.cpp

- out.front() was failing on empty out
- Semaphores were crazy with value rising high and hit some assert on thread->to_do status. The cause was spurious wake ups that can be fixed with predicates. Thanks @isJuhn

Some fixes done while using Retroarch

---

.travis/linux/build.sh
external/unicorn-build.sh
format.sh
gen-linux.sh
gen-macos.sh

Not all *Nix systems have bash located at /bin/bash, this pr fixes building
Vita3k on them.

Get Bash from /usr/bin/env

---

vita3k/renderer/src/gl/compile_program.cpp

I was debugging on bootcamp again and noticed it was printing an empty error message for every shader it recompiled. This pr should fix this again.

renderer/gl: check status instead of info length

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area_dialog.cpp
vita3k/gui/src/manual_dialog.cpp
vita3k/interface.cpp
vita3k/main.cpp

lot improvement on live area, fix few gate not found and lot other things, code text and lot other get reworked.
- replace start button by button very close on psvita.
- fix log for not show error if not have icon manuel/search and if using default fw content.
- add slider in live area game screen for slider in gamelist.
- fix issue relate hide gui id if press g before (like on search game)
- Add Help screen for indicate how works Live Area/Manual with what button
- New Little King's Story (fix text size and position like said by template)
- different language for start button (here in jap) 
- Add Help screen for indicate how works Live Area/Manual with what button

gui: improve live area game screen.

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/game_context_menu.cpp
vita3k/gui/src/game_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/host/include/host/state.h

- game context menu: add check game compat
- game context menu: refactor all dialog and simplify code.
- game context menu: add support sys lang on title and on new add short_title.
- game context menu: add trophy earning on information dialog.
- game selector: add category tab.
- Information
- Delete game/save
- Update history

Add check game compat

---

vita3k/host/CMakeLists.txt
vita3k/host/src/load_self.cpp

Issue #673 Alerts users when a vitamin dump is launched.
Tested with a real vitamin dump.

Alert users of vitamin dump

---

vita3k/config/include/config/config.h
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/game_context_menu.cpp
vita3k/gui/src/game_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp
vita3k/main.cpp

- move app background in boot app like psvita

gui: move apps background on boot app.

---

vita3k/interface.cpp

I completely forgot to add DLC installation support for `install_vpk`, now user can install .vpk/.zip/nonpdrm DLC (one by one) 
.zip contents must be immediate 
```
├───DLC_FOLDER.zip
│   └───sce_sys
│       └───param.sfo
```

DLC Install

---

vita3k/config/include/config/config.h
vita3k/gui/include/gui/functions.h
vita3k/gui/src/game_context_menu.cpp
vita3k/gui/src/game_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/private.h
vita3k/gui/src/settings_dialog.cpp
vita3k/main.cpp

- Add grid mode for Apps list 
- refactor code for game selector and can now scrool without lost bar for id/ and search
- grid mode 
- scroll good now

gui: add grid mode for apps list.

---

vita3k/io/src/io.cpp

If the `emulated_path` has a trailing slash, calling `parent_path()` on it only removes the trailing slash and doesn't actually return the expected parent path.
Example with the game Pingo (https://github.com/Grzybojad/Pingo/releases/tag/2.1):
```
std::string pathData = "ux0:/data/Pingo/";
[...]
sceIoMkdir( pathData.c_str(), 0777 );
```
`emulated_path` on my computer is "C:/Users/scribam/AppData/Roaming/Vita3K/Vita3K/ux0/data/Pingo/"
- master: `emulated_path.parent_path()` is "C:/Users/scribam/AppData/Roaming/Vita3K/Vita3K/ux0/data/Pingo" and the game crashes
- pr: `emulated_path.remove_trailing_separator().parent_path()` is "C:/Users/scribam/AppData/Roaming/Vita3K/Vita3K/ux0/data" and the game doesn't crash, the directory is created and files inside it too.

io: Fix parent path when emulated_path has a trailing slash

---

vita3k/gxm/include/gxm/functions.h
vita3k/gxm/src/textures.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/texture.cpp

thx @pent0 for your help and your time for search and help me.
- implement sceGxmTextureInitLinearStrided.
Get ingame/menu or just show any render for lot game.
- implement sceGxmTextureGetStride.
- STEINS;GATE 0 menu now (ingame on ngs wip)
- CHAOS;CHILD Menu video news game no play
- CHAOS;CHILD らぶchu☆chu!! Menu same other video issue no play
- ingame
- Jet set radio - intro show this loading animation and crash

Implement some gxm function

---

vita3k/modules/SceSysmem/SceSysmem.cpp

inspired by @KorewaWatchful code hack
- fix crashing on akiba, durriing boot game with it spam try free block uid 0 not found
- Acces on intro logo, and if disable play video get menu and after shader crash

fix akiba crash not found mem block

---

.gitmodules
external/CMakeLists.txt

And restore the official repository for this submodule as Vita3k's one is not necessary anymore.
How to update this submodule after the merge?
```
git submodule sync
git submodule update --init external/SPIRV-Cross
```

external: Update SPIRV-Cross to version 2020-05-19

---

vita3k/io/src/io.cpp

Fix crash when saving the highscore in "2048" (https://github.com/dots-tb/psp2048).
Related code: https://github.com/dots-tb/psp2048/blob/ced08ab88f0415db76f5935c6d6a3eeb627f2189/src/file.c#L25-L36

io: Check if the directory exists before to write the file

---

.gitmodules
vita3k/CMakeLists.txt

This submodule is no longer needed since the shader recompiler has been improved enough.
Using the shaders from this submodule with ubo brings graphical issues (some examples: Flood It!, Retroarch).

shaders-db: Remove submodule

---

vita3k/kernel/src/relocation.cpp

Triggered when a cast to `Code` is done with a value which does not match the enum values.
Found in Flood It! as the game has an unhandled relocation code:
> |W| [relocate_entry]: Unhandled relocation code 102.

kernel: Fix "Load of value 102, which is not a valid value for type 'Code'" from UBSan

---

vita3k/modules/SceAppUtil/SceAppUtil.cpp

I guess this is what is expected as, without the return instruction, it does nothing.

modules: Add missing return instruction to sceAppUtilDrmOpen

---

vita3k/shader/src/usse_program_analyzer.cpp

https://github.com/Vita3K/Vita3K/blob/fcf844ce052c01194d1517d21868dd09533c027a/vita3k/gxm/include/gxm/types.h#L1356-L1360
https://github.com/Vita3K/Vita3K/blob/fcf844ce052c01194d1517d21868dd09533c027a/vita3k/gxm/include/gxm/types.h#L157-L163
- `parameter.category` is supposed to be a `SceGxmParameterCategory`
- `parameter.type` is supposed to be a `SceGxmParameterType`
I think it does not make sense to compare a `SceGxmParameterType` with a SCE_GXM_PARAMETER_CATEGORY_*
It fixes some asserts in VitaQuake, in `match_uniform_buffer_with_buffer_size` and `get_uniform_buffer_base`. You can see there the comparison between a `parameter.category` and a SCE_GXM_PARAMETER_CATEGORY_*

shader: Compare SCE_GXM_PARAMETER_CATEGORY* with the right parameter member

---

.github/workflows/c-cpp.yml

Example on my fork (with ccache enabled): https://github.com/scribam/Vita3K/actions/runs/99061727

Replace AppVeyor/Travis by GitHub Actions

---

vita3k/gui/src/themes.cpp

```
/home/scribam/CLionProjects/Vita3K/vita3k/gui/src/themes.cpp:624:52: error: no viable conversion from 'std::string' (aka 'basic_string<char>') to 'const char *'
ImGui::TextColored(GUI_COLOR_TEXT, themes_info[selected].version);
```
The other changes are warning fixes.

gui: Compilation fixes for clang-10

---

vita3k/app/src/app_init.cpp
vita3k/host/src/load_self.cpp
vita3k/nids/CMakeLists.txt
vita3k/nids/include/nids/functions.h
vita3k/nids/include/nids/nid_vars.h

This PR adds support for HLE NID variable exports and export _pLibPerfCaptureFlagPtr as non-zero value.
The saekano game crashed immediately without even tracing the stack. When the _sceUltUlthreadRuntimeCreate was run, it printed that _sceFiberInitializeWithInternalOptionImpl was not implemented and crashed. This kind of error was reported before in https://github.com/Vita3K/compatibility/issues/331.  
It seemed like _sceFiberInitializeWithInternalOptionImpl was the problem here. But, the actual code that crasehd the game turned out to be
```
ldr r1, [r0]
```
Which dereferenced some pointer. It turned out the code dereferenced the _pLibPerfCaptureFlagPtr which was imported in libult elf module. And, if the value is 0, it breakpoints, otherwise do nothing.
However, as …

Add hle nid variable exports

---

vita3k/mem/include/mem/mem.h
vita3k/mem/src/mem.cpp
vita3k/modules/SceSysmem/SceSysmem.cpp

In the saekano game, the following error was preventing to load the opening video before entering  the loading scene after the logo scene.
It turned out that the video decoder allocate the memory block by non-null sceKernelAllocMemBlockOpt with alignment option. The game crashes manually when it found out the block address is not aligned.
Provided sceKernelAllocMemBlockOpt:
This PR add the memory alignment implementation. With this PR, the game can now finish the  logo scene and enter the loading scene.

Support alignment in sceKernelAllocMemBlock

---

vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
vita3k/np/src/trophy/context.cpp

- Fix two value after searh on my trophy manager works, found issue relate load/save
- Implement timestamps.
- Fix trophy count get +1 caused by first count is " trophyset-version", so fix it with using compare string

np/trophy: Implement timestamp and fix some things

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/texture_yuv.cpp

GXM Texture fix:
> Data might be null to indicate no data is given and it will be filled out at a later stage.
(This behaviour is present in openGL, so I assume it might be the same for GXM)
> It fixes Texture corruption for New Game! The Challange Stage (and apparently boots into video but crash on main screen due to network.) Tested another app, seems to work fine as well... (Though the texture was flipped lol)
YUV2RGB Optimisation:
> Cache the SwsContext from frame to frame. Reuse the context if we are using the same frame, else we recreate it.

GXM Texture Fix & YUV2RGB Optimisation

---

building.md
gen-linux.sh

this increases the build time tremendously since ninja actually compiles
more files in parallel, while the Makefile results that both nids.cpp
and module_parent.cpp are compiled alone, which probably doubles intial
build time (if not more)
I can provide exact numbers if wanted tomorrow
And update the ci script probably.

vita3k: recommend ninja over make for compiling on linux

---

vita3k/app/src/app_init.cpp
vita3k/main.cpp

Some people ran into error dialog `"Host initialisation failed."` but the error log does not show anything.

app: show useful errors on initialization failed

---

vita3k/cpu/include/cpu/functions.h
vita3k/cpu/src/cpu.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/host/src/load_self.cpp
vita3k/interface.cpp
vita3k/kernel/include/kernel/functions.h
vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/thread/thread_functions.h
vita3k/kernel/src/kernel.cpp
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp
vita3k/modules/include/modules/module_parent.h
vita3k/modules/module_parent.cpp
vita3k/util/src/util.cpp

- Add pc information in import call and memory log (unicorn hook)
- If the export function is reached, log its name
- Optionally add register values in code log (LOG_REGISTERS)
- Add variable access watch
- Add toggling code, memory log, and import call log through gui
- Add thread id in code and memory log
You can trace the access to variables you're interested in by adding the following code in interface.cpp or anywhere that can assess KernelState.
```cpp
add_watch_memory(kernel, 0x5353, 10); 
// 0x5353 is the address of the variable
// 10 is the size of the variable
```
It's very hard to debug the unicorn errors since we don't have something like stack traceback. Code, memory, and import call logs might serve as a great alternative to the traceback. However, they drastically slow down …

Improve code log and memory log & add toggling them through gui

---

vita3k/app/src/app_init.cpp
vita3k/kernel/include/kernel/state.h
vita3k/modules/SceProcessmgr/SceProcessmgr.cpp

- Implement sceKernelLibcClock
Turned out it's just the same as c clock function.
In libc,
About type, it's the same as time_t

Implement sceKernelLibcClock

---

vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp
vita3k/util/CMakeLists.txt
vita3k/util/include/util/semaphore.h

- Add semaphore implementation
- Implement sceKernelSendSignal and sceKernelWaitSignal in order to get libult working
Libult was not working with incomplete signals implementation. It was failed with an assertion "dret == 0" If I use a single condition_variable to implement wait and notify behavior, I got "queue_result != null"
With this PR, majority of libult functions start to get working, and it finally moves saenai game and some megas engine games forward to ingame status.

Implement sceKernelSendSignal and sceKernelWaitSignal

---

vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/modules/SceFiber/SceFiber.cpp

- Fix a bug in resetting fiber
- Clean up some duplicated code
Fibers can be created from the thread that will not run them. (a thread can create fiber and pass it to another thread) Since we saved the initial fibers in thread state, sometimes the fiber with null addrContext was not reseted as it could not find its initial fiber.

Refactor and fix a bug in fiber

---

vita3k/gui/CMakeLists.txt
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/gui.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/private.h
vita3k/gui/src/trophy.cpp

- Add trophy manager
- Like psvita, can sort list by progress/update and name
- Global view
- Detail global view
- Global Group view
- Trophy list for one group (view is same if game don't have any group)
- Detail select one group
- Trophy detail

Add trophy manager.

---

vita3k/gui/CMakeLists.txt
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/game_selector.cpp
vita3k/gui/src/gui.cpp

- Refactor code for stock information update
- Refactor viewing update app style.
- small split stuff refacftor game to app inside, rename file game context to app context.
- some refactor on game selector, on grid mode change title to short title and set it in center icon position, like psvita used.
- Add scaling for grid mode for can run it un full screen or with resizeing window.
- Add possible search app with short title.
- fix search bar with label for don't scroll with wheel mouse.
- clock (updatted) showed like real psvita
- Update history more close real psvita
- fix text size for ask, fix box outside screen, and fix icon position 
- using short title for box not get monster size
- game selector using short title with centering position on gris mod

some refactor on gui

---

vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/usse_utilities.cpp

- Make outs variables larger to fit v_TexCoord9.
- Fix spir-v to glsl compilation error regarding vector with one component.
- Make LBP into intro
There was "Cannot subdivide a scalar value!" caused by spir-v to glsl compiler trying to encode OpVectorExtractDynamic of vec1 as index representation.

Fix minor index errors

---

vita3k/config/include/config/config.h
vita3k/config/src/config.cpp
vita3k/cpu/include/cpu/functions.h
vita3k/cpu/src/cpu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/host/src/load_self.cpp
vita3k/interface.cpp
vita3k/kernel/include/kernel/functions.h
vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/thread/thread_functions.h
vita3k/kernel/src/kernel.cpp
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp
vita3k/modules/include/modules/module_parent.h
vita3k/modules/module_parent.cpp

- Manually create stack frames by hooking push and pop instructions
- Add log_stack_frames function that prints the stack traceback
- Add gui to toggle this function
If you want to just see how does it reach to this hle function. Just use the code below in EXPORT to print the stack traceback. 
```cpp
const auto thread = lock_and_find(thread_id, host.kernel.threads, host.kernel.mutex);
log_stack_frames(*thread->cpu);
```
If you want to use stack frames to do more advanced things (such as tracing the arguments or local variables), use get_stack_frames.
```cpp
auto stack_frames = get_stack_frames(*thread->cpu);
```
We can see the address of subroutines that were traveled to reach this point. We can also see fp (frame pointer) Might use it to access arguments and local variables.

Add stack traceback in unicorn engine

---

vita3k/shader/include/shader/usse_translator.h
vita3k/shader/include/shader/usse_utilities.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/texture.cpp
vita3k/shader/src/usse_translator_entry.cpp
vita3k/shader/src/usse_utilities.cpp

Related to #629 
Fixed some spir-v errors following through the validation errors.
Optimization in general fails if the validation fails. (internally they use same parsing function with validation) So, this can benefit the mentioned PR.

shader: fix spir-v errors

---

vita3k/main.cpp

- fix my mistake causing regression get by https://github.com/Vita3K/Vita3K/pull/689, with re allow common dialog showing or just called during app loading.
Thx to @sunho For catch this issue

Fix load Common Dialog also during app boot

---

vita3k/interface.cpp
vita3k/module/include/module/load_module.h

After confirme this is preloaded before boot all game.
- Add load lle pvf get some game perfectly show text now.
Request for gravity rush menu
- Reworks pre load modules if app modules don't exist 
- preload modules on psvita for all game boot
>00:21:06 [SceLibKernel               ]:Starting...  OK        801usec
00:21:06 [SceDriverUser              ]:Starting...  OK        780usec
00:21:06 [SceAvcodecUser             ]:Starting...  OK          1usec
00:21:06 [SceGpuEs4User              ]:Starting...  OK        829usec
00:21:06 [SceGxm                     ]:Starting...  OK        590usec
00:21:06 [SceLibFios2                ]:Starting...  OK       1140usec
00:21:06 [SceLibc                    ]:Starting...  OK     297935usec
00:21:06 [SceShellSvc                ]:Starting...  OK …

module: load firmware module for pvf and Ft2.

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/themes.cpp

- improve date position for start screen with using calc text size for template 2.
- fix line position on start screen
- fix small things relate switch bg broken after outside start screen.
- fix size text more close psvita
- create information bar like on psvita, with show clock and batteries level (totaly fake here lol)
- fix quality on big text size for clock, thx to @VelocityRa  for code and help 
also thx to @1whatleytay for color code :)
- Add info bar on live area screen/theme/screen start
- Master
- PR
- fix position for title name and separator
- add space for themes list and on information
- Add also info bar on live area screen
- Information bar Indicator color (clock only here)

themes: some improvement

---

vita3k/gui/include/gui/functions.h
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/trophy.cpp

- Add popup for can delete trophy.
- Fix crash if trophy folder is empty and open it anyway with show message .
- Some smalll fix
- fix crash if data progress is outdated with clean it.
- Add scroll pos backup/restore on np com list/group list/trophy list for never lost current position to scroll pos, for can brow easy all your trophy list without restart on 0
And,  i have no edit all that, stupid github... is just line move with add { } 🤦 
- For new config or if all trophy is deleted
- For delete trophy popup
- add information bar
- fix position for detail app

Trophy collection: some add/fix/improvement.

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/gui/src/themes.cpp
vita3k/gui/src/trophy.cpp
vita3k/interface.cpp
vita3k/main.cpp

Split Other pr for get more small to review (theme part for icon only on other pr)
- gui/Apps Selector: Move trophy and themes & background inside Apps Selector
- gui/Apps Selector: fix using short title in grid mode
- gui/app context refactor information and delete pupup
- gui/app context menu: fix using short title
- gui/live area: small clean 
- Grid mode with icon 
- Live area trophy
- Live Arera theme background (is settings)
- information, change icon size/name position get exactly same psvita
- Content delete popup

gui: move trophy and theme inside app selector

---

vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp
vita3k/shader/src/translator/branch_cond.cpp
vita3k/shader/src/usse_translator_entry.cpp

- Implement int32 subs in vtest
- Correct register type in vtest (no double regs)
- Match more kill instructions
- Map gl_fragcoord to v_Position in fragment input 
This is equivalent to WPOS. So, we can just give gl_fragcoord to it.
With updated vtest & v_Position, vitagl texture sample is now working correctly.
Updated v_Position fixes a compile error of one fragment shader in LBP.

Fix kiil and vtest instruction + v_Position

---

tools/usse-decoder-gen/autogen.py
tools/usse-decoder-gen/grammar.yaml
vita3k/shader/include/shader/usse_translator.h
vita3k/shader/src/translator/branch_cond.cpp
vita3k/shader/src/translator/special.cpp
vita3k/shader/src/usse_translator_entry.cpp

- Move usse-decoder-gen to here
- autogen.py now directly update the actual source code
- Update grammar.yaml to reflect recent changes
It's generally good practice to manage auto-generated code by the tool that generated it. But, another reason is that it's very tiring to edit the bit-field of existing decoder. (after all, the motivation behind usse-decoder-gen was the difficulty of bit-field as I know)
Notice that the function parameters don't change in cpp files (except nop), and the bit fields and the order of matchers don't change in entry.cpp in this PR.

Move usse-decoder-gen to Vita3k & improve it

---

vita3k/kernel/include/kernel/state.h
vita3k/mem/include/mem/ptr.h
vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
vita3k/modules/SceCodecEngine/SceCodecEngineUser.cpp
vita3k/modules/SceCodecEngine/SceCodecEngineUser.h
vita3k/modules/SceSysmem/SceSysmem.cpp
vita3k/modules/SceSysmem/SceSysmem.h
vita3k/modules/SceVideodec/SceVideodecUser.cpp

- Fix some issues regarding full mspace
- Stub codecengine
- Stub avcdec memsize functions
It's used to give work memory for codec library. But, codecengine apparently allocates it at separate hardware unit. So, if lle mp4 and avplayer turned out to use this worker memory directly, it can be quite troublesome. I just stubbed it for the moment, but if some of those lle functions are not working correctly, we might look at codecengine again.
Video is now working in many games with this. But, it randomly got stuck or crash in the middle of video. This is maybe related to sync primitives which we need to investigate on. Also, audio is not working correctly because of incomplete audiodec. ngs pr (https://github.com/Vita3K/Vita3K/pull/657) improves the situation, but we also need to implement …

Make lle mp4 and avplayer bootable

---

vita3k/renderer/include/renderer/gl/types.h
vita3k/renderer/src/gl/compile_program.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/shader/include/shader/spirv_recompiler.h
vita3k/shader/src/spirv_recompiler.cpp

Samplers cannot be bound by uniform buffer object. We need to bind them manually.
I think, literally all games that use shader with uniform sampler
I checked that it fixes lbp intro screen little bit.

renderer: consider different uniform sampler order

---

vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/scene.cpp

- Support rgba color surface
Xeodrifter was using color surface data as texture in rgba color format.
Improves rendering of xeodrifter along with https://github.com/Vita3K/Vita3K/pull/828

Support rgba color surface

---

vita3k/app/src/app_init.cpp
vita3k/audio/src/audio.cpp

Tries to skip no audio device error.
Audio callback will not be called if SDL couldn't open the audio properly. So, we can just warn the users and keep going.
fix https://github.com/Vita3K/Vita3K/issues/751

app: don't crash if it couldn't find audio device

---

vita3k/renderer/src/gl/load_shaders.cpp
vita3k/shader/include/shader/spirv_recompiler.h
vita3k/shader/src/spirv_recompiler.cpp

- Dump shader immediate and final forms as soon as it becomes available
If the game crashes because of shader recompiler related issue, gxp and other immediate files are not dumped. This is annoying because they're basis for shader debugging.

Dump shader before crashing

---

vita3k/gxm/include/gxm/types.h
vita3k/shader/src/spirv_recompiler.cpp

- Adjust pa offset in non native color fragment shader
This can break a lot of games potentially. Needs to be tested in as many games as possible.
In some non-native color fragment shader, the output was present in pa2 not pa0. We need to adjust this value. Reversing gxm, I found this promising field in SceGxmProgramVertexOutput. But, I'm not 100% sure because related code was really complicated.
Fixes yellow video in saenai game.
Fixes test shader below.
```
usampler2D test_sampler;
unsigned char4 main(half2 coord : TEXCOORD0): COLOR0 {     
return tex2D<unsigned char4>(test_sampler, coord); 
}
```

Adjust pa offset in non native color

---

vita3k/app/src/app_init.cpp
vita3k/config/include/config/state.h
vita3k/config/src/config.cpp
vita3k/gui/src/archive_install_dialog.cpp
vita3k/host/include/host/state.h
vita3k/interface.cpp
vita3k/interface.h
vita3k/io/include/io/device.h
vita3k/io/include/io/functions.h
vita3k/io/include/io/state.h
vita3k/io/src/io.cpp
vita3k/main.cpp
vita3k/util/include/util/log.h
vita3k/util/src/util.cpp

With this, we can conveniently run cli vita apps. This would come handy for building up testing infrastructure.
It redirects stdout, argc, and argv. If the app printf it will printf in the vita3k as well, and the arguments given to vita3k will be also available to the app. host0 io device is redirected to pwd. By writing to and reading from "host0:/hello.txt," you can read and write from the hello.txt in the working directory.
e.g.
```
Vita3k -z true -Z "this is argument" hello_world.vpk
```
```c
#include <psp2/kernel/processmgr.h>
#include <stdio.h>
int main(int argc, char *argv[]) {
printf("argc: %d argv[1]: %s\n", argc, argv[1]);
FILE* fp = fopen("host0:/hello", "w");
fprintf(fp, "Argument: %s\n", argv[1]);
fclose(fp);
printf("Hello world\n");
sceKernelExitProcess(0);
return 0;
}
```

Add console mode

---

vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/gl/types.h
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/uniforms.cpp
vita3k/renderer/src/state_set.cpp
vita3k/util/include/util/log.h
vita3k/util/src/util.cpp

It's useful for debugging shaders. Renderdoc does some dumping, but it's in scientific notation. I found hex more handy.

renderer: add ability to log active default uniform buffers

---

vita3k/gui/include/gui/functions.h
vita3k/gui/src/trophy.cpp
vita3k/gui/src/trophy_unlocked.cpp
vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
vita3k/np/include/np/state.h
vita3k/np/include/np/trophy/context.h
vita3k/np/src/trophy/context.cpp

This pr for split my other pr, with so here only change and fix relate trophy.
- trophy: fix get trophy name for showed on popup notif
- trophy collection: improve gui and add open trophy id for notice info.
- set margin left for trophy icon like on psvita (in center pos compare mp com id icon.
- small fix margin left also for group (is same in finnaly for both)
- Fix trophy display name missing for some game and reworks gui like on psvita

trophy: some fix/improvement

---

vita3k/io/src/filesystem.cpp
vita3k/io/src/io.cpp
vita3k/modules/SceAppUtil/SceAppUtil.cpp

- undertale writes its save file in truncate mode, so that's been fixed
- some mages games consider a save file to be corrupt if param-status isn't 0
- SCE_O_WRONLY shouldn't create files, only SCE_O_CREAT can

io/SceAppUtil: fix saving

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/shader/include/shader/usse_types.h
vita3k/shader/include/shader/usse_utilities.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp
vita3k/shader/src/translator/data.cpp
vita3k/shader/src/translator/texture.cpp
vita3k/shader/src/usse_program_analyzer.cpp
vita3k/shader/src/usse_utilities.cpp

- Fix trivial errors in sop2 implementation
- Implement pack & unpack of uint8
- Handle uint8 (or uchar) sampler
- Handle uint8 output, input and colorattachment
- Update SOP2 to receives and returns uint8 values
- Update VPCK to support uint8
Analyzing shaders using SOP2, I observed four behaviors about sop2.
1. It can use uchar value coming from uniform parameter directly as its sources.
2. The output from one sop2 can be also used directly as sources of another sop2.
3. It can do y = ```(1-x)*color1 + x*color2```. And 1 was immediate value.
4. In 3, x can be 0xff in uint8 bytes.
From 1 and 2, I thought that sop2 actually takes uint8 and returns uint8. Before, we were inputting and outputting fp8 values.
From 3 and 4, I thought that sop2 is actually normalizing the sources internally. I …

Fix uint8 in shader

---

vita3k/modules/SceNgsUser/SceNgs.cpp

when voice_state_data.size() == 0, it crashed before.

Fix minor index error

---

.github/workflows/c-cpp.yml
README.md

This creates a Release tag that will contain the latest github ci builds so they can easily linked to. Right now it doesn't set it as pre release automatically and doesn't recreate the tag, so the release will show a old commit number (but contain the latest artifacts)

Upload github CI master branch artifcats to a CI Release tag

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/pkg_install_dialog.cpp
vita3k/gui/src/themes.cpp
vita3k/gui/src/trophy_unlocked.cpp

- Add notification center
- Empty
- New notification
- Notifications Already check
- Like on psvita, click on trophy unlocked open it inside trophy collections
- Delete notifications
- for notice icon without any icon theme is, Some theme see no have any icon for notice 
other exemple theme with having this icon

gui: add notifications

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/manual.cpp
vita3k/gui/src/themes.cpp
vita3k/host/include/host/state.h
vita3k/interface.cpp
vita3k/main.cpp

- gui/main menubar: fix set value.
- gui/app sellector: Add information bar.
- gui: reworks app selector and live area switch game.
- Live area app with arrow left/right for switch app opened
- App Selector with arrow in left for open it on live area 
- App running go live area and left for show app selector
(for can go on system app for now, can launch another app in futur like psvita)

GUI: Some refactor

---

.github/workflows/c-cpp.yml

Prerelease doesn't show up in github main page because we already have releases.

Continuous tag is release

---

vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/themes.cpp

- Fix start in french
- fix dispear info bar on  live area if usiing load last app
- same for open start screen if before you have go to menu bar
- Add resume name for all language, name change relate if you run app or not, like psvita, run app, press PS get live area with it show Continue on gate.
all after is for missing fw font
- FIx large font
- fix position for clock in info bar, and fix missing clock in start screen 
Without fw font
- Master
- PR
- Fix french name on start
- Add continue if this game game running (other app open in list keep start)

gui: fix clock/date pos if missing fw font.

---

vita3k/gxm/include/gxm/types.h
vita3k/renderer/src/gl/draw.cpp

When the app unregisters program, very rarely, the program address can be the same as the previous program. To avoid drawing using incorrect program in this situation, this PR doesn't let it pass even if the program address is the same as before.
The additional cost should be two string comparisons and copying, so I think this PR shouldn't cause drastic performance drop.

Stricter last draw program cache validation

---

vita3k/shader/CMakeLists.txt
vita3k/shader/include/shader/gxp_parser.h
vita3k/shader/include/shader/usse_program_analyzer.h
vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp
vita3k/util/CMakeLists.txt
vita3k/util/include/util/overloaded.h

- Separate gxp input parsing part from spirv recompiler
- Fix non-ubo mode uniform bug
- Refactor various utility functions
- Refactor create_parameters of spirv_recompiler.cpp
GXP input parsing part can be reused for many purposes (fuzzing/debugging/optimizing/etc) But, we had it inside private recompiler function that also deals with spir-v setting up, hiding useful parsed information.
With this PR, now we can get almost all information about input data of gxp shader program using code like below. 
```cpp
const auto prgoram_input = shader::get_program_input(program);
```

Refactor GXP input parsing

---

vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp

Fix mistake I made in recent pr. Fix regression in blazblade and other games that use non-default uniform buffers.

Fix ubo not binding

---

vita3k/config/include/config/config.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/gui/src/themes.cpp
vita3k/interface.cpp

Juste reworks some thinks for can works more like PSVita, particularity for theme and start screen.
Also:
- Add fake background for start screen and for live area if fw is missing.
- Fix issue relate delete user background
- Add font color for different bg if exist on theme.
- Color font for this bg on theme
- on other theme

Gui/themes: some reafctor and add

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/content_manager.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/themes.cpp
vita3k/gui/src/trophy.cpp

Fix some things
- Reworks delete theme and Fix if delete theme actually set.
- hide Select button if is already it currently set for start/theme. 
- Small improvement on grid mode for app title, more close psvita.
- Refactor app icon for split user app and sys app
- Restore scrollbar for app selector and add it for trophy list, theme list.
- fix mistake on themes code for start background

gui/themes: some fix and refactor.

---

vita3k/shader/include/shader/usse_translator.h
vita3k/shader/include/shader/usse_utilities.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp
vita3k/shader/src/translator/branch_cond.cpp
vita3k/shader/src/translator/data.cpp
vita3k/shader/src/translator/ialu.cpp
vita3k/shader/src/translator/texture.cpp
vita3k/shader/src/translator/utils.cpp
vita3k/shader/src/usse_utilities.cpp

- Make load of int value outputs ivec or uvec always
- Make store of int value takes ivec or uvec always
- Non-built in int pack & unpack function that uses ivec or uvec (built in ones output normalized float)
- Adjust some instructions using int values
- Correct vpck with two f32 sources
- Complete vpck with int values
- Fix vtst
With https://github.com/Vita3K/Vita3K/pull/942, this fixes vitagl and vitaquake3.
With this pr, every int load & store should work correctly, and store & load function with int values becomes more intuitive. (less side effect) There are more description inside commits, reviewer or future contributor can read it to understand the motivation more deeply.

Complete int load & store, Fix VPCK / VTST

---

vita3k/shader/src/translator/data.cpp

This mistake is minor but it breaks 483792142 games.

Fix minor mistake

---

vita3k/shader/src/usse_utilities.cpp

This should fix "LSD" render and many color exploding regressions. (pink in terraria, etc)

Clamp float when converting to int

---

.gitmodules
vita3k/gui/src/gui.cpp
vita3k/gui/src/themes.cpp

Small split PR #865 
is my reworks code based on @EXtremeExploit  works for unicode, just here only for theme and particluary for user home background and user start backgfround
- Add unicode support inside themes for user start background and user image background

gui/theme: add unicode support for user background

---

vita3k/shader/include/shader/gxp_parser.h
vita3k/shader/include/shader/usse_program_analyzer.h
vita3k/shader/include/shader/usse_translator_types.h
vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/data.cpp
vita3k/shader/src/usse_program_analyzer.cpp

- Don't analyze shader instructions to find out the size of uniform buffers
- Deal with half register half memory uniform buffer
Fixes p4g sunny character rendering.
We used to analyze the program to determine the size of memory uniform buffer. However, this method will require tons of works when dealing with ldr with temporary register for base field. (this can happen)
From my observation, uniform parameters of memory uniform buffer are not stripped away. Utilizing this, I tried to determine uniform buffer size from uniform parameters. I also observed half register half memory uniform buffer. (this seems to happen in large default uniform buffer) In this case the size_in_f32 is less than the total size of uniform buffer, and the ldr instruction will be used to access fields not available …

Rework uniform buffers

---

vita3k/modules/SceGxm/SceGxm.cpp

Settexturemodesafe was buggy and it rejected some supported address modes including repeat. (probably because it was not synced with normal settexturemode)
This fixes p4g road texture.

Fix settexturemodesafe

---

vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp

One dependent sampler can exist in multiple bases. I'm not sure why multiple bases exist yet. (maybe related to swizzle?) But, I assumed uniqueness in recent refactor and it resulted in some sampler not found errors.

Consider multiple dependent sampler parameters for one sampler

---

vita3k/shader/src/spirv_recompiler.cpp

The depth test is not in action if we use image_store to write to framebuffer. Early testing would discard pixel before fragment shader is executed so that imagestore is not called.
Fixes overdraw issues in p4g.

Enable early testing for programmable blending

---

vita3k/gui/src/gui.cpp
vita3k/interface.cpp

Add Log info for can indicate inside it after boot game if ngs is enable or disable.
- log: add log for ngs state.
- gui: small reworks app icon init.

log: add log for ngs state.

---

vita3k/main.cpp

Small fix to prevent high CPU usage when selecting applications. Turns out we are running too fast.
Current limit is 60fps, though feel free to tweak.
After tweak: 
Current Master:

Limit Framerate when selecting applications

---

vita3k/gui/src/firmware_install_dialog.cpp
vita3k/host/include/host/functions.h
vita3k/host/src/pup.cpp

split other unicode pr, but this time, using only my proper code writed and thinked alone, after understund how it works.
- Add unciode path support for install pup file (firmware and system data)

firmware install: Add unicode path support.

---

vita3k/io/src/io.cpp

`sceIoRemove` and `sceIoRmdir` must return 0 on success which is not the case on master as `remove_file` and `remove_dir` return true (aka 1) on success

io: Fix sceIoRemove and sceIoRmdir return codes on success

---

vita3k/gui/src/common_dialog.cpp

To match with: https://github.com/Vita3K/Vita3K/blob/8369d0287bb0e525b77a7488edad4c9d59390fc3/vita3k/gui/src/common_dialog.cpp#L69

gui: Add missing PopStyleColor

---

external/CMakeLists.txt
vita3k/CMakeLists.txt

For some reason, mingw unicorn outperforms msvc unicorn. (2 fps vs 15 fps in p4g) For this reason, this pr tries to use the mingw unicorn automatically built by github ci in vita3k unicorn repository. (https://github.com/Vita3K/unicorn/releases/tag/4b52942b)
Ideally, we should spot out some subtlety in msvc version of unicorn and remove bottlenecks at some moment. Because msvc version is a lot better in term of debugging experience. (i.e. we can breakpoint at unicorn source code)

external: use unicorn built with mingw for windows executable

---

vita3k/shader/src/usse_utilities.cpp

SPIRV Cross doesn't support OpSatConvert yet. OpUConvert and OpSConvert provide what we want in current glsl recompiler implementation.

shader: don't use saturated conversion

---

vita3k/shader/include/shader/usse_translator_types.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/data.cpp

I observed some shader that actually use some value mutated by alu as base. So current method will fail because it assumes that shader will always use certain registers listed in meta as base.
This pr tries to better emulate uniform buffer part of gpu memory by the following method. 
- Create an array varialbe that is big enough
- Load all uniform buffer data to that variable
- The base will be just index of that array 
- Use float scalar array instead of vector array to ease the implementation difficulty

shader: memory load instruction with actual base and float scalar array

---

vita3k/modules/SceGxm/SceGxm.cpp

This pr should fix the crash at p4g shopping street after the mem leak pr. 
The game added some commands outside the scene which added some command to the command list that is already submitted. However, the renderer frees the command list after it processed it. Therefore, commands were added to freed command list, which resulted in undefined behavior. I'm not sure how was it able to function without crash before the mem leak pr. (maybe bigger available memory area give more room?) After all it's all inside undefined world, so it's probably not wise to investigate this seriously.

renderer: reset command list at the end of scene

---

.github/workflows/c-cpp.yml

See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Action and workflow authors who are setting environment variables via stdout should update any usage of the set-env and add-path workflow commands to use the new environment files.

GitHub Actions: Replace deprecated add-path and set-env

---

.github/workflows/codeql-analysis.yml

CodeQL: Replace deprecated set-env by $GITHUB_ENV

---

tools/usse-decoder-gen/grammar.yaml
vita3k/shader/include/shader/usse_translator.h
vita3k/shader/include/shader/usse_utilities.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/data.cpp
vita3k/shader/src/translator/ialu.cpp
vita3k/shader/src/usse_translator_entry.cpp
vita3k/shader/src/usse_utilities.cpp

- Implement i32mad
- Better stub for sn argument of i32mad2
- Memory address in bytes (it was in words before)
This pr tries to better support memory uniform buffer which is usually used in big vertex shader programs. i32mad and i32mad2 were used to manipulate the pointer (memory address) to uniform buffer.
Fixes mesh rendering of adventure of mana.

shader: implement i32mad and fix bugs in ub memory 

---

vita3k/gxm/include/gxm/types.h
vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
vita3k/renderer/src/gl/renderer.cpp

- Fix the mismatch between vertex attribute name of shader and runtime
- Shrink the size of semantic field of gxm parameter struct
sceGxmProgramFindParameterBySemantic tried to find parameter with semantic 0x6, but it failed because the desired parameter has semantic 0x0106. 0x01 should be from another field. (I guess it's a flag)
This fixes the black screen render of ingame and title of puyo puyo tetris.

renderer: fix few bugs

---

vita3k/np/src/init.cpp

Otherwise, if you call `sceNpInit` =>`sceNpTerm` => `sceNpInit`, you have a `SCE_NP_ERROR_ALREADY_INITIALIZED` error. Same thing for the trophy functions.

np: set state.inited to false on deinit

---

tools/gen-modules/gen-modules.cpp

With PR #649, vita-headers is not in the repository anymore.

gen-modules: remove hardcoded path to db.yml

---

vita3k/gui/src/settings_dialog.cpp

Sony changed the link to the firmware download. The new link: https://www.playstation.com/en-us/support/hardware/psvita/system-software/

Updated firmware link to new link

---

.gitmodules
vita3k/kernel/include/kernel/state.h
vita3k/renderer/src/texture_cache.cpp

* XXH3 is faster than accumulate and SHA256
* Also optimize nids find inside resolve_export function
Since my PC is not that great i am unable to detect any performance boost with this, but technically it should, if someone could do some benchmarking justo to get some numbers would be great

gxm: Optimize graphics hashing with XXH3

---

vita3k/modules/SceGxm/SceGxm.cpp

And remove some invalid checks in `sceGxmTextureGet*` functions (verified by RE)

SceGxm: add missing returns before RET_ERROR

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/texture.cpp

I'm not happy with the way the depalletization is split in two parts, but keeping them together doesn't seem to function correctly. Insight would be appreciated.

add support for various texture formats

---

vita3k/gxm/include/gxm/types.h
vita3k/modules/SceGxm/SceGxm.cpp

Also:
- remove assert from the code when there is already an explicit check which returns an error (RET_ERROR)
- add assert to the code when there is no explicit check found in RE
- change return types to more accurate ones

SceGxm: add function arguments and error checks

---

vita3k/modules/SceGxm/SceGxm.cpp

I didn't found a similar check during RE, not sure why it was added.

SceGxm: do not check outputRegisterSize value in sceGxmColorSurfaceInit

---

vita3k/modules/SceLibKernel/SceLibKernel.cpp

[1001 Spikes [PCSE00349]](https://github.com/Vita3K/compatibility/issues/186): Bootable/Menu => Ingame

SceLibKernel: check if a thread is valid in sceKernelWaitThreadEnd/sceKernelWaitThreadEndCB before to lock

---

vita3k/CMakeLists.txt

Fixes issue #392. `discord_game_sdk.bundle` changed to match the dylib dependency `@rpath/discord_game_sdk.dylib`. Also changed the rpath to `@loader_path` according to https://blog.krzyzanowskim.com/2018/12/05/rpath-what. Tested and verified on 2 different machines. However, according to Apple it'd be best to move all libraries to the Frameworks directory.

Fix macOS rpath

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/data.cpp
vita3k/shader/src/translator/ialu.cpp
vita3k/shader/src/usse_disasm.cpp

- Correct the unit of src1 in ldr (it was in words instead of bytes)
- Correct repeat offset of vbw (it needed /2)
- Adjust null checks 
- Improve logging
Fixes regression in BlazBlue.

shader: fix bugs in uniform buffer & improve logging

---

vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/shader/src/spirv_recompiler.cpp

When viewport is disabled, the shader output should be in screen space, but opengl expects gl_Position to be in ndc. This pr add appropriate conversion that is done in vertex opengl shader.
Gets blazblue ingame.

shader: convert position in screen space

---

vita3k/modules/SceGxm/SceGxm.cpp

[Danganronpa Another Episode: Ultra Despair Girls [PCSB00788]](https://github.com/Vita3K/compatibility/issues/294): Nothing => Menu
There is some checks where the value `multisampleMode` is compared to others but they exist in a more complex way than the one we have in the code. So, until further investigation is done, I think it is better to remove this inaccurate check.

SceGxm: more error checks update

---

vita3k/gxm/include/gxm/types.h

Previously, we had:
```
uint16_t semantic;
[...]
bool is_sampler_cube() const {
return (semantic >> 12) & 1;
}
```
then the `semantic` variable split into two uint8_t:
```
uint8_t semantic;
uint8_t semantic_index;
```
so I believe the `is_sampler_cube` method needs an update. Also, it makes no sense to shift an uint8_t to the right by 12 bits

gxm: fix is_sampler_cube method

---

vita3k/cpu/src/cpu.cpp

Sometimes PC for some reason was 0, if this happend the emulator would crash. now it doesn't 😎

cpu: check Program count on unicorn error 

---

vita3k/modules/SceAppUtil/SceAppUtil.cpp

On master, the function returns `SCE_APPUTIL_ERROR_NOT_INITIALIZED` instead of `SCE_APPUTIL_ERROR_PARAMETER`  when dirName is NULL.

sceAppUtilDrmOpen: fix error code when dirName is NULL

---

vita3k/renderer/src/gl/texture.cpp

Fix #1044 which was a regression introduced by #1023

SceGxm: restore previous pixels_per_stride value for paletted textures

---

vita3k/interface.cpp

Fixes:
* Drag and drop for vpk/zip files
* Some zip/vpk had more than 1 folder depth ("game.zip/foo/bar/eboot.bin") where the game is at, this has now been fixed too

gui: support for more than 1 folder inside vpk root

---

vita3k/gxm/include/gxm/functions.h
vita3k/gxm/src/attributes.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/renderer.cpp

Sometimes game overwrite indicies data when a scene has not been finished by command list. This maybe understandable since there's no vertex sync object, indicies submitting maybe is very fast on vita or copied on vita. 
PR copies indicies data first and delete them later when command list got them. Virtua tennis 4 flickering disappear

gxm: Save indicies data in beginscene

---

vita3k/modules/SceCtrl/SceCtrl.cpp
vita3k/touch/src/touch.cpp

Slight change from #561 to achieve the same result except this time, having `host.common_dialog.status == SCE_COMMON_DIALOG_STATUS_FINISHED` will not disable polling.
Fix #1094

dialog: Disable sceTouch and sceCtrl polling when common dialog is running

---

.github/workflows/c-cpp.yml
.github/workflows/codeql-analysis.yml

- Add sccache for Windows (Ninja is required to use it), fix #859 
- Use Ninja for all os, remove hardcoded job count
- Replace sha by tag for some actions as referencing actions by the short SHA will be disabled soon (see warnings in our GitHub Actions)
Cache needs to warn up but you can have an overview of build times here: https://github.com/scribam/Vita3K/actions/runs/507424280

ci: add sccache with ninja generator

---

vita3k/config/include/config/config.h
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/common_dialog.cpp
vita3k/gui/src/content_manager.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/settings.cpp
vita3k/gui/src/settings_dialog.cpp

split more lang pr for get good support on all font can exist now
- small refactor on app context menu
- reworks font support for asia format.
- add checkbox for Asia font support (Korean+Chinese trad) on  setting dialog in gui tab, enable both take 300 mo on memory, so is option
- fix old issue with some character missing on text, like ('), (tm), (star), musical note, roman number and more 
- fix also space on russian
- with option asia font support enable, show full text correctly with latin + korean

gui: improve font format support.

---

external/CMakeLists.txt
vita3k/CMakeLists.txt
vita3k/app/CMakeLists.txt

it needs some more testing.
I'm on linux but discord sdk wouldn't build I tried to desactivate it with the `USE_DISCORD_RICH_PRESENCE` flag but it doesn't do much (still linked to the library, built it and copy it)
so it needs to be tested on mac, linux and windows with the flag enabled

use USE_DISCORD_RICH_PRESENCE to prevent building discord sdk

---

vita3k/renderer/src/gl/renderer.cpp

- fix font on hatsune miku withimplement SCE_GXM_COLOR_FORMAT_F16F16F16F16_ABGR

renderer/get_surface_data: add few color format support.

---

CMakeLists.txt

Inspired by https://gitlab.kitware.com/cmake/cmake/-/blob/master/CompileFlags.cmake#L117-138

cmake: Append "/MP" flags only when necessary

---

vita3k/modules/SceGxm/SceGxm.cpp

The game (motorstorm) uses precomputed, and use background texture to calculate the surface size and submit to display. But anyway since we don't fill it all controls words are 0 and size return 1, making it display nothing
fine now

modules/SceGxm: Initialise background texture of color surface

---

vita3k/gxm/include/gxm/types.h
vita3k/gxm/src/gxp.cpp
vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp

Fix some games unable to clear. VitaGL clear shader uses gl_VertexID kind of like that.

shader: Implement built in VertexID and InstanceID

---

vita3k/renderer/src/gl/renderer.cpp

works little inspired on @kd-11 works
- fix color one racer in Wipeout 2048
- fix caracterestique racer missing
- master
- pr 
- master
- pr
- master
- pr

Add color format for Wipeout 2048 and fix color for racer

---

vita3k/gui/src/content_manager.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/trophy_collection.cpp
vita3k/kernel/include/kernel/state.h
vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
vita3k/modules/SceRtc/SceRtc.cpp
vita3k/modules/SceRtc/SceRtcUser.cpp
vita3k/util/CMakeLists.txt
vita3k/util/include/util/safe_time.h

`std::localtime` and `std::gmtime` use static state by default, meaning they aren't especially threadsafe. Platform specific methods fix this by letting you allocate your own `tm` structure that won't be overwritten by a rogue function call.
I don't think this is a priority, I just want something simple to go through right now, and CodeQL has some simple warnings that are easy to resolve. Will probably be going through more until #1079 gets merged.

Use threadsafe versions of std::localtime and std::gmtime

---

vita3k/renderer/src/gl/texture.cpp

@kd-11 commit, fix one error on code.
- The attempt to round up bit-width to nearest 8 did not work due to poor bracket placement=

texture/gl: Fix borked optimization attempt

---

vita3k/gxm/include/gxm/types.h
vita3k/renderer/include/renderer/gl/types.h
vita3k/renderer/src/gl/attribute_formats.cpp
vita3k/renderer/src/gl/compile_program.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/renderer.cpp
vita3k/renderer/src/state_set.cpp
vita3k/shader/include/shader/usse_program_analyzer.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/usse_program_analyzer.cpp

- Enable viewport by default (I have noticed a bunch of games don't set viewport mode at all)
- Only set viewport mode to enable/disable when in function sceGxmSetViewportEnable. We overwritten the viewport setting in sceGxmBeginScene, if this is set outside. Fix Haiyore rendering
- Allocate each input attribute in shader a location
* Previously we manually queried them. I don't know if this break homebrew hand-written shader.
- Calculate attribute location using linear allocation, not by dividing register index.
* There are some cases when the input variable in shader are not aligned by 4 floats, so for example half4 a, half4 b will have the same attribute location (0/4 and 2/4 = 0), if we use old method
* Old method results in some attributes being disabled and overwritten.
* => Should …

Random GXM game fixes for the chads

---

vita3k/config/include/config/config.h
vita3k/features/include/features/state.h
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp
vita3k/main.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/scene.cpp
vita3k/renderer/src/state_set.cpp
vita3k/shader/include/shader/usse_types.h
vita3k/shader/src/gxp_parser.cpp
vita3k/shader/src/spirv_recompiler.cpp

- It's a big block before, but now they are removed so I removed them.
- Sync some states again when viewport flip changes. It should help some game with some part being black (ff10), fix flood it hardware flip
- Remove sync_state function, no one uses it

Remove legacy compabilities with hand-written shader

---

CMakeLists.txt
vita3k/io/src/io.cpp
vita3k/kernel/src/kernel.cpp
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp

Different small fixes.
cmake: improved boost search  - fix #1037 can't be checked by CI. need manual check on linux and macos
kernel: Clear TLS on first get - not a good fix, all TLS shoul be rewritten, but now it make possible to run libUlt.suprx used in some games
modules/sceLibKernel: _sceKernelGetThreadInfo. fix stack pointer - looks like misprint, and also fix libUlt.suprx
Mostly help to run "Ar nosurge Plus - Ode to an Unborn Star" [PCSE00707]

Small fixes

---

vita3k/interface.cpp

- fix log name for special character with enable archive log for jap/etc...
- inverse order titile / id for more easy order in log list 
- fix log level choice if archive log enable
- master
- pr
- real name

fix log name for archive log.

---

vita3k/io/include/io/device.h

Which problem(s) does it fix and how? What does this PR add?
Some games send "app0:APP0" and get_device will fail because of the all caps APP0, this fixes it by making the device part all lowercase and then getting the device
Also deletes extra device paths on path recursively (app0:APP0:/pog/champ.txt => ux0/app/GAMEID/pog/champ.txt)
* Makes PCSG01093 [このすば Attack of the Destroyer] bootable

io: Fix get_device work case insensitive, also delete extra device path

---

vita3k/gui/src/settings.cpp
vita3k/modules/SceAppUtil/SceAppUtil.cpp

Gets rid of CodeQL warnings about time, based on @1whatleytay https://github.com/Vita3K/Vita3K/pull/1080

CodeQL: Use SAFETIME on new code

---

vita3k/util/CMakeLists.txt
vita3k/util/include/util/instrset_detect.h
vita3k/util/src/instrset_detect.cpp
vita3k/util/src/util.cpp

Check if AVX2 is suported at run-time and use appropriate conversion function.
I check on Intel(R) Core(TM) i5-2500K CPU and MSVC 2019 compiler and it works well, but it needs check on other CPUs and compilers.

util: Support f32 to f16 conversion even without AVX2

---

vita3k/app/include/app/functions.h
vita3k/app/src/app_init.cpp
vita3k/config/include/config/config.h
vita3k/cpu/include/cpu/functions.h
vita3k/cpu/src/cpu.cpp
vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/thread/thread_functions.h
vita3k/kernel/src/thread/thread.cpp
vita3k/main.cpp
vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceNetCtl/SceNetCtl.cpp
vita3k/modules/SceNpManager/SceNpManager.cpp
vita3k/modules/module_parent.cpp
vita3k/util/CMakeLists.txt
vita3k/util/include/util/pool.h

This should be without erratic bug when calling lle callback function (after running one callback function it will go outside the interrupt handler) 
I used cpu instance pool to solve the problem. It grabs one cpu instance from the pool, execute the lle code on it, and return instance to the pool. If service call is made inside lle callback code, it should work fine, since it's brand new cpu instance separate from the original cpu instance of the thread (the one called something like sceNpCheckCallback) The cursed nested loop like service call -> callback -> service call -> callback -> service call also work fine. But, if the depth is higher than the volume of cpu pool, it would break. I set it to 10 for now. I think it should work fine as long as there's no infinite recursion or …

kernel: reimplement run_callback

---

vita3k/gxm/src/attributes.cpp
vita3k/renderer/src/gl/attribute_formats.cpp
vita3k/renderer/src/gl/sync_state.cpp

untyped attribute formats are simply 32 bit untyped data, GL_INT is 32 bit so it is ok to use it here

gxm: Implement untype attribute format

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp

Adds 3 missing checks:
Draw precomputed: vertex_state and fragment_state
kernelLwLockMutex: workarea

gxm/kernel: Add missing checks in draw precomputed and lock lw mutex

---

vita3k/gui/src/imgui_impl_sdl.cpp
vita3k/interface.cpp
vita3k/kernel/src/relocation.cpp
vita3k/main.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/usse_utilities.cpp

Gets rid of some compiler warnings and corrects type of sceKernelGetTimerBaseWide

vita3k: Some refactor on compiler warnings

---

vita3k/shader/src/translator/alu.cpp

Typos at lines 132 and 257:
Before: vsrc0: {}, vsr1: {}, vsrc2: {}
After: vsrc0: {}, vsrc1: {}, vsrc2: {}
Warning at line 1346:
C4804	'>>': unsafe use of type 'bool' in operation

Fixed typos at lines 132 and 257 and one warning at line 1346

---

vita3k/gui/src/settings_dialog.cpp
vita3k/io/include/io/functions.h
vita3k/io/include/io/state.h
vita3k/io/src/io.cpp
vita3k/util/include/util/string_utils.h
vita3k/util/src/util.cpp

Fixes #681, on case-sensitive filesystems some files couldn't be found, code attempts to iterate through game directory and find a file.

IO: Handle case-sensitive filesystems + cache

---

vita3k/gui/include/gui/functions.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/perf_overlay.cpp
vita3k/gui/src/reinstall.cpp
vita3k/interface.cpp
vita3k/interface.h
vita3k/main.cpp

- for can fix app icon missing if return on live area in commend line run idn, fix also get good name after launch and remove double code no needed anymore 
- refactor main for get app id and fix vpk drop, and stop using vpk path wide for app id, no have sense, more smart without repeat code
- change code for can open home and no boot  content if is no app. 
- remove also old code no used anymore.
- add drop file possible for can install content and refactor reinstall dialog for can show what app you try reinstall.

gui: Refactor get user app info.

---

vita3k/modules/SceGxm/SceGxm.cpp

- get improvement status on very some game request this function, can move some game to nothing to ingame or menu/intro etc 
- Secret of mana move from nothing to menu

modules/SceGxm: Stub TextureInitCube.

---

vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/gl/texture_formats.cpp

Full based on @kd-11 commit, and fixed one mistake by me
- based on two commit:
https://github.com/kd-11/Vita3K/commit/1aec47263344311ac24ccdf52ebcbd6bceca60ec
https://github.com/kd-11/Vita3K/commit/9b9f2d5266fae68e2f2c76e294f066821ccef2a8
- fix color issue
- fix yellow things showed on screen
- fix the transition from one scene to another during the replay/intro
- intro
- Player view in replay

renderer/gl: Implement decode E5M9 texture format.

---

.github/workflows/c-cpp.yml

Boost has been removed from Windows images (https://github.com/actions/virtual-environments/issues/2667) so we have to install it manually.

ci: install boost on Windows

---

lang/en.xml
lang/es.xml
lang/fr.xml
lang/it.xml
lang/ja.xml
lang/ko.xml
lang/nl.xml
lang/ru.xml
lang/zh-s.xml
lang/zh-t.xml
vita3k/dialog/include/dialog/state.h
vita3k/gui/src/common_dialog.cpp
vita3k/gui/src/live_area.cpp
vita3k/host/src/load_self.cpp
vita3k/modules/SceCommonDialog/SceCommonDialog.cpp

- refactor gui code for prepare trophy setup with also add languague support, get more close psvita
- add support of diferent clock format for date and time
- add lang support for save data dialog
- fix start size in live area for full screen mode
- # Result:
- Trophy
- Save Data

common dialog: add lang support for (trophy/save data) dialog

---

.github/workflows/c-cpp.yml
.github/workflows/codeql-analysis.yml

Fix issue #1182 but discord integration has to be disabled to prevent a compilation issue with clang.

ci: Set clang as default compiler for Ubuntu

---

building.md

Because VS2017 is no longer supported by this project, it should be removed from this documentation.

Remove mention of VS 2017

---

gen-windows.bat

i have thinks recently, is time to drop vs 2017 support, and user have confirm my soupcon, is no longer works, obsolete compiler.

buid: remove select choice visual studio.

---

vita3k/audio/include/audio/state.h
vita3k/audio/src/audio.cpp
vita3k/modules/SceAudio/SceAudio.cpp

Implementing sceAudioOutSetVolume to allow software to adjust volume
This turns out to be a little more complicated than expected. Since audio relies on the **SDL_MixAudio** function, that function takes a volume param and applies the volume when mixing the samples. But the sceAudioOutSetVolume function can specify which channel it wants to lower volume on, which you cannot do with SDL_MixAudio. What I did in this PR is average the left and right channel volumes together and applied that to the **SDL_MixAudio** function, which I'm assuming we're not going to want to do. 
Possible solutions:
Apply the volume to the samples in the streams before mixing, but then we're running essentially the same function twice over the same set of sample data, also we'd have to account for every possible …

audio: Programmatic audio control

---

vita3k/app/src/app_init.cpp
vita3k/cpu/include/cpu/functions.h
vita3k/gdbstub/src/gdb.cpp
vita3k/host/src/load_self.cpp
vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/kernel/src/kernel.cpp
vita3k/mem/CMakeLists.txt
vita3k/mem/include/mem/functions.h
vita3k/mem/include/mem/ptr.h
vita3k/mem/include/mem/state.h
vita3k/mem/include/mem/util.h
vita3k/mem/src/mem.cpp
vita3k/net/include/net/types.h
vita3k/ngs/src/ngs.cpp
vita3k/np/include/np/state.h

I've had a lot of free time to do programming as of late, so I ended up doing more refactoring, naturally. However, it got to the point where this (which was _previously_ on my "To-Do List") has caught up: splitting `mem.h` so it properly reflects the rest of the repo.

mem: Split `mem.h` into `functions.h`, `state.h`, and `util.h`

---

vita3k/gxm/include/gxm/types.h

Texunit Flags
There are 4 bits for each of the 16 texunits. Bit 0 tells if the texunit is being sampled non dependently, Bit 1 tells if it is being sampled dependently. Both of these bits can be active simultaneously in one program. The remaining flags are unknown.
Sampler Query Info
If there are samplers used in the shader program sampler_query_info_offset will point to an array of 16 uint16_t.
The low 8 bits for each uint16_t contains a bitmask of the different precisions at which the sampler is queried within the program. Those precisions are U8, S8, U16, S16, U32, S32, F16, F32; not specifically in that order.
The first 2 bits of the high 8 bits is the query_component_count - 1.
The remaining bits are seemingly flags about the texture query. Bit 11(0x800) is the flag for if the query …

Add and name some SceGxmProgram fields

---

vita3k/gui/src/app_selector.cpp
vita3k/gui/src/information_bar.cpp

- add home icon.
- small reworks app icon size

gui/information bar: add home icon.

---

CMakeLists.txt
cmake/GetStandard.cmake
vita3k/CMakeLists.txt
vita3k/config/include/config/state.h
vita3k/config/src/config.cpp
vita3k/main.cpp
vita3k/renderer/include/renderer/commands.h
vita3k/shader/include/shader/usse_translator.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/translator/alu.cpp
vita3k/shader/src/usse_translator_entry.cpp
vita3k/util/CMakeLists.txt

Subset of #660. Done for easier merging.
This adds in the ability to compile Vita3K as a C++17 program. C++17 compilation will be used by default, but we still need Boost for the rest of the program (such as `psvpsfstools`), so `external/boost` won't be modified in this PR for safety.
~~Note that the minimum version requirement of Boost version 1.72 is for `boost::optional::has_value()` (which is effectively the same as `boost::optional::is_initialized()`).~~
Edit: I originally had the Boost requirement as 1.72, but that will only be built by the user, the CI will never need to use that, and APT is *for some absurd reason* still stuck on 1.71. Since we already have a local Boost at 1.72 and C++17, this requirements seems to be fully satisfied.

util: Use std::optional for C++17 builds

---

vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/state_set.cpp

- fix issue for some game when two side is disabled.
- fix image remanent on wheel rotate
- fix black screen on ingame render.
- fix font render and charachter missing

draw: handle two sided rendering for fragment program disable.

---

vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/gl/texture_formats.cpp

- Add support for X8D24 depth-stencil format read.
- Add support for F32M.
- fix crash on boot for Urban trial and get menu with 3d font render (yellow issue)

Add Texture format handle support.

---

.github/workflows/codeql-analysis.yml

https://docs.github.com/en/code-security/secure-coding/troubleshooting-the-codeql-workflow#warning-git-checkout-head2-is-no-longer-necessary

codeql: Fix warning "git checkout HEAD^2 is no longer necessary"

---

vita3k/gui/src/trophy_collection.cpp
vita3k/gui/src/trophy_unlocked.cpp

I have see on my test, window and font is very small on my monitor, totaly forget change it after dpi works
- gui/trophy collection: Add cancel lang text.
| Before | After |
| --- | --- |
| <img  src="https://cdn.discordapp.com/attachments/831294989837402135/839672629400305694/unknown.png"> | <img  src="https://user-images.githubusercontent.com/5261759/117230213-de7d4100-ae1c-11eb-85d2-284e1e53fce3.png"> |

gui/trophy unlocked: fix font and window size for high dpi.

---

vita3k/app/src/app_init.cpp
vita3k/config/include/config/config.h
vita3k/config/src/config.cpp
vita3k/gui/src/settings_dialog.cpp

- Add cpu backend choice in setting dialog.
- Add cpu backend used in log.
- reafctor cpu backend in app init

gui/settings dialog: Add cpu backend choice.

---

vita3k/gui/src/app_selector.cpp

- just see on my psvita, it only using maximum 6 app open in same time on live area
- also new app open is open in first position and no in last, and delete so last app it already 6 app opened

live area: small refactor app list opened.

---

vita3k/cpu/include/cpu/common.h
vita3k/kernel/include/kernel/thread/thread_functions.h
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceFiber/SceFiber.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp

- Correct copying data to stack in startthread
- Add some functions for debugging
This one fixes the crash happening in the boot stage of gravity crash full version. (it's still in black screen so don't be hyped yet)

Correct copying data to stack in startthread

---

vita3k/modules/SceCommonDialog/SceCommonDialog.cpp

- it crash if running on other type with status is finished.
- fix crash on Catherine full body.
- boot more with logo

modules/SceCommonDialog: Fix crash on SceSaveDataDialogGetResult.

---

lang/en-gb.xml
lang/en.xml
lang/fr.xml
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/private.h
vita3k/gui/src/settings.cpp
vita3k/interface.cpp

- Adding dialog warning for can close app if one running.
- Improve update app list openend more psvitya close, app already open is move in first place, and for one app run if is last app in list, it erase just before it.

gui: Add dialog warning for app close.

---

vita3k/renderer/src/gl/renderer.cpp

- fix occult nine render.
- text keep missing

renderer: Add color format U8U8_AR.

---

vita3k/renderer/include/renderer/functions.h
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/texture_format.cpp

This was causing heap corruption in gravity rush.

Fix ubc texture with width or height not divisible by 4

---

vita3k/renderer/include/renderer/functions.h
vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/texture_format.cpp

The ubc was swizzled outside 4x4 block so my recent pr that assumed linear layout was wrong. 
This pr reverts that recent pr and tris to solve the original problem again. It does by padding destination buffer to multiples of 4. It will not run out of source because source is destined to have enough amount of blocks. (since bc format doesn't define "half block") Texture will be read correctly by opengl since it's using appropriate stride that accounts for padding and supply "orig_width," and "orig_height" as texture size.

Fix ubc with width or height not divisible by 4 again

---

vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/kernel/src/thread/thread.cpp
vita3k/modules/SceFiber/SceFiber.cpp
vita3k/modules/SceFiber/SceFiber.h

There were many bugs in our fiber implementation mostly on dealing of status, returntothread, no context fiber, and runOn notification. This pr reimplements fiber with cleaner code.
- Gravity rush demo random crash at the beginning.
- Saenai random crash. (seems to be fixed; need to confirm)

kernel: Reimplement SceFiber

---

vita3k/gui/src/live_area.cpp

- resogun using demo mode but no have retail folder.
- fix also stupid forget for using app index for app title.
normally game have license with sku flag choise 1/3 have also retail folder for full template because other is writed demo etc; bur resogun using this mode, but no have retail folder, it using only one template for 2 mode

gui/live area: fix get template if retail folder no exist.

---

vita3k/cpu/include/cpu/impl/interface.h
vita3k/modules/SceFiber/SceFiber.cpp

Fixing some stupid mistakes. Cpu mem leak happens when you create bunch of threads. The derived destructor was not called so cpu was not freed even after thread was freed.

Fix fiber regression and remove cpu mem leak

---

vita3k/cpu/src/dynarmic_cpu.cpp

Ensure all raised exceptions are handed.
Also reduce tick count (it's actually internally interpreted as a signed integer).

arm_dynarmic: Minor changes

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/gui.cpp
vita3k/gui/src/trophy_unlocked.cpp

In master, i have see case on MS RC, i have get 3 trophy in same time with using my psvita save, and Unlocked dialog + notification have glitched with get 3 time same trophy unlock.
- fix trophy order and out in unlocked and notif dialog if get few trophy in same time.
| Before | After |
| --- | --- |
| <img  src="https://user-images.githubusercontent.com/5261759/118427410-6856c500-b6cd-11eb-9130-24cd2abff257.png"> | <img  src="https://user-images.githubusercontent.com/5261759/118426978-82dc6e80-b6cc-11eb-8467-4928089aabc7.png"> |

gui: fix trophy dialog for multiple unlock in same time.

---

vita3k/CMakeLists.txt
vita3k/app/src/app_init.cpp
vita3k/interface.cpp
vita3k/kernel/CMakeLists.txt
vita3k/kernel/include/kernel/cpu_protocol.h
vita3k/kernel/include/kernel/functions.h
vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/sync_primitives.h
vita3k/kernel/include/kernel/thread/thread_functions.h
vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/kernel/src/cpu_protocol.cpp
vita3k/kernel/src/kernel.cpp
vita3k/kernel/src/sync_primitives.cpp
vita3k/kernel/src/thread.cpp
vita3k/main.cpp
vita3k/modules/SceAudio/SceAudio.cpp
vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/modules/SceIme/SceIme.cpp
vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp
vita3k/modules/SceNetCtl/SceNetCtl.cpp
vita3k/modules/SceNpManager/SceNpManager.cpp
vita3k/modules/module_parent.cpp
vita3k/ngs/src/ngs.cpp

You can call guest function through three ways.
1. request_callback(current_thread, address, args) inside the interrupt handler
This queue a callback to current thread. After hle function returns, the thread will run the callback function, and return to the previous point. Any number of callbacks work, callback inside callback also works.
2. run_guest_function(kernel, address, args) from anywhere
This will queue a quest function call to single global worker thread. The worker thread will run requested quest functions one by one. This function is blocking and returned value is what guest function returned.
3. run_guest_function(kernel, worker_thread, address, args) from anywhere
If you don't want to use global worker in concern of bottleneck, you can create additional thread and specify …

Redesign guest function calling

---

vita3k/config/include/config/config.h
vita3k/config/include/config/state.h
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp
vita3k/modules/SceAudiodec/SceAudiodecUser.cpp

After request change, i so add option in setting dialog for can disable At9 audio decoder in setting dialog.
Obligatory request for moment in gravity rush.
- Hack for moment external for lle MP4

config: add disable at9 audio decoder option in settings dialog

---

vita3k/gxm/include/gxm/types.h
vita3k/gxm/src/textures.cpp
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/texture.cpp

- Fix some texture missing on gravity rush, like white texture for button confirm on option/ingame dialog, or also in texture view inside render doc
- Texture of dialog choice

modules: Fix texture size for swizzled and cubed

---

vita3k/interface.cpp

User and myself have see mai dump boot is roken, and i have thinks too, using original eboot is better for compat, mai dump is strange and ussless for emu.
- fix boot mai dump app and is better for compat.
PS: @sunho i know you fwill fix it later, like need fix lib kernel loading,  but for mai-dump is beter using origin eboot.

interface: load original eboot if detect mai-dump.

---

vita3k/gui/src/app_selector.cpp
vita3k/gui/src/content_manager.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/information_bar.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/settings.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/gui/src/trophy_collection.cpp
vita3k/gui/src/user_management.cpp
vita3k/interface.cpp

- interface: small refactor press key event.
- fix title id for sys app without fw.
- fix apply in general config.
- merge Save & Apply in one button in settings dialog.
- Add close button in setting dialog. (small cross have get me hungry on my tab 😂 )
- disable toogle gui and live area call if setting dialog/control dialog is open 
- set default background for system app if missing fw.
- small change button in setting dialog.
- fix  position broken recently for Day moment AM/PM in start screen and in formation bar

gui: fix some small things.

---

vita3k/gui/src/app_selector.cpp

- Add fake button for can view directly what game have custom config, i have lost time with all time check what game have custom config or no.
Why fake button ? already, button is no possible click because have selectable, and is good because, using text only alone is bad, for font text, can be hidden by depending color of icon.
Why CC ? because no can using icon, or need create it, so i have just founded CC for Custom Config.
-  disable count of start screen if any settings or control dialog is open.
- In list
- In grid

gui/app selector: Add button on app icon if custom config exist.

---

vita3k/shader/src/usse_utilities.cpp

In an example shader I use this assembly:
VF16MUL pa0.xyzw pa2.111w pa0.xyz1
Which is supposed to multiply a color value with a constant alpha value of 1.0 with a given alpha value in another register. In the current generator this doesn't happen and the alpha is some random value and leads to wrong results, see:
Note the character sprites and the alpha on some of the groundwork in which occluded geometry shines through.
The corrected version leads to a more expected outcome:

Fix constant swizzle accessors like pa2.111w

---

vita3k/kernel/src/sync_primitives.cpp

This reverts commit 587db019864f15305756681df52a065916d491ac.
Like request, revert this commit for fix regression.

Revert "kernel: Add missing lock"

---

lang/en-gb.xml
lang/en.xml
lang/es.xml
lang/fr.xml
lang/it.xml
lang/ru.xml
lang/zh-s.xml
lang/zh-t.xml
vita3k/config/include/config/config.h
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/gui/src/settings_dialog.cpp

Like sugested in one doc 😄 , i have so remplaced launch one last app with can load last 10 apps
- settings dialog: refactor display title in custom config.
- custom config: fix warning of xml file.
- for new custom config title.
- for new last loaded apps

config: change last app to vector last loaded apps.

---

vita3k/config/include/config/config.h

All games using libult are essentially broken in unicorn. (which is quite a lot of games) Even if games use unimplemented/unpredictable instructions, we've got unicorn fallback. Why not making dynarmic default.

config: Use dynarmic as default

---

vita3k/kernel/include/kernel/debugger.h
vita3k/kernel/src/debugger.cpp

Happens when Debug settings are configured prior to initialization of kernel

debugger: Fix crash when update_watches is called without valid parent

---

vita3k/gui/src/app_selector.cpp
vita3k/gui/src/information_bar.cpp

I have see after get one or some new notice, it is no select in blue if emu reboot, but only if get new notice during current running, i have so see in code, value for set notice info new is no set on init notice info.
- reworks order saved in xml.
- enable seletable for now all notification, with new code, game can switch in other game, so old code is no necessary anymore.
- fix position for cc button in app selector.

gui/Notice: fix load new notice selected.

---

vita3k/cpu/src/dynarmic_cpu.cpp
vita3k/host/src/load_self.cpp
vita3k/interface.cpp
vita3k/io/include/io/util.h
vita3k/kernel/include/kernel/state.h
vita3k/kernel/include/kernel/types.h
vita3k/kernel/src/kernel.cpp
vita3k/mem/include/mem/ptr.h
vita3k/modules/SceFiber/SceFiber.cpp
vita3k/modules/SceNgsUser/SceNgs.cpp
vita3k/renderer/src/scene.cpp

- mem: Allow Ptr = nullptr
- kernel: Ignore some invalid process param
- dynarmic_cpu: Disable fastmem when optimization is off
- vita3k: Remove mai dump hack
- io: Correct life cycle of vita_loc
Various fixes to make it working.

Fix booting of old vitasdk homebrew in dynarmic

---

vita3k/renderer/include/renderer/types.h
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/state_set.cpp
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/usse_translator_entry.cpp

Fix vitagl clipping.
Together with the recent kernel pr, SuperMarioWar vita port renders almost perfectly.

renderer: Overhaul fragment masking

---

vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp

Should bind framebuffer early cause set_context clear depth etc.

renderer: Bind mask buffer properly

---

vita3k/mem/src/mem.cpp

Mark the zero-page as invalid in the page-table.
This is so that the page-table access of the protected zero page will fail gracefully rather than crash.

mem: Zeropage is invalid

---

vita3k/gxm/include/gxm/types.h
vita3k/renderer/src/gl/draw.cpp

If both side is disabled, fragment shader discards every pixel, not writing to depth. But, we want it to still write to depth as long as depthwrite is enabled. This pr just mask color when both side is disabled to mitigate the issue. This fixes the regression in asphalt and progresses it by fixing the skybox.
I personally don't like the way we're implementing disabled side. Discarding pixel according to facing can be done by culling, so we don't need to have some sort of flag in fragbufferblock or have slow conditional discarding in fragment shader. But, I'm not sure what's going to happen when there is culling at the same time disabled side. So, I'm just keeping it for now.

renderer: Allow writing depth when both side fragment program is disabled

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/archive_install_dialog.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/information_bar.cpp
vita3k/gui/src/pkg_install_dialog.cpp
vita3k/host/src/license.cpp
vita3k/interface.cpp

Refactor and reworks archive install dialog for can install exemple 100 app/dlc/theme in one time with select directory.
- allow can using folder for install some archive in same time.
- new select choice
- Exemple on install directory
- after finish

gui/archive install dialog: refactor dialog.

---

vita3k/config/include/config/config.h
vita3k/cpu/src/dynarmic_cpu.cpp
vita3k/gdbstub/src/gdb.cpp
vita3k/gui/src/allocations_dialog.cpp
vita3k/gui/src/disassembly_dialog.cpp
vita3k/mem/CMakeLists.txt
vita3k/mem/include/mem/allocator.h
vita3k/mem/include/mem/functions.h
vita3k/mem/include/mem/ptr.h
vita3k/mem/include/mem/state.h
vita3k/mem/include/mem/util.h
vita3k/mem/src/allocator.cpp
vita3k/mem/src/mem.cpp
vita3k/mem/tests/allocator_tests.cpp
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/texture_cache_state.h
vita3k/renderer/src/creation.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/texture_cache.cpp

- external: Update dynarmic
- mem: Fix bugs in bitmapallocator
- mem: Support windows write protect
- mem: Properly decommit memory in windows
- renderer: Add write protect based texture dirty flag
- mem: Use custom allocator and optimized page table
- dynarmic_cpu: Don't use page_table
Attempt to optimize texture cache further and use custom allocator.

Implement hashless texture cache

---

vita3k/modules/SceGxm/SceGxm.cpp

after see issue i get with this game is caused by shader issue like some toher game,  and no by this function directly, i thinks can stub it for now and fine
- allow some game move to ingame, ex: valkyrie drive.
- hack shader get fine render
this game and one other move to bootable to ingame

modules/SceGxm: Stub BeginSceneEx.

---

vita3k/renderer/src/gl/texture_formats.cpp

- fix gl error and visible render on Valkyrie drive.
- tv crypted effect and black and white is caused by one frag shader broken.
- using hack on this broken shader
Render keep have glitch on color, skin is full white etc

gl/texture_formats: fix value for U2F10F10F10.

---

vita3k/interface.cpp

See on dlc for escape plain, and maybe other, some content can using empty directory request, before it no create this directory if is empty.
Improve in same time this code

interface: fix install empty directory.

---

CMakeLists.txt

Make CMake skip b2 compilation (Boost configure step) if it already exists to save time on CMake re-runs.

Build system: Skip Boost's b2 compilation if it already exists

---

building.md
gen-windows.bat

command is wrong, number is inversed for cmake, fix generate project.
- add pause in end script for can view result before close alone.

project: fix typo on gen-windows.

---

lang/en-gb.xml
lang/en.xml
lang/es.xml
lang/fr.xml
lang/it.xml
lang/nl.xml
lang/ru.xml
lang/zh-s.xml
lang/zh-t.xml
vita3k/config/include/config/config.h
vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/live_area.cpp
vita3k/gui/src/main_menubar.cpp
vita3k/interface.cpp
vita3k/kernel/include/kernel/object_store.h
vita3k/main.cpp

Add time app used inside app context menu in information.
Refactor code for can using new value for no get double value exist for same things.
Using so now app list by user.
- move cfg to new value.
- is fake time used here off course, is just for test etc :D

gui: add time app used & refactor.

---

vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/main_menubar.cpp

Refactor delete app with delete all content relate app.
- prevent crash if no success delete app.
- fix open app folder when app path have space.
- menu bar/last apps used: prevent crash when app no found.

gui: some refactor for delete app and some crash fix.

---

vita3k/gui/include/gui/functions.h
vita3k/gui/include/gui/imgui_impl_sdl_state.h
vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp
vita3k/gui/src/archive_install_dialog.cpp
vita3k/gui/src/gui.cpp
vita3k/gui/src/imgui_impl_sdl.cpp
vita3k/gui/src/pkg_install_dialog.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/gui/src/user_management.cpp
vita3k/interface.cpp

Add cache of apps list for can get boot emu more quickely after first time.
- boot emu (without icon), take littarly 1 sec compare 50 sec  in first boot with 1420 app installed.
- add async load app icon for get open emu very quickely in first boot

gui: add cache of apps list.

---

vita3k/gui/include/gui/state.h
vita3k/kernel/src/load_self.cpp

gui: fix missing atomic header

---

vita3k/shader/src/translator/branch_cond.cpp

Correct bits of VTST sources on non-F32 data type. fix already two game for move it to Ingame/playable.
- Fix A virus named tom & ONE PIECE Unlimited WR.
- One piece go ingame
with some shader hack
- A virus named tom to

shader: fix shader crash for a virus named tom

---

vita3k/io/src/io.cpp

I've removed a condition that doesn't make sense to me in order to fix dhewm3 finding a file.

io: add IFREG if is_regular_file

---

vita3k/config/include/config/state.h
vita3k/gui/src/controls_dialog.cpp
vita3k/gui/src/settings_dialog.cpp
vita3k/modules/SceCtrl/SceCtrl.cpp
vita3k/modules/SceSysmem/SceSysmem.cpp

Move PS TV mode in custom config.
- No all game support ps tv mode, some can said controller no connected if is used, so request separate in for allow custom config by game.

setting: move PS TV mode custom config.

---

lang/ja.xml

Complette part missing or japanse translate causing empty string on setting.

lang: Add more string translate.

---

vita3k/io/src/device.cpp
vita3k/io/src/io.cpp

some games hardcode backslashes in their paths and this causes linux and macos to fail when checking if the path exists.
we do replace invalid slashes in the path but only AFTER checking if the path exists. this PR replaces the slashes before.
i moved the invalid slashes replacement to `translate_path` so `system_path` can be a valid path on *nix system.
games like TxK and minecraft boot further on unix systems with this fix

io: fix backslashes

---

vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp

- fix crash on some game using it with ignore this module.
relate issue https://github.com/Vita3K/Vita3K/issues/1095
some game like gravity duck/rush rover move from nothing to full playable.

modules/SceModulemgr: workaround for rgpluginsgm_psvita module.

---

vita3k/renderer/src/texture_format.cpp

- fix crash on one game with fix also render on it.
origin of pr for this code
https://github.com/Vita3K/Vita3K/pull/543 in commit https://github.com/Vita3K/Vita3K/commit/963c1699654a2ce694ec1f302d1a403ea0ee8531#diff-0a445e58d6c273c10266b1ed8e609cccbcaf2164c74780845336ee5720514e68
never touched again after
fix cvrash on this game and get pêrfect ingame render

fix calcule of tiled texture

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/gui.cpp
vita3k/host/include/host/state.h
vita3k/io/include/io/state.h
vita3k/io/src/io.cpp
vita3k/main.cpp

Is close things in my recent pr for savedata, some game using diferent value for store dlc compare title id, example one app have diferent title id, and using same dlc folder for this all id
- should fix game no found dlc after install it.
- in app list, i have this using diferent addcont id compare title id

addcont: Add support of INSTALL_DIR_ADDCONT value in sfo.

---

vita3k/kernel/include/kernel/object_store.h

Regression caused by commit: https://github.com/Vita3K/Vita3K/commit/8576b497a75039e4301203234a3203f964b15df6 in pr : #1388
For user and  want testing this game.
you need this shader hacked for can get playable.
[6b232cb61f61808c116740b095bdae607996a730aaddbb7d315d5d0f9c9b0e08.zip](https://github.com/Vita3K/Vita3K/files/7371604/6b232cb61f61808c116740b095bdae607996a730aaddbb7d315d5d0f9c9b0e08.zip)
put it with using emu on right click on this game and click on open folder/shader cache, and set file inside
- this, also fix some unity game
with shader hacked and commit here, you can finish tutorial without any problem.

kernel: fix crash when try erase object no exist

---

vita3k/kernel/include/kernel/types.h
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
vita3k/modules/SceLibKernel/SceLibKernel.cpp

- implement sceKernelGet(EventFlag/Cond)Info.
- move sceKernelCreateCond inside it and refactor sceKernelGetThreadInfo.
fix lock on boot for some unity game
- fix crash on first logo

SceKernelThreadMgr: implement 2 function getinfo and small refactor

---

vita3k/kernel/include/kernel/types.h
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
vita3k/modules/SceLibKernel/SceKernelForMono.cpp
vita3k/modules/SceLibKernel/SceKernelForVM.cpp
vita3k/modules/SceLibKernel/SceLibKernel.cpp

Stub Resume/suspend thrad ForMono/Vm used by all unity game.
Prepare sceKernel(Get/Set)ThreadContextForVM for futur implement.
fix boot on 50 unity game, with go to playable on menu/intro, if crash on avplayer just using lle.
thx @sunho for help 
- go ingame for first time
- story mode works  without any error
- acces instant ingame after video, no error
- first time ingame
and more....

modules/SceKernelThreadMgr: stub SceKernel(Resume/Suspend)ThreadForVM.

---

vita3k/modules/SceNet/SceNet.cpp

- founded after try fix boot of corps party with hang on setup trophy.
@bookmist give me good error normally returned.
- fix infinite load on corps paarty//fat princess/tetris ultimate, counter Spy,  Asdivinie heart and more...
- can go load game file after trophy setup and go ingame
- can go and load ingame
- fix infinite loading check connexion, get start, menu, and ingame (warning on your ears)
- fix infinite loading on first logo and go ingame

modules/SceNet: fix return value in Init when is already inited.

---

vita3k/renderer/src/state_set.cpp

- fix scissors value, relate a cropped corners on gintama.

renderer: Fix scissors value being down aligned incorrectly.

---

vita3k/modules/SceMp4/SceMp4.cpp

- After my pr of add Scemp4 library have get game stop boot on using this function, this function normally return size, so here i put fake size works fine. 
- fix Persona 4 GOLDEN (USA/EURO) pass intro video and go menu like before add this library.

modules/SceMp4: Stub sceMp4OpenFile.

---

vita3k/gui/src/app_selector.cpp

- Add clock after date in last time column.

gui/app selector: add clock in last time for No grid mode.

---

vita3k/gxm/include/gxm/types.h
vita3k/modules/SceGxm/SceGxm.cpp

- sceGxmPrecomputedDrawSetParamsInstanced.
- implement sceGxmPrecomputedVertexStateSetAllTextures & sceGxmPrecomputedVertexStateSetTexture.
- implement add texture for vertex texture in sceGxmDrawPrecomputed.
- add support of vertex texture in SceGxmPrecomputedVertex.
thx to @pent0, for found myè stupid forget things.
- stub sceGxmPrecomputedDrawSetParamsInstanced give this game go ingame and playable.

implement some function for precomputed.

---

vita3k/modules/SceGxm/SceGxm.cpp

- fix loop set value too much, max size is 14, so have only 14 array available (0-13), fix crash with dynarmic error on load ingame

modules/SceGxm: fix regression in loop of both StateSetAllUniformBuffers

---

.gitmodules
external/CMakeLists.txt
vita3k/codec/CMakeLists.txt
vita3k/codec/include/codec/state.h
vita3k/codec/src/atrac9.cpp
vita3k/ngs/src/modules/atrac9.cpp

- move atrac9 decoding to libatrac9
- fix sound quality of some game when using atrac9 decoder
We have more control and error codes, also avoid some shortcoming of
ffmpeg port

codec: Use libatrac9 library for atrac9 decoding

---

vita3k/gxm/include/gxm/types.h

- fix default value for SceGxmStencilFunc.

renderer: Correct initial stencil func

---

vita3k/renderer/src/gl/texture_formats.cpp

- set correct value of SCE_GXM_TEXTURE_ADDR_MIRROR_CLAMP in translate_wrap_mode.
- opengl 4.3 should be compatible with this value.

texture formats: fix return value of TEXTURE_ADDR_MIRROR_CLAMP.

---

vita3k/shader/src/gxp_parser.cpp

- fix one regression of some game causing black or white screen.
- like on durara relay/uncharted fight for fortune/flow

shader: Correct default UB index in input analyzing.

---

vita3k/renderer/src/gl/renderer.cpp

- fix very old issue with some part of screen cut
and more...

renderer: Fix depth and stencil clear limited to scissor on context set

---

vita3k/renderer/src/gl/texture_formats.cpp

render of replay is perfect now

renderer/texture formats: remove warn of TEXTURE_BASE_FORMAT_SE5M9M9M9.

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp

- print modules mode used in log like string.
- gui/settings_dialog: using loop for modules mode view.

interface: print string of modules mode used in log.

---

vita3k/renderer/src/batch.cpp

- report by tester,  master have actually get regression on some game, particularity on low cpu 
- prefer using avg scene per frame when is used iside pad gxm function

renderer/batch: small improvement of process batch.

---

vita3k/gui/src/live_area.cpp

- using like psvita when live area content is missing
- reference
- result

live area: using app icon when gate icon no exist.

---

.github/workflows/c-cpp.yml
building.md
gen-windows.bat
vita3k/gxm/src/gxp.cpp
vita3k/io/include/io/device.h
vita3k/ngs/src/modules/master.cpp
vita3k/util/src/util.cpp

- add support of Visual Studio 2022 (VC143), with update boost on 1.78, and with update gen window

build: add suport of VS 2022.

---

vita3k/renderer/src/pvrt-dec.cpp
vita3k/renderer/src/texture_cache.cpp

This PR fixes PVRTII texture decompression issue caused by uninitialized memory in the modulation parameter arrays.
It also includes a fix for a Clang-specific issue uncovered by the PVRTII decompression fix and caused due to compiler optimizations that makes texture caching fail. The issue is likely caused by some optimizations done by Clang conflicting with the way pointers are implemented in the texture caching system, so the whole cache system should be revised at some point to detect more possible points of failure related to memory protection but for now this should do the job.

renderer: Fix PVRTII decompression

---

vita3k/gui/include/gui/functions.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/compile_shaders.cpp
vita3k/io/src/io.cpp
vita3k/main.cpp
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/gl/state.h
vita3k/renderer/include/renderer/state.h
vita3k/renderer/include/renderer/types.h
vita3k/renderer/src/gl/compile_program.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/load_shaders.cpp

- implement pre-compile shaders and program in boot game.
- Add progress bar during pre compile shader.
- remove useless shaderlog in io and app context
- move shader path in good path
- Draw pre compile shaders progress bar
video demonstration
https://www.youtube.com/watch?v=bYAXP3wmZq4

Implement pre-compile shaders cache.

---

vita3k/gui/src/app_context_menu.cpp

Some linux systems, when vita3k opens the browser through the Download Firmware button it hangs the emulator until the browser closes, this is due to xdg-open waiting for the process to finish, although the reason of why it only happens on some systems its unknown, it doesn't bring any downside of transferring the browser to a unattached background job.

vita3k: Fix xdg-open hanging the emu on some linux systems

---

vita3k/main.cpp

fixes typos on File dropped not supported and window title when compiling shaders

vita3k: Fix some typos

---

vita3k/gui/src/common_dialog.cpp

Fix the error that makes vita3k-git not being able to build in the Arch AUR (https://aur.archlinux.org/packages/vita3k-git), as described in the comments the error comes from the functions argument being only no_save_data,  while it should be `("%s", no_save_data)`

gui: Fix string literal not being string literal

---

vita3k/dialog/include/dialog/types.h
vita3k/host/include/host/app_util.h
vita3k/modules/SceAppUtil/SceAppUtil.cpp
vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
vita3k/modules/SceDriverUser/SceAppMgrUser.cpp

i split other pr for set other things no reélate app util function.
- modules/SceCommonDialog: fix savedata dialog when emptyparam is null.
- refactor check_empty_param for no have double code.
- app util: clean double value.
- modules/(SceAppUtil/SceAppMgrUser): set good value name.

modules/SceCommonDialog: fix savedata dialog when emptyparam is null.

---

vita3k/gui/src/app_context_menu.cpp
vita3k/io/src/io.cpp
vita3k/main.cpp
vita3k/renderer/src/gl/load_shaders.cpp

- isolate inside shaders cache only shaders file  generated, without gxp/dsm file

shaders: split shaders cache to shaderlog.

---

vita3k/modules/SceGxm/SceGxm.cpp

- Implement sceGxmRenderTargetGetDriverMemBlock.
- should fix crash on some game.
get ingame for Senran kagura/to love ru battle ectasy and more

modules/SceGxm: Implement RenderTargetGetDriverMemBlock.

---

vita3k/modules/SceRegistryMgr/SceRegMgr.cpp

- stub sceRegMgrGetKeyInt used by psp emu with give value request.
(real implementation request can read config file)

modules/SceRegMgr: stub sceRegMgrGetKeyInt for psp emu.

---

vita3k/modules/SceDisplay/SceDisplay.cpp
vita3k/modules/SceDisplay/SceDisplay.h
vita3k/modules/SceDriverUser/SceDisplayUser.cpp

- implement sceDisplayGetFrameBuf.
- fix crash on Danganronpa Another Episode: Ultra Despair Girls move from intro to playable.
- delete one declaration no used.
- have some graphical glitch on texture, texture moviçng with character moving

modules/SceDisplay: Implmement sceDisplayGetFrameBuf.

---

vita3k/config/include/config/config.h
vita3k/gui/src/manual.cpp
vita3k/gui/src/perf_overlay.cpp
vita3k/gui/src/settings_dialog.cpp

- Add position choice of performance overlay
- add low detail for separe fps alone and fps + avg
- code refactor

gui/perf overlay: Add position select and refactor.

---

vita3k/gui/src/firmware_install_dialog.cpp

- gui/firmware install dialog: Init theme after install firmware.
- fix refresh sys app icon and theme without reboot request.
- add button for download font package if is missing after install fw.

gui/firmware install dialog: Init theme after install firmware.

---

vita3k/gui/include/gui/state.h
vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/app_selector.cpp

small gui stuff add, after i have played more 24h on one game, see 25h is ugly, so i have thinks add days, and after add in same time week, exemple
- fix one things for no can shows start screen when app info is open
- time player > 1 days 
- fake time for time played more 1 weeks (for testing code)

gui/app_context_menu: Add week and days in  time used.

---

vita3k/shader/src/translator/alu.cpp
vita3k/shader/src/translator/ialu.cpp

An optimization of shader recompiler. If second operand of OR operation is constant zero, then implement this OR operation as assignment operation.
Usually this also mean no conversion of float to uint and back to float. Code duplication is needed to avoid this unneeded conversion.
It's a small optimisation, but I hope it's just a first step.

shader/translator: optimisation. implement operation [any OR 0] as assign

---

external/CMakeLists.txt

only visual makeup. no code changes. Some external libraries were in the root MSVC solution folder, I move their projects in solution into external subfolder.

external: put external libraries into external folder in the solution

---

vita3k/shader/src/translator/data.cpp

Refactored to prefer `std::any_of` over raw range-for loop.

shader/translator: refactor using standard algorithms

---

vita3k/modules/SceGxm/SceGxm.cpp

- modules/SceGxm: implement both _sceGxmTextureSet(Height/width)
- fix log spam when texture format is tasked on sceGxmTextureSetWidth.

modules/SceGxm: implement both _sceGxmTextureSet(Height/width)

---

vita3k/gui/src/app_context_menu.cpp
vita3k/gui/src/content_manager.cpp

- the ‘DLC’ rename to ‘AddCont’ looks like more reasonable, and the 'AddCont' option is based on psvita devkit / testkit system.

gui/app context menu: rename looks like more reasonable.

---

vita3k/gxm/CMakeLists.txt
vita3k/gxm/include/gxm/functions.h
vita3k/gxm/include/gxm/types.h
vita3k/gxm/src/attributes.cpp
vita3k/gxm/src/gxp.cpp
vita3k/renderer/CMakeLists.txt
vita3k/renderer/include/renderer/gxm_types.h
vita3k/renderer/include/renderer/surface_cache.h
vita3k/renderer/include/renderer/types.h
vita3k/renderer/src/color_format.cpp
vita3k/shader/include/shader/usse_translator_types.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/util/include/util/function_info.h

With this change, we are separating the public SceGxm enums/structs from Vita3K's internal implementation of SceGxm opaque types, and also internal Vita3K structs/contexts.
This allows dropping the dependency of `gxm` from `mem` so that `gxm` becomes more generic with very few dependencies to Vita3K.
Vita3K's internal implementation of SceGxm opaque types are moved to `vita3k/renderer/include/renderer/gxm_types.h`.

gxm: split public SceGxm types and internal+opaque SceGxm types

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/texture_cache.cpp

fix precompute draw when state is null.
- fix missing render

modules/SceGxm: fix handle precomputation when state is null.

---

vita3k/shader/src/usse_utilities.cpp

- fix mistake with inverses if condition for get number of contener when is vector.
That fix value get all time 1 also when is vector

shader/usse utilities: fix get comp_count value.

---

vita3k/gui/src/user_management.cpp

We should make these warnings/messages in windows be treated as errors so that it doesn't happen again and linux can compile

gui: Fix some elemements not using string literals

---

vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
vita3k/modules/SceAudiodec/SceAudiodecUser.h
vita3k/modules/include/modules/library_init_list.inc

Fix a crash that happens when multiple calls to sceAudiodecInitLibrary and sceAudiodecTermLibrary are done.
sceAudiodecInitLibrary is called once for each codec used. However the object AudioCodec is discarded from the object store after a call to sceAudiodecTermLibrary, even though only decoders associated with the codec terminated should be discarded.
As an example the following code is valid but crashes in Vita3K:
sceAudiodecInitLibrary(codec1)
sceAudiodecInitLibrary(codec2)
sceAudiodecTermLibrary(codec2)
Use codec1 -> crash : AudioCodec could not be found
How I fixed it is by only removing decoders associated with the codec passed as a parameter to sceAudiodecTermLibrary when it is called. 
This fix allows Tales of Hearts R to get to the startup menu (and even ingame with AT9 audio …

modules/SceAudiodec: Handle multiple init and term library calls with different codecs

---

vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp

After a bit of reverse engineering, it looks like _sceKernelDeleteLwMutex returns value 0x80020006 (SCE_KERNEL_ERROR_ILLEGAL_ADDR) when workarea is nullptr.
This pull request replicates this behavior in the HLE (instead of crashing).
This allows Tales of Innocence R to go ingame.

modules/SceKernelThreadMgr: Handle null workarea for _sceKernelDeleteLwMutex

---

vita3k/gdbstub/src/gdb.cpp
vita3k/kernel/src/thread.cpp

When a thread is resumed immediately after being paused, a race condition can occur between the thread transitioning to the wait state and resuming at the same time.
To prevent that, the thread mutex must be locked in the resume function, to make sure the thread is not going into the wait state at the same time.
This race condition can occur in the vblank thread. This fixes the random freeze in Tales of Innocence R.

kernel: Make ThreadState resume thread safe

---

vita3k/kernel/include/kernel/thread/thread_data_queue.h
vita3k/kernel/src/sync_primitives.cpp

This pull request contains fixes for the following 3 bugs in sync_primitives.cpp:
- When calling `erase` on a `PriorityThreadDataQueue`, all waiting threads with the same priority will be erased because a multiset tests equalities using `<` and not `==`. 
- All mutex locks in sync_primitives are acquired the following way: acquire the primitive (event/mutex/semaphore...) mutex first then the thread mutex second. The same must be done for handle_timeout in order to prevent deadlocks. Unlocking one mutex before locking the other kind of works but it allows race conditions to happen.
- Fix race condition in `eventflag_set`: if the thread mutex cannot be acquired immediatly, the thread will sleep forever. The thread mutex is locked to prevent this issue. There should not be any deadlock with …

kernel: Fix deadlocks and handle_timeout

---

vita3k/kernel/src/sync_primitives.cpp

When waiting for a primitive (event, semaphore, mutex, ...) with *timeout = 0, we should resume immediately the thread instead of considering it the same way as timeout = nullptr which is not the case ([https://wiki.henkaku.xyz/vita/SceKernelThreadMgr#sceKernelWaitEventFlag](https://wiki.henkaku.xyz/vita/SceKernelThreadMgr#sceKernelWaitEventFlag)).
This fixes the freeze during startup on A.W. : Phoenix Festa.

kernel: Immediatly resume from wait if *timeout is 0

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/gxm_types.h

When generating a `SceGxmPrecomputedDraw`, `SceGxmPrecomputedFragmentState` or `SceGxmPrecomputedVertexState`, we always generate one with the maximum possible size and return its size accordingly when asked.
However, this makes these objects weigh much more than expected and can result in a crash if a buffer too small was allocated. This is the case in uncharted where a 2M buffer is used to allocate all 3.5k+ `SceGxmPrecomputedFragmentState`and `SceGxmPrecomputedVertexState`. It is not enough if they all have the maximum size.
Because arrays now don't have a fixed size anymore and we cannot add any overhead, I used pointers to replace existing `std::array`.
This allows Uncharted to get to the boot menu.

modules/SceGxm: fix precomputed state always having max size

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/gxm_types.h

Fix GxmContextState's stream_data size from my previous pull request #1694. Also contains slight code readability improvements.

modules/SceGxm: fix array size for GxmContextState stream_data

---

vita3k/display/include/display/functions.h
vita3k/display/src/display.cpp
vita3k/kernel/include/kernel/thread/thread_state.h
vita3k/kernel/src/thread.cpp
vita3k/modules/SceDisplay/SceDisplay.cpp

- `sceDisplayGetVcount` should only return the lower 16bit value of the vcount
- `sceDisplayWait...Multi(CB)` should cause the thread to wait for a specified amount of vblank from the last time it woke up to a display_wait and not from the time this function was called
- Fix some really tight race conditions, like getting a thread from its id without acquiring a mutex or the possibility that the vblank thread can be launched more than once (happened on my computer).
The second part allows Tales of games to run at a stable 30fps.

display: Implement proper behavior of SceDisplay functions

---

vita3k/codec/include/codec/state.h
vita3k/codec/src/decoder.cpp
vita3k/codec/src/h264.cpp
vita3k/modules/SceVideodec/SceVideodecUser.cpp

- Fix wrong resolution of video in few game (Street fighter, omega labyrinth, etc...)
thx special for @bookmist for disasm function.

modules/SceVideodecUser: Add support to back res value of AvcdecDecode.

---

vita3k/display/include/display/functions.h
vita3k/display/src/display.cpp
vita3k/modules/SceDisplay/SceDisplay.cpp

`sceDisplayWaitSetFrameBuf(Multi)` was broken since #1697, leading to a regression causing some games to go faster or slower than expected because of the wrong wait time.
This allows the fps to go back to 30 (from 20) in AOT Wings of Freedom and Jet Set Radio.

display: fix sceDisplayWaitSetFrameBuf

---

external/CMakeLists.txt

standalone soundstretch application is just don't needed

external/SoundTouch: remove soundstretch build

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/include/renderer/gxm_types.h
vita3k/renderer/src/sync.cpp

When there are two close calls to `sceGxmDisplayQueueAddEntry` (in particular when the second one is done before the first one has finished). There is a time window where between the time the first call and the second call is done, where a scene can be drawn and mess the buffer to be displayed.
One simple fix is to add wishlist calls to `sceGxmDisplayQueueAddEntry`. However it makes this function blocking (functions calling it can easily wait 2 frames). In order to prevent performance deteriorations, I had to implement specific sync functions in order to allow `sceGxmDisplayQueueAddEntry` calls to be non-blocking between them but to be blocking for other calls.
This also fixes a really tight softlock that can happen in `wishlist`.
This fixes Oreshika's intro and partially the intro of …

modules/SceGxm: Handle consecutive calls to sceGxmDisplayQueueAddEntry

---

vita3k/app/src/screen_render.cpp
vita3k/display/include/display/state.h
vita3k/display/src/display.cpp
vita3k/modules/SceDisplay/SceDisplay.cpp

Take into account the sync param when calling _sceDisplaySetFrameBuf: if it is set to `SCE_DISPLAY_SETBUF_NEXTFRAME` we should wait for the next vblank to change the framebuffer infos.
This pull request also contains slight improvements to the vblank thread and the way it sleeps between each vblank. This should allow games running at 28/29 fps to run at a stable 30fps.
It also contains a small fix, from my understanding (I'm not entirely sure), `sceDisplayWaitSetFrameBuf...` should not update `last_vblank_waited`.

SceDisplay: proper implementation of _sceDisplaySetFrameBuf

---

vita3k/modules/SceHttp/SceHttp.cpp

Temporary fix until #1676 is merged, fail when sceHttpInit is called;
This allows Run Sackboy! and Little King's story to reach the startup menu.

modules/SceHttp: Fail on sceHttpInit

---

vita3k/app/src/app.cpp
vita3k/display/src/display.cpp

Pull request #1711 allowed the delay between vblanks to be more accurate: the average delay is now exactly `AVERAGE_MS_PER_FRAME`. However this value is `16` whereas its real value is `1000/60 = 16.666...`. This made the emulator slightly faster than expected with games running at 62 fps. 
Switching from milliseconds to microseconds solves this issue.
Also improves the accuracy of the displayed fps and ms_per_frame by rounding to the nearest integer the computed values instead of truncating (a game running at 29.9 fps would be shown as running at 29 fps before and 30 fps now).

display, app: More accurate vblank delay and fps displayed

---

vita3k/codec/include/codec/state.h
vita3k/codec/src/aac.cpp
vita3k/codec/src/atrac9.cpp
vita3k/codec/src/decoder.cpp
vita3k/codec/src/mp3.cpp
vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
vita3k/ngs/src/modules/atrac9.cpp

Atrac9 decoding was broken in its current state: `sceAudiodecDecode` should only decode one frame and then stop but for At9 it decoded at superframe which could be 1 frame (ok) or 4 frames (bad) which lead to a buffer overflow of the pcm buffer. This pull request fixes this behavior.
However, because there can be some padding bytes between two consecutive superframes, the Atrac9decoder must remember the decoding state in the superframe and add those padding bytes when needed.
This should fix games that were having random issues (caused by the buffer overflow) using atrac9. In particular Tales of games are now working with the sound enabled.
This pull request also implements sceAudiodecClearContext.  This fixes the crash happening in Tales of games when the background music loops back to …

codec, modules/SceAudiodec: Fix Atrac9 and implement sceAudiodecClearContext

---

vita3k/app/src/app_init.cpp
vita3k/config/include/config/config.h
vita3k/renderer/CMakeLists.txt
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/include/renderer/gl/fence.h
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/gl/ring_buffer.h
vita3k/renderer/include/renderer/gl/types.h
vita3k/renderer/include/renderer/types.h
vita3k/renderer/src/creation.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/fence.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/ring_buffer.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/gl/uniforms.cpp
vita3k/renderer/src/renderer.cpp
vita3k/renderer/src/scene.cpp
vita3k/renderer/src/state_set.cpp

Other split of graphics branch, tested and ready, improve perfomance on some game, get tales of inoncence run to 30 fps stable
- renderer/gl: Use persistent mapped buffer for continous data streaming.
- orphan a buffer is much more inefficient. Improve perf a bit.

renderer/gl: Use persistent mapped buffer for continous data streaming.

---

vita3k/codec/src/atrac9.cpp
vita3k/ngs/src/modules/atrac9.cpp

PR #1715 had a line missing in `ngs/atrac9.cpp` which broke ngs Atrac9 audio.
I also use this PR to fix a compiler warning error in Atrac9.

ngs: Fix broken Atrac9

---

vita3k/kernel/include/kernel/state.h
vita3k/kernel/src/load_self.cpp
vita3k/modules/module_parent.cpp

`sceSysmoduleLoadModule` can be called ingame and load a lle module.
However this function modifies `export_nids_mutex` without any mutex locking mechanism. Therefore if another thread calls a firmware function at the same time, it can lead to a crash when accessing `export_nids_mutex ` (it already happened a few times for me).
I used a shared_lock because writers are really rare (almost none after the beginning of the game) while there are lots of readers (every time a fw function is called), so it should be faster.
I still assumed in this PR that only one `sceSysmoduleLoadModule` would be called at a given time. Otherwise there will be a lot more things to make thread safe.

modules/SceSysmodule: prevent random crash when calling sceSysmoduleLoadModule

---

vita3k/kernel/include/kernel/sync_primitives.h
vita3k/kernel/src/sync_primitives.cpp

Event Flags had multiple issues:
- When calling `_sceKernelPollEventFlag`, if the flag is not set, an error should be returned.
- The `pResultPat` should not be ANDed with the bitPattern
- `pResultPat` should be set after the wait has ended and not before
This should fix potential softlocks occuring in games using event flags. In particular, along with pr #1728 , it fixes sound effects and cutscene softlocks in Tales of Hearts R.

kernel: Fix event flags

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/gl/surface_cache.h
vita3k/renderer/include/renderer/surface_cache.h
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/surface_cache.cpp
vita3k/renderer/src/gl/sync_state.cpp

- Does not support force load from memory. Use from stored FB.
Hope no game is crazy to make its own depth
- fix transparant issue on all psvita game have it before

renderer: Implement partial force load.

---

vita3k/modules/SceNgsUser/SceNgs.cpp
vita3k/ngs/include/ngs/system.h

`ngs::VoiceState` does not exactly match ngs voice state representation, there should be 4 main states and additional flags that can be ORed with the main state. This is not an issue (for now) but it needs to be accounted for when returning the voice state.
Also fix `sceNgsVoiceKeyOff` which should kill the voice after finalizing it.
This fixes the startup menu sound effects in Chronovolt.

ngs: Fix VoiceState and sceNgsVoiceKeyOff

---

vita3k/shader/src/translator/alu.cpp

- Fix source load comp count not matching dest mask.
Just use it right away on vector operation
fix black texture on few game
- all black texture fixed on AC chronicle
- on atelier game too

shader: Fix source load comp count not matching dest mask

---

vita3k/modules/SceNgsUser/SceNgs.cpp
vita3k/ngs/include/ngs/modules/atrac9.h
vita3k/ngs/include/ngs/modules/equalizer.h
vita3k/ngs/include/ngs/modules/master.h
vita3k/ngs/include/ngs/modules/null.h
vita3k/ngs/include/ngs/modules/passthrough.h
vita3k/ngs/include/ngs/modules/player.h
vita3k/ngs/include/ngs/scheduler.h
vita3k/ngs/include/ngs/system.h
vita3k/ngs/src/modules/atrac9.cpp
vita3k/ngs/src/modules/equalizer.cpp
vita3k/ngs/src/modules/master.cpp
vita3k/ngs/src/modules/null.cpp
vita3k/ngs/src/modules/passthrough.cpp
vita3k/ngs/src/modules/player.cpp
vita3k/ngs/src/ngs.cpp
vita3k/ngs/src/route.cpp
vita3k/ngs/src/scheduler.cpp

Mutexes should be locked for a fixed and known amount of time, they should not be locked while calling callback. This pr makes it so that all mutexes are unlocked before calling a callback, and also makes the scheduler mutex a recursive mutex to prevent any issue while stopping a voice in update. Also rename locks mutexes because they are mutexes, not locks.
This fixes freezes in chronovolt and Rayman origins and should fix many more games.

ngs: Fix softlock happening when calling update

---

vita3k/ngs/src/modules/atrac9.cpp

Ngs atrac9 `get_buffer_parameter` gave completely wrong results, fix this.
This allows Uncharted to go slighly further in the boot menu with ngs enabled.

ngs: Fix get_buffer_parameter

---

vita3k/renderer/src/gl/surface_cache.cpp

- fix missing piece of uncharted loading

renderer: Fix depth stencil surface not caching.

---

vita3k/shader/src/translator/alu.cpp

- shader/alu/dual: Adjust config 3 layout of dual.
Based on some tests that is visible on assasin's creed chronicles.
All 3 text shaders all have src_config = 3. And it uses internals1 x unified.

shader/alu/dual: Adjust config 3 layout of dual.

---

vita3k/modules/SceNgsUser/SceNgs.cpp
vita3k/ngs/include/ngs/system.h
vita3k/ngs/src/ngs.cpp

Return `ModuleParameterHeader` to its previous structure to match the sdk, and adapt `parse_params` (which was broken anyway).
Also add missing checks to ngs calls.

ngs: Fix parse_params and add missing checks

---

vita3k/app/CMakeLists.txt
vita3k/app/src/app_init.cpp
vita3k/features/include/features/state.h
vita3k/main.cpp
vita3k/renderer/CMakeLists.txt
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/gl/screen_render.h
vita3k/renderer/include/renderer/gl/state.h
vita3k/renderer/include/renderer/gl/surface_cache.h
vita3k/renderer/include/renderer/state.h
vita3k/renderer/include/renderer/surface_cache.h
vita3k/renderer/src/creation.cpp
vita3k/renderer/src/gl/color_formats.cpp
vita3k/renderer/src/gl/compile_program.cpp
vita3k/renderer/src/gl/load_shaders.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/screen_render.cpp
vita3k/renderer/src/gl/surface_cache.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/shader/include/shader/spirv_recompiler.h
vita3k/shader/src/spirv_recompiler.cpp
vita3k/shader/src/usse_translator_entry.cpp

- renderer/gl: Reuse the cached surface if available and support surface casting.
- Move screen render to renderer module. It does not make much sense to be in app module now.
When combine with #1761 
- Before
- After
- fix also ingame to it, for first time go ingame

renderer/gl: Reuse the cached surface if available and support casting.

---

vita3k/shader/src/translator/data.cpp
vita3k/shader/src/translator/ialu.cpp
vita3k/shader/src/usse_utilities.cpp

Shader bitwise instructions have a flag to specify whether the registers are 16 or 32 bits.
This fixes the graphics in Dragon Quest Builder.

shader: Handle 16-bit bitwise instructions

---

vita3k/renderer/src/gl/texture.cpp

This fixes the text rendering in Dragon Quest Builder.

renderer: SCE_GXM_TEXTURE_BASE_FORMAT_U8 can be unswizzled without decoding on cpu

---

vita3k/gxm/include/gxm/state.h
vita3k/main.cpp
vita3k/renderer/include/renderer/gl/state.h
vita3k/renderer/include/renderer/state.h
vita3k/renderer/src/gl/renderer.cpp

- renderer: improve render frame from surface cache.
- renderer: Fix special converse format cause sigsegv.
We must reserve temporary storage for it!

renderer: improve render frame from surface cache.

---

vita3k/display/include/display/functions.h
vita3k/display/src/display.cpp
vita3k/interface.cpp

Right now, the vsync thread is started when the first waitVBlank or waitSetFrameBuf is called. 
However the vsync thread has more uses than this (like updating the framebuffer infos) and should be started when the application boots up.
This fixes the sample vitasdk program displaying a red square.

display: Start vsync thread during boot

---

vita3k/glutil/include/glutil/object_array.h
vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/include/renderer/commands.h
vita3k/renderer/include/renderer/functions.h
vita3k/renderer/src/batch.cpp
vita3k/renderer/src/creation.cpp
vita3k/renderer/src/driver_functions.h
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/renderer.cpp

This fixes the yellow screen when using mesa drivers (mainly used by linux users).
Textures used for image load/store must be immutable (use glTexStorage2D) (otherwise mesa drivers will silently fail when executing shaders...). This was not the case for the mask texture. I haven't been able to find if this is required by the doc or only specific to mesa drivers.
Also fix sceGxmDestroyContext which was broken for many reasons:
- opengl buffers' deletion is not done on the same thread as other opengl calls
- it frees the memory used by the GxmContext, but it is not up to this function to do so (double free).
Also fix debug builds, opengl debug context and increase the opengl version requirement: we use glBufferStorage which requires openGL 4.4 anyway.

renderer: Fix renderer for mesa drivers

---

vita3k/shader/src/spirv_recompiler.cpp

- add part of commit missing from #1761

shader/spirv recompiler: handle default sampler value when no exist.

---

vita3k/shader/src/gxp_parser.cpp

- Improve render of gravity rush with fix green, lsd and some effect visible
- fix black screen of super stardust ultra and resident evil revelation 2
- Before
- After
- Alone
- Combined with #1779  
- Black screen fixed

 shader: Correct buffer copy to register offset. 

---

vita3k/module/include/module/bridge.h

Tracy names were cropped to 8 characters because sizeof was used instead of strlen.

tracy: Fix cropped names

---

vita3k/modules/SceVideodec/SceVideodecUser.cpp

This allows Persona 3 dancing to get ingame, although I really doubt that these functions are called with an invalid decoder on a real ps vita.

modules/SceVideodec: Return error if decoder is invalid

---

vita3k/codec/include/codec/state.h
vita3k/modules/SceVideodec/SceVideodecUser.cpp

I guess the PS vita expects us to be able to output one last frame when calling `sceAvcdecDecodeStop`, however ffmpeg does not allow us to do so (different decoder internals, maybe it is expecting a bit more data to generate the frame). 
Proper fix inspired by a hack from bookmist.
This fixes the softlocks occuring when skipping fmvs in Tales of games and also a lot of the AVAGAIN fmvs warnings in games like persona dancing where it is calling `sceAvcdecDecodeStop` until it gets its last frame.

modules/SceVideodec: Return one last frame when calling sceAvcdecDecodeStop

---

vita3k/gxm/include/gxm/types.h

You MUST never use different data types in a C structure that uses bit fields (and always use an integer type). Otherwise 9 time out of 10 it will work perfectly fine but the 10th it will give weird results that are really hard to understand.
Specifying a few enums to be uint8_t fixes this problem for `SceGxmBlendInfo`.
This fixes the blending in Persona 4 dancing (and it should be fixed in many other games that use blending).

renderer: Fix blending

---

vita3k/ngs/include/ngs/modules/atrac9.h
vita3k/ngs/src/modules/atrac9.cpp

Rewrite the ngs Atrac9 player to be cleaner and add support for discarding samples at the beginning and the end of the buffer.
I thought it would greatly help the audio in a few games but it looks like it doesn't.. At least it is cleaner and it will be easier to implement playback rate scaling now when needed.

ngs: Implement atrac9 start and end sample skip

---

vita3k/shader/src/usse_utilities.cpp

This fixes Persona 3 Dancing graphic issues.

shader: Do not compute data type size too early

---

vita3k/io/src/state_functions.cpp

Ftell was not working on files bigger than 2 GB (and I doubt that io ever worked on files bigger than 2 GB in Linux because of how late _FILE_OFFSET_BITS is defined.
This allows Summon night 6 to go ingame.

io: Allow ftell to work on files bigger than 2 GB

---

vita3k/ngs/src/modules/atrac9.cpp

Fix regression from #1795 which caused the audio to loop on a small sample.

ngs: Pass proper argument to buffer swap callback

---

vita3k/modules/SceNgsUser/SceNgs.cpp
vita3k/ngs/include/ngs/modules/atrac9.h
vita3k/ngs/include/ngs/modules/player.h
vita3k/ngs/include/ngs/system.h
vita3k/ngs/src/modules/atrac9.cpp
vita3k/ngs/src/modules/player.cpp
vita3k/ngs/src/ngs.cpp

Implement playback rate in the Atrac9 player and add improvement to the atrac9 and normal player in case the playback settings of a voice change.
Also fix a regression in the atrac9 player if a frame is across two buffers.

ngs: Implement playback rate in the Atrac9 player

---

vita3k/np/src/trophy/context.cpp

- one game get overflow of com id data, with get 10 char and no 9 like is normally max
so i just get only first 9 char of data

np/context: fix of create trophy context when com id get overflow.

---

vita3k/app/src/app.cpp
vita3k/config/include/config/config.h
vita3k/config/include/config/state.h
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp
vita3k/renderer/include/renderer/gl/functions.h
vita3k/renderer/include/renderer/gl/surface_cache.h
vita3k/renderer/include/renderer/gl/types.h
vita3k/renderer/include/renderer/state.h
vita3k/renderer/include/renderer/surface_cache.h
vita3k/renderer/src/creation.cpp
vita3k/renderer/src/gl/draw.cpp
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/surface_cache.cpp
vita3k/renderer/src/gl/sync_state.cpp
vita3k/renderer/src/scene.cpp
vita3k/renderer/src/state_set.cpp
vita3k/shader/src/spirv_recompiler.cpp

Add upscaling support to Vita3K.
The most important thing left to do is to implement surface readback to the cpu. It isn't hard but I need first to fix and merge #1770 in order for it not to kill performance.

renderer: Add upscaling support

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/renderer.cpp

Deferred contexts had a few issues, one of them being that the index_data during a draw call is not deferred (leading to a double-free error), the other was that vdm buffer swapping was not handled correctly.
This allows Dungeon Travelers 2 to get ingame (although it has other issues).

modules/SceGxm: Fix deferred contexts

---

vita3k/cpu/include/cpu/common.h
vita3k/gui/src/settings_dialog.cpp

Right now there is no real reason to use either Unicorn or Spir-V, mark them as deprecated to discourage users from using them.

gui: Mark Unicorn and Spir-V shader as deprecated

---

README.md

Now that i have write perms of the vita3k AUR packages, i fixed the -git one and added a -bin one, can say this packages are "official" as they are maintained by a dev
Someday in the future maybe the CI will export linux packages, could be an AppImage, deb. But right now its just the executable which is fine

docs: Add official AUR links

---

vita3k/config/include/config/config.h
vita3k/config/include/config/state.h
vita3k/gui/src/settings_dialog.cpp
vita3k/renderer/include/renderer/gl/screen_render.h
vita3k/renderer/include/renderer/gl/state.h
vita3k/renderer/include/renderer/gl/surface_cache.h
vita3k/renderer/include/renderer/state.h
vita3k/renderer/include/renderer/surface_cache.h
vita3k/renderer/src/gl/renderer.cpp
vita3k/renderer/src/gl/screen_render.cpp
vita3k/renderer/src/gl/surface_cache.cpp
vita3k/shaders-builtin/render_main_fxaa.frag

Add FXAA support to Vita3K. 
When upscaling it adds a nice touch. At native resolution, it is not looking as good as I thought it would be.
The PS Vita supports natively MSAA (which Vita3K does not yet), but this gives another option which is not as good but has almost no impact on performance.

renderer: Add anti-aliasing support (FXAA)

---

vita3k/app/src/app.cpp

Add FXAA status to title bar.
Very minor, but it allows users to easily see whether or not FXAA is active in game since there's no indicator otherwise.
(Removes `title_to_set` const declaration)

gui: Add FXAA status to title bar

---

vita3k/modules/SceAudio/SceAudio.cpp

This allows Trails of Cold Steel to go ingame.

modules/SceAudio: Return error when port is invalid

---

vita3k/renderer/include/renderer/vulkan/state.h
vita3k/renderer/src/vulkan/renderer.cpp

Vulkan build was broken for quite a time. This allows it to compile again.

renderer: Make Vulkan build compile again

---

vita3k/renderer/src/gl/texture.cpp
vita3k/renderer/src/texture_format.cpp

Fix an unsigned underflow that occured when computing the load bias (a load bias of 5e8 is a bit too much).
Also fix the function which was used to compute the size of compressed formats. This should fix the textures in games that are using unswizzled compressed textures.

renderer: Fix lod bias underflow and unswizzled compressed textures

---

vita3k/shader/include/shader/usse_translator.h
vita3k/shader/src/translator/special.cpp
vita3k/shader/src/usse_translator_entry.cpp

VPCK can have a really big repeat count (can go up to 15, meaning 16 repetitions), Increase the possible values of `repeat_increase` (and correct the definition of vpck) to account for it.
This fixes the blur effect during gameplay on persona 4 dancing.

shader: Fix behavior of vpck on large repeat count

---

vita3k/config/include/config/config.h
vita3k/gui/src/settings_dialog.cpp
vita3k/interface.cpp

- settings dialog: app option for boot apps in full screen.
- change pos of title for emulated storage

settings dialog: app option for boot apps in full screen.

---

vita3k/modules/SceGxm/SceGxm.cpp
vita3k/renderer/src/gl/texture_formats.cpp

Please comment if the fallback format is OK, i used RGBA because its the one that has the most cases and its very common

gxm/renderer: Fix 3 warnings of txt format

---

vita3k/interface.cpp

- fix wrong size of app background with refresh size of viewport immediately after go on full screen.

interface: refresh immediately size of viewport.

---

vita3k/gxm/include/gxm/types.h

in c++20 operations between different enum types was deprecated, this casts  the enums to uint32_t so now both enums are the same type, this does not affect behaviour as its based on the bits and theres no reason for it to change

gxm: Fix depracation warning of operations on different enums

---

vita3k/ngs/src/ngs.cpp

The data passed to initialize a rack can contain garbage (it can match a previous deleted voice if RackRelease was called). It needs to be cleared when creating a new Voice.
This fixes a crash in Valkyria Revolution, allowing to progress (slightly) further.

ngs: Clear voice memory location when initializing it

---

vita3k/CMakeLists.txt
vita3k/audio/CMakeLists.txt
vita3k/codec/CMakeLists.txt
vita3k/dialog/CMakeLists.txt
vita3k/display/CMakeLists.txt
vita3k/gdbstub/CMakeLists.txt
vita3k/gui/include/gui/state.h
vita3k/gui/src/allocations_dialog.cpp
vita3k/ime/CMakeLists.txt
vita3k/modules/SceLibc/SceLibc.cpp
vita3k/net/CMakeLists.txt
vita3k/ngs/CMakeLists.txt
vita3k/np/CMakeLists.txt
vita3k/rtc/CMakeLists.txt

From now on the compiler will treat cases where the function arguments are string formatted, if the argument is not a string literal it will give an error. This is to make sure that it compiles on linux with the default makepkg flags And just makes the code more consistent

cmake: Treat format-security warnings as errors

---

vita3k/gui/src/license_install_dialog.cpp
vita3k/host/src/license.cpp

I would not like Vita3K to try to delete the work.bin/rif file after installing using the license install dialog. I give the emulator read-only access to my dumps because I don't want to modify the archives, only install from it to the emulator. That results in a crash when trying to delete it.
The install pkg and install archive dialogs ask for this, so this PR makes the license dialog behave more consistently with the other dialogs.
Additionally, I fixed a typo in the successful installation message.

Ask user to delete license after installing license from the license install dialog rather than always delete + fix typo

---

vita3k/renderer/src/texture_palette.cpp

- should fix lot game with texture etired, like Operation Babel: New Tokyo Legacy and amagami and some other

renderer/texture palette: fix stride of palete texture.

---

vita3k/renderer/src/gl/texture.cpp

- fix regression of text in amagami game.

renderer/texture: fix stride of P4 texture in linear strided type.

---

vita3k/util/include/util/fs.h

On GNU/Linux, compilation currently fails with the following error messages:
```
/mnt/tmp/vita3k-git/src/vita3k-git/vita3k/interface.cpp:377:9: error: no type named 'ifstream' in namespace 'boost::filesystem'; did you mean 'std::ifstream'?
fs::ifstream f{ path, fs::ifstream::binary };
^~~~~~~~~~~~
std::ifstream
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/iosfwd:162:34: note: 'std::ifstream' declared here
typedef basic_ifstream<char>          ifstream;
^
/mnt/tmp/vita3k-git/src/vita3k-git/vita3k/interface.cpp:377:31: error: no member named 'ifstream' in namespace 'boost::filesystem'; did you mean 'std::ifstream'?
fs::ifstream f{ path, fs::ifstream::binary };
^~~~~~~~~~~~
std::ifstream
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c+ …
```

util: Add missing include in fs.h

---

vita3k/gui/src/settings_dialog.cpp

- fix custom config of anisotropic filter with fix typo on save it

custom config: fix typo of save anisotropic filtering.

---

README.md

Remove macOS references (for now) from the `README.md` as it can be confusing for newcomers (#1856).

readme: Remove references to macOS.

---

vita3k/modules/SceGxm/SceGxm.cpp

Apply the fix from PR #1862 to `sceGxmSetBackStencilFunc`. Also break the long if condition into multiple lines.

modules/SceGxm: Fix sceGxmSetBackStencilFunc

---

vita3k/renderer/src/gl/surface_cache.cpp
vita3k/renderer/src/gl/sync_state.cpp

OpenGL texture filter parameters should be integers, not floats. Also fix a typo for raw textures.

renderer: Fix wrong parameter type for texture filter

---

vita3k/renderer/src/gl/sync_state.cpp

The `sync_mask` function is really slow (initializing a big array then copying to the gpu memory).
Because we require opengl 4.4, we can make it a lot faster.

renderer: optimize sync_mask

---

vita3k/gui/src/imgui_impl_sdl_gl3.cpp
vita3k/renderer/src/gl/screen_render.cpp

Save the color mask before rendering to the screen, also remove unnecessary saves and restores (we disable the blending and scissor test anyway in the screen renderer).
This fixes the intro in Trillion.

renderer: Improve saving and restoring the opengl state

---

.github/workflows/c-cpp.yml

Refractor the github action Windows build to:
- download and compile only the necessary components of boost using vcpkg (10 min gain)
- Do not use scoop anymore and use other github actions instead
- Maybe fix the cache (I doubt it was working before for Windows)
I put this pr as a draft until I'm sure the cache is properly working

github: Refractor Windows build for github action

---

vita3k/codec/include/codec/state.h
vita3k/codec/src/pcm.cpp
vita3k/ngs/include/ngs/modules/player.h
vita3k/ngs/src/modules/player.cpp

Mono audio is playing fine. However that doesn't apply to any multichannel sound. In HEVAG audio is packed in frames that contain 28 samples each. But they're not interleaved in frame. Instead channel interleaving is done on frame level. frame `n` has channel 0 data and frame `n+1` has channel 1 data and so on. If we reach last channel, `n` is wrapped back to 0. Each channel has `adpcm_history` and it must be separate for each channel

audio: Fix ADPCM decoding

---

CMakeLists.txt

Also discards finding variant and icl modules due to CMake not being able to find them

Build: Unify Boost module requirement setting

---

vita3k/renderer/src/gl/screen_render.cpp

Currently, when the aspect ratio does not match the PS Vita's one, the borders are yellow as the color is inherited from the default framebuffer clear color.
However while the yellow colors is useful for debugging purposes for the framebuffers, it doesn't make any sense for the borders in which we won't draw anything anyway.

renderer: Change border color to black when aspect ratio doesn't match

---

vita3k/audio/src/audio.cpp
vita3k/modules/SceAudio/SceAudio.cpp

Because of the difference between the host audio buffer size and the guest buffer size, we need the host audio buffer size to be a lot larger compared to the guest one to avoid audio issues.
This resolves the audio issues in games which had an audio buffer larger than the host one like Dungeon Travelers 2. However this will also slightly increase the audio latency depending on the game.

audio: Increase audio host buffer size

---

vita3k/renderer/src/gl/screen_render.cpp
vita3k/renderer/src/gl/surface_cache.cpp

Some games like to do blending on a framebuffer that was just initialized. The alpha value needs to be 0 for this to properly work.

renderer: Set alpha value of default clear color to 0

---

vita3k/modules/SceSysmem/SceSysmem.cpp

Increase the default user_rw alignment to 32KB instead of 4KB. 
This allows Freedom Wars to go ingame.

modules/SceSysmem: Increase default user_rw alignment

---

vita3k/modules/SceDisplay/SceDisplay.cpp

Due to a regression, games using (stubbed) immediate display were not working anymore, fix this.
This fixes the regression in digimon next order chinese version.

modules/SceDisplay: Fix behavior of stubbed imediate display

---

vita3k/io/src/io.cpp

File reads and seeks clutter up the log when trace is enabled and are almost never useful (I never used them to solve an issue), having the file open and close log is enough. Moreover this makes it harder to find the interesting parts of the log.

io: Do not log file reads and seeks by default

---

vita3k/gui/src/common_dialog.cpp
vita3k/modules/SceCommonDialog/SceCommonDialog.cpp

utf16 strings must end with 2 null bytes and not 1. This allows digimon next order japanese version to go past the character name screen every time without the string length error.
Also improve the return errors given by the api calls (many of them were incorrect).

modules/SceCommonDialog: Fix utf16 ending bytes and improve api errors

---

vita3k/renderer/src/gl/texture.cpp

Soul Sacrifice reads from a 2x2 UBC1 texture. Because the width and the height are not aligned, this causes a buffer overflow.

renderer: Allocate enough memory for decompressed textures
