- vita3k/modules/SceGxm/SceGxm.cpp
This allows Soul Sacrifice to reach its menu.
> modules/SceGxm: Return error for invalid index in sceGxmPrecomputedFragmentStateSetTexture

- vita3k/CMakeLists.txt
- vita3k: fix working directory using current configuration.
should fix using debugger for  current path keep configuration folder.
> vita3k: fix working directory of VS using current configuration.

- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/shader/include/shader/usse_program_analyzer.h
- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
This fix mesh render of lbp. It's still broken but we get something like this in intermediate framebuffer. (it's overwritten by another broken shader immediately so it doesn't show in final render)
> Support regformat vertex attributes

- vita3k/interface.cpp
I forget the case when thread finished too fast (or not yet created)
> vita3k/interface: fix race and crash on application close again

- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fr.xml
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/lang/include/lang/state.h
- Add spanish/en-gb lang
-  Add screen if install update fail for allow cancel and back in emu home screen
- add text if version of vit'a3k is upper compare current
- fix warn compile on line find for windows
- check if powershell version is upper to 3 for can using rest-method
- add timeout of 4 sec on check versionn, if github down  etc...
> vita3k update: add some lang string and fix.

- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/texture_format.cpp
- vita3k/util/include/util/align.h
- vita3k/util/src/util.cpp
- Added direct upload of BCn textures without decoding
- Reworked BCn decoder. Even though we don't need it, it's nice to have it for some cases
- Added missing BCn texture types
> renderer: reworked decoding of BCn texture types

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
As @korenkonder pointed out, raw textures prevent classic blending from working correctly. However, they are still needed for some games (like Gravity Rush) which rely on NaN floating values.
Add an option in the gui to disable raw texture, doing so fixes blending in Project Diva X.
> gui, renderer: Add option to disable raw surfaces

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/texture.cpp
These fixes are ported from @korenkonder fixes in his glsl branch.
Fix VRCP decoding when the input and output are not the same size (SpirV-cross did it for us before but the generated spirV code was not valid).
Implement smp texture grad for cube textures.
This fix allow Hatsune Miku Project Diva X to run without shader errors and should fix some of its graphical issues.
> Shader: Fix VRCP decoding and cube textureGrad

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/features/include/features/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/gl/color_formats.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/spirv_recompiler.cpp
Programmable blending was broken when the surface was not rgba8. Raw surfaces were used as a way to prevent that for the special case of F16F16F16F16 surfaces (but not for the right reason and it broke classic blending).
Because this is fixed, raw textures are no longer needed. I keep them in the code because I now need another opengl extension ( not necessary but without it we would have to modify the shader code to generate one shader for each surface format used), so they are enabled only if this extension is missing (and direct frag color is not possible).
Also bump the shader version because disabling raw textures change shaders quite a lot.
> Fix programmable blending and remove raw surfaces

- vita3k/renderer/src/gl/color_formats.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
Compute the openGL format later in the surface cache. 
Also don't try to read an U8U8U8 texture from a surface. Even though it exists, it is a packed format (so no game should use it as a render target) and we do not support it yet. If there is really a game that uses this format and samples from it this will need to be changed (and implemented), but I doubt this is the case.
This should fix the Unsupported format log error in most games which had it.
> renderer: Compute format later in surface cache and do not try to read an u8u8u8 surface

- vita3k/io/src/io.cpp
Check first if the root (from the game's perspective) folder even exists in the first place
> io: Fix case sensitive path when it doesn't exist

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/pcm.cpp
- vita3k/ngs/include/ngs/modules/player.h
- vita3k/ngs/src/modules/player.cpp
There was a race condition leading to a possible double free of the adpcm history or the resampler (mostly the adpcm history, the resampler was a bit more protected).
This should fix the random crash in Project Diva X.
> codec, ngs: Fix race condition with swr and adpcm history

- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/spirv_recompiler.cpp
If the GPU does not support `GL_EXT_shader_image_load_formatted` (mostly some AMD GPUs), use a better workaround than using rbga8 format and raw textures, instead give the format of the current surface to the builtin sampler.
This should almost always work, the only case where it won't is if a shader reading from it own color attachment and is used on surfaces with different color formats (Hopefully no game ever does that).
> shader, renderer: use format of current surface if gpu does not support unknown format

- vita3k/gui/src/live_area.cpp
This happens with ARK Fast from https://github.com/Vita3K/Vita3K/issues/191
Without this it was checking the file size of the folder which boost hasn't implemented and crashed
> gui: Check first if livearea content is empty

- vita3k/renderer/src/gl/texture.cpp
This fixes the uploading of arbitrary textures, if they are compressed or mipmapped.
It allows Spider-Man to get back to menu like it used to.
> renderer: Fix arbitrary compressed textures

- vita3k/gxm/include/gxm/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/threads/include/threads/queue.h
These patches make sure that sceGxmTerminate doesn't trigger a segmentation fault in SDL thread by emptying the work queue first and by aborting it.
Then, the thread is waited for before killing the SceGxm thread.
This PR also includes a fix on a warning raised by clang about memset being called with an improper size.
Finally, the reset() implementation of Queue is fixed to properly build.
> Fix sceGxmTerminate

- vita3k/app/src/app.cpp
this changes the frames/sec string into FPS which is more readable, also makes the window title format more readable, a new line every `|` to make the code not burn eyes
> vita3k: Change frames/sec to FPS and refactor a little

- vita3k/modules/SceAppUtil/SceAppUtil.cpp
Earlier it was writing the buffer pointer pointer, now its the actual buffer pointer where data is located
> AppUtil: Fix read safemem pointer

- vita3k/modules/SceGxm/SceGxm.cpp
Improve `sceGxmPrecomputedVertexStateSetTexture` and `sceGxmPrecomputedFragmentStateSetTexture` error checks.
This fixes a regression in Persona 4 Golden.
> modules/SceGxm: Improve PrecomputedStateSetTexture functions

- vita3k/util/include/util/time.h
With this you can now time exactly how long it takes a code block, meaning in the case below, it will create a logger right before the push, and when the push is done it will exit the code block so that the logger gets destroyed, when a `TimeLogger` gets destroyed it outputs the time it spent alive, in this case its measuring how long it takes to push `display_callback` to `display_queue`
Example from SceGxm.cpp sceGxmDisplayQueueAddEntry
```cpp
// code here
{
TimeLogger::TimeLogger a("cool name");
// function may be blocking here (expected behavior)
emuenv.gxm.display_queue.push(display_callback);
}
// more code here
```
will result in output:
```
[19:54:53.214] |T| [~TimeLogger]: cool name took 42002107 ns | 42002 μs | 42 ms
[19:54:53.281] |T| [~TimeLogger]: cool name took 63875140 ns | …
```
> util: Add TimeLogger utility

- vita3k/io/src/io.cpp
File stats cause a lot of logging on some apps/games, specially realtime stats. derived from #1902
> io: Do not log file stats by default

- vita3k/io/include/io/types.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
wish that there was a list or a clue of what commands exist, i could only find the one the VITAident uses which uses to get the device capacity status. Implementing cluster size doesn't look very important and it requieres os specific code so i left it out stubbed to 4096 which is the default for an NTFS FS, which is the most commonly used
showing correctly
> kernel: Partially implement command for sceIoDevctl

- vita3k/kernel/src/sync_primitives.cpp
Lock the kernel mutex instead of one that's going to be deleted when a guest mutex is deleted.
This fixes a crash I had in Freedom Wars.
> kernel: Lock correct host mutex when deleting guest mutex

- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/usse_utilities.cpp
Add a missing float to integer conversion when reading integer input variables in the shader.
Also fix the start range when converting floats to integers which was reversed between signed and unsigned integer.
The first part fixes the minimap in Tales of Hearts R, the second part should fix any game that is using negative signed integers, as they were clamped to 0 previously.
> shader: Fix input variables with integer type

- vita3k/CMakeLists.txt
- fix repo author when git is clonned in ssh mode
- before
- after
> vita3k: fix repo author when is in SSH.

- vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
seems to work just like `sceKernelLibcLocaltime_r`
> processmgr: Implement sceKernelLibcGmtime_r

- vita3k/shader/src/spirv_recompiler.cpp
When the shader had its symbols stripped, anonymous textures were always given a ressource index of 0.
This fixes the intro of Trails of Cold steel, there is another issue harder to fix preventing the game from rendering correctly ingame.
> shader: Fix anonymous textures

- vita3k/kernel/src/thread.cpp
Unicorn is still useful to debug some weird ass cpu problems, by providing the thread id it is possible to know exactly what instructions the thread that failed execute, watch code just says the thread id and instruction, its far better to say in logs what thread failed than to also print the thread id every cpu instruction
> cpu: Also log thread id when an unicorn error occurs

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
This puts the logging the status of the CPU in a single place, Now it only displays the time on the unicorn/dynarmic error line and then the cpu status without the time at the start of each line
> cpu: Generalize CPU Error logging

- vita3k/modules/SceNetCtl/SceNetCtl.cpp
In linux system gethostbyname uses /etc/hosts to get its own ip, in the majority of cases it won't know it's LAN IP, instead it will fallback to loopback (127.0.0.1). This makes so that if it doesn't find any ip default it to loopback instead of an undefined string
> net/ctl: Add loopback IP as default in case no other IP is found

- vita3k/shader/src/spirv_recompiler.cpp
Fix an out-of-bound write that can happen while copying the uniform buffer to the sa register in the shader code.
It looks like OpenGL doesn't really care about this (at least on my computer), however with Vulkan on my Nvidia GPU it leads to vertex explosions and on my Intel iGPU it crashes my computer (yes, you read that right...).
This fixes the graphics / the computer crash of Trails of Cold Steel menu in the Vulkan renderer.
> shader: Fix Out-of-bound shader write

- vita3k/shader/src/spirv_recompiler.cpp
Fix g++ compiler error with the use of offsetof and overloaded functions.
This is needed by vita2hos which uses the g++ compiler.
> shader: Fix g++ compiler error

- vita3k/main.cpp
Before this PR, the UI thread stops pumping events (i.e. no calls to `handle_events()`) when shaders are being compiled and while the application is "loading" (i.e. before the first frame is rendered). On Windows, this makes the window unresponsive: it cannot be minimized, maximized, resized, moved, or closed. I assume similar things may happen on other platforms but cannot confirm.
Fix by calling `handle_events()` in both loops to ensure events are pumped from the SDL event queue, making the window responsive again. Additionally, move the SDL_SetWindowTitle out of the loops - it doesn't need to be called every time as the title is static (no FPS counter/progess).
NOTE: Because shader cache precompilation is done synchronously on the UI thread, and it can block for a long time, the window …
> app: Fix main window not pumping events during loading

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
the `CI` variable isn't used by vita3k nor any depend, cmake makes a warning because of it, literally its there for nothing lol
> workflow: Delete unused CI variable

- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/include/renderer/shaders.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/shaders.cpp
- vita3k/renderer/src/texture_format.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/shader/CMakeLists.txt
- vita3k/shader/include/shader/gxp_parser.h
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_translator_types.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/translator/texture.cpp
- vita3k/shader/src/usse_translator_entry.cpp
This PR contains 4 commits, each one containing different improvements to the shader recompiler and in particular texture sampling.
- First, rewrite the hint system used by the shader recompiler. The current system is not enough, for some instructions we need to know the texture format (to be more precise the component type and the component count).
- Apply the color swizzle in the shader. Our current implementation didn't work when writing to a texture with different swizzles and didn't support some swizzles like SWIZZLE1_A, this is now fixed.
- Take into account the component count of a texture when sampling. If the texture has only one component (SWIZZLE1_R, for example a depth buffer), do not overwrite the memory at locations that would have matched the 2nd to 4th components.
- …
> shader: Improve texture instructions

- vita3k/shader/src/gxp_parser.cpp
> shader: Remove shader:: from functions already in namespace shader

- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- Fix the pa offset in the shader (do not take into account the sa offset variable)
- In Freedom wars, the shaders does the following computation in shadowed areas:
`exp(log(0) * 0)`
This gets evaluated to NaN, but I'm 90% sure it should be evaluated to 1.0f. Maybe because this is because it is done on F16 which may have a different behavior on some functions concerning NaN? I am really not sure. To fix this, I define in the shader exp(Nan) to be equal to 1.0. This hack should not impact other games anyway.
This PR fixes almost all the graphical glitches in Freedom Wars US and EU versions.
> shader: Fix pa offset and NaN hack

- vita3k/shader/src/translator/data.cpp
Correct the src2 type in the conditional mov instruction which was not specified.
This fixes a shader error in One Piece Unlimited.
> shader : Fix conditional mov src2 type

- vita3k/shader/src/spirv_recompiler.cpp
The PS Vita does not support textures with 32-bit integer components, only textures with 32-bit float components. Therefore when it tries to read or write a 32-bit integer value, we need to interpret it as the raw content (same as a f32) and not try to convert it to a float by normalizing it, which is wrong because this would cause a loss of precision.
This partially fixes the graphics of Uncharted menu.
> shader: Read and write raw content to the surface when it is a 32-bit integer

- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Fix the stride computation when a surface is being read (before it was incorrect for linear and tiled texture).
This improves the graphics in Uncharted menu.
> renderer: fix texture stride

- vita3k/gxm/include/gxm/types.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gxm_types.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/vkutil/include/vkutil/objects.h
- vita3k/vkutil/src/objects.cpp
Implement gamma correction (only for Vulkan for now).
It is not perfect as there are many srgb texture formats and surfaces formats that are not supported in Vulkan compared to the PS Vita.
This fixes the brightness of many games.
> renderer/vulkan: Implement gamma correction

- vita3k/io/include/io/functions.h
- vita3k/io/include/io/state.h
- vita3k/io/include/io/types.h
- vita3k/io/src/io.cpp
- vita3k/modules/SceDriverUser/SceFios2User.cpp
- vita3k/modules/SceDriverUser/SceFios2User.h
Implement some of the Fios overlays functions, which can't be LLEd.
This allows Trails in the sky games to get to the menu, however they are still stuck after because of kernel issues.
> modules/SceFios2User: Partial implementation of fios overlays

- .github/workflows/c-cpp.yml
When psvpfstools does not find a version of zlib already available, it uses its own included binaries. However these are debug binaries which are very slow. Use boost zlib which will link against its release binaries instead.
This should really speed up any operation that involves using zlib on Windows.
> ci: Use zlib boost version for Windows

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/include/cpu/state.h
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
- vita3k/interface.cpp
- vita3k/io/src/io.cpp
- vita3k/kernel/include/kernel/cpu_protocol.h
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/callback.cpp
- vita3k/kernel/src/cpu_protocol.cpp
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceIme/SceIme.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgrCoredumpTime.cpp
- vita3k/modules/SceNetCtl/SceNetCtl.cpp
- vita3k/modules/SceNpCommon/SceNpCommon.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- vita3k/modules/module_parent.cpp
- vita3k/ngs/src/ngs.cpp
- vita3k/ngs/src/scheduler.cpp
Rewrite the SVC calls to stop the CPU. This allows hle functions to call callbacks in the same thread without having to use a guest function or a job queue. This is needed in order to have multiple levels of callbacks (like allocating callbacked gxm memory inside a kernel callback).
This allows Trails in the sky games to go ingame.
> kernel: Rewrite the way svc and callbacks are handled

- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgrCoredumpTime.cpp
Fix a regression in my previous commit which caused SceKernelExitThread to delete the thread. Also rename ThreadToDo::exit into ThreadToDo::remove because that's what it does now (delete would be better but it's a c++ keyword).
This allows Tales of Innocence to go back ingame and should fix other regressions.
> kernel: Do not delete thread when calling SceKernelExitThread

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
sceKernelWaitThreadEndCB was processing the callbacks of the wrong thread.
This allows Omega Labyrinth Z to go from Nothing to Intro.
> kernel: Fix sceKernelWaitThreadEndCB

- vita3k/kernel/src/sync_primitives.cpp
The `finish()` lambda used in msgpipe operation functions expected the thread to be in `wait`ing state and checked this using the `expected` argument of `thread->update_status()`.
However, the wakeup of threads sleeping on a message pipe is done by changing their status from `wait` to `run`, breaking this assumption.
This leads to an assertion failure and crash, preventing e.g. Ratchet & Clank from booting.
Fix (workaround) by no longer verifying the thread's status on `finish()`.
> kernel: don't check status on msgpipe finish

- vita3k/gui/src/settings_dialog.cpp
- vita3k/main.cpp
- Allow can switch backend render before boot app.
- Allow can swit-ch backend render & resolution multiplier when app run.
- refactror setting dialopg gpu tab and add arrow of change slider value.
> vita3k: allow switch backend render & Reso multiplier when app run. 

- .gitmodules
- external/CMakeLists.txt
- vita3k/interface.cpp
- vita3k/kernel/CMakeLists.txt
- vita3k/kernel/src/load_self.cpp
- vita3k/mem/include/mem/functions.h
- vita3k/mem/src/mem.cpp
- vita3k/util/CMakeLists.txt
- vita3k/util/include/util/elf.h
Removes dependency on the external library ELFIO, only used in the SELF loader.
The refactored loader performs many more sanity checks on the input file and is aware of more SCE ELF specifics. This notably fixes `Unknown segment type 0x6FFFFF0x` in Ratchet & Clank and probably other games.
Some changes are commented out as TODO/FIXME because they require broader changes but are not critical.
> kernel: Refactor SELF loader to remove dependency on ELFIO

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
Always use find_package (even in Linux, as it's a bad habit to assume that a header is present without checking it), also copy the dlls for Windows when using prebuilt as it requires both a lib file when linking and a dll while running.
> cmake: Always use find_package for openssl and copy dlls if available

- vita3k/kernel/src/relocation.cpp
According to the reverse engineering I did on Gnosia, the unknown field of EntryFormat1Alt, used to relocate imported symbols, is in fact an addend value (in words). This is used to import and relocate type_info symbols from libstdcxx (so for games written in c++).
This allows Gnosia to go slightly further in its boot process and Uncharted Golden Abyss to go ingame.
> kernel: Implement unknown field of EntryFormat1Alt

- vita3k/modules/SceHttp/SceHttp.cpp
If the game servers are down the connect would literally take 2 minutes and end up returning an error, its far better to be able of just toggling this and just return ok when http is disabled, its not like its needed when its disabled
> http: Also return 0 on connection when disabled

- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
A few commits to partially fix the graphics of Uncharted:
- Uncharted specifies a uniform of size 960 but accesses elements far beyond. This is technically allowed, although no expected. This uniform must be detected (the other option would be to set all uniforms as unbound which would be slower).
- The PS Vita graphics API is able to detect when a fragment shader does not write to output and disable it. Do it for empty fragment shaders for now.
- The generated spirv code to copy unaligned uniform buffers was broken. Fix it and optimize it (it was using four times more loads than what was necessary).
> renderer, shader: Fix uniform copies, specify a uniform as unbounded and disable empty shaders

- vita3k/renderer/src/texture_cache.cpp
Do as the title says (uncharted uses a cube map of f16f16f16f16 textures, which are therefore swizzled).
Also add an error if we try to decompress an unknown texture because this is the second time it happens.
This fixes the big graphical issues in uncharted.
> renderer: Do not try to decompress swizzled f16f16f16f16

- vita3k/gxm/include/gxm/types.h
A fragment shader can have no primary or secondary program but still write to the output by copying directly an attribute or using an independent texture read. Update the definition of an empty shader to take this behavior into account.
This should fix the regressions caused by #2104 .
> gxm: Correct definition of empty shader

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
Some games can do fancy stuff even with an empty shader with blending without looking at the generated color of the fragment shader. So if blending is enabled always run the fragment shader.
This should fix the regressions left by my "empty shader disabled" commit.
> renderer/vulkan: Do not disable fragment shader if blending is enabled

- external/CMakeLists.txt
some build systems (nixos) delete all the .git folders inside submodules, because of this when generating the cmake project it will fail because it would think modules are not inited, but they actually are, checking if submodules have AT LEAST one file should be enough, as un-inited modules have 0 contents inside them
> cmake: Check for any file instead of .git on external

- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
as the comments say, if the user has some tracy modules enabled, ALL the modules that just support tracy will get some performance hit because of std::find, but if the list is ordered then we can use binary search so the time it takes to find if a specific module is enabled or not is considerably low, there aren't many tracy modules but in some near future there may be +50 and that may put some overhead, especially on kernel or gxm exports
> tracy: Use binary search when possible

- vita3k/gui/include/gui/state.h
- it's "Polski", not "Polskis".
> settings: corrects Polish in system language

- vita3k/gui/src/content_manager.cpp
Corrected capitalization
Character spacing has been made closer to that of the actual device.
Vita3K
Vita
> gui: fix content manager

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/scene.cpp
Remove unnecessary copies done by gxm before sending data (vertices, indices and buffers) to the renderer.
Doing so allowed me to uncover a few inaccuracies that I had to fix to prevent regressions:
- The pending queue size includes the frame currently rendering, so the queue size must be reduced by one.
- The behavior of the default uniform buffer allocation and the vertex/fragment ring buffer was inaccurate.
This should improve the performance of the emulator (#android) (as all the data rendered is now copied once instead of twice, the goal being for it only to be copied when it changes) and is the first step towards properly implementing memory mapping.
This pr needs a bit more testing to make sure there are no regressions.
> modules/SceGxm: Remove unnecessary copies to the renderer

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
Revert the "empty fragment" commit as it causes too many regressions.
> renderer/vulkan: Revert empty fragment commit

- vita3k/modules/SceGxm/SceGxm.cpp
Fix a regression from my last commit. I'm not really sure that this is completely accurate but at least this is better compared to the current state.
This fixes the 24FPS speed of Tales of games.
> modules/SceGxm: Fix regression from last commit

- vita3k/ngs/src/modules/atrac9.cpp
There was a typo in the Atrac9 ngs player that caused it when playback rate was enabled and some samples at the beginning or the end were skipped to do out of bound memory reads, causing a crash or bad audio.
> ngs: Fix resampling for Atrac9 player

- vita3k/gxm/include/gxm/functions.h
- vita3k/gxm/src/gxp.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
Improve the way we handle textures to sync them only right before the draw call. The code should handle better (less texture sync) the transitions between precomputed and normal draws.
Moreover, each texture sync now is inside a scene, so we can remove the inefficient single time submits in the vulkan renderer.
> modules/SceGxm: Improve texture handling

- vita3k/display/src/display.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- vita3k/modules/SceDisplay/SceDisplay.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/sync.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
Synchronise the guest and the host fps : if there is no frame ready, do not re-render the last frame. This should slightly improve the performance of games, allow external fps counters to work properly and prevent the emulator from rendering at 300 fps with vsync off when there is nothing to display.
The only downside is that the gui's fps will also be the same as the game fps but I can't really do a lot about it because of the way it is integrated in Vita3K.
> display, renderer: Sync guest and host fps

- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/translator/data.cpp
Fix the conditional mov instruction when the data type isn't a F32.
This fixes the "boxes" appearing in many games.
Also bump the shader version number as it fixes many games.
> shader: Unboxing the graphics

- vita3k/shader/include/shader/usse_types.h
very IMO, its far better to return NONE instead of just letting it in the hands of undefined behaviour, as reaching function end without returning anything is actually undefined behaviour and ANYTHING can happen, it will still trigger the assert if it happens as theres no break
> shader: Fix UB on ext_vec_predicate_to_ext

- vita3k/shader/src/translator/alu.cpp
Define exp(NaN) as 1.0 for the FEXP operand (this was already the case for VEXP).
Same as Freedom Wars, Soul sacrifice computes exp(0*log(0)) and expects it to be 1 but it is nan.
This fixes the blue textures in Soul Sacrifice.
> shader: Define exp(NaN) as 1.0

- vita3k/glutil/include/glutil/shader.h
I set up Vita3K to build on MSVC 2022 entirely fresh, and it doesn't build without this include.
It doesn't fix it if I add it in the .cpp file, only the header. Either way, I could be doing something wrong if nobody has encountered this issue before.
> glutil: fix mvsc error

- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/shader/src/spirv_recompiler.cpp
Improve the accuracy of the depth buffer cache when sampling from only a part of the depth buffer.
The other commit also handles the case when a shader declares 4 16bit outputs on a surface with only 2 components, it should be seen as 2 32bit outputs.
This partially fixes the graphics of Assassin Creed 3.
> renderer/vulkan: Improve the accuracy of the depth buffer cache

- vita3k/renderer/src/vulkan/texture.cpp
Fix an issue when converting rgb8 to rgba8 textures where it took the width instead of the stride during the copy. This led to an out-of-bound read and crash after.
This fixes the crash in Velocity2x in Vulkan.
> renderer/vulkan: Fix crash while converting rgb8 textures

- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix a regression caused by #2193 which broke the vulkan renderer when upscaling was used.
> renderer/vulkan: Fix regression when upscaling

- lang/fi.xml
- lang/no.xml
- lang/pl.xml
- lang/sv.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/trophy_collection.cpp
Fixed https://github.com/Vita3K/Vita3K/pull/2194 issue, the "Delete All" should be in the correct position, also fixed typo of the xml.
plz Mr. @Zangetsu38 check it.
- psvita
- before
- after
> gui/trophy_collection: Fix the Delete All position

- vita3k/modules/SceLibKernel/SceKernelForMono.cpp
Real infinite sleep is OS specific (as far as I know), so I just use some big value.
> modules/SceKernelForMono: Reduce cpu consumption and fix strange crash in (STAY)

- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/translator/ialu.cpp
Fix some issues with vtstmsk (the test type does not determine the dest type) and or/xor with a 0 which stored the result as a float instead of an integer.
Also, when a game downscales a surface without using msaa (why would you do that??), the viewport and scissor must have their dimensions divided by 2 as we are directly rendering to the downscaled surface.
This fixes most of the graphical issues of ys memories of Celceta.
> shader: Fix vtstmsk and or/xor, resize viewport/scissor when the image is downscaled

- vita3k/WindowsDpiAwareness.manifest
- vita3k/audio/src/audio.cpp
- vita3k/io/src/io.cpp
- vita3k/kernel/src/sync_primitives.cpp
- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/modules/SceHttp/SceHttp.cpp
- vita3k/modules/SceTouch/SceTouch.cpp
Here I collect all improvements which do not fix any game. It make emulation more accurate, implement unimplemented and so on.
* audio/audio: fix theoretically possible sound freeze
* io/io: workaround of exception on file delete
* kernel/sync_primitives: set timeout if needed and minor event improvement
* vita3k/manifest: fix xml to build with msvc-clang
* modules/SceFiber: functions return errors instead of crash
* modules/SceTouch: Stubbed implementation of sceTouchGetPixelDensity
* modules/SceHttp: improved hard to understand check in sceHttpUriParse
> Theoretical improvements

- vita3k/gui/src/manual.cpp
I don't know what the deleted lines were intended to exist, but I was able to correct them and will pr
- fix separater position
- the number of pages should be in the middle.
> gui: small fix

- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/context.cpp
Fix crash caused by PR #2205 when changing the viewport/scissor when there is no active render target.
Also reverts some changes from PR #2193 as they are breaking the shadows of many games. I will have to think of a more accurate way to do this. The issue being that a render targer can use a render surface smaller while this is not allowed in Vulkan.
> renderer: Fix regressions

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/live_area.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
add some lang strings to the livearea/help dialog, add lang can help some users to know about these controls. plz Mr. @Zangetsu38 check this PR. 
- not install fw
- installed fw
> gui/live_area: Add lang strings to the help dialog

- .github/workflows/c-cpp.yml
Add the openssl shared objects to the Vita3K package.
This should fix Vita3K not starting on the Steam Deck because openssl is not up to date.
This commit is temporary and should be reverted once openssl is updated on the Steam Deck.
I would also need someone with a Steam Deck to test it and confirm it is working.
> ci: Bundle openssl so with Vita3K

- CMakeLists.txt
Ready for review and merge. It fix a problem with sccache in github ci. Not completely fix, there are still many non-cacheable calls (558 cacheable 148 non-cacheable)
> CMake: disable unknown compiler flags for sccache on windows on github ci

- vita3k/audio/include/audio/state.h
Fix a crash that could occur when changing the audio backend before starting a game, the previous backend destructor was not called, leading to some undefined behavior.
> audio: Make AudioAdapter destructor virtual

- vita3k/renderer/include/renderer/vulkan/pipeline_cache.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
Fix regression an AMD GPU from commit 2779298d70616b2f5d89c7cb9813d2d44df77fbc
Now it checks for each possibly unsupported format separately and use workaround only if needed. It fix regression for PCSE00707 - Ar nosurge... and fix crash on PCSB00102 - Chronovolt
> renderer/vulkan/pipeline_cache: fix regression on commit 2779298

- vita3k/shader/src/spirv_recompiler.cpp
I've filed a bug to SPIRV-Cross and they have fixed an issue with restrict keyword on Metal (https://github.com/KhronosGroup/SPIRV-Cross/pull/2044).
Latest release of MoltenVK 1.2.1 (Vulkan SDK 1.3.236) contains that fix.(https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.1)
So disabling DecorationRestrict on macOS is not needed anymore.
> shader: Revert disabling DecorationRestrict on macOS

- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/vkutil/include/vkutil/objects.h
- vita3k/vkutil/src/objects.cpp
Add (optional) support for the VK_KHR_image_format_list extension.
This allows, when creating an image with the mutable flag (used only for srgb) to say we will only use the linear and srgb corresponding format on it. This can improve performance.
> renderer/vulkan: Add support for VK_KHR_image_format_list

- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/vulkan/scene.cpp
Right now programmable blending (pipeline self-dependency for vulkan, surface texture binding for opengl) is used if the fragment shader is using native color. This works fine but is not optimized as we should only do that if the shader is reading the previous fragment color only.
> renderer: Only enable programmable blending when direct frag color is used

- vita3k/features/include/features/state.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/spirv_recompiler.cpp
Some game were passing as input vector of 3 components and expecting as an input in the shader a vector of 4 components. When this happens, the 4-th component is set to 1. However, because amd GPUs do not support 3-component input vectors, we are instead passing them as 4-component vector, causing the 4th value to be what is in the memory at that location (often 0 or the r-value of the next input). 
Look for these cases when compiling the shader and manually set the 4th component to 1.
This should fix all the vertex explosion happening only on AMD GPUs (like in Uncharted):
> shader: Fix 4th component of rgb input on AMD GPUs

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- CMakePresets.json
Ubuntu-latest is now based on ubuntu 22.
As such we can now switch to clang 14 for the linux build (we are using clang 12 right now).
> ci: Switch to clang-14 for the ubuntu build

- vita3k/renderer/src/vulkan/renderer.cpp
Nvidia GPUs do not allow the priority of the device to be set to higher than normal.
So just disable this extension to avoid a benign error when starting Vita3K on an NVidia GPU with validation layers activated.
> renderer/vulkan: disable VK_EXT_global_priority on Nvidia GPUs

- vita3k/net/src/posixsocket.cpp
Functions `sceNetSend` and `sceNetRecv` should return the number of bytes sent/received. Currently they always return `0` on success.
This PR changes `translate_errorcode` to fix this. It also changes the name to `translate_return_value` to more clearly state the intention (since not all return values are errors). Error handling for other socket functions such as bind, listen, connect etc. should not be affected because they only return either `0` or `-1`.
This vitasdk sample can be used as a test case for this change: https://github.com/vitasdk/samples/tree/master/net_http_bsd
Before: it hangs forever
After: it works.
> net: Fix return value of sceNetSend/sceNetRecv

- vita3k/modules/module_parent.cpp
I was very curious why "Import function for NID 0xE340* not found" appears in log so often and completely disappear when I comment out lle call stub. Now I found why and how to fix it.
Jit cache invalidate is intentional.
> modules/module_parent: More correct LLE import path. Fix "Import function for NID 0xE340* not found"

- vita3k/modules/SceNet/SceNet.cpp
- vita3k/net/CMakeLists.txt
- vita3k/net/include/net/epoll.h
- vita3k/net/include/net/socket.h
- vita3k/net/include/net/state.h
- vita3k/net/include/net/types.h
- vita3k/net/src/epoll.cpp
- vita3k/net/src/p2psocket.cpp
- vita3k/net/src/posixsocket.cpp
Implement and improve some of the network functions. Improves compatibility with homebrew built using vitasdk that use `select`. This also includes those that use libcurl such as this sample program: https://github.com/vitasdk/samples/tree/master/net_libcurl
- Implement `sceNetEpollControl`
- Implement `sceNetEpollCreate`
- Implement `sceNetEpollDestroy`
- Implement `sceNetEpollWait`
- Implement `sceNetGetsockopt`
- Improve `sceNetSetsockopt` implementation
> modules/SceNet: scenetEpoll* functions and sockopts

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/scene.cpp
Metal requires strides to be multiple of 4 bytes.
This will extend stream's data to make stride multiple of 4 bytes.
> renderer/vulkan: Restride vertex streams to be aligned by 4 bytes on macOS

- vita3k/modules/module_parent.cpp
modules/module_parent: invalidate jit cache only for current thread
fix regression on STREET FIGHTER X TEKKEN
> modules/module_parent: fix regression on STREET FIGHTER X TEKKEN

- vita3k/modules/SceNpManager/SceNpManager.cpp
- Stub sceNpGetServiceState.
Should fix boot of Senran Kagura EV.
> modules/SceNpManager: Stub sceNpGetServiceState.

- vita3k/renderer/src/vulkan/context.cpp
Fix an issue where a texture could still stay bound in the next scene if it was unused, but a texture bound to a slot with a higher index was used. The bound texture could then be invalid which caused the vulkan driver to crash (even though the texture itself was not used).
This fixes the crashes in Uncharted.
> renderer/vulkan: Clear the bound textures at the start of each renderpass

- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/include/renderer/texture_cache_state.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Improve the vulkan texture uploading code so that no fence wait occurs (most of the time).
There are now 16 staging buffers used to transfer texture data, a wait will occur only if these 16 buffers are busy sending data and we will wait only for the oldest buffer. Moreover, the number of image transition has been reduced as only 2 transitions are done per texture upload (instead of 2 per mip per face).
This should reduce stutter when the game uses lots of new images at the same time.
This PR needs a bit more testing before merging.
> renderer/vulkan: Improve texture uploading

- vita3k/vkutil/include/vkutil/objects.h
- vita3k/vkutil/src/objects.cpp
AMD GPUs running on Metal have a host-visible memory type that is not coherent. A flush is therefore needed for the buffers to be seen by the GPU.
This allows games to render with Vita3K on AMD GPUs with MacOS
Thank you very much for Lupia for the help in finding out this issue.
> renderer/vulkan: Flush ring buffers if memory is not coherent

- CMakePresets.json
I've tested this on my 22.04 laptop and it worked perfectly - I'd be willing to guess this number can go even lower, but I don't have a 20.04 system to test CMake 3.16 currently.
> cmake: allow building on Ubuntu 22.04

- vita3k/compat/include/compat/state.h
- vita3k/compat/src/compat.cpp
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- gui/home screen: Add badge of compat.
Add feature to display icons and compat badges only in visible area.
- compat: small refactor compat db loaded.
- grid mode
- List mode
> gui/home screen: Add badge of compat.

- vita3k/vkutil/include/vkutil/objects.h
This fixes the random crash that can occur when starting a game.
> vkutil: Initialize size of buffer to 0

- vita3k/interface.cpp
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/src/load_self.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
This PR should fix crashes in games with "[load_var_imports]: 	NID NOT FOUND" warning. It's almost all unity games and some other. I check on "miku miku hockey" game.
The code looks not so good organized, so if you have suggestion of how to make it more simple and understandable, please, comment.
> kernel/load_self: implement late binding for export variables

- README.md
- lang/en-gb.xml
- lang/es.xml
Changes:
- Included mentions of Vita3K being on Android in the readme (this includes links to said repo)
- Added some words in the Spanish translation file (there's too much English!)
- Made changes to the en-gb language file
- Fixed inaccurate PS Vita trademark on readme (PS Vita is NOT a registered trademark, but PLAYSTATION VITA is. Source: https://trademarks.ipo.gov.uk/ipo-tmcase/page/Results/1/UK00910017861
Idk why, I can't merge all commits into one ¯\_(ツ)_/¯
> Typo and wording fixes Season 2

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/information_bar.cpp
- gui/home screen: Switch app icon  to circle.
same change on information app/delete app.
> gui/home screen: Switch app icon  to circle.

- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
This fixes the characters in A.W Phoenix Fiesta and Batman.
> renderer/vulkan: Fix typo for 16-bit 4-component scaled attributes

- vita3k/compat/src/compat.cpp
Updating and loading compat DB on macOS failed due to two reasons.
First, it try to download `app_compat_db.xml` to `~/cache/app_compat_db.xml`. But if `~/cache` directory doesn't exist, it will fail to download.
Second, if `~/cache` directory exist `app_compat_db.xml` is downloaded successfully. However Vita3k try to load `app_compat_db.xml` from `Vita3K.app/Contents/Resources/cache/app_compat_db.xml` which is not the place where `app_compat_db.xml ` has been downloaded.
BTW, it doesn't need to download `app_compat_db.xml` in `~/cache/app_compat_db.xml`. So doing same with Linux will make it work.
> compat: Fix failure when updating compat DB on macOS

- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/imgui_impl_sdl_gl3.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/interface.cpp
Ignore keystrokes while entering text.
Disables opening the live area while typing.
> gui: Ignore keystrokes while entering text

- vita3k/display/include/display/state.h
- vita3k/display/src/display.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/shader/src/usse_translator_entry.cpp
A few simple fixes:
- When calling sceGxmProgramGetParameter, il the parameter index is not valid, exist archive uses this (iterate until null is returned)
- Fix a regression caused when using VBlank callbacks since the svc rewrite, they were executed by the VBlank thread instead of the callback Thread, which made dynarmic crash.
- Fix a validation error when making a loop in spirV
This allows the game exist archive to go from nothing to menu.
> modules/SceGxm, display, shader: Small fixes

- vita3k/features/include/features/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/commands.h
- vita3k/renderer/include/renderer/driver_functions.h
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/types.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/sync.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/include/shader/usse_translator_types.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_utilities.cpp
- vita3k/threads/include/threads/queue.h
- vita3k/vkutil/include/vkutil/objects.h
Implement Memory mapping in Vulkan, this is a first implementation and requires the following extensions:
- VK_KHR_external_memory_host to make the buffers gxm wants to map host gpu accessible
- VK_KHR_buffer_device_address to access buffers using their address instead of a ssbo
- VK_KHR_uniform_buffer_standard_layout so that the uniform buffer passed to shaders are not twice as big as they should be, because in the default std140 layout, the stride of an array of uvec2 is 16 bytes...
This requires a lot of modification, in particular how we handle gxm notifications because now the host gpu must be done when the notification is signaled.
What will be done in other PR:
- Add another memory mapping implementation using a page table for devices not supporting VK_KHR_external_memory_host 
- …
> renderer/vulkan: Implement Memory Mapping

- vita3k/modules/SceVideodec/SceVideodecUser.cpp
Setting horizontalSize and verticalSize values is needed for MGF and Project Diva games to not get stuck when handling AVC videos.
Another thing probably worth mentioning is that, these game may also depend on a stopped video for its game object textures, if the video is stopped, the related object will have green color. Potential fix would be for sceAvcdecDecodeStop to return 0 frames or return the last decoded frame. This however, is not the scope of the current PR.
> modules/SceVideodecUser: set frame horizontalSize and verticalSize

- vita3k/config/include/config/version.h
- vita3k/config/src/version.cpp.in
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
- gui/app context menu/compat: Add pre-filled body in create issue.
- gui: rename struct LiveAreaState live_area to VitaAreaState vita_area.
- gui: fix click on button of info message when start screen is open.
- gui/themes: fix one warning compile.
- create template of open new issue in compat
> gui/app context menu/compat: Add pre-filled body in create issue and small fix

- vita3k/compat/include/compat/state.h
- vita3k/compat/src/compat.cpp
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- gui/home screen: Add app compatibility sorting feature. 
remove app selector state, no have any utility.
-  gui/src/app_context_menu: Add cah copy vita3k summary for can easy update issue.
> gui/home screen: Add app compatibility sorting feature.

- vita3k/gui/src/gui.cpp
- gui: merge merge Japanese and Extra ranges
free some memory.
- small refactor of monospaced font.
- before after
> gui: merge Japanese and Extra ranges

- vita3k/app/src/app_init.cpp
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/gui/src/allocations_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/mem/include/mem/functions.h
- vita3k/mem/include/mem/ptr.h
- vita3k/mem/include/mem/state.h
- vita3k/mem/src/mem.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
Add another implementation for memory mapping which does not rely on the VK_External_Memory_Host extension.
This is only useful on PC for debugging purposes (Renderdoc does not support it). However it will be useful for the Android version as the external memory host is not supported on most android devices.
> renderer/vulkan: Add PageTable implementation for memory mapping

- vita3k/config/include/config/state.h
- vita3k/kernel/include/kernel/types.h
- vita3k/modules/SceDriverUser/SceRtcUser.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
modules/SceThreadmgr: implement _sceKernelGetMutexInfo, sceKernelSetTimerTimeWide; refactor _sceKernelGetLwMutexInfoById
_sceKernelGetSemaInfo - fix returning data
_sceKernelGetThreadInfo - also return thread exit status; sceKernelChangeThreadVfpException, sceIoIoctl - describe parameters
modules/SceGxm: implement sceGxmProgramGetOutputRegisterFormat, sceGxmDepthStencilSurfaceGetFormat
modules/SceRtcUser: implement sceRtcCompareTick, sceRtcGetDosTime, sceRtcGetWin32FileTime
modules/SceKernelModulemgr: sceKernelGetModuleInfo change assert to error code
modules/SceLibKernel: sceKernelCreateMutex: add stub if priority ceiling feature is used
config/state: add forgotten module (SceNetInternal) into tracy modules list
> modules: implement and improve some functions

- vita3k/app/src/app_init.cpp
- vita3k/compat/src/compat.cpp
- vita3k/emuenv/include/emuenv/state.h
- vita3k Add dpi support on linux.
- Disable SDL_WINDOW_ALLOW_HIGHDPI for mac.
should fix big size issue and set all element in good size.
- compat: little clean code no needed.
- before in old build
- in pr
> vita3k Add dpi support on linux. 

- vita3k/mem/include/mem/functions.h
- vita3k/mem/include/mem/state.h
- vita3k/mem/src/mem.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/texture_cache.cpp
Fix many issues concerning our memory protection, mainly:
- Out of bound iterator reads and writes
- remove all the const_casts
- some speed optimizations
- better debugging and logging of windows / unix errors
- fix memory unprotecting happening when it shouldn't
- replace all size_t by uint32_t: this is confusing and we are emulating a 32-bit address range anyway
> mem: Improve protection

- vita3k/util/src/util.cpp
util: log crashes (Windows only), also set console encoding on Windows to utf-8
Windows only, because I don't have Linux to debug this (and it was needed a lot of debug)
> util: log crashes and flush log file (Windows only)

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- modules/SceCommonDialog: Update SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_MIC_DISABLED
Can solve some games to close microphone dialog, e.g. Senran Kagura: Shinovi Versus, etc,.
> modules/SceCommonDialog: Update SCE_MSG_DIALOG_SYSMSG_TYPE_TRC_MIC_DISABLED

- vita3k/renderer/src/texture_cache.cpp
- Add texture format U8U8 on can_texture_be_unswizzled_without_decode
- fix render on limbo
> renderer/texture cache: add fmt U8U8 in unswizzled without decode.

- vita3k/util/src/util.cpp
Now (I hope) crashes will be fixed. I finally found how to call spdlog flush.
> util: Fix log craches again

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/lang/include/lang/state.h
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- lang: Complement more languages text
based on psvita lang, and fixed a few typo.
- gui/lang: Add a few lang strings.
- gui/settings dialog: Adjust the text display.
used [CXML-Decompiler](https://bitbucket.org/SilicaAndPina/cxml-decompiler) by SilicaAndPina dumped the original lang xml from psvita fw rco files, complement to `dialog`, `indicator` and `vita3k_update`. not exactly 100% correct for `vita3k_update`, i currently only understand en/zh-s/zh-t. need devs, contributors and users check this lang pr.
> lang: Complement more languages text

- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- gui/settings dialog: Add clean all custom config
to make it easier to clear all custom config settings.
- gui/trophy collection: Add delete all trophies log info
Please Mr. @Zangetsu38 check this PR.
> gui/settings dialog: Add clean all custom config

- vita3k/mem/src/mem.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
Some old GPU support external memory mapping, but the mapped memory has no flag. However it looks like it is working fine, so  display an error but do not fail if this happens.
Also fix a bug in open_access_parent_protect_segment.
> renderer/vulkan, mem: Small bug fixes

- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- Gamma correction was not taken into account when computing the pipeline hash, causing incompatible render passes issues with Vulkan.
- Add support for BC4 textures, which are used by Killzone (but gamma correction is not supported on them...)
- Add missing swizzles for Vulkan 4-component textures
This fixes graphical issues occuring in Killzone, but a GPU with support for rgba4 color attachments is necessary for it to render properly.
> renderer/vulkan: Various fixes

- vita3k/renderer/src/pvrt-dec.cpp
Fix stack corruption happening while decompressing PVRT2 textures. Thanks visual studio debugger and being able to put data breakpoints in the stack.
> renderer: Fix stack corruption while decompressing PVRT2

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/user_management.cpp
- gui/vita3k update: move init after open user.
should fix select user superposed on Vita3K updater when news version is available.
> gui/vita3k update: move init after open user.

- CMakeLists.txt
- external/CMakeLists.txt
This reverts commit 7f67d1cdcd6b3ef70af26a1498ac1fe40ad311a9.
I'll instead make two different builds (AVX2 and SSE4).
> Revert "vita3k: Enable AVX for the compiler"

- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/player.cpp
Ngs samples are not following the usual sample definition (when using stereo audio, two samples are counted each time).
This fixes the speed issues in Persona 3 and 5 Dancing.
> ngs: Return correct number of samples

- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Killzone uses S8S8S8 textures. Because their support using Vulkan is not widespread, they are decompressed into S8S8S8S8 textures.
> renderer/vulkan: Add support for s8s8s8 textures

- vita3k/CMakeLists.txt
- vita3k/Windows.manifest
This should helps with unicode characters in pref path and vita3k folder path on windows.
It fix unicode problems only on win 10  (May 2019 Update) and later, but I don't think it's cause to not do it at all.
more info about utf-8 in windows is here https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page
> vita3k/manifest: set default encoding on windows to utf-8

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/lang/include/lang/state.h
this is pr with #1827, add the 'Delete DLC' dialog to avoid deleting DLC(addcont)/license by mistake, and to keep or delete the DLC/license, and also update lang strings
- PSVita (devkit/testkit fw)
- Vita3K
> gui/app context menu: Add delete DLC/license dialog

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/ja.xml
- vita3k/compat/include/compat/state.h
- vita3k/compat/src/compat.cpp
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/welcome_dialog.cpp
- vita3k/https/src/https.cpp
- vita3k/lang/include/lang/state.h
- gui/home screen: Add app filter by compat state.
- compat: fix typo of enum.
- gui: fix day on format dd/mm/yyyy for start screen.
> gui/home screen: Add app filter by compat state.

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/util/CMakeLists.txt
- vita3k/util/include/util/float_to_half.h
- vita3k/util/include/util/keywords.h
- vita3k/vkutil/src/objects.cpp
Implement surface sync on the Vulkan renderer.
For many reasons (it is a lot easier to code and a lot more efficient), surface sync can be enabled only with memory mapping.
This implementation is far better than the opengl one. First, if upscaling is enabled, the surface is downscaled on the GPU instead of the CPU. Second, memory trapping is used so that surface sync is done only on surfaces that really need it.
> renderer/vulkan: Implement surface sync

- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/state_set.cpp
Replace the use of std::function with function pointers.
This simplifies the code thanks to the decltype keyword but also makes it faster as std::function adds a level of indirection (although I don't think it will be possible to feel the difference).
It ain't much but it's honest work.
> renderer: Simplify batch and state function dispatch

- external/CMakeLists.txt
- vita3k/codec/include/codec/state.h
- vita3k/codec/src/aac.cpp
- vita3k/codec/src/atrac9.cpp
- vita3k/codec/src/decoder.cpp
- vita3k/codec/src/h264.cpp
- vita3k/codec/src/mjpeg.cpp
- vita3k/codec/src/mp3.cpp
- vita3k/codec/src/pcm.cpp
- vita3k/codec/src/player.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/player.cpp
Update ffmpeg to 5.1.2 (from 4.4).
I updated the code to remove all calls and accesses to deprecated ffmepg functions and variable. Also I had to modify the decode call for the H264 decoder as we use an internal ffmpeg function whose location changed.
I also did a bit of cleanup in the codec files.
The new ffmpeg prebuilt are better optimized and should be much faster for some cases.
> external/codec: Update ffmpeg

- vita3k/codec/include/codec/state.h
swr_alloc_set_opts2 expect the SwrContext pointer to be NULL, it can crash otherwise.
> codec: Initialize SwrContext to nullptr

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- vita3k/modules/SceHttp/SceHttp.cpp
- vita3k/modules/SceNetCtl/SceNetCtl.cpp
- vita3k/net/include/net/types.h
~Allows highschool dxd to go past the PSN screen, but then servers are down so i have to find a workaround for when servers of a game are down. i saw that games that use this compare to 0 and values above it, so -1 is kinda out of place, still tho, i prefer if more games were tested just to make sure this doesn't break any game that require PSN connectivity~
EDIT: 
* Make `sceNetCheckDialogGetResult` result be a valid number
* A bit better of http handling when its HLE and http disabled
* Implement IP OBTAINED callback 
* Fix http read body data always returning 0
> net/http: Some improvements

- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/surface_cache.cpp
Perform the rgba->rgb surface sync conversion using ffmpeg swscale.
Thanks to #2487 , this is much faster than the plain C implementation which is not optimized by compilers.
This allows Project Diva X to run at full speed with surface sync enabled.
> renderer/vulkan: Peform rgba->rgb conversion using ffmpeg

- vita3k/modules/SceAppUtil/SceAppUtil.cpp
So turns out that requiredKiB is not always initialized to 0 ingame, so it ended up being a pointer to garbage and stayed garbage cause we dont do nothing to it, so we have to set it to 0 it ourselves, this fixes minecraft saying that theres no free space
> savedata: Fix requiredKiB not being set to 0 when all executed nicely

- vita3k/net/include/net/types.h
I got an error if s_addr macro is not defined back on msvc-clang-16
> net/types: fix compile error for msvc-clang

- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/texture_format.cpp
- Implement convert linear to swizzled for transfercopy.
- fix transition screen of angry birst stars wars
- fix render of background on &: Sora no Mukou de Saki Masuyou ni
> renderer/scene: Implement convert linear to swizzled for transfercopy.

- vita3k/gui/src/gui.cpp
It could happens on badly installed game and no firmware, or just wrong icon
should fix SIGABRT here #2499
> vita3k/gui: fix crash on wrong app icon

- vita3k/modules/SceNgsUser/SceNgs.cpp
This allows Trails of Cold Steel 2 to go ingame and fixes its sound.
> modules/SceNgs: Do not return error for sceNgsVoiceGetStateData if mem is null

- vita3k/app/src/app_init.cpp
- vita3k/gui/src/gui.cpp
Correctly apply the DPI scaling by scaling the original font instead of using a huge font atlas which for high enough DPI caused the font not to render.
Also do not use `__LINUX__` which is defined by SDL and not for Android, use `__linux__` instead.
> gui: Correctly apply DPI scaling to fonts

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
corruptions are VERY BAD, it should be better to have them be a critical log and then log the current state of the cpu just so its easier to see when the corruption happened c:
> modules/kernel: Better logging on stack corruption

- vita3k/io/src/io.cpp
- vita3k/packages/src/license.cpp
- vita3k/renderer/src/shaders.cpp
the use of copy_option enum was depracated in boost 1.74.0
> **Deprecated:** The `copy_option` enumeration that is used with the `copy_file` operation is deprecated. As a replacement, the new enum `copy_options` (note the trailing 's') has been added. The new enum contains values similar to the `copy_options` enum from C++20. The old enum values are mapped onto the new enum. The old enum will be removed in a future release.
> io: use copy_options instead of copy_option

- vita3k/renderer/src/vulkan/sync_state.cpp
- renderer/vulkan/sync state: stub SCE_GXM_REGION_CLIP_INSIDE.
should fix Ridge racer render in vulkan backend.
- fix yellow screen issue in vulkan
> renderer/vulkan/sync state: stub SCE_GXM_REGION_CLIP_INSIDE.

- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/themes.cpp
- vita3k/net/include/net/types.h
- vita3k/renderer/src/scene.cpp
- fix display manual image when aspect ration is not 16/9, with so can using scrolling
- gui: move some push back to emplace back for init texture.
> gui/manual: handle manual pages of different aspect ratios.

- vita3k/display/CMakeLists.txt
- vita3k/display/src/display.cpp
When a dialog is being shown, even if the game does not render anything new, we should still refresh the screen to allow the user to interact with the dialog.
This allows save states creation and loading to work in Trails Evolution games.
> display: Always refresh screen if a dialog is being shown

- tools/usse-decoder-gen/grammar.yaml
- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_translator_entry.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/special.cpp
- vita3k/shader/src/usse_translator_entry.cpp
Implement the DEPTHF shader instruction, which allows modifying the depth in the fragment buffer.
Also contain some fixes concerning  depth buffer used when MSAA is enabled as their size is not the one expected.
> shader/renderer: Implement DEPTHF instruction and some depth buffer fixes

- vita3k/kernel/include/kernel/types.h
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
The Caligula effect initializes NGS only if the NGS submodule is not loaded yet.
By returning HLEd submodule as unloaded before  the matching load is called, this allows the game to boot further.
> modules/SceSysmodule: Improve sceSysmoduleIsLoaded check

- vita3k/codec/src/aac.cpp
According to docs (https://ffmpeg.org/doxygen/3.2/group__lswr.html#gaa5bb6cab830146efa8c760fa66ee582a) swr_convert returns number of samples output per channel, negative value on error.
Not sure if this correct.
Fixes crash Zero Escape: The Nonary Games (it will crash anyway after few secs).
> Fix assertion in AacDecoderState::receive

- vita3k/ctrl/CMakeLists.txt
- vita3k/ctrl/include/ctrl/ctrl.h
- vita3k/ctrl/include/ctrl/functions.h
- vita3k/ctrl/include/ctrl/state.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/modules/SceCtrl/SceCtrl.cpp
Improve accuracy of the peak/read functions.
In particular, the read function can cause the calling thread to enter a wait state and the number of buffer returned can be lower than the number of buffer asked. Also return correct timestamps.
This allows A-men games to be playable.
> ctrl: Improve accuracy of controller functions

- vita3k/shader/src/usse_utilities.cpp
> shader: Remove warning about unnecesary enclosed ints

- vita3k/kernel/src/load_self.cpp
When the self file is compressed, the elf size is no longer equal to the self size (minus the self header). This causes the dumped elf to be corrupted and an out of bound write when dumping an elf.
This PR fixes elf dump for homebrew apps (which are to my knowledge the only self files with compressed segments).
> kernel: Fix compressed self dump

- vita3k/renderer/src/texture_cache.cpp
- fix stupid fail on typo for set block size and allow continue execute fonction
- fix all background texture using UBC1 in arbitrary texture type.
> renderer/texture_cache: fix block size set and execute for UBC1/4.

- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/main.cpp
- Allow respect size of user background for no deforme it
- user management: small refactor of calculate size for keep aspect ratio.
- in preview
> gui/themes: refactor display background, allow respect aspect ratio.

- vita3k/renderer/src/vulkan/surface_cache.cpp
This should fix the Vulkan errors in some games after my previous PR. Basically, if we are writing to the buffer, we only care about the real width and height of the buffer as they must (at least) match the one of the framebuffer.
> renderer/vulkan: MSAA depth buffer handling fixes

- vita3k/Vita3K.rc
- vita3k/main.cpp
- vita3k/script/update-windows.bat
- vita3k/util/src/util.cpp
- Vita3k: Using FreeConsole for Windows for execv and updater
- Set console title.
- should fix load exec with using windows 11 terminal.
> Vita3k: Using FreeConsole for Windows for execv and updater and little more

- vita3k/renderer/src/vulkan/renderer.cpp
Add an additional FP16 check for FSR, didn't think there would be GPUs which support int8 but not fp16.
This should fix #2602 .
> renderer/vulkan: Add additional FP16 check

- vita3k/modules/SceGxm/SceGxm.cpp
This allows NFS to go ingame with memory mapping.
> modules/SceGxm: Fix typo in sceGxmMapMemory

- vita3k/renderer/src/vulkan/scene.cpp
This fixes part of the graphics of Samurai Warrior 4 on Vulkan when using upscaling.
> renderer/vulkan: Fix flat viewport when upscaling is used

- external/CMakeLists.txt
Also drop no more used workaround
MSVC use clang 15 by default, but also it can use standalone clang 16
> CMake: fix build of dynarmic/mcl library on msvc-clang with clang 16

- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/spirv_recompiler.cpp
Improve the handling of MSAA'd non-downscaled surfaces and the opposite (downscaled non-MSAA'd surfaces) by both the renderer and the shaders.
This information is passed to the shader using the res_multiplier variable which now has to be a float. Moreover, the fragCoord variable used by the recompiled shader was not taking it into account previously.
I also had to make a few changes, like making the mask texture be upscaled in OpenGL for it to work as planned.
This should fix a lot of the special affects appearing only on the top-left corner. It does so for Gravity Rush and Samurai warrior 4.
> renderer,shader: Improve Vita's MSAA handling

- vita3k/kernel/include/kernel/types.h
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- vita3k/modules/SceDriverUser/SceRtcUser.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceHttp/SceHttp.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceNet/SceNet.cpp
- vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
- vita3k/modules/SceNpTrophy/SceNpTrophy.h
- vita3k/modules/SceVideodec/SceVideodecUser.cpp
- vita3k/np/include/np/trophy/context.h
* modules/SceNet: a bit more correct error codes
* modules/SceHttp: fix crash at HLE http on connection closing
* modules/SceRtcUser: implement sceRtcTickAddYears, sceRtcTickAddMonths
* modules/SceLibKernel: stubbed sceKernelGetRWLockInfo, sceKernelTrySendMsgPipe
* modules/SceGxm: Workaround possible crash on game exit (exit_delete_all_threads)
Crash happens when internal kernel display_queue_thread is destroyed before internal sdl SceGxmDisplayQueue thread
* modules/SceNpTrophy: stubbed impl of sceNpTrophyGetGroupInfo. also remove std:: from types
* modules/SceThreadmgr: implement sceKernelDeleteCallback
* modules/SceAudiodec: a bit better logs
* modules/SceVideodec: describe enums
I'm going to squash all this into one commit. Here and now it's separated in case if some of them will be …
> modules: implement and stub some functions and do some more fixes

- vita3k/codec/CMakeLists.txt
- vita3k/codec/include/codec/state.h
- vita3k/codec/include/codec/types.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/config/include/config/state.h
- vita3k/modules/SceJpegEnc/SceJpegEncUser.cpp
- MJpeg and sceJpegEncoderSetValidRegion functions are not yet supported.
- Ignores the CompressionRatio parameter.
> modules/sceJpegEncUser: Implements most of functions.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gxm_types.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
Implement the PS Vita visibility buffer using Vulkan occlusion queries.
This divides by 2 the number of draws in Gravity Rush.
> modules/SceGxm, renderer/vulkan: Implement visibility buffer using occlusion queries

- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix depth sampling which was previously not working if there was a stencil component.
Also implement stencil rendering on the vulkan renderer.
This fixes most of the graphical issues left on Gravity Rush
> renderer: Fix stencil and depth sampling

- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
* sceFiberGetInfo used in Kick and Fennick [PCSE00485] (menu -> ingame)
* sceGxmShaderPatcherGetUserData used in MLB15 THE SHOW [PCSA00511], MLB 13 The Show [PCSA00065] (not checked)
* sceKernelCheckThreadStack used in Othello [PCSG00427] (not checked)
> modules: implement some functions

- external/CMakeLists.txt
spotted by @german77, and see again by myself, archive downloaded have now diferent name for directory inside, move from openssl-3 to openssl-3.0
- fix cmake gen if using this download zip.
> external: fix the path to openssl from the extracted archive.

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/modules/SceJpegEnc/SceJpegEncUser.cpp
Fixed issue when inPitch and width are different on modules/sceJpegEncUser/sceJpegEncoderCsc
Similar to PS Vita's handling of video files, if the input image is inPitch * height, it is used to crop and encode only the width * height portion of the image. (This is probably related to optimizing the utilization of the PS Vita hardware unit).
In the previous implementation, the handling of inPitch was missing.
> modules/sceJpegEncUser: fix sceJpegEncoderCsc inPitch misbehavior

- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- Convert texture for can correct handle it
should fix this texture format.
> renderer/texture: convert U8U3U3U2 to U8U8U8U8.

- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
Add some additional checks in case sceGxmSetVisibilityTestIndex is used before sceGxmSetVisibilityBuffer for the first time.
This fixes a crash in Freedom War.
> renderer/vulkan: Add additional check for valid buffer

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/atrac9.cpp
- vita3k/ngs/include/ngs/modules/atrac9.h
- vita3k/ngs/src/modules/atrac9.cpp
Even when decoding a new atrac9 superframe, the atrac9 decoder needs the data from the previous frame to decode the next one. We were using the same atrac9 decoder in ngs for multiple voice, causing the previous frame data to be incorrect when switching between voices and leading to some audio noise when two or more atrac9 voices overlaps.
This PR adds an Atrac9 state saved by each voice to prevent this issue.
This fixes the audio issues in Persona dancing, Dragon's crown and many over games.
> ngs: Save Atrac9 decoder state

- vita3k/renderer/src/vulkan/surface_cache.cpp
This fixes a validation error causing a crash on Persona 4 Dancing.
> renderer/vulkan: Fix depth stencil surfaces initialization

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/h264.cpp
- vita3k/codec/src/player.cpp
- vita3k/modules/SceJpeg/SceJpegUser.cpp
- vita3k/modules/SceVideodec/SceVideodecUser.cpp
- using resolution send by app for decode video
- should fix video resolution in lego game
- remove memset to 0 on last frame in sceAvcdecDecodeStop, should fix green screen regression.
- fix video broken in lego marvel
- fix green screen when video finish
> SceVideodec: Fix resolution of video decode.

- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
Persona 4 dancing uses a surface with a separate depth and stencil buffer, then only the stencil buffer is used in a separate scene.
Adapt the code to handle this case, this fixes the Depth-Of-Field effect on Persona 4 Dancing (using vulkan).
> renderer: Fix issue when sampling stencil without depth buffer

- vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
- vita3k/np/include/np/common.h
- vita3k/np/include/np/trophy/context.h
- vita3k/np/src/trophy/context.cpp
- modules/SceNpTrophy: Fix platinum trophy unlock.
Unlock platinum trophy compare if trophies count is same as total unlocked, but that's not possible, because trophy counting includes platinum.
So need remove 1 from the trophy count to check that only one is missing.
> modules/SceNpTrophy: Fix platinum trophy unlock.

- vita3k/dialog/include/dialog/state.h
- vita3k/gui/src/common_dialog.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- modules/SceCommonDialog: Fix allocate EmptyParam for slot upper 0.
Empty param is not only in slot 0, is for all slot available, so move on vector.
Should fix all missing new save icon.
- gui/common dialog/save dialog: fix position of text in new save.
Fix pos and the size of the elements regardless of the size of the window.
Fix scroll bar missing.
- master 
- pr
> modules/SceCommonDialog: Fix allocate EmptyParam for slot upper 0.

- vita3k/renderer/src/gl/screen_render.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
This yellow color is not useful to debug graphical issues.
Moreover it causes itself graphical issues in many games (screen borders in P4D, Ys8, transitions in Dragon's crown, Trails games...)
> renderer: Remove debug color

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/modules/SceJpegEnc/SceJpegEncUser.cpp
- Fixes issue where sceJpegEncoderEncode would generate a still MJPEG instead of a JPEG
- Implement the behavior of sceJpegEncoderSetCompressionRatio
> modules/sceJpegEncUser: Improve JPEG encoding more strictly

- vita3k/modules/SceDisplay/SceDisplay.cpp
- vita3k/modules/SceDisplay/SceDisplay.h
- vita3k/modules/SceDriverUser/SceDisplayUser.cpp
Improve the accuracy of the FrameBuf functions, they take one more argument compared the the user driver version. 
Moreover, Big Sky uses the SceDisplayFrameBuf with an additional field that I have not fully reversed engineered. 
This allows Big Sky to go ingame.
> modules/SceDisplay: Improve accuracy of FrameBuf functions

- vita3k/ngs/include/ngs/modules/equalizer.h
World of Final Fantasy looks like it assumes something about the layout of the ngs memory: it acts as if it knows there is a second SceNgsParamEqParams right after the first one (see screenshot).
My guess is that the param buffer after is the real one (which is copied to after the call the unlock).
Double the size of the Equalizer paramter modules allows the game not to write to undefined memory.
This allows World of Final Fantasy to go ingame with ngs enabled.
> ngs: Double param buffer size for the equalizer

- vita3k/dialog/include/dialog/state.h
- vita3k/gui/src/common_dialog.cpp
- vita3k/main.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- gui & modules/save data dialog: Some fix and reworks.
fix crash on fixed mode with reworks navigate in button and set first switch of display mode.
fix icon missing in fixed mode for slot > 0 with reworks load icon texture.
fix clean preview info in SaveDataDialogInit with reset savedata struct.
fix dialog show one save of system data with this reset of struct.
disable common dialog when app is paused.
remove duplicate code of open save slot with set all inside cehck save file.
> gui & modules/save data dialog: Some fix and reworks.

- vita3k/gui/src/common_dialog.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- modules/SceCommonDialog: Init vector of savedata in progress bar mode.
should fix crach caused with try set value inside empty vector.
should fix issue https://github.com/Vita3K/Vita3K/issues/2693
- gui./save data dialog:; small improvement of progress bar.
> modules/SceCommonDialog: Init vector of savedata in progress bar mode.

- vita3k/shader/src/gxp_parser.cpp
World of final fantasy uses a literal buffer address which is not yet implemented in the shader recompiler and its implementation will be a bit tricky.
For the time being, use a buffer address as a placeholder instead of doing nothing.
This allows World of Final Fantasy to go ingame with the Vulkan renderer and memory mapping.
> shader: Implement workaround for literal buffer address

- vita3k/io/src/io.cpp
- This fix prevents an unusual situation where an open_file on a directory returns success, and is followed by a seek_file try.
> io/open_file: Returns an error when trying to open a directory

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
modules/SceThreadmgr: fix _sceKernelGetThreadCpuAffinityMask for default thread affinity
Fix regression from #2273 for Uncharted fight for fortune
> modules/SceThreadmgr: fix _sceKernelGetThreadCpuAffinityMask

- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
after reverse in ghidra, see this function send enventNum with value particular very big, causing big freeze in very long loop of call recieve event function
So Accorded with @CreepNT , event is not implemented to Vita3K, so just set 0 for can skip it and stop freeze
> modules/SceDriverUser/SceAppMgrUser: Stub sceAppMgrReceiveEventNum.

- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/pipeline_cache.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/shaders.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/spirv_recompiler.cpp
Implement shader interlock to emulate more accurately programmable blending on desktop GPUs.
This PR is overly complicated for the single reason that Vulkan does not allow a surface to be used both as a color attachment and a storage image (and barrier for this not supported case do not work).
So I have to duplicate all the vulkan structures (render pass, framebuffer...) for them to work with shader interlock.
This has been tested with a NVidia GPU on Windows and an AMD GPU on linux with a dev mesa build.
Without
With
I also improved the shader cache to be cleared when using a different GPUs as shader will now most likely not be compatible anymore.
There shouldn't be any graphical regressions, but shader interlock may have a moderate performance impact.
This should fix the 'boxes' issues …
> renderer/vulkan: Implement shader interlock

- vita3k/mem/src/mem.cpp
On windows, when a free is called, VirtualFree is used with MEM_DECOMMIT to decommit (free) the memory. However, on Linux, the only thing done was to protect the memory range, which does not free the underlying memory.
Calling madvise with the MADV_DONTNEED flag does it. This should decrease the memory usage depending on the game.
> mem: Free memory when it is freed on Linux

- vita3k/modules/SceGxm/SceGxm.cpp
SceMidSceneFlush empties the command list, and sceGxmExecuteCommandList  does not except the command list to be empty. handle this case.
This allows Zanki zero to reach intro (was previously nothing).
> modules/SceGxm: Handle calling sceGxmExecuteCommandList with empty immediate list

- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Emulate macroblock tile sync basically by stopping and starting again the recording at every draw when the render target has the macroblock flag. This is accurate but kind of slow, I'll implement soon something better.
> renderer/vulkan: Emulate macroblock tile sync

- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
U1U5U5U5 texture swizzle is not fully supported right now. However we are using an argb texture when rendering to it (the rgba version is not compatible with all GPUs). Therefore it is more accurate to use a argb swizzle.
This fixes the screen transition in trails games.
> renderer/vulkan: Improve u1u5u5u5 swizzle

- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- fix wrong swizzle on this 2 format 
finally fix color and face broken on this hyperdimension game during some moment, like here or when finish one level
fix also pause in to love ru BE
- Master
- PR
> render: fix swizzle of RGB1 and BGR1

- vita3k/gui/src/gui.cpp
- vita3k/modules/SceRegistryMgr/SceRegMgr.cpp
- vita3k/modules/SceRegistryMgr/SceRegMgrForGame.cpp
- vita3k/modules/SceRegistryMgr/SceRegMgrForSDK.cpp
- vita3k/regmgr/include/regmgr/functions.h
- vita3k/regmgr/include/regmgr/state.h
- vita3k/regmgr/src/regmgr.cpp
- regmgr: Add more id on get category and name by id.
Fix crash when category/name is empty.
Fix crash when category/name is empty.
Fix init regmgr when change pref path.
Fix crash if value is not int for get int.
Add Set default value if value is corrupted.
Using vector for reg category template for keep order instead unordered map for fix broken file when switch pref path directory.
> regmgr: Add more id on get category and name by id.

- vita3k/gui/src/allocations_dialog.cpp
- vita3k/kernel/src/load_self.cpp
ranges are 32 bit, not 64, also segment indicator wasnt working
> gui: Fix allocations dialog typo and incorrect type

- vita3k/modules/SceGxm/SceGxm.cpp
God eater allocates some pretty tight vdm buffers. Reduce the command footprint to make our commands fit.
> modules/SceGxm: Decrease vdm command footprint

- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
God eater loads and starts the libdflt module, which has no module_start.
This allows the game to progress slightly further.
> modules/SceModuleMgr: Add check before calling module_start

- vita3k/module/src/write_return_value.cpp
- vita3k/modules/CMakeLists.txt
- vita3k/modules/SceLibKernel/SceRtabi.cpp
- vita3k/modules/SceLibKernel/SceRtabi.h
- vita3k/nids/include/nids/nids.inc
used by driver_us.suprx
Return value of `__rtabi_ldivmod` is very unusual but it seems correct.
Behavior on division by zero is taken from original disasmed code.
original names of functions are `__aeabi_*` but they was renamed to not mix with same functions in other module with other nids
> modules: Describe and partial implememt SceRtabi module

- building.md
Fixes CMake error when running `cmake --preset linux-ninja-clang` on Lubuntu 22.04.1:
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the                                                  
system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY                                                          
OPENSSL_INCLUDE_DIR)                                                                                                       
Call Stack (most recent call first):                                                                                         
/usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE) …
```
> Add libssl-dev for building on Ubuntu/Debian

- vita3k/modules/SceNet/SceNet.cpp
- vita3k/net/include/net/types.h
* Implement both htonll and ntohll, some platforms/systems dont have the syscall, so we have to check for ourselves the endianness and do the operation on our side
* ethernet addr translation implemented (sceNetEtherNtostr, sceNetEtherStrton), sceNetEtherStrton is good as long as the input string is not too short or has some unexpected stuff, but that just doesnt happen, so should still be good
* add some param checks sceNetInit <:
~~smol pr~~
> net: Some implement some rare net funcs

- vita3k/modules/SceNgsUser/SceNgs.cpp
This fixes a crash in PixelJunk Shooter Ultimate Vita3k/compatibility#1628 which was passing a nullptr for the error count parameter.
> modules/SceNgsUser: Fix crash in sceNgsVoiceSetParamsBlock

- vita3k/gui/src/home_screen.cpp
- vita3k/regmgr/src/regmgr.cpp
- regmgr: fix crash when reg is missing on app try using it.
remove loop for task on space, using vector char.
> regmgr: fix crash when reg is missing on app try using it.

- vita3k/net/src/epoll.cpp
turns out that the `nfds` param needs to be the highest fd PLUS ONE, 
linux says this in its documentation, but on windows its missing this tiny detail, i've seen other people use select and having it only work if adding 1 to nfds, so its the same as linux
https://man7.org/linux/man-pages/man2/select.2.html
this fixes a forever waiting/loading on some homebrews with epoll waits (idk about commercial games)
> net: Fix max epoll nfd number on wait

- vita3k/interface.cpp
- vita3k/interface.h
- vita3k/io/include/io/functions.h
- vita3k/io/src/io.cpp
- vita3k/kernel/include/kernel/load_self.h
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/include/kernel/types.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/load_self.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/main.cpp
- vita3k/module/include/module/load_module.h
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
UPD: This PR now include big refactoring. See https://github.com/Vita3K/Vita3K/pull/2677#issuecomment-1632181174
This modules are not a part of firmware and distributed as part of game. AFAIK there is only two such modules.
libsmart is used in Vita AR games. libface is face recognition module.
> module: use LLE and fix module load for libsmart and libface

- vita3k/gdbstub/src/gdb.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgrCoredumpTime.cpp
- vita3k/modules/module_parent.cpp
Fix a regression caused by the fact that preloaded modules were not registered, causing some game to see them unloaded and try to load them again, causing a freeze.
Also put the thread callbacks at the right location (run_callback can only be called in the thread and run_guest_function is not appropriate here).
Also some fixes, there is no reason to pass the kernel state to all the thread functions.
This fixes regression in spiderman.
> interface, kernel: Fixes

- vita3k/cpu/include/cpu/impl/dynarmic_cpu.h
- vita3k/cpu/src/dynarmic_cpu.cpp
A few years ago, this may have been useful. However, now dynarmic is more accurate and feature-complete compared to unicorn. If we reach an invalid opcode, it means for 99% of the cases that we did something wrong previously and even in the 1% left switching to unicorn won't help.
Also it produces a huge unreadable backlog.
> cpu: Remove unicorn fallback for dynarmic

- .github/workflows/c-cpp.yml
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/src/load_self.cpp
- vita3k/modules/module_parent.cpp
Resolving the NID during an HLE (or first LLE) call takes a non-negligeable amount of time (on android the current implementation was taking almost 10-15% of many threads processing time), here are two performance improvements (the first being already used on Android):
- using a shared-mutex is not a good idea because of its implementation, it shouldn't be used to lock something which is quite fast (like nid resolving) as it amounts basically to two consecutive mutex locks. Replace it by a standard mutex, it is in practise much faster.
- Use a faster data structure for the nid map: a boost::unordered_flat_map is around 3 times faster than a std::unordered_map.
Also updates the boost requirement to 1.81.0 as boost::unordered_flat_map was added at this version.
> kernel, modules: Improve nid performance

- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/texture_yuv.cpp
24-bit packed rgb is not supported on modern desktop GPUs, this causes the renderer to do a conversion from 24-bit format to 32-bit, in the background for opengl or done ourself when using vulkan.
So we might as well directly decompress the YUV image to 32-bit RGBX format, this avoids an intermediate step.
> renderer: Decompress YUV as RGBX

- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Fix a potential (very rare) freeze that can happen when using the vulkan renderer.
Basically, if when using the vulkan renderer, a scene using macroblock tile sync is using a lot (but not too much) new textures, this will cause a fence which is never signaled to be waited for.
I am not aware of anyone getting a freeze cause by this.
> renderer/vulkan: Fix potential freeze

- vita3k/renderer/src/vulkan/scene.cpp
This fixes the vertex explosion when using non-multiple of 4 stride with MoltenVK, was caused by a typo.
> renderer/vulkan: Fix vertex explosion on Mac

- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/vulkan/context.cpp
As found out by @saturnsky , surface sync was applied after notifications were signaled, leading to a race condition.
> renderer: Apply surface sync before signaling notifications

- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/state.h
- Fix allow Apply change stretch display area state in real time.
Fix refresh module list when open setting dialog.
> gui/settings dialog: Fix refresh option stretch the display area.

- vita3k/config/include/config/config.h
- Fix default Mapping of R2 buttons
should fix cross input on corps party.
> config: Fix default R2 mapping.

- .github/workflows/c-cpp.yml
macOS CI's ccache hit rate was bad(about 0.00%) because Compiler mtime was changed on every CI run. So changing ccache's compiler check from mtime to content will make cache work on macOS.
I did 5 CI run on my forked repo and it took average 10 min to finish. Surprisingly, on all 5 run macOS finished faster than Windows.
First CI run after this PR merged will take time because previous cache is not usable.
> ci: fix bad ccache hit rate on macOS

- vita3k/kernel/src/load_self.cpp
- vita3k/kernel/src/relocation.cpp
This tables are used then import function address is used for anything except function call
Details: https://wiki.henkaku.xyz/vita/Modules#reftable_.28Variable.2Ffunction-address_imports.29
It is used by libkernel.
> kernel/load_self: implement function's associated reftables

- vita3k/gui/src/main_menubar.cpp
gui/main_menubar: fix crash on "Emulation/Last Apps used" menu when last open app is system app
> gui/main_menubar: fix crash on "Emulation/Last Apps used" menu

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
some games use HLE libc, the ones that do sometimes use the safe variant, and the safe variant is just not a simple memcpy, it does some checks to alert memory overlaps and has breakpoints for games that are in the development process, so i decided to replicate this, also technically the memcpy still happens whatever the overlap is, should be 1:1 to real hw (afaik), mainly pr just in case a game actually has memory overlaps due to bugs on emu side and other devs dont pull their hairs out because of memory corruption. should have no effect for game compatibility
> kernel: Implement sceClibMemcpy_safe

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/commands.h
- vita3k/renderer/include/renderer/driver_functions.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_utilities.cpp
Implement the shader store operation, which is used by shaders to modify the content of buffers.
This obviously only works with memory mapping enabled, as without it, shaders only have access to a copy of the buffer that gets recreated every draw.
This fixes games using this features, mainly 3D Unity games.
However, only half of them are fixed as we still don't implement properly the repeat count for shader stores. This is a bit harder than I thought it would be to reverse engineer, so I will do it in another PR.
> shader: Implement the shader store operation

- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- gui/main menubar: Display Icons of app in emulation menu.
Fix one typo in setting dialog.
> gui/main menubar: Display Icons of app in emulation menu.

- .github/workflows/c-cpp.yml
- CMakeLists.txt
Due to discord game SDK and homebrew, possible macOS minimum target version is macOS 11, but CI is automatically setting target version to 12.6 which is OS version of CI environment. So it will manually specify minimum target version for macOS.
But if homebrew remove support for big_sur bottles, we have to change target version corresponding to brew bottles, or we have to build OpenSSL and boost ourselves.
> vita3k: specify minimum version of the target on macOS

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
- vita3k/cpu/include/cpu/impl/interface.h
- vita3k/cpu/include/cpu/impl/unicorn_cpu.h
- vita3k/cpu/src/unicorn_cpu.cpp
Update unicorn to unicorn2.
Benefits:
- About 5 times faster performance-wise (still a lot slower than dynarmic)
- On windows, build statically instead of using mingw prebuilts. Allow 3 dlls to be removed from the final zip.
I had to implement cache invalidation for Vita3K to work with unicorn2 (even though I don't understand how unicorn1 was working without cache invalidation after bookmist's changes anyway).
We are still using a custom repository for this as I had to do some modifications to unicorn CMakeList for it to build with our CI.
> external: switch to unicorn2

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
- vita3k/touch/include/touch/functions.h
- vita3k/touch/include/touch/touch.h
- vita3k/touch/src/touch.cpp
- touch: Fix and improve finger touch. by @Macdu  from Android version.
- touch: Add touchpad support.
Allow double touch in pc with using touchpad of DS/4.
Add draw touchpad cursor when is used.
Add config for allow disable show this cursor per game.
Using click on touchpad for switch to rear/front touchport
> touch: Add touchpad support.

- CMakeLists.txt
glslang has the highest requirement (3.14.0)
https://github.com/KhronosGroup/glslang/blob/ca8d07d0bc1c6390b83915700439fa7719de6a2a/CMakeLists.txt#L36
> cmake: Update minimum required

- vita3k/modules/SceGxm/SceGxm.cpp
Calls to sceGxmDrawPrecomputed can only have parts of the pipeline precomputed. In this case if a default uniform was reserved for a non-precomputed part, it must be reset.
This should fix the regressions caused by #2902.
> modules/SceGxm: Fix default uniform reservation with precomputed drawing

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
We can safely remove this because:
- GNU implementation prior to 9.1 requires linking with -lstdc++fs and LLVM implementation prior to LLVM 9.0 requires linking with -lc++fs
- The dynarmic dependency uses consteval which requires at least GCC 10 and LLVM 11
> cmake: Remove specific code for unsupported compilers

- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/vkutil/src/objects.cpp
Fix a memory leak causing the texture cache not to free previous textures when it is full.
Also correct the behavior of the destroy function of vulkan buffers.
> renderer/vulkan, vutil: Fix texture memory leak

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gxm_types.h
- vita3k/renderer/include/renderer/vulkan/gxm_to_vulkan.h
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- vita3k/renderer/src/vulkan/texture.cpp
Fix many inaccuracies related to gxm texture functions:
- The background texture for color surface was most of the time not right and not updated accordingly
- The default address mode was not correct for some texture types
- Add some additional checks 
- Add a warning as we don't support unnormalized textures
- Fix the min filter for linear strided textures
- Fix mipmapping and trilinear filtering for some cases when creating a texture sampler.
> modules/SceGxm, renderer/vulkan: Improve accuracy of texture related functions

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gxm_types.h
- vita3k/renderer/include/renderer/vulkan/pipeline_cache.h
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- Fix an issue where the 4 upper bits of the stencil were always cleared with force_load disabled
- Update the SceGxmDepthStencilSurface to make it nicer and have the same layout as SceGxm
- Handle disabled stencil surfaces in the renderer, can potentially slightly improve performance on tiled renderers
> modules/SceGxm, renderer: Improve accuracy of depth stencil surface

- vita3k/shader/include/shader/usse_constant_table.h
- vita3k/shader/src/usse_utilities.cpp
- vita3k/util/include/util/bit_cast.h
- vita3k/util/include/util/float_to_half.h
Fixes ` warning: dereferencing type-punned pointer will break
strict-aliasing rules [-Wstrict-aliasing]` when compiling with `-Wall`.
`assert()` is ignored on release builds.
Fixes many `may be used uninitialized` warnings.
> shader: use `std::bit_set`,  return `nullptr` after `assert`

- vita3k/modules/SceDriverUser/SceMotion.cpp
forgor the *, pretty sure it didn't mean to set only a few bytes to 0 :D
> modules/sceMotion: Fix wrong sizeof usage on memset

- vita3k/config/include/config/config.h
- vita3k/ctrl/include/ctrl/state.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/gui/src/controllers_dialog.cpp
gui/controllers dialog: Add custom LED color support.
- Add checkbox for enable custom color.
- Fix End() pos.
> gui/controllers dialog: Add custom LED color support.

- vita3k/renderer/src/texture_cache.cpp
This is my last resort of fixing this weird bug that only happens on the AUR, AND I DONT KNOW WHY asserts are being compiled, i checked every compiler flag and it still doesn't make sense to why it happens on a release build, but anyways, i didnt want to modify upstream but here i am, doing exactly that, i give up, this is only needed for that one specific case of being compiled using makepkg
fixes https://github.com/Vita3K/Vita3K/issues/2922
> renderer: Fix OOB access on texture cache

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/src/modules/player.cpp
- vita3k/util/include/util/log.h
util/log: LOG_*_ONCE macros
modules/SceNgs: implement sceNgsVoiceGetModuleType
ngs/modules/player: workaround crash if required playback frequency is invalid
ngs: stub for incomplete output paths (for Smart As [PCSF00216])
ngs: stub for null voice definition
> ngs: workaround crashes on invalid configurations

- vita3k/vkutil/include/vkutil/vkutil.h
Just hide some annoying warnings in VulkanMemoryAllocator-Hpp for clang
> vkutil: hide some warnings

- vita3k/config/include/config/config.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/shader/src/spirv_recompiler.cpp
Fix an issue where the offset in the generated shader was wrong when using texture viewport without memory mapping. Also add memory mapping support in the feature mask. This should fix #2943 .
The second commit sets by default the renderer accuracy to high. On desktop, performance is already fine with the accuracy set to high (except when upscaling a lot I guess), so it does not make too much sense to set it to standard by default.
> renderer/vulkan, shader: Fix texture viewport without memory mapping

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/interface.cpp
- gui: Fix Ignore the ps key on the user management.
should fix crash and double view in home when press ps with ignore it.
fix pos of ignore key pressed.
> gui: Fix Ignore the ps key on the user management.

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
Fixes crash in the case when `sceSaveDataDialogGetResult` is used on a save dialog with no slots.
> sceSaveDataDialogGetResult: Fix OOB when slots are empty

- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/texture.cpp
The game flower does not specify a scissor matching the current macroblock, so as a fallback this PR implement a workaround (quite inefficient, but it can't really do better, render each draw in its own render pass).
This fixes the graphical regressions in flower and also the blur issues (like other games using macroblock sync).
> renderer/vulkan: Add support for macroblock sync when a scissor is not specified

- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/texture_format.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
Perform the following fixes:
- BC4 and BC5 have respectively 1 and 2 components but we apply a 4-component swizzle to them
- Add signed BC4 and BC5 to Vulkan
- Only BC1 and BC4 have 8-byte blocks
- When decompressing BC2, the alpha component is wrong and corrupts the whole texture (backport from Android, not an issue on PC as BC textures are never decompressed)
This fixes the text not showing in One Piece Burning Blood.
> renderer: Fix BCn textures

- vita3k/kernel/src/sync_primitives.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/translator/texture.cpp
- vita3k/shader/src/usse_utilities.cpp
When converting (and normalizing) from float to integer, it looks like the value needs to be rounded.
Not doing that causes a bone index of value 308.999 to be rounded down to 308, causing the bone index to be wrong.
This PR also removes the unnecessary std 450 imports (that otherwise pollute the generated shader and could cause some issues with shader driver compilers).
I also removed the sema cancel because something that can happen multiple times per frame shouldn't be logged.
This fixes the vertex explosion in FIFA games.
> shader: Round before converting to integer

- vita3k/modules/SceGxm/SceGxm.cpp
Some fields of linear strided textures were left initialized, in particular the one controlling gamma correction. This caused the YUV planes used during God of War cutscenes to have gamma correction enabled, in turn causing the cutscenes to be green.
> modules/SceGxm: Properly initialize all fields of linear strided textures

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/src/ngs.cpp
My previous pr #2967 caused regressions in other games. This was due to an inaccuracy in another function sceNgsPatchGetInfo which returned that the input and output of a patch were always stereo. Returning the correct number of channels fixes this issue.
I also updated the fix to take into account the case where the destination channel is mono (should cause less issues because the output is almost always stereo but anyway).
Finally, looking at the behavior of many games when creating a patch, I'm quite positive the volume matrix must be set to 0 at the beginning and not the identity.
> ngs: Improve support for mono voices

- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
This fixes the score evolution in persona dancing not being visible on higher resolutions.
> renderer: Scale line width with resolution multiplier

- vita3k/gui/src/gui.cpp
- gui: check if app is found in index for log in init_app_background.
should fix crash when fw is missing.
> gui: check if app is found in index for log in init_app_background.

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
I'm wondering how this wasn't breaking every game using a stencil.
Fixes FIFA graphics.
> renderer/vulkan: Fix stencil fail op

- vita3k/shader/include/shader/usse_translator.h
The RepeatMode Both means that both internal and external register must be increased during each step.
This (partially) fixes graphics in Chaos Rings 2.
> shader: Increase repeat offset for GPI on mode both

- vita3k/shader/src/translator/ialu.cpp
- vita3k/shader/src/usse_disasm.cpp
- vita3k/shader/src/usse_utilities.cpp
This fixes the graphics of the refined version of Odin's sphere.
Clearing the shader cache is required to see the improvement.
> shader: Fix loading of negative immediate and implement rotation

- vita3k/kernel/include/kernel/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gl/types.h
- vita3k/renderer/include/renderer/texture_cache.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/util/include/util/containers.h
The current vulkan surface cache was basically a copy-paste of the opengl surface cache, swapping opengl functions with vulkan functions.
But it had many issues related to the fact it was really complex and to the way vulkan is a lot closer to the harware:
- create two different functions for retrieving surfaces either as a framebuffer or as a texture. Make the code much more readable and easy to modify.
- Refractor the result given when retrieving textures from the surface cache so that a whole new Image field does not have to be created when all we want is a different view
- The sampler state is different compared to the texture state in Vulkan. So create a separate sampler cache for it. This avoids duplication of textures if the only thing which changes is the filter or lod parameter. …
> renderer/vulkan: Rewrite surface cache

- external/CMakeLists.txt
- vita3k/config/include/config/functions.h
- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/module/include/module/bridge.h
- vita3k/util/CMakeLists.txt
- vita3k/util/include/util/tracy.h
- vita3k/util/include/util/tracy_module_utils.h
- vita3k/util/include/util/vector_utils.h
- vita3k/util/src/util.cpp
Main idea of this PR is optimization of tracy usage
* automatic collection of modules list for advanced profiling. Remove available modules list from config.
* faster check if module is active for advanced profiling
* rename some macro not used yet to correspond tracy naming convention
* disable unused tracy option to save screenshots on demand. This option create background thread to compress that images, so it's better to disable this if nobody use it.
* some minor code improvements
I use global variables because I'm lazy.
> tracy: autoregister modules, faster check if module is profiling

- vita3k/config/src/config.cpp
pretty self explanatory, if config.yml doesnt exist it will just make it with the default config + CLI args, else it will simply load it and dont generate anything, just parsing it + CLI args, like it should have been from the start.
> config: Get rid of default.yml

- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
There were many cases where (especially in initial setup) where the native file dialog would fail to open either due to bad system config or something else, now instead of just doing nothing it will actually log why it failed to open the file dialog in case it happens.
Especially useful for experienced users which can debug and fix it if the error is bad configuration on system side
> gui: Add log of NFD Error in ever case it can happen

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_utilities.cpp
Indexed values had a few issues:
- The shift offset wasn't considered
- The value position is not known at compile time, so the code has to be modified to do the vec4 offset computation in spirv instead of in c++ when it is not possible to do the latter. 
This fixes the screen transition in hyperdimension neptunia games.
> shader: Fix loading of indexed values

- vita3k/shader/src/translator/texture.cpp
The PA registers can't be used in the secondary program, replace it by SA when it happens.
This fixes the character borders in Hyperdimension Neptunia games.
> shader: Do not sample to PA in secondary program

- vita3k/renderer/src/vulkan/context.cpp
Hyperdimension neptunia also does not respect the macroblock constraints (but this time the scissor extent is not the rendertarget extent). Handle this case for the slow path.
Also replace the renderpass by one which loads and saves the stencil each time, as this is needed for the slow path.
This fixes half the screen being black in hyperdimension neptunia.
> renderer/vulkan: Improve macroblock slow path workaround

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- CMakePresets.json
The linux CI started failing randomly because of some constexpr/consteval bug.
Hopefully updating to clang15 should fix it (and anyway it's still a good thing to do).
> ci: Switch to clang15 for the linux build

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
At the request of retrodeck's developper, add an option to disable checking for updates during startup.
> config, gui: Add option to disable checking for updates

- .github/workflows/c-cpp.yml
The latest moltenVK release does not have a big sur bottle, so stop using it.
I believe this increases the MacOs version required to use Vita3K but that's still better than the CI not working. 
@KhoraLee if you want you can try to find a better solution after this PR is merged.
> ci: Remove big-sur bottles for homebrew

- external/ddspp/ddspp.h
- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/textures.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/texture_cache.h
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/texture/format.cpp
- vita3k/renderer/src/texture/replacement.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- Fix DDS exporting where some dumped textures could be not recognized by some tools because of garbage in the header
- Fix the swizzle of some DDS textures being imported
- Add support for importing BC6/BC7 textures
- Allow imported textures to be placed in subfolders in the import folder
- Fix loading of mips for compressed textures (error in the DDS library)
> renderer: Multiple improvements for texture replacement

- vita3k/CMakeLists.txt
Static linking stdc++ allows the user to run a kernel that doesnt run the correct version of libc, which its pretty common because of distros not updating in time or simply the ci updates and very few people are on the updated kernel, should fix all errors of linux users not being able to run the emulator (SteamOS, debian, ubuntu, etc)
> cmake: Static link stdc++

- .github/workflows/c-cpp.yml
The version of sccache used by the github action was too old (and the ccache version installed by github action is also too old)
Instead, switch to ccache and install the latest version using chocolatey.
This fixes the build time on Windows https://github.com/Macdu/Vita3K/actions/runs/6677842203/job/18148254373
> ci: Switch to a recent version of ccache on Windows

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/gui.cpp
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/pipeline_cache.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
On Vulkan, what is causing stutter is not really the step to create the ShaderModule, but instead a new pipeline creation. These two often coincide but sometimes not (also a lot more pipelines are created compared to shader compiled).
This PR changes the message on Vulkan from "k shaders compiled" to "k pipelines compiled" to have a better understanding of if a pipeline compilation is causing the stutter.
I also changed the pipeline lookup from an unordered_map to a boost unordered_map_flat, as this structure is accessed a lot.
> renderer/vulkan, gui: Replace shaders compiled by pipelines compiled on Vulkan

- external/CMakeLists.txt
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
Vita3K is currently compiled with only SSE support. This is annoying as xxhash has AVX2 (and even AVX512) paths that are 2 times faster than the SSE2 paths and that the main bottleneck for the render thread on PC is texture hashing.
Enable the dispatch version which allows the fastest path always to be taken when hashing. This should decrease a lot the CPU load (which is not high, but anyway) when the CPU supports AVX2.
I do not use the dispatch version for the pipeline cache hash as the size is known (and small) so the inline version should be as fast.
> external: Use dispatch version of xxhash

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
Make sure the pipeline cache gets saved when new pipelines get compiled, even when no shader was compiled.
> renderer/vulkan: Move pipeline save refresh timer

- vita3k/renderer/src/vulkan/context.cpp
First, indeed using MSAA without a color surface on the PS Vita is completely useless (the depth stencil is never downscaled). The only thing it changes is the scaling of the fragment coordinate in the fragment shader I guess.
FFX remaster uses it. This fixes the crash when launching it with the vulkan renderer.
> renderer/vulkan: Improve support of MSAA without a color surface

- vita3k/gui/src/gui.cpp
At midnight, GUI displays 0:[MM] AM.
At noon, GUI displays 12:[MM] AM.
This is incorrect; midnight should be rendered as 12:[MM] AM, and noon should be rendered as 12:[MM] PM.
> gui: Fix 12-hour time display.

- vita3k/mem/include/mem/functions.h
- vita3k/mem/src/mem.cpp
- vita3k/modules/SceLibc/SceLibc.cpp
- vita3k/modules/SceSysmem/SceSysmem.cpp
Improve how the virtual memory is handled to match better what is happening on a real PS Vita.
Right now, the memory is allocated starting from 0 whereas on the PS Vita, the user main memory is allocated starting from 0x81000000. This can have some impact as games can expect addresses to be negative. 
I'm starting the user address at 0x80000000 instead of 0x81000000 because it shouldn't make a difference and games compiled with old SDKs want the elf segment to be exactly as 0x81000000 so doing so makes sure this memory range is not allocated for whatever reason before.
This fixes a crash in Trails in the sky the 3rd.
> mem: Improve accuracy of virtual memory

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
This is needed to fix Retroarch and Gundam Extreme VS-Force.
I'm not entirely sure this is the right behavior (could be disabling depth clipping, but then what would happen with normalized depth formats?). At least this is more accurate than what we are doing right now.
> renderer/vulkan: Enable depth clamping

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
The libcurldev library in ubuntu implements all the protocols, so it has a lot of dependencies (most not supported by the steam deck....)
Use the builtin version (implementing only HTTP and HTTPS) to fix that for the time being.
> ci: Switch to builtin curl for linux

- vita3k/config/include/config/config.h
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/renderer/include/renderer/gl/state.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/texture_cache.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/texture/replacement.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
At the request of a third-party group, add a keyboard shortcut to toggle texture replacement (enable/disable texture importation). 
Also contains some code cleanup for accessing the texture cache.
> renderer, gui: Add keyboard shortcut to toggle texture replacement

- vita3k/display/src/display.cpp
On some devices (like the steam deck), the screen has a refresh rate of 60 and they don't support the Mailbox present mode. 
Because when the UI/common dialog is displayed ingame, a frame tries to be presented 1/60th of a second, this can cause the command buffer processing to starve when the display thread and the screen VBlank are slightly out of sync. To fix this limit the presentation rate of the UI/common dialog while ingame to 30fps.
This should fix the Save dialog being unresponsive on the Steam deck and other devices.
> display: Limit the refresh rate of the UI/common dialog

- CMakeLists.txt
- vita3k/CMakeLists.txt
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/texture/replacement.cpp
Fixes Vita3K/#3069
First commit fixes the build issues with Boost 1.74 by replacing the Boost::unordered_set::contains() usage with a ::find() != ... ::end() check. [As mentioned by @Macdu.](https://github.com/Vita3K/Vita3K/issues/3069#issuecomment-1805704221) Also fixes a build bug involving a std::string_view.
Second commit fixes cmake so that enabling VITA3K_FORCE_CUSTOM_BOOST will _actually_ force the use / compilation of the Boost submodule over whatever the host provides.
> renderer/texture: Build fix for Boost 1.74.

- external/CMakeLists.txt
Issue reported in [the AUR](https://aur.archlinux.org/packages/vita3k-git#comment-942974), This enables the option of compiling the AVX implementation of xxh3 even if it will crash on SSE2-Only CPUs, as this seems to only affect few users at the moment i decided to go with OFF as default, once merged the option will be set on the PKGBUILD as ON for the few users as the build generated by it is intended for usage in the same machine it was compiled on, not sharing
> cmake: Enable XXH_X86DISPATCH_ALLOW_AVX by default

- vita3k/modules/SceJpeg/SceJpegUser.cpp
My PR #3041 caused some regressions in Gravity Rush. I believe it is caused by malloc-ing and then freeing a buffer of size 0 (which the game/underlying librairies do not like).
To fix this, I give a small, but non-zero value to the buffer sizes returned by sceJpegGetOutputInfo (I don't think reverse engineering this value is worth the time, also before PR #3041, the buffer allocated was literally of random size).
> modules/SceJpeg: Fix buffer sizes value

- .github/workflows/c-cpp.yml
- .gitignore
- CMakeLists.txt
- CMakePresets.json
- appimage/apprun.sh
- appimage/build.sh
- appimage/build_updater.sh
- appimage/vita3k.desktop
- vita3k/CMakeLists.txt
This is an attempt at packaging Vita3K as an AppImage.
It currently depends on [linuxdeploy](https://github.com/linuxdeploy/linuxdeploy) as it's final packager. (linuxdeploy itself is shipped as an AppImage.)
To build it, simply place the release from linuxdeploy in appimage/linuxdeploy.AppImage and use the linux-ninja-clang-appimage cmake preset.
> build: Add support for building AppImages under linux

- vita3k/app/src/app.cpp
- vita3k/display/include/display/functions.h
- vita3k/display/include/display/state.h
- vita3k/display/src/display.cpp
- vita3k/gxm/include/gxm/state.h
- vita3k/main.cpp
- vita3k/modules/SceDisplay/SceDisplay.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gl/state.h
- vita3k/renderer/include/renderer/gxm_types.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/sync.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
First part: There was some flickering in some games (persona 4 dancing, Catherine) when using memory mapping. This was caused by the game using the display callback in order to know when the rendering was done (which is fine without memory mapping because everything is copied, but with the game was corrupting some uniforms / vertex buffers). Making the sync object be signaled after the GPU rendering is done (like what they are supposed to do) fixes this issue but...
Second part: This causes an increase of video latency (the frame needs to be rendered, then the request thread notified, then the display thread notified, then the callback executed, which calls setDisplay, then the main thread finishes its queue, record the render command and swapchain swaps and submit them...). To prevent …
> modules/SceGxm, display, renderer: Improve accuracy of sync objects and decrease video latency

- .github/workflows/c-cpp.yml
The current ci doesn't copy the output *.AppImage files in create-release. As such it doesn't appear on the releases page.
That's due to me using invalid expansions in the if statement and cp command, and not having a valid directory to copy to. (Copy paste bug. The macos-build cd's into it's directory before the cp command is given, whereas the appimage build does not. As such the artifacts directory is in the PWD when cp is called.)
This PR should fix both of these errors.
> ci: Fix copying AppImage build in create-release

- vita3k/app/src/app_init.cpp
- vita3k/emuenv/include/emuenv/state.h
- vita3k/gui/include/gui/imgui_impl_sdl.h
- vita3k/gui/include/gui/imgui_impl_sdl_vulkan.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/imgui_impl_sdl.cpp
- vita3k/gui/src/imgui_impl_sdl_vulkan.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/lang/src/lang.cpp
- vita3k/renderer/include/renderer/gl/screen_render.h
- vita3k/renderer/include/renderer/gl/state.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/screen_renderer.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/screen_render.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/screen_filters.cpp
- vita3k/renderer/src/vulkan/screen_renderer.cpp
- vita3k/util/include/util/fs.h
This fixed imported/exported textures being in the same path as the executable (in linux) by default, however, this come at the super small cost of not being able to change the base path from where gui font, lang and builtin shaders get loaded from, shouldnt be a problem since i really see no reason for someone to use it, now the textures folder is `.local/share/Vita3K/textures` by default, shared_path should never be used for stuff thats meant to be inside the executable folder, and base_path only for reading files, never writing
> io: Fix export/import textures path being same place as exec in linux

- vita3k/modules/SceNpBasic/SceNpBasic.cpp
Because the number of friends was not initialized, Borderlands 2 was thinking that I had around 2 billion friends and literally had not enough space to handle them all.
Instead, tell the games we have no friends (sad Macdu emote) as a workaround.
This allows Borderlands 2 to get back to menu.
> modules/SceNpBasic: Tell games that I have no friends

- vita3k/app/src/app_init.cpp
`static_assets_path` was not set and this empty value caused vulkan renderer initialize failure on macOS
Fix #3085
> io: set default static assets path with base path

- vita3k/util/src/float_to_half.cpp
Improve the float_to_half code such that native __fp16 types are used on aarch64 and on x86_64, the fast path can be used with any compiler (and not just MSVC).
> util: Improve float_to_half code

- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/screen_filters.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
- vita3k/renderer/src/vulkan/texture.cpp
- vita3k/util/include/util/bit_cast.h
- vita3k/vkutil/include/vkutil/objects.h
- vita3k/vkutil/include/vkutil/vkutil.h
- vita3k/vkutil/src/objects.cpp
A lot of small changes to the vulkan renderer:
- Remove the mask bit support, was not really supported (never enabled), and if I ever end up implementing it, I would do something completely different anyway
- Move a bunch of stuff from the context to the state. This is kind of necessary for some gxm commands to be called before the gxm context is created. This allows chaos ring to go ingame with the Vulkan renderer
- Make the vma allocator a static field in vkutil, instead of having to supply it to every object. Also remove the thread safety part of vma as it's not needed by Vita3K right now (all vma calls are in the same thread). And replace some of my custom functions by a call to std::bit_cast which does the same thing.
- Rewrite the descriptor set model, this allows the call to …
> renderer/vulkan, vkutil: Refractoring of the Vulkan renderer

- vita3k/ngs/include/ngs/modules/equalizer.h
- vita3k/ngs/src/ngs.cpp
The two duplicate info buffer (VoiceLock causes ngs to use one and returns the other) are adjacent in memory.
Replicate (kind of) this behavior in Vita3K.
This fixes Borderlands 2 crashing with ngs enabled.
> ngs: Duplicate info buffers

- vita3k/gxm/include/gxm/types.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
If the fragment shader outputs no color and has no effect, it must be disabled.
This fixes the rendering issues in Borderlands 2.
> renderer/vulkan: Disable the fragment shader when it has no effect

- CMakePresets.json
- appimage/apprun.sh
- vita3k/app/src/app_init.cpp
* Shared path is supposed to be ALWAYS read-write, with this we only set the static assets dir to the correct one inside appdir for the appimage
Before:
After:
> io/appimage: Correctly handle appdir for static and shared assets

- appimage/apprun.sh
- appimage/vita3k.desktop
Running the appimage once worked fine, but clicking the option to integrate it into the desktop wasnt working because the desktop entry was wrong, it was missing the `Exec` line.
> appimage: Fix desktop integration

- vita3k/util/include/util/tracy_module_utils.h
- vita3k/util/src/tracy.cpp
This is a fix for the static initialization problem which can lead to a crash. I compile Vita3K myself with Clang on Windows and it does crash without this fix. See https://isocpp.org/wiki/faq/ctors#static-init-order.
> util: Fix static initialization in tracy.cpp

- vita3k/modules/SceGxm/SceGxm.cpp
sceGxmMidSceneFlush can only be called within a scene.
This allows Metal Gear Solid 2 to go ingame using the vulkan renderer.
> modules/SceGxm: Add missing parameter check for sceGxmMidSceneFlush

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- vita3k/np/include/np/state.h
Remove the PSN status option as Vita3K supports no online capability and Unknown is basically never supposed to be returned.
Set the PSN status to signed out by default as this matches the best the current state of Vita3K (we don't want games calling too many PSN functions).
This allows Borderlands 2 and Bastion to boot without having to change settings.
> gui, np: Replace PSN status by signed in

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/h264.cpp
- vita3k/codec/src/player.cpp
- vita3k/modules/SceVideodec/SceVideodecUser.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/texture/yuv.cpp
When using the video decoder, the game can ask whether to output YUV P3 (3 planes) or YUV P2(2planes, the U and V components are interleaved). Most games actually ask for a YUV P2 format.
However, before this PR, Vita3K was not looking at this and always outputting YUVP3 images. This was not causing issues for most of the games as YUVP2 textures are decoded as if they were YUVP3 (which is completely wrong, I noticed this while rewriting the texture cache and this was not documented...).
This PR properly decodes H264 as YUVP2 or YUVP3 depending on what has been asked and properly support the YUVP2 format in the renderer.
This fixes the FMVs in Ys Origin.
> codec, renderer: Improve YUV format implementation

- vita3k/kernel/src/thread.cpp
- The value given to the thread end callback should obviously be SCE_KERNEL_THREAD_EVENT_TYPE_END and not SCE_KERNEL_THREAD_EVENT_TYPE_START (although it did not matter as this value is not used by libc's callback)
- We must make sure the returned value is not modified by the thread end callback, Tearaway was expecting a thread to return 1 and the callback was modifying it to 0, causing the game to loop in menu.
This allows Tearaway to go back again ingame.
> kernel: Improve thread end callback

- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/usse_utilities.cpp
Some shader fixes (the constant table being used for f32 loading could be wrong and 16-bit integer loading was also wrong).
Also the absolute flag was used when it shouldn't for some cases of the vdual instruction.
This fixes all the remaining graphical issues in 2D ubisoft games (rayman and child of light)
> shader: Fix constant loading, dual absolute + typo

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
If a fragment shader has no output, but has a side effect (depth replacement / discard), we can't disable it. However, we still want it not to affect the surface (by setting the write mask to 0).
This fixes the (small) remaining graphical issues during menu/character selection in project diva X.
> renderer/vulkan: Use empty mask if frag has no output

- vita3k/kernel/src/thread.cpp
The kernel rounds up the stack size to the next page size.
Spiderman was allocating a stack of size 0x180c4 and expecting the stack pointer to be 8 byte aligned, which wasn't the case.
This allows Spiderman to go ingame---.
> kernel: Page-align the stack size

- vita3k/modules/SceGxm/SceGxm.cpp
According to my testing, the rendertarget size goes from 80 KB (128x128, one scene per frame) to 5MB (4096x4096, 3 scenes per frame), and is for a usual target around 200KB. The current value of 2MB is way too much and can cause out of memory issues in some cases. It is way better to give a lower bound (we don't use this memory anyway), so I now set it to 64KB.
This allows Killzone to progress further ingame.
> modules/SceGxm: Decrease stubbed rendertarget size

- vita3k/app/src/app_init.cpp
Fixes an issue where if Vita3K is called to run from an AppImage (not AS an AppImage) it will incorrectly believe that it is running AS an AppImage, and try to read its files from a place they do not exist
> app: fix incorrect AppImage assets handling

- vita3k/renderer/src/sync.cpp
Only signaling sync objects after the whole render has been done is more accurate and needed by a few games (like Persona 4).
However, it has a really big performance cost for many games (30-40% performance decrease), so this PR only enables it with high accuracy enabled.
> renderer: Use accurate sync object synchronisation only with high accuracy

- vita3k/modules/SceGxm/SceGxm.cpp
Unit 13 has a situation where:
- Frame A is being presented
- The game asks for frame B to be presented instead of frame A, causing the display entry thread to wait for frame B to be ready before swapping it
- The game renders to frame A then to frame B, causing the render thread to wait for frame A to be available (not being displayed anymore) before doing anything
To be honest, I'm not sure how to react in this situation, but it looks like softlocking is not the correct way. Instead, as a better workaround, if the display thread waits for (way) too much, just do the swap.
This allows Unit 13 to go ingame.
> modules/SceGxm: Workaround to prevent softlock when swapping images

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Returning 0 as the process id sounds like a very bad idea. I'm not sure if this fixes anything but I'd better change it now than spend hours debugging a game to figure out this is the cause.
> modules/SceThreadmgr: Return 1 as the process id

- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/include/shader/usse_program_analyzer.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- vita3k/shader/src/usse_utilities.cpp
Implement the FX10 unpack instruction on the shader. From my (limited) understanding and reverse engineering, the C10 type is actually a signed fixed-point floating point.
Another issue that pops up is that we are always using 32-bit type for regformat vertex attributes, this can cause the data to be unaligned (fine for most gpu), but also the data to overlap itself (killzone uses a regformat char2 with a 2-bytes stride), which causes most GPU to crash.
Instead, rewrite the regformat attribute to use an underlying type of the same size (for half type, use a U16 type). The only exception being the above 10-byte floating points which are passed using a vector of char (minimal alignment requirement, safest way to do it).
This fixes a few issues with Killzone and allows it to go ingame using …
> renderer, shader: FX10 and regformat improvements

- tools/usse-decoder-gen/grammar.yaml
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/translator/special.cpp
- vita3k/shader/src/usse_translator_entry.cpp
Multiple small shader fixes:
- Fix the mask of CMP(MSK) for multiple cases where it was wrong
- From my understanding, CMOV is vectorized only for floating points
- Implement the SMBO shader instruction
This allows Spiderman to go ingame using the Vulkan renderer
> shader: Test and conditional moves improvements

- vita3k/gxm/include/gxm/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gxm_types.h
This improves and supersedes PR #3140 as it was causing issues (messing the sync objects) in some cases when the timeout was triggered but a softlock was not expected to happen.
This does not handle all cases (it won't work if scenes using the old and new sync objects are interleaved) but it is good enough to still allow Unit 13 to go ingame and will only trigger to prevent a softlock.
This should fix #3157.
> modules/SceGxm: Improve softlock prevention for sync object

- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/surface_cache.cpp
Improve the surface cache modification:
- Make sure the tiling and stride always match, this should fix all false positives when looking for a texture in the surface cache (hopefully this fixes the random graphical glitches in Freedom war and Tales of Hearts).
- Fix some issues caused by using the width instead of the stride, this fixes some lighting issues in FIFA and is also needed for spiderman to render correctly.
> renderer/vulkan: Improve surface cache

- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix a small mistake from my PR #3160
> renderer/vulkan: Fix issue with surface cache typeless copies

- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- Remove the use of the can_use_deferred_compilation flag as it causes way too many false positives (for the really few games for which this causes long-standing graphical issues, you can disable async pipeline compilation instead).
- Make sure to detect all the cases where a shader draws over all the surface (draw count = 3: can be a triangle covering everything, draw count = 4 or 6: can be a quad covering the surface).
- Fix an issue where the compiling pipeline message could show up for pipelines already cached.
> renderer/vulkan: Improvements for asynchronous pipeline compilation

- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix some regressions from my surface cache rewrite. This caused D24S8 (but not only) depth sampling to sample the stencil instead.
This fixes the light/shadow regression in gravity rush and should fix a few other regressions too.
> renderer/vulkan: Fix depth/stencil identification

- vita3k/modules/SceAudio/SceAudio.cpp
If (-1) is specified for any argument (excepted for port), current configuration is used instead.
Fixes crashes in some VNs (and maybe in other games which use this).
Thanks nishinji who found the commit when the regression appeared.
> Fix sceAudioOutSetConfig implementation

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/display/include/display/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/modules/SceDisplay/SceDisplay.cpp
Add a FPS hack, similar to what most VitaGrafix patches are doing (but on the emulator side).
This hack allows some games running at 30 fps to run at 60 fps.
However it is only a hack, meaning it won't work on all games, in particular:
- Some games won't be affected at all
- Some games will run at twice the speed (but with the audio running at the correct speed)
I tested it on Ys 8, GoW and Uncharted where it works as intended.
> display: Add FPS hack

- .github/workflows/c-cpp.yml
Switch to using static librairies with vcpkg on Windows (instead of dynamic ones).
This removes 5 dll (boost, curl, openssl ssl and crypto and zlib) from the generated windows zip and decreases its size by a few megabytes.
> ci: Use static dependencies on windows

- vita3k/renderer/src/transfer.cpp
- vita3k/util/include/util/keywords.h
Me and nishinji were having problems building RelDebug.
That's because this macro is conflicting with tracy submodule. So I decided to rename it.
If you have better idea for new name or other ways to fix it, feel free to tell.
> Fix building RelDebug

- lang/system/en-gb.xml
- lang/system/en.xml
- vita3k/app/src/app_init.cpp
- vita3k/audio/include/audio/state.h
- vita3k/audio/src/audio.cpp
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
Adds a setting to configure a global audio volume. This works by multiplying each audio port's volume by the global volume at the adapter level. For example, if you set the global volume to 50%, it will multiply each port's volume by 0.5, cutting it in half.
The setting is only usable with the Cubeb backend, as the SDL backend does not provide a means of changing the volume.
> config: Implement global volume percent setting.

- vita3k/app/src/app_init.cpp
Improves path support in the following ways:
* macOS:
* Config and other files are currently placed inside the app bundle's `Resources` directory, as by default this is what `SDL_GetBasePath` returns. This can be inconvenient as if the app bundle is ever deleted/replaced, config files will be lost. Users will also likely not even realize the files are being stored here as generally app bundles are not used to store user data. Instead, use the `SDL_GetPrefPath` "~/Library/Application Support/Vita3K/Vita3K" by default.
* We can't just use the path outside the app bundle as the user may install Vita3K to "/Applications/", which should not be used to store emulator data.
* macOS & Linux:
* Since macOS now uses the user data path by default, and Linux already uses the XDG paths by default, …
> vita3k: Improve path support for Linux and macOS.

- vita3k/renderer/src/texture/replacement.cpp
Probably fixes most crashes because of texture export in most games.  At least it fixes texture export in Gravity Rush.
This thing was going OOB.
> Fix texture export for gamma textures

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/gl/surface_cache.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/vulkan/creation.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/renderer/src/vulkan/sync_state.cpp
Implement fractional resolution upscaling.
It is now possible to set the resolution upscaling value from 0.5x to 8x, with increments of 0.25x.
This implentation relies on the fact that 32-bit floating points can represent integer values (with a fractional part of either 0, 0.25, 0.5 or 0.75) exactly up to 4 194 304.75.
Not that there may be some small issues appearing with games that don't use a width or height that is a multiple of 4.
Also I'm disabling surface sync on OpenGL if the resolution multiplier is not an integer because its implementation does not allow it.
> renderer: Implement fractional upscaling

- vita3k/codec/include/codec/state.h
- vita3k/config/include/config/state.h
- vita3k/gdbstub/src/gdb.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/threads_dialog.cpp
- vita3k/io/src/io.cpp
- vita3k/kernel/src/debugger.cpp
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/load_self.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/main.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/shader/include/shader/usse_program_analyzer.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/vkutil/include/vkutil/objects.h
kernel/thread: fix possible crash in log_stack_traceback
modules/SceLibKernel: more correct sceClibSnprintf
kernel/load_self: fix possible crash on incorrect library modules. load process params from first loaded module (eboot.bin) only
modules/SceGxm: fix crash if display_thread not found
kernel/debugger: remove direct access to mem.memory to support memory mapping more complete
vita3k: remove direct access to kernel.threads (it's not thread-safe)
vita3k: implement and fix virtual destructors for class hierarchies to prevent memory leaks
clang-tidy warning: Constructing string from nullptr is undefined behaviour
clang warning: use after std::move
> vita3k: some minor bugfixes

- vita3k/renderer/src/vulkan/surface_cache.cpp
When using MSAA, tiles size is actually 32x16 and not 16x32.
This fixes the blur in Nihon Falcom games.
> renderer/vulkan: Fix MSAA2x

- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/vkutil/include/vkutil/vkutil.h
```
Vita3K: /media/fan/odin2/soft/Vita3K/external/VulkanMemoryAllocator-Hpp/VulkanMemoryAllocator/include/vk_mem_alloc.h:14965: VkResult VmaAllocator_T::CalcAllocationParams(VmaAllocationCreateInfo &, bool, bool): Assertion `(inoutCreateInfo.flags & (VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT | VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT)) != 0 && "When using VMA_ALLOCATION_CREATE_MAPPED_BIT and usage = VMA_MEMORY_USAGE_AUTO*, you must also specify VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT or VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT."' failed.
```
When I tried running it on arm64 Linux, I encountered this error. The game crashes as soon as I start it. However, after I made some modifications to the memory allocation part, I was able to successfully enter the …
> vita3k: Fix some arm64 running issues

- vita3k/cpu/include/cpu/impl/dynarmic_cpu.h
- vita3k/cpu/src/dynarmic_cpu.cpp
Update dynarmic to the latest version, I didn't add the latest riscv related commits as they are not relevant for Vita3K for the time being.
This contains some performance improvements but also a commit making memory invalidation thread safe (which I will soon need).
> external, cpu: Update dynarmic

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/transfer.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
Improve the transfer copy and downscale operations to look at the surface cache and wait if needed and surface sync is available.
Moreover, rewrite the transfer downscale operation with an are filter if available (this matches the PS Vita behavior).
This fixes character textures in Phantasy Star Nova (with memory mapping and surface sync enabled).
> renderer: Improve transfer copy and downscale

- vita3k/interface.cpp
- vita3k/kernel/include/kernel/load_self.h
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/types.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/load_self.cpp
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
This PR adds support for module unloading and reloading (for both sysmodules and user modules).
This is allowed thanks to the recent dynarmic update which made memory invalidation thread safe.
This requires tracking all the imported and exported variables and functions for all the modules.
In the way I fixed a lot of thread races and other issues.
This allows Final Fantasy X to be playable.
> kernel: Add support for module unloading/reloading

- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/texture.cpp
The spv::Builder::createOp function seems to only take spv::Builder generated id rather than arbitrary values, and the spv::Builder::addIdOperand throw an assert when receiving 0 as an id. So i replaced all c++ id literals by makeIntConstant, I'm really not sure if this is what should be done here but at least it prevent the assert.
> shader: fixed misuse of spv::Builder::createOp with spv::OpVectorShuffle

- vita3k/gui/src/app_context_menu.cpp
- vita3k/renderer/include/renderer/gl/state.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
In addition to @nishinji PR, let's add GPU name into github issue template too.
IDK why, but github clang-format go crazy on brackets around (version_raw)
> renderer: add actual GPU name into github issue template

- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/usse_translator_entry.cpp
The std map seems unnecessary here and can safely be replaced by std array. Doing so will avoid unnecessary dynamic allocations and more expensive iterations/lookups.
> shader: replaced std map by std array to store shader code in convert_gxp_usse_to_spirv

- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_utilities.cpp
There are two main ways used by GPU to normalize and un-normalize signed integers, each with its pros and cons.
This is why signed integer normalization is implemented by Vita3K's shader recompiler... in a third way that is both really inefficient performance wise and just wrong.
I corrected this to match the behavior of a real PS Vita GPU. I also fixed the range from the fx10 type (from my testing on Killzone, fx10 fixed range is actually [-2,2])
> shader: Improve signed integer normalization

- vita3k/renderer/include/renderer/vulkan/surface_cache.h
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/vkutil/include/vkutil/vkutil.h
- vita3k/vkutil/src/vkutil.cpp
Allow games to sample only a part of a depth/stencil (instead of only the whole or upper part).
This fixes shadows in Ratchet and Clank games.
I alsor renamed the DepthReadOnly layout to DepthStencilReadOnly because it is also used for stencil reading.
> renderer/vulkan: Improve depth/stencil retrieval

- vita3k/kernel/src/load_self.cpp
New variable was introduced and immediately go out of scope. Instead of this an existent variable should be used
> kernel/load_self: fix memory leak

- vita3k/kernel/include/kernel/thread/thread_data_queue.h
- vita3k/mem/include/mem/mempool.h
These headers are now needed for compiling, for std::find and std::lower_bound
> mem/threads: Include some missing header files

- lang/system/en-gb.xml
- lang/system/en.xml
- lang/system/zh-s.xml
- lang/system/zh-t.xml
- lang/user/ua.xml
- vita3k/app/src/app_init.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/interface.cpp
- vita3k/io/include/io/file.h
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- vita3k/interface: More detailed error message.
- app/app_init: Fix typos.
- gui/common_dialog: Add IsKeyPressed to the buttons.
- io: Fix std::size_t type name.
> vita3k/interface: More detailed error message.

- vita3k/gui/src/about_dialog.cpp
Tiny PR to fix an imgui assert when selecting Help -> About at the main menu. Since the column size is explicitly passed in I thought the WidthFixed flag made the most sense.
> gui: Fix about_dialog imgui assert

- vita3k/modules/SceNgsUser/SceNgs.cpp
This PR fix https://github.com/Vita3K/Vita3K/issues/3286
I do reverse engineering too and found a small difference. 
Also I'm not sure about https://github.com/Vita3K/Vita3K/blob/76bd1ce4459363425e2ba0518b2f741da345cfba/vita3k/modules/SceNgsUser/SceNgs.cpp#L140-L141
I did not find anything like this in decompiled code, but game works with it, so I don't remove this code
> modules/SceNgs: fix crash of Helldivers game

- vita3k/renderer/include/renderer/vulkan/pipeline_cache.h
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/include/shader/usse_translator_types.h
- vita3k/shader/src/spirv_recompiler.cpp
Using shader interlock requires the render surface to be loaded as a storage image.
However, storage images with gamma correction are mostly not supported, this was causing some graphical (darkness) issues in some games like Mortal Kombat.
The solution is to perform gamma correction in the shader. Because I'd much rather not have to specify if the surface is gamma corrected in an uniform or make two versions of each fragment shader, I instead opted to use a specialization constant. Using an old shader cache with this update won't cause any crash, but updating the shader cache is required to see the improvement.
Before:
After:
> shader, renderer/vulkan: Perform gamma correction within shaders when using shader interlock

- vita3k/renderer/src/texture/format.cpp
Multiple texture conversion functions were using a (very) wrong texture offset in each iteration.
> renderer: Fix conversion bugs

- vita3k/CMakeLists.txt
- vita3k/util/CMakeLists.txt
- vita3k/util/src/vc_runtime_checker.cpp
Direct port from https://github.com/PCSX2/pcsx2/pull/11361. 
Basically the latest VC++ runtime is not backward-compatible, this shows an error message with a link to download the latest VC++ runtime instead of straight up crashing.
I modified it slightly to fix an issue with the version check.
For some reasons, the check wasn't running when added to the util CMakeList, I had to add it directly to the vita3k CMakeList (but left it in util because I don't want to pollute the vita3k directory)
> util: Add very-early VC++ runtime version check

- .github/workflows/c-cpp.yml
~~Vita3K can run more games and regressions are not unusual for now, it is better to retain past builds.
Looking at PCSX2, there does not appear to be a capacity limit on releases.
Release looks like this.
If you do not want a large number of releases created, i can change code to have a release created when a tag is created.~~
Edited: To avoid makeing dirty the main repository, changed approach to push builds to store repository(https://github.com/Vita3K/Vita3K-builds)
we can also create a release there, maybe need to give push permission for token.
> .github: push builds to store repository

- vita3k/audio/include/audio/state.h
- vita3k/audio/src/audio.cpp
- vita3k/codec/src/atrac9.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
The expected behavior of `sceAudioOutOutput` is to block until the previous buffer has been completely used. If we were to do that, this would cause a lot of audio noise, because the host audio parameters are different compared to the PS Vita's one.
Instead, what we are doing right now is make sure a good enough amount of audio is kept so that there is no shortage for the host of audio samples to output. This often causes a call to sceAudioOutOutput to return immediatly while it would have blocked a bit on a PS Vita.
Ar Nosurge plus is periodically decoding atrac9 audio to feed it to NGS, but because of our previous approach, there could be two subsequent immediate calls to NGS and the second audio update was not able to get audio, causing many audio accuracies.
To solve this issue, …
> audio, code: Improve Audio output accuracy

- .github/workflows/c-cpp.yml
Create releases directly using ghr to avoid bloat in Vita3K-builds.
Too bad there will need to re-set token. 🙏
> .github/workflows: Push build to store repository using ghr

- vita3k/gui/src/gui.cpp
I have no idea what this changes or fixes, but the compiler was complaining about it and comparing a char* with another char* is just not cool so i turned the `app` char* into a string_view
> gui: Fix char* comparasion being made over string literal

- vita3k/gui/src/common_dialog.cpp
If you use the [I] button to view info for a save file in the save dialog then press the down button a few times with your controller there is an access violation on this patched line.  Tales of Innocence R where the info contains stats of 8 members of the party and requires scrolling down to view.  This fixes a crash that could cause a person to lose progress if inside the info dialog.
> [gui] common_dialog.cpp fix save info dialog crash

- CMakeLists.txt
Boost 1.81 is required to have support for std::string_view in path constructors, assignment and appending operations.
> cmake: set boost minimum version

- vita3k/renderer/src/gl/texture.cpp
Fix #2032 
Fix these errors in logs:
```
|D| [debug_output_callback]: [OPENGL - ERROR - HIGH] GL_INVALID_VALUE in glCompressedTexSubImage2D(size=X)
|E| [after_callback]: OpenGL: glCompressedTexSubImage2D set error 1281.
```
**Fuuraiki 3 master**
**Fuuraiki 3 PR**
**Danganronpa v3 master**
**Danganronpa v3 PR**
> renderer/gl: fix bcn compressed size in upload_texture_impl

- vita3k/renderer/src/vulkan/renderer.cpp
```
physical_device_properties = physical_device.getProperties();
physical_device_features = physical_device.getFeatures();
physical_device_memory = physical_device.getMemoryProperties();
physical_device_queue_families = physical_device.getQueueFamilyProperties();
```
can not be called with a null `physical_device`
> renderer/vk: use physical_device if not null

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/ime.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
Before imgui 1.90 (November 2023), the "ImGuiChildFlags child_flags = 0" parameter was "bool border = false" in BeginChild.
Although the imgui code should be backward compatible, when using a Debug build, I am hitting this static_assert https://github.com/ocornut/imgui/blob/cb16be3a3fc1f9cd146ae24d52b615f8a05fa93d/imgui.cpp#L5541 because `ImGuiWindowFlags_AlwaysAutoResize` is used with BeginChild.
> IM_ASSERT((window_flags & ImGuiWindowFlags_AlwaysAutoResize) == 0 && "Cannot specify ImGuiWindowFlags_AlwaysAutoResize for BeginChild(). Use ImGuiChildFlags_AlwaysAutoResize!");
This PR fixes it and does the migration from bool to ImGuiChildFlags
> imgui: ImGuiChildFlags_Border migration

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/imgui_impl_sdl.cpp
- vita3k/gui/src/imgui_impl_sdl_gl3.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/vita3k_update.cpp
**Added:**
- New cursors from upstream
**Fixed:**
- Only the OpenGL backend currently frees the SDL cursors. By moving the code to ImGui_ImplSdl_Shutdown, it will be free for all backends.
**Breaking changes related to v1.91.1 I fixed:**
> - BeginChild(): renamed ImGuiChildFlags_Border to ImGuiChildFlags_Borders for consistency.
> - IO: moved clipboard functions from ImGuiIO to ImGuiPlatformIO:
>   - io.GetClipboardTextFn -> platform_io.Platform_GetClipboardTextFn
>   - io.SetClipboardTextFn -> platform_io.Platform_SetClipboardTextFn
>   - in function signatures, changed void* user_data to ImGuiContext* ctx for consistency with other functions. Pull your user data from platform_io.ClipboardUserData if used.
> imgui updates

- CMakeLists.txt
- external: Update boost to 1.86.
Adding crc module.
- Fix Boost linkage issues in release build.
Fix path of BOOST_LIBRARYDIR.
> external: Update boost to 1.86.

- vita3k/renderer/src/gl/color_formats.cpp
This PR adds support for the `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8` color format in the OpenGL renderer. This format was previously unsupported, which could lead to rendering issues in games that use it.
- Added `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8` to the `translate_internal_format` function, mapping it to `GL_RGB8`
- Updated `translate_format` to return `GL_RGB` for `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8`
- Modified `translate_type` to return `GL_UNSIGNED_BYTE` for `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8`
- Updated `translate_swizzle` to handle `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8`
- Added `SCE_GXM_COLOR_BASE_FORMAT_U8U8U8` to `bytes_per_pixel_in_gl_storage`, returning 3 bytes per pixel
- Tested with Ken Ga Kimi For V (PCSG00553), which now renders correctly with this change
> renderer/gl: Add support for U8U8U8 color format

- vita3k/gui/src/vita3k_update.cpp
- gui/vita3k updater: Fix batch script path handling on Windows.
Replaced '/' with '\\' to fix path handling and resolve issues caused by incorrect path interpretation.
that totaly fix update batch not run anymore on last version of windows
> gui/vita3k updater: Fix batch script path handling on Windows.

- vita3k/app/src/app_init.cpp
Inspired by the Dolphin Progress report.
Disable round corners for the game window on Windows.
The round corners can hide up to 0.0005% of the game being rendered, that was unacceptable.
> app: Disable round window corners on Windows

- vita3k/renderer/src/gl/texture.cpp
This PR addresses an issue where `translate_type()` was being unnecessarily called for compressed textures in the OpenGL renderer. This was causing unnecessary warnings in certain games.
- Modified `GLTextureCache::configure_texture()` to avoid calling `translate_type()` for compressed textures
- Tested with PhotoKano (PCSG00139) and RecoLove Gold Beach (PCSG00782)
- Confirmed that the unnecessary warnings previously observed in these games no longer occur
This change eliminates unnecessary function calls and warnings, potentially improving performance and reducing console clutter during gameplay and debugging.
> renderer/gl: Fix unnecessary translate_type() call for compressed textures

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/modules/SceJpeg/SceJpegUser.cpp
This PR implements MCU-based decoding for JPEG images to more accurately emulate the PS Vita's hardware decoder behavior. The PS Vita primarily uses hardware decoding for JPEG images, which includes certain assumptions in its output. Some games have hardcoded these assumptions, leading to compatibility issues with our previous implementation.
- Modified JPEG decoding to always output images in multiples of MCU size
- Updated pitch calculation to reflect this MCU-based approach
- Tested with AI Kiss (PCSG01325) and Kiss Ato (PCSG00742), resolving image issues during JPEG decoding
This change is based on the assumption that the PS Vita's hardware decoder always outputs images in multiples of MCU size. While this fixes known issues in some games, further testing across a wider range of …
> modules/SceJpeg: Implement MCU-based decoding and pitch calculation

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/reinstall.cpp
- vita3k/interface.cpp
With a vpk installed and the renderer backend set to Vulkan, trying to reinstall the same vpk using drag and drop will crash the app. Using OpenGL related functions with Vulkan is not a good idea, this PR fixes it.
> gui/interface: Fix reinstall using DnD and Vulkan

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
- vita3k: fix openssl path install of new 3.3.2 version.
Set and use OPENSSL_ROOT_DIR as a cache variable to copy the bin files.
Fix generate project on windows with using pre-build version
> external: Fix OpenSSL path installation for the new 3.3.2 version. 

- vita3k/renderer/src/gl/color_formats.cpp
This PR adds support for the `SCE_GXM_COLOR_BASE_FORMAT_F32` color format in the OpenGL renderer. This format was previously unsupported, which could lead to rendering issues in games that use it.
- Added `SCE_GXM_COLOR_BASE_FORMAT_F32` to the `translate_internal_format` function, mapping it to `GL_R32F`
- Updated `translate_format` to return `GL_RED` for `SCE_GXM_COLOR_BASE_FORMAT_F32`
- Modified `translate_type` to return `GL_FLOAT` for `SCE_GXM_COLOR_BASE_FORMAT_F32`
- Updated `translate_swizzle` to handle `SCE_GXM_COLOR_BASE_FORMAT_F32`
- Added `SCE_GXM_COLOR_BASE_FORMAT_F32` to `bytes_per_pixel_in_gl_storage`, returning 4 bytes per pixel
- Tested with Gundam EXTREME VS-FORCE (PCSG00738), the error that occurred in OpenGL has been fixed. And when depth accuracy is applied, it will be …
> renderer/gl: Implement F32 base color format

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/modules/SceJpeg/SceJpegUser.cpp
This PR enhances the SceJpeg module to more accurately emulate the PS Vita's hardware JPEG decoder, including its specific limitations. The improvements were developed by creating and comparing with a real HomeBrew application running on PS Vita hardware, aiming to replicate its behavior and constraints as closely as possible.
- Refined pitch calculation, which greatly improves emulation accuracy for Visual Novels
- Implemented BGRA decoding
- Added downscale decoding functionality
- Emulated PS Vita hardware limitations
- Implemented sceJpegCsc function for color space conversion from YUV444 to RGBA
- Added support for iFrameWidth argument in sceJpegMJpegCsc function
- Accurately emulated PS Vita's decoding size limits, ensuring that oversized images are handled the same way as on actual …
> modules/SceJpeg: Improve JPEG decoding accuracy

- lang/system/en.xml
- vita3k/Windows.manifest
- vita3k/codec/src/atrac9.cpp
- vita3k/gui/src/gui.cpp
- vita3k/io/src/io.cpp
- vita3k/lang/include/lang/state.h
I don't like to see big negative numbers in log (´･д･`)
> vita3k: Use hex for error codes

- vita3k/gui/src/perf_overlay.cpp
- gui/perf overlay: Fix window size on Mininum detail.
Fix my mistake after rewrite some’part on code with forget check Minimum detail level
Thx to crotmaniac for catch it on discord
> gui/perf overlay: Fix window size on Mininum detail.

- vita3k/modules/CMakeLists.txt
- vita3k/modules/SceUlobjDbg/SceUlobjDbg.cpp
- vita3k/nids/include/nids/nids.inc
This PR adds NIDs for SceUlobjDbg-related functions that were not previously included in Vita3K. The names of these functions are not known anywhere, and it is only known that they belong to the corresponding module.
This modification does not change any functionality of Vita3K. When NID error messages related to SceUlobjDbg occur in Vita3K's logs, it only reduces the time developers spend pondering over messages like "Import function for NID 0xd7f0f610 not found".
- Added NIDs for the SceUlobjDbg module to the appropriate NID database file
> modules: Add SceUlobjDbg related new NIDs

- vita3k/modules/SceSysmem/SceSysmem.cpp
This PR addresses a regression introduced after Build 3463 ([#3043](https://github.com/Vita3K/Vita3K/pull/3043)) that affected some games ([#3217](https://github.com/Vita3K/Vita3K/issues/3217)). The issue was caused by games incorrectly interpreting the address returned by `sceKernelGetMemBlockBase` as a signed value and treating negative values as errors.
- Updated the `sceKernelAllocMemBlock` function in the SceSysmem module
- Set the correct `start_address` for `SCE_KERNEL_MEMBLOCK_TYPE_USER_RW_UNCACHE`
- Verified that `SCE_KERNEL_MEMBLOCK_TYPE_USER_RW_UNCACHE` uses the same memory region as `SCE_KERNEL_MEMBLOCK_TYPE_USER_MAIN_PHYCONT_NC_RW`
- Both memory block types now use the 0x70000000 address range
This fix should resolve the regression issues reported in #3217, improving …
> modules/SceSysmem: Set correct start_address for USER_RW_UNCACHE

- vita3k/gui/src/information_bar.cpp
This PR addresses a critical iterator invalidation bug in the notice list processing logic within the information bar component. The bug was caused by erasing elements from a container while iterating over it, which can lead to undefined behavior and potential crashes.
Actual issues in the existing code would have primarily occurred only when manually deleting multiple files, so most users would not have experienced problems in the majority of usage scenarios. 
- Replaced index-based erase with safe iterator-based erase
> gui/information bar: Fix iterator invalidation bug in notice list processing

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
This PR implements the `sceKernelGetEventPattern` function in the SceLibKernel module, enhancing the emulation of the PS Vita's event handling system.
- Implemented `sceKernelGetEventPattern` function in SceLibKernel module
- Implemented `_sceKernelGetEventPattern` function in SceKernelThreadMgr module
- Updated function signatures and declarations in header files
- The implementation follows the expected behavior of the PS Vita's kernel, retrieving the event pattern for a given event ID
- While this implementation covers the basic functionality, there might be edge cases or specific hardware behaviors that are not yet fully emulated
- The implementation follows the code convention used in other `event_id` related functions for consistency
> modules/SceKernel: Implement sceKernelGetEventPattern

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/trophy_unlocked.cpp
Also set the correct type for `size`, `stbi_load_from_memory` uses an `int`
```
STBIDEF stbi_uc *stbi_load_from_memory(stbi_uc const *buffer, int len, int *x, int *y, int *comp, int req_comp)
```
> gui: Fix load_image pointer validity check

- vita3k/gui/src/ime.cpp
Fixed priority of operator `||` in judgment.
> gui/ime: Fix IME crash when backspace button is pressed when the input box is empty

- external/CppCommon/include/cpu.h
- external/CppCommon/source/environment.cpp
- tools/gen-modules/gen-modules.cpp
- vita3k/app/src/app_init.cpp
- vita3k/ctrl/include/ctrl/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/io/include/io/filesystem.h
- vita3k/io/src/filesystem.cpp
- vita3k/io/src/io.cpp
- vita3k/main.cpp
- vita3k/mem/include/mem/atomic.h
- vita3k/mem/src/mem.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceHttp/SceHttp.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceLibc/SceLibc.cpp
- vita3k/modules/SceNet/SceNet.cpp
- vita3k/net/include/net/socket.h
- vita3k/net/src/posixsocket.cpp
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/util/include/util/exec.h
- vita3k/util/include/util/safe_time.h
- vita3k/util/include/util/string_utils.h
- vita3k/util/src/logging.cpp
- vita3k/util/src/net_utils.cpp
- vita3k/util/src/string_utils.cpp
These commits make it possible to compile the emulator on Windows with GCC and Clang. It does not build because the unicorn submodule needs an update for mingw-w64. I will submit it later.
> Add support for mingw-w64

- vita3k/renderer/src/batch.cpp
The wait_cmd function was reading the timestamp value from an incorrect memory offset, which could lead to synchronization issues.
> renderer: Fix incorrect timestamp offset in wait_cmd function

- building.md
Adds a sub-section for Fedora dependencies (with updated package names)
also includes `libc++-static` (required for final linking to complete in tested configuration)
- MacBookPro (late 2020) M1 16GB 1TB
- Fedora Asahi Remix release 40
- build [3666-52b82dd](https://github.com/Vita3K/Vita3K/commit/52b82dd)
- reuse Vita3K config dirs (firmware and ux0) from Batocera Linux SHARE partition
Build completes and verified:
1. initial setup screen: select language, prefPath, and install firmware
2. logging in as default user and navigating main PS Vita screen
3. launch pre-installed app [PCSB00302] (documented [issue launching](https://github.com/Vita3K/compatibility/issues/45#issuecomment-2439711010))
Despite run-time issue launching title, emulator appears to be stable in main UI helping verify …
> add build instructions for Fedora

- vita3k/compat/src/compat.cpp
Follow ISO 8601.
`yyyy-mm-dd` is defined in ISO. The compat-repo must be changed at the same time.
> compat: change time style to yyyy-mm-dd

- vita3k/gxm/include/gxm/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
This PR is intended to address issue #3403.
The logic of `sceGxmDisplayQueueAddEntry` has been modified according to the implementation of the PS Vita, so that it now waits for both `oldBufferSync` and `newBufferSync`. After this change, workaround codes that seemed unnecessary have also been removed. Additionally, the `handle_wait_sync_object` command has been removed, as it no longer appears logically necessary after these changes. Now, blocks related to `SyncObject` exist only within the logic of `sceGxmDisplayQueueAddEntry` (specifically in `display_entry_thread`).
This is a very aggressive modification, so there is a possibility of errors. However, based on my understanding, this change does not seem to introduce any logical issues.
The part related to frame prediction has been left …
> modules/SceGxm: Improve sync object handling and simplify display queue logic

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
Changelog 2.30.9:
- Fixed audio issues on Android 15
- Fixed rare audio distortion and crash when audio devices are changed on Windows
- Fixed the PS5 controller face buttons on Amazon Fire TV
- Fixed detecting the Steam Virtual Gamepad on macOS
- Added support for wired XBox controllers on macOS 15.0 Sequoia
- Added support for the Steam Virtual Gamepad on macOS Sequoia
- Fixed the Steam Virtual Gamepad from showing up when games aren't running under Steam
- Fixed flicker when entering/exiting fullscreen or moving the window between scaled and non-scaled displays under Wayland.
- Fixes for data addresses above 2gb on Emscripten
- Fixed horizontal mousewheel scale on Emscripten
Changelog 2.30.8:
- Fixed a crash in XInput code at startup
- Fixed flooding the OS with I/O when a PS4/PS5 …
> external: update sdl to version 2.30.9

- lang/system/en.xml
- vita3k/config/include/config/config.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/ime.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/gui/src/welcome_dialog.cpp
- vita3k/interface.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
* lang: more verbose error on wrong lang.xml
* gui: refactoring: replace magic strings to enum types, move static vars inside corresponding functions, fix datatypes
* gui: refactoring: minor fixes: global vars as static, add or remove ref if needed
* gui: fix a bug when one button could be mapped to two commands (for screenshots and texture replacement)
* gui: refactoring: Extract functions to draw text centered
* gui: Settings dialog: more translatable strings
> GUI: translation extension, refactoring and some improvements

- vita3k/app/src/app_init.cpp
XDG_DATA_DIRS is used mainly to find default configuration files or system-wide configuration for apps, like a window manager having a default/system configuration file in /usr/share/WM/foo.
The idea for it is that it checks that path only if there is no user configuration, but because Vita3K doesnt have a default/system-wide configuration file AND the configuration is generated on first start, it really isnt needed + shared path shouldnt be system-wide as it needs to be read-write by the user
> app: Ignore XDG_DATA_DIRS for shared path

- vita3k/modules/SceTouch/SceTouch.cpp
- vita3k/touch/include/touch/touch.h
- vita3k/touch/src/touch.cpp
This is a quick pass to the current touch code. I don't expect any games be affected by these changes.
- Ensures all input parameters are properly validated to return the same error code as the actual console
- Removes a bit of duplication code in `sceTouchGetPanelInfo` to simplify reading.
- ~~Partially implements `sceTouchGetPixelDensity` with `GetHardwareInfo` calls~~. In reality these values are stored in a global set at module init but vita3k doesn't seem to have any proper initialization for modules.
> touch: Validate all input params and simplify code

- vita3k/modules/SceDriverUser/SceMotion.cpp
- vita3k/motion/include/motion/functions.h
- vita3k/motion/include/motion/motion_input.h
- vita3k/motion/src/motion.cpp
- vita3k/motion/src/motion_input.cpp
This PR aims to make sceMotion behavior more similar to PS Vita and implement some unimplemented functions.
I made the following modifications:
1. Basic Orientation is calculated according to gravity, identical to PS Vita.
2. `sceMotionGetState` function updates basicOrientation information when called.
3. Modified gyro-related behavior to match PS Vita values. This involved modifying the `UpdateRotation` function and `get_orientation` function.
I implemented the following functions:
1. `sceMotionReset` function updates quat values to their initial values. This function has been implemented.
2. `sceMotionRotateYaw` function does exactly what its name suggests.
3. Added some stubbed functions.
Testing across multiple games is required for merging this PR.
Since I tried to solve this by …
> modules/SceMotion: Improve motion support

- vita3k/interface.cpp
#3330 Installation fails because zombiebound is homebrew but has an empty `sce_sys/package/work.bin`.
Check `title_id` instead.
If you have a better way of identifying commercial and homebrew games, please let me know.
> Fix for zombiebound

- .github/labeler.yml
- .github/workflows/c-cpp.yml
Add the `replace` option to solve the problem of failed uploads of artefacts.
```bash
-replace \        # Replace artifacts if it is already uploaded
```
> .github/workflows: Add the replace option to ghr

- .github/workflows/c-cpp.yml
Requested by @Zangetsu38.
Limit concurrent execution of create-release jobs to prevent bugs.
Also removes the `replace` option that was useless to fix the bug.
> ci: Limit concurrent execution of create-release jobs to prevent bugs

- vita3k/gui/src/common_dialog.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- gui/save data dialog: fix display slot on load with empty param available like on real psvita.
fix position of title of list when is too long.
- gui/ime dialog: fix enter name.
that fix ,issue signaled by one tester compared real psvita.
- fix game with it display only load list mode with all empty param, is exactly same on psvita
- And so get same result like on real psvita for app give empty param.
- No affect other game when no give empty param
> gui/save data dialog: fix display slot on load with empty param.

- vita3k/gui/src/common_dialog.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- gui/common dialog: Refactor display list mode.
fix when game using delete mode like select new save or exist.
- Fix this app using delete mode for create new save or using current
> gui/common dialog: Refactor display list mode & Fix crash on check empty param and fix getstatus check.

- external/CMakeLists.txt
The `MVK_CONFIG_FULL_IMAGE_VIEW_SWIZZLE` setting is not working as expected.
This issue seems to be caused by an older version of MoltenVK, as a recent fix related to this setting has been applied.
Updating MoltenVK to the latest version should resolve this problem.
> Ensure all MoltenVK config info set by VK_EXT_layer_settings is used
https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.11
> external: update MoltenVK to 1.2.11

- vita3k/interface.cpp
The purpose of this PR is to block ui_navigation for second and subsequent inputs when multiple controllers simultaneously trigger SDL_CONTROLLERBUTTONDOWN events for the same key.
-----
Here's why this PR is necessary. I've written a detailed explanation since this PR might seem unnecessary at first glance.
Many controllers use the Xbox 360 Controller driver in Windows environments. Since the Xbox 360 Controller driver doesn't support gyro functionality, the gyro hardware often can't be practically used even when it exists in the controller.
There are several third-party solutions to work around this issue. The most well-known approach is using cemuhookudp (which isn't yet supported by Vita3K), but there's also an approach that emulates a Dualshock 4 controller by combining controller …
> gui/interface: Ignore simultaneous identical keydown events from controller

- vita3k/gui/include/gui/imgui_impl_sdl_state.h
- vita3k/gui/src/imgui_impl_sdl.cpp
Backported imgui_impl_sdl.cpp from the vita3k-android project to the current project to avoid using features that will become obsolete in ImGui during subsequent development.
> gui/imgui: Backport imgi_impl_sdl from vita3k-android

- vita3k/ctrl/include/ctrl/state.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/interface.cpp
- vita3k/modules/SceCtrl/SceCtrl.cpp
Feature Implementation:
I modified the controller assignment functionality to match the Vita TV.
On Vita TV, newly connected controllers are always sequentially assigned starting from port 1 to the next available number, and users can explicitly reassign controllers to any number from 1-4. No special handling is implemented when a disconnected controller is reconnected.
Bug Fix:
I fixed an issue where incorrect behavior occurred when a connected controller was disconnected. Previously, when a disconnected controller created a gap in port numbers, only iterated through the number of connected controllers, causing issues like being unable to check controllers with higher port numbers.
> gui/controllers: align controller assignment behavior with Vita TV

- .github/workflows/c-cpp.yml
The `ubuntu-latest` CI was just changed today to use ubuntu 24.04. This had the effect of breaking normal linux operation due to it being built with a newer version of libc than we previously targeted. The libc version on 24.04 is not backwards compatible with 22.04, so the binary could not be run on 22.04-based systems.
Ubuntu 22.04 will be supported by Canonical until 2027, though GitHub may end its support sooner (though this is doubtful seeing as they still have a 20.04 runner, and non-LTS 20.04 support is to be axed in April 2025).
I'm like 98% sure this won't change the artifact names due to how it handles it with basename/cut, so nothing else SHOULD need changed in response to this PR.
> ci: use ubuntu-22.04 instead of ubuntu-latest

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- modules/SceSaveDataDialog: Fix display list when list size is 0.
moving check empty param inside check save file.
- modules/SceMsgDialog: Fix reset bar progress in init.
- FIx display save slot after save like as psvita
> modules/SceSaveDataDialog: Fix display list when list size is 0.

- vita3k/util/include/util/log.h
The `uint_8t` is internally `unsigned char`, so in the example below it is recognised as an ASCII code 3 and displayed incorrectly; converting it once to a string fixes this.
Before:
After:
> util/log.h: Fix log_hex

- vita3k/gui/src/manual.cpp
- gui/manual: Refactor page loading logic.
Simplified by replacing directory iteration with direct use of indexed filenames (e.g., 001.png, 002.png).
Fix issue signaled by reena on discord, causing on macOS, page is disordered
> gui/manual: Refactor page loading logic. 

- vita3k/packages/src/sce_utils.cpp
- Use `vector.data()+pos` instead of `&vector[pos]` because here `pos` may be equal to `vector.size()` and `operator[]` checks bounds at debug build. -> #3508
> packages: Fix method to get range in std::vector.

- vita3k/ngs/src/modules/atrac9.cpp
- `uint32_t decoded_size` may overflow to a very large number by subtracting a number larger than itself, which causes `data.extra_storage.resize(curr_pos + decoded_size * sizeof(float) * 2)` to try to allocate huge amounts of memory (and the process freezes as a result).
- I'm not actually sure if I wrote it correctly this way, I just referenced the previous line of code, but judging by the results, it works fine.
> ngs: Fix attempts to allocate huge amounts of memory causing the process to freeze.

- vita3k/util/include/util/bytes.h
- `(0xFFFFFFFF & 0x1) == 0x00000001` is always true.
> util/bytes: Fix method to get system endian type

- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/themes.cpp
- vita3k/renderer/src/texture/replacement.cpp
- The use of `sscanf` should be reduced, to improve efficiency and get rid of the cumbersome format specifiers.
> gui/renderer: Replace sscanf when not parsing a complex string

- vita3k/modules/SceNpCommon/SceNpCommon.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- vita3k/np/include/np/common.h
Old implementation is just wrong and causes segfault in some cases. Implement it according RE.
> npCommon: Fix NpCmpNpId

- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Add a small delay after sceKernelStartThread. If this delay is not put, sceKernelWaitThreadEnd and sceKernelDeleteThread functions which are too close work randomly and many glitches can appear. Tested with Ciel Nosurge Offline, fixes all the random freezes and graphical glitches with 3D models. 1µs is enough with tests I made. However, more tests could be performed to make sure it works properly everywhere since it's a very crucial function.
> Add the run status to sceKernelStartThread immediately after calling it

- vita3k/ngs/src/modules/player.cpp
- ngs/player: Prevent crash by rounding playback rate up.
Some Unity games set very low playback frequencies (e.g., 0.xx), causing FFmpeg to crash.
- Improve validation for playback_scalar and playback_frequency.
Replaced redundant checks for playback_scalar and playback_frequency with dedicated lambda functions for better readability and maintainability.
- Adjusted the validation logic to properly handle edge cases:
Allowed playback_scalar values between 0 and 10.
Allowed playback_frequency values between 0 and 192000.
fix crash of Looney Tunes Galactic Sports, Spongebob, Stick it to the man, etc....
credit to @bookmist for help
> ngs/player: ngs/player: Prevent crash by rounding playback rate up.

- vita3k/ctrl/src/ctrl.cpp
- vita3k/emuenv/include/emuenv/state.h
- vita3k/interface.cpp
Based on https://github.com/Vita3K/Vita3K/pull/2937 but totaly refactored and fixed with lower change
- vita3k: Drop inputs while any settings or controls dialog is open.
Allow app and gui no take any input anymore when this dialogs is open.
> vita3k: Drop inputs while any settings or controls dialog is open.

- vita3k/gui/src/gui.cpp
- This PR is separated from #3505.
- Before this PR, Chinese fonts cannot be loaded when we launch the emulator for the first time, because the default system language is English (US).
> We can see a lot of question marks in the image, these are the characters that are missing from the font.
> gui: Fix missing Chinese fonts in initial setup screen.

- vita3k/gui/src/gui.cpp
- Fix CJK characters are still displayed as Japanese glyphs when the system language is Chinese.
> gui: Fix Chinese characters are displayed as Japanese glyphs

- vita3k/app/src/app_init.cpp
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/lang/include/lang/state.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/vulkan/screen_filters.cpp
Since the resolution of the PS Vita is very close from a 16:9 one (just 4 extra height pixels), I propose this change. It allows to take all the screen width and crop 2 pixels in the top and the bottom in fullscreen mode when the resolution of the screen is 16:9 only. It's especially interesting for 1080p (pixels x 4) and 4K (pixels x 16) resolutions which are integer multiples of 960x540 to get the best possible rendering. The same method is used by the plugin Sharpscale on PSTV with the Integer mode in 1080i.
If you prefer, we could also add a combo box with three modes to replace the "Stretch to Display Area" one:
- Fit (Standard mode)
- Stretch to full screen
- Stretch to full width (keep aspect ratio)
This time, I think I did things properly with the pull request ^^
> Add the "Fullscreen HD res pixel perfect" checkbox in the GUI section

- vita3k/modules/SceNet/SceNet.cpp
Fix wrong declaration of uint64 conversion function (This functions are used by some games but I don't know how important they are)
> modules/SceNet: correct declaration of byte order conversion functions

- vita3k/modules/SceIme/SceIme.cpp
- The ime state must be checked before sending an ime event to the ime event handle.
> modules/SceIme: Fix freezing at sceImeSetCaret/sceImeSetPreeditGeometry

- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/texture/replacement.cpp
- vita3k/renderer/src/transfer.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/usse_utilities.cpp
- vita3k/util/include/util/log.h
log_hex is broken by #3514, so revert it.
Also avoid using log_hex where fmt is used.
> Revert #3514

- .gitignore
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
I fixed some problems with the settings dialogs.
1. As a user I don't know what the "Close" button does. Does it save & close or simply close? I renamed it to "Cancel" to make clear that is cancels the dialog.
2. "Save" does not close the dialog which means that I have to click "Close" afterwards. I changed it to close the the dialog. One click less.
> gui: improve settings dialog

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- modules/SceCommonDialog: Reset button id in sceSaveDataDialogContinue.
Prevents the app from looping back to list mode when "No" is selected.
Senran Kagura EV calls GetResult after any confirmation, but if the button ID is already set to "No" while in list mode, it doesn't transition to fixed mode for load/save confirmation. Instead, it loops back in list mode.
Other game ignore this and juste open fixed mode.
> modules/SceCommonDialog: Reset button id in sceSaveDataDialogContinue.

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/src/disasm.cpp
- vita3k/gdbstub/src/gdb.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/util/include/util/tracy.h
- vita3k/util/src/string_utils.cpp
- Replace `std::stringstream::operator<<` with faster `fmt::format_to` and `std::string::operator+=`.
- Replace `std::stringstream::operator>>` with faster `std::strtoul`.
- Use `std::move` when return `std::stringstream::str`.
- Distinguish between output-only and input-only streams.
> vita3k: Improve use of string/stringstream

- vita3k/renderer/include/renderer/vulkan/types.h
- vita3k/renderer/src/vulkan/creation.cpp
- Ensure that `VKContext::gpu_request_wait_thread` is not joinable when the `VKContext` object is destroyed. (RAII)
> renderer/vulkan: Ensure that the std::thread object is destroyed properly.

- vita3k/modules/SceGxm/SceGxm.cpp
Fix crashes for games which call this functions more then once (with same target). 
For example [PCSB00882] SENRAN KAGURA ESTIVAL VERSUS
Fix bug when game crash immediately after exit from main menu
> modules/SceGxm: add ptr.valid check in sceGxmDestroyRenderTarget

- vita3k/mem/include/mem/ptr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- `Ptr<T>::Ptr<U>(U *, const MemState &)` has redundant template, which allows code like `Ptr<int>::Ptr<char>(char *, const MemState &)` to pass compilation.
> mem/ptr.h: Remove template for 'Ptr(U *, const MemState &)'

- vita3k/kernel/src/load_self.cpp
- vita3k/packages/src/sce_utils.cpp
- packages/sce utils: skip fself decryption for invalid SELF files.
Prevents crashes or errors when games try to load no valid self or content still layer-encrypted.
fix regression repoorted on https://github.com/Vita3K/compatibility/issues/154#issuecomment-2883266134
> packages/sce utils: skip fself decryption for invalid SELF files.

- external/CMakeLists.txt
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/translator/special.cpp
- vita3k/shader/src/translator/texture.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- vita3k/shader/src/usse_utilities.cpp
The current version of glslang Vita3K was using no longer builds on the latest gcc (see [here](https://github.com/KhronosGroup/glslang/issues/3950)). Therefore update glslang to the latest release and also fix the breaking changes. The generated shader code should be the same.
cc @EXtremeExploit
> shader, external: Update glslang

- vita3k/ngs/src/modules/player.cpp
I investigated and found that Power Pro Baseball 2013 is no longer playable.
This will allow to play Power Pro Baseball 2013 again.
> ngs/player: fix small typo

- vita3k/ctrl/src/ctrl.cpp
This PR treats all controller inputs as port 1 input when not in PSTV mode, enabling gameplay without changing controller order in environments where multiple controllers are connected.
This is a workaround for the issue mentioned in #3244, and I couldn't think of a better solution.
> ctrl: Map all controllers to port 1 when not in PSTV mode

- vita3k/packages/include/packages/sfo.h
- vita3k/packages/src/sfo.cpp
- packages/sfo: Refactor and handle all supported SFO data fmt.
Properly handle ASCII, UTF-8, UTF-8 NULL-terminated, and 32-bit unsigned integer formats during parsing.
Remove dirty hacks for memory handling and string conversions, ensuring cleaner and more reliable code.
Split other pr for get this commit alone
> packages/sfo: Refactor and handle all supported SFO data fmt.

- vita3k/util/include/util/exec.h
- `"exec.h"` lacks the necessary header file, and although it does not report an error at compile time (because there is no file that references it), opening the file in IDE displays with error.
> util/exec.h: Fix include

- vita3k/module/src/load_module.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- modules/SceSysmodule: Avoid reloading already loaded module.
- module/load_module: Use contains() instead of find() in is_module_loaded.
fix regression on sao move for ingame to bootable, with no can using fios module already loaded.
- get back to ingame again
> modules/SceSysmodule: Avoid reloading already loaded module.
