Vita3K/Vita3K

- src/emulator/io/src/io.cpp
PSVITA supports partition referencing even without the / (eg. app0:eboot.bin).
This will properly handle such cases.
> Fix for app0 and ux0 paths without '/'

- src/emulator/io/src/io.cpp
uma0: partition is used in some homebrews (eg. HCL-Vita) as replacement for ux0 when SD2VITA adapter is mounted as uma0: partition and user wants to use homebrew data files on it.
The old assert was causing a crash with those homebrews.
> Added uma0: partition support.

- src/emulator/load_self.cpp
> Allow compressed selfs

- src/emulator/module/include/module/module.h
- src/emulator/module/src/module.cpp
- src/emulator/modules/SceDisplay/src/SceDisplayUser.cpp
- src/emulator/modules/SceLibKernel/src/SceLibKernel.cpp
We can get rid of all those asserts with this while still getting debug infos when something wrong happened.
> Added SCE errorcodes warning.

- CMakeLists.txt
- gen.bat
- gen.sh
- src/CMakeLists.txt
- src/external/CMakeLists.txt
Taken from here: https://github.com/yuzu-emu/yuzu/blob/master/CMakeLists.txt
> Check the presence of the submodules

- README.md
- appveyor.yml
This will make it much easier for the general emulator userbase to get and test the emulator, because they won't have to build it themselves.
> Add AppVeyor Configuration File

- src/emulator/CMakeLists.txt
- src/emulator/main.cpp
- src/emulator/util/CMakeLists.txt
- src/emulator/util/include/util/string_convert.h
- src/emulator/util/src/util.cpp
- src/emulator/vpk.cpp
- src/emulator/vpk.h
> Support Unicode paths on Windows

- .gitmodules
- src/emulator/io/CMakeLists.txt
- src/emulator/io/include/io/functions.h
- src/emulator/io/include/io/state.h
- src/emulator/io/src/io.cpp
- src/emulator/modules/SceIofilemgr/src/SceIofilemgr.cpp
- src/emulator/modules/SceLibKernel/src/SceLibKernel.cpp
- src/external/CMakeLists.txt
Very basic implementation.
Fix #16
> Add sceIoGetstat, sceIoDopen, sceIoDread, sceIoDclose

- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/rtc.h
- src/emulator/host/src/host.cpp
- src/emulator/kernel/include/kernel/state.h
- src/emulator/modules/SceLibKernel/src/SceLibKernel.cpp
- src/emulator/modules/SceRtc/src/SceRtcUser.cpp
vitaQuake multiplayer works with this + #39 
Resolves #56
> [libRtc/libKernel] Fix clock implementation

- README.md
> Add Linux build instructions

- src/emulator/CMakeLists.txt
- src/emulator/cpu/include/cpu/functions.h
- src/emulator/cpu/src/cpu.cpp
- src/emulator/gxm/CMakeLists.txt
- src/emulator/gxm/include/gxm/state.h
- src/emulator/gxm/include/gxm/types.h
- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/state.h
- src/emulator/host/src/host.cpp
- src/emulator/kernel/CMakeLists.txt
- src/emulator/kernel/include/kernel/thread_functions.h
- src/emulator/kernel/include/kernel/thread_state.h
- src/emulator/kernel/src/thread.cpp
- src/emulator/load_self.cpp
- src/emulator/main.cpp
- src/emulator/module/include/module/bridge_args.h
- src/emulator/modules/SceDisplay/SceDisplay.cpp
- src/emulator/modules/SceDisplay/SceDisplayUser.cpp
- src/emulator/modules/SceGxm/SceGxm.cpp
- src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- src/emulator/threads/CMakeLists.txt
- src/emulator/threads/include/threads/queue.h
Please show your opinion
Moved to other issues
- Gxm sync primitives
- Some games are pretty slow
> [READY TO MERGE] Threads refactoring

- src/emulator/util/include/util/log.h
> Shorten the log format a little.

- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/rtc.h
- src/emulator/host/src/rtc.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- src/emulator/modules/ScePower/ScePower.cpp
- src/emulator/modules/SceRtc/SceRtcUser.cpp
> Implement sceRtcGetTime*_t

- src/emulator/CMakeLists.txt
- src/emulator/host/include/host/state.h
- src/emulator/main.cpp
- src/emulator/sfo.cpp
- src/emulator/sfo.h
- src/emulator/vpk.cpp
- src/emulator/vpk.h
- Add a SFO parser
- Add title_id and game_title variable to host state
> Display Game title and Title ID on Window title

- src/emulator/shaders/76a4758e3e5027ca2c19d9e9a6dca9eda8b733bf0bfee7931abf461455e6aebb.frag
- src/emulator/shaders/7ab03ae7c55b085887bf61bc7dcc7bd403f36fd1be9b8d74783363a761a52aa9.vert
Shaders for http://vitadb.rinnegatamante.it/#/info/156
> Added Flood It! shaders.

- src/emulator/CMakeLists.txt
- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/sfo.h
- src/emulator/host/include/host/state.h
- src/emulator/host/src/sfo.cpp
- src/emulator/main.cpp
- src/emulator/modules/SceAppMgr/SceAppMgrUser.cpp
- src/emulator/vpk.cpp
- src/emulator/vpk.h
Untested since i was unable to find a proper homebrew to test with.
> Added sceAppMgrAppParamGetString implementation.

- src/emulator/gui/src/ui_threads_dialog.cpp
> [gui] Added Thread ID info in Threads dialog.

- src/emulator/gxm/src/gxm.cpp
- src/emulator/modules/SceGxm/SceGxm.cpp
> Support SCE_GXM_TEXTURE_FORMAT_U5U6U5_RGB

- src/emulator/gxm/src/gxm.cpp
- src/emulator/modules/SceGxm/SceGxm.cpp
-fix correct value return for U5U6U5_RGB.
-Add log for indicate if value is missing (i have founded this fix like that)
Fix NumptyPhysics ingame, Move him to playable
> Add Support SCE_GXM_TEXTURE_FORMAT_U5U6U5_BGR

- src/emulator/vpk.cpp
Also eboot path and game category (from .sfo).
Tiny change, I'd put it in the other PR but I don't want to re-create #118 again.
> Log Title and Title ID

- src/emulator/gui/CMakeLists.txt
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/ui_main.cpp
- src/emulator/gui/src/ui_mutexes_dialog.cpp
- src/emulator/gui/src/ui_semaphores_dialog.cpp
> [gui] Added semaphore and mutex dialogs.

- src/emulator/host/include/host/functions.h
- src/emulator/kernel/include/kernel/state.h
- src/emulator/kernel/src/thread.cpp
- src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- Now supports priority-based scheduling
- Return proper error when surpassing max value, instead of clamping
- Refactored to own functions
- Removed an unneeded assert
> [kernel] Improve semaphores

- src/emulator/kernel/src/load_self.cpp
- src/emulator/mem/include/mem/mem.h
- src/emulator/mem/src/mem.cpp
This elf type needs to load segments at p_vaddr
> Allow ET_SCE_EXEC

- src/emulator/kernel/src/thread.cpp
- src/emulator/modules/SceNetCtl/SceNetCtl.cpp
- src/emulator/net/CMakeLists.txt
- src/emulator/net/include/net/state.h
I think is better to have small PR than a big one with full functionality
> Initial stubbing of netcallbacks

- src/emulator/io/include/io/state.h
- src/emulator/io/src/io.cpp
- src/emulator/vpk.cpp
- Fixed read_file_from_zip, now can be used more than once.
- Fixed load_vpk that was opening two file handlers without a good reason.
> Added maidump dumps native support

- src/emulator/modules/SceLibKernel/SceLibRng.cpp
> [rng] Initial implement sceKernelGetRandomNumber

- src/emulator/cpu/src/cpu.cpp
S0-S31 are not available, you need to access D0-D15
> Fix reading of floats

- src/emulator/shaders/10b8bbfc68d071f19af1e798f857422e8ec77a61ed2e5def5b55b2f4268eb5a7.vert
- src/emulator/shaders/1cb20053d85431ef8b8ba077b45fc87b11d886f4d3688411a4e5afe43bda16a9.frag
- src/emulator/shaders/9622051182914dd8284a5961bd82278b07d06690703753be3f2eca23e23e6e84.vert
- src/emulator/shaders/b48c128b9a63bc410b3209358f74e958a23e099df8a7804177c195d5f93ee651.frag
> Add shaders for Siralim game.

- src/emulator/gui/include/gui/functions.h
- src/emulator/gui/src/ui_main.cpp
- src/emulator/host/src/app.cpp
Added a reinstall application dialog triggered when someone starts the emulator giving a vpk/zip as argument and the emulator detects the application as already installed, useful for homebrew updates installation for example.
> [dialog] Added possibility to reinstall an app.

- src/emulator/cpu/src/cpu.cpp
- src/emulator/gxm/src/gxm.cpp
- src/emulator/host/src/host.cpp
- src/emulator/io/src/io.cpp
- src/emulator/kernel/include/kernel/state.h
- src/emulator/kernel/include/kernel/thread/sync_primitives.h
- src/emulator/kernel/src/load_self.cpp
- src/emulator/kernel/src/thread/sync_primitives.cpp
- src/emulator/mem/src/mem.cpp
- src/emulator/modules/SceGxm/SceGxm.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
Fix something from #236, logging improvements/fixes in sync objects and io.
> Link sceKernelWait*Cond to impl. and some logging tweaks

- src/emulator/module/include/module/lay_out_args.h
> Fix null dereference in `constexpr` function.

- README.md
- src/emulator/CMakeLists.txt
- src/emulator/audio/src/audio.cpp
- src/emulator/glutil/CMakeLists.txt
- src/emulator/glutil/include/glutil/object.h
- src/emulator/glutil/include/glutil/shader.h
- src/emulator/glutil/src/object.cpp
- src/emulator/glutil/src/shader.cpp
- src/emulator/gui/include/gui/functions.h
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/ui_main.cpp
- src/emulator/gui/src/ui_main_menubar.cpp
- src/emulator/gxm/include/gxm/types.h
- src/emulator/gxm/src/texture_cache.cpp
- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/app.h
- src/emulator/host/include/host/screen_render.h
- src/emulator/host/include/host/state.h
- src/emulator/host/src/app.cpp
- src/emulator/host/src/host.cpp
- src/emulator/host/src/screen_render.cpp
- src/emulator/main.cpp
- src/emulator/shaders-builtin/render_main.frag
- src/emulator/shaders-builtin/render_main.vert
We used to rely on imgui to render everything. This PR includes OpenGL screen texture rendering support so that we can do that ourselves and without displaying any GUI.
Use the **"G"** key to toggle GUI rendering on or off (more precisely, toggle rendering methods).
Includes some refactoring (as usual).
> Independent rendering support

- .travis.yml
- CMakeLists.txt
- src/emulator/disasm/src/disasm.cpp
- src/emulator/glutil/include/glutil/object_array.h
- src/emulator/glutil/src/object.cpp
- src/emulator/kernel/include/kernel/relocation.h
- src/emulator/kernel/src/load_self.cpp
- src/emulator/kernel/src/relocation.cpp
- src/emulator/modules/SceNet/SceNet.cpp
Wait for my second commit before to compare compilation times on Travis.
> Add ccache support

- src/emulator/host/src/app.cpp
- src/emulator/host/src/host.cpp
- src/emulator/kernel/include/kernel/load_self.h
- src/emulator/kernel/include/kernel/relocation.h
- src/emulator/kernel/src/load_self.cpp
- src/emulator/mem/src/mem.cpp
- src/emulator/modules/SceAppUtil/SceAppUtil.cpp
- src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
Various fixes, mostly centered around modules.
> Mostly module fixes

- src/emulator/cpu/include/cpu/functions.h
- src/emulator/cpu/src/cpu.cpp
- src/emulator/host/CMakeLists.txt
- src/emulator/host/include/host/state.h
- src/emulator/host/src/host.cpp
- src/emulator/io/include/io/io.h
- src/emulator/io/src/io.cpp
- src/emulator/modules/SceNgs/SceNgs.cpp
- src/emulator/nids/CMakeLists.txt
- src/emulator/nids/include/nids/types.h
Many games getting stuck on `sceNgs` should now progress.
I only tested **Risk of Rain** and **Garou: Mark of the Wolves**, but from what I remember looking at logs, there were lots of games previously getting stuck on sceNgs.
Also contains some debugging aids and an `io` fix.
> Stub commonly used sceNgs functions

- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/ui_main.cpp
- src/emulator/host/include/host/app.h
- src/emulator/host/src/app.cpp
- src/emulator/host/src/host.cpp
- src/emulator/main.cpp
- Game Select
- It's column/row based now
- Added sorting by TitleID and Title
- Sorts by Title by default
* Fix crash when quitting from Game Select screen
* Report zip-related errors
> Game Select: Redesign & sorting functionality

- src/external/CMakeLists.txt
It fixes the noexcept compilation issues under VS2017 15.8
More information: https://github.com/jbeder/yaml-cpp/pull/597
> Update yaml-cpp submodule

- src/emulator/module/include/module/write_return_value.h
- src/emulator/module/src/write_return_value.cpp
- src/emulator/modules/SceCommonDialog/SceCommonDialog.cpp
- src/emulator/modules/SceNet/SceNet.cpp
- src/emulator/modules/SceNetCtl/SceNetCtl.cpp
- src/emulator/net/include/net/state.h
- src/emulator/shadergen/src/shadergen_spirv.cpp
This enables Downwell to go in-game.
> Stub `sceNetCheckDialogGetStatus`

- src/emulator/io/include/io/functions.h
- src/emulator/io/include/io/state.h
- src/emulator/io/src/io.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
This PR takes @VelocityRa idea, but store Vita path with each file/directory handle.
Ready for testing and review.
> Implement sceIoGetstatByFd

- .gitmodules
- src/emulator/mem/include/mem/ptr.h
- src/emulator/module/CMakeLists.txt
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- src/emulator/renderer/src/renderer.cpp
- src/emulator/renderer/src/sync_state.cpp
- src/emulator/renderer/src/texture_palette.cpp
- src/external/CMakeLists.txt
> First Mspace implementations and small fixes

- README.md
- gen.bat
- gen.sh
- src/emulator/gui/src/ui_common_dialog.cpp
- src/emulator/host/include/host/app.h
- src/emulator/host/include/host/config.h
- src/emulator/host/include/host/functions.h
- src/emulator/host/include/host/state.h
- src/emulator/host/src/app.cpp
- src/emulator/host/src/config.cpp
- src/emulator/host/src/host.cpp
- src/emulator/io/include/io/io.h
- src/emulator/io/src/io.cpp
- src/emulator/kernel/include/kernel/thread/sync_primitives.h
- src/emulator/kernel/src/thread/sync_primitives.cpp
- src/emulator/kernel/src/thread/thread.cpp
- src/emulator/main.cpp
- src/emulator/modules/SceCommonDialog/SceCommonDialog.cpp
- src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- src/emulator/util/CMakeLists.txt
- src/emulator/util/include/util/string_utils.h
- src/emulator/util/src/util.cpp
Kernel implementations, a threadmgr crash fix and some IO refactoring.
These are from #316, but since it's taking a while, let's get these merged here (they're unrelated to LLE modules anyway).
> Kernel/threadmgr fixes & IO refactoring

- src/emulator/io/include/io/functions.h
- src/emulator/io/src/io.cpp
- src/emulator/modules/SceIofilemgr/SceIofilemgr.cpp
This makes Another Metroid 2 Remake to get ingame:
https://cdn.discordapp.com/attachments/408917186254733317/527218326712090625/unknown.png
> Replaced some asserts in IO code with error handling

- src/emulator/kernel/src/load_self.cpp
- Fixes regression in Downwell and other titles
- Resolves #343
- Update shaders-db to latest master
> Fix Downwell regression

- src/emulator/modules/SceCtrl/SceCtrl.cpp
Handles https://github.com/Vita3K/Vita3K/issues/373
> Updating controllers status in sceCtrlGetControllerPortInfo

- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/ui_allocations_dialog.cpp
- src/emulator/kernel/src/kernel.cpp
- src/emulator/kernel/src/load_self.cpp
- src/emulator/kernel/src/relocation.cpp
- src/emulator/kernel/src/thread/sync_primitives.cpp
- src/emulator/kernel/src/thread/thread.cpp
- src/emulator/mem/include/mem/mem.h
- src/emulator/modules/SceDisplay/SceDisplay.cpp
- src/emulator/modules/SceLibc/SceLibc.cpp
- src/emulator/modules/SceLibc/SceLibstdcxx.cpp
Read commits.
The loader commit prevents some crashes (ie. for LUFTRAUSERS).
> Minor memory debugging improvements & a loader fix

- src/emulator/modules/SceCtrl/SceCtrl.cpp
- Implemented sceCtrlPeekBufferNegative, sceCtrlReadBufferNegative
- Implemented sceCtrlPeekBufferPositiveExt2, sceCtrlReadBufferPositiveExt2
- Fixed returned value of sceCtrlPeekBufferPositive and sceCtrlReadBufferPositive
> Improvement to sceCtrl.

- src/emulator/util/include/util/log.h
- src/emulator/util/src/util.cpp
- src/external/CMakeLists.txt
Update submodule to version 1.3.1 and take advantages of the new
features
> external/log: Improve spdlog integration

- src/emulator/gui/src/ui_controls_dialog.cpp
- src/emulator/modules/SceCtrl/SceCtrl.cpp
- Implements sceCtrlPeekBufferPositive2, sceCtrlPeekBufferNegative2, sceCtrlReadBufferPositive2, sceCtrlReadBufferNegative2.
- Implements sceCtrlPeekBufferPositiveExt, sceCtrlReadBufferPositiveExt.
- Adds L2/R2/L3/R3 detection to sceCtrlPeekBufferPositiveExt2, sceCtrlReadBufferPositiveExt2.
- Properly reflects PSTV mode controls in Controls GUI window.
> Implemented some missing sceCtrl functions.

- src/emulator/gxm/include/gxm/state.h
- src/emulator/modules/SceGxm/SceGxm.cpp
Fixes https://github.com/Vita3K/Vita3K/issues/201
> [gxm] Killing display queue thread on sceGxmTerminate.

- src/emulator/gui/CMakeLists.txt
- src/emulator/gui/include/gui/functions.h
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/ui_about_dialog.cpp
- src/emulator/gui/src/ui_main.cpp
- src/emulator/gui/src/ui_main_menubar.cpp
~~i messed up the first pr beyond repair~~
- Version string
- A short description about the emulator
- Useful links
here's how it looks
> gui: add about page

- src/emulator/CMakeLists.txt
This adds a `CFBundleIdentifier` and a `CFBundleName`.
> cmake: Add some Info.plist entries.

- src/emulator/host/src/app.cpp
> host: warn user & quit when attempting to install a vitamin dump

- src/emulator/shader/src/usse_translator_entry.cpp
> shader: Remove explicit qualification in convert_gxp_usse_to_spirv

- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/game_selector.cpp
- src/emulator/host/include/host/state.h
- src/emulator/host/src/app.cpp
- src/emulator/host/src/host.cpp
Add app_ver on game list and inside log.
Like you see here:
I have set version before title game, same tittle id, because game name longer is random.
I have think add it like rpcs3 for can know what version game is used, i have see few time, diferent version can get different boot statut
Update few submodule.
gslang to last tag ->7.11.3113
imgui to last tag ->1.69
last master shader_db
> Gui: add app_ver on game list

- src/emulator/module/include/module/bridge.h
- src/emulator/modules/SceGxm/SceGxm.cpp
- src/emulator/renderer/include/renderer/types.h
- src/emulator/renderer/src/uniforms.cpp
- src/emulator/shader/src/usse_translator.cpp
Each commit already describes what it does
Second commit is a correction of the original method to determines mat4 uniform type. The fault was pointed out by @petmac
> Another miscs

- src/emulator/gui/src/main_menubar.cpp
- src/emulator/host/include/host/config.h
- src/emulator/host/src/app.cpp
- src/emulator/host/src/config.cpp
detected with test rtc, gui hide all time up part on screen for game, i have so thinked can add possibility for can hide gui in boot game directly without press G
> Gui: Add can hide gui after boot game.

- src/emulator/kernel/src/load_self.cpp
This is for stubbed var imports.
Correct hle of var imports will be done in other pr
> Fix for stubbed var imports

- src/emulator/host/src/app.cpp
- src/emulator/kernel/src/load_self.cpp
- Fix regression caused on last pr  https://github.com/Vita3K/Vita3K/pull/436
- Fix clang format on my last pr
> kernel/load_self: Fix var imports load module

- README.md
Patrons who donate $4 or more can request to have their name added. Apologies for not noticing #425 sooner.
> Recognise supporter who requested a mention

- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/game_selector.cpp
- src/emulator/util/include/util/string_utils.h
- src/emulator/util/src/util.cpp
- Made the Title sorter non case-dependant.
- Added descendant/ascendant sorting for every sort mode.
> gui: Improvements in game selector sorter.

- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
- Implemented sceClibMemcmp, sceClibMemmove and sceClibStrcmp.
- Made sceClibMemcpy and sceClibMemcpy_safe compliant to standard C functions.
> modules/SceLibKernel: Some sceClib improvements.

- src/emulator/gxm/include/gxm/types.h
- src/emulator/shader/include/shader/usse_decoder_helpers.h
- src/emulator/shader/include/shader/usse_disasm.h
- src/emulator/shader/include/shader/usse_translator.h
- src/emulator/shader/include/shader/usse_translator_entry.h
- src/emulator/shader/include/shader/usse_translator_types.h
- src/emulator/shader/include/shader/usse_types.h
- src/emulator/shader/src/spirv_recompiler.cpp
- src/emulator/shader/src/usse_decode_helpers.cpp
- src/emulator/shader/src/usse_disasm.cpp
- src/emulator/shader/src/usse_translator.cpp
- src/emulator/shader/src/usse_translator_entry.cpp
TODO:
- Instructions:
TODO next PR:
- Block support: Branch and recompile
- Constant table (*C* bank)
- f16/f32 uniform/buffer parameter (?)
> Recompback

- src/emulator/init.cpp
> emulator: Throw error dialogue when failed to create OpenGL context

- src/emulator/gui/src/game_selector.cpp
The search bar can filter using the game's title and title ID
Closes #415
> Search bar for games

- src/emulator/config.cpp
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/game_selector.cpp
- src/emulator/gui/src/gui.cpp
- src/emulator/host/include/host/config.h
thx @1whatleytay for all help.
thx also to @VelocityRa for review and help me improve code.
For user want test this PR, i have seet 4 size icon diferent, Small/Medium/Big/Original
Vita3K create news line for first time launch inside config.yml file, just need change value: 0 to 4 for change icon size. 
Eg with Big value:
> Gui: add Game icon and size icon choice in config

- src/emulator/io/include/io/functions.h
- src/emulator/io/src/io.cpp
- src/emulator/modules/SceLibKernel/SceLibKernel.cpp
Have a possibility to fix MAGES games (freeze on shader.bin seeking end to get size, but get garbage value instead because r1 is not set)
> modules/SceLibKernel: Correct sceIoLSeek return types

- src/emulator/config.cpp
- src/emulator/gui/include/gui/functions.h
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/game_selector.cpp
- src/emulator/gui/src/gui.cpp
- src/emulator/gui/src/settings_dialog.cpp
- src/emulator/host/include/host/config.h
- src/emulator/init.cpp
- src/external/CMakeLists.txt
- Fix save change on init. (On master before, save only if you set one think special, on last master it save also if you open settings dialog, causing problem for pref path)
- Add pref path in Emulator Tab for can set personal folder without edit config file manually.
- Fix log level choice works on config, on master it reset your value changed all time.
- Add log level choice in settings dialog.
- Add Background image path on setting dialog.
- Fix Background Alpha with disable it if not have image set.
- Add possibility can change background image without reboot.
- Add game background on font by @1whatleytay thx for that.
- Add gamebackfront apear with get mouse on icon.
- Add restore background user with set cursor on other Icon/title ID
(for it, i have added space free(TitleID), for …
> Settings: Add news options and fix some things

- src/emulator/config.cpp
- src/emulator/host/include/host/config.h
fix issue with get wrong default value on news config file created.
> Gui/settings: fix initialize value for news config.

- README.md
It wasn't caught that I spelled Grzybojad's name wrong... fixed.
> readme: Update2

- src/emulator/shader/src/translator/alu.cpp
Helped by @pent0 for set code in clear.
> shader/translator: Implement VDSX and VDSY.

- src/emulator/gui/src/gui.cpp
Passed the base_path of the app to init_font in order to make the fonts load when the app is loaded from any location.
> fixed the loading of the font

- README.md
> readme: Note about potential Unicorn issue on Linux

- src/emulator/gui/CMakeLists.txt
- src/emulator/gui/include/gui/state.h
- src/emulator/gui/src/gui.cpp
- src/emulator/gui/src/main_menubar.cpp
- src/emulator/gui/src/private.h
- src/emulator/gui/src/shader_editor_dialog.cpp
- src/emulator/gxm/include/gxm/types.h
- src/emulator/modules/SceGxm/SceGxm.cpp
- src/emulator/renderer/include/renderer/functions.h
- src/emulator/renderer/include/renderer/state.h
- src/emulator/renderer/include/renderer/types.h
- src/emulator/renderer/src/functions.h
- src/emulator/renderer/src/load_shaders.cpp
- src/emulator/renderer/src/renderer.cpp
- src/emulator/shader/src/translator/utils.cpp
- src/emulator/util/CMakeLists.txt
- src/emulator/util/include/util/exec.h
> gui/renderer: Shader debugging utilities

- src/emulator/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- src/emulator/modules/SceSysmodule/SceSysmodule.cpp
Also:
- module/sysmodule: Add SceMp4 dependency to SceAvPlayer
>  kernel/threadmgr: Accurate sceKernelDelayThread* sleep

- src/emulator/modules/SceProcessmgr/SceProcessmgr.cpp
The dog thought that it's winter....
But it was me! Summer
> modules/SceProcessMgr: Correct and implement Libc time functions

- src/emulator/shader/include/shader/usse_program_analyzer.h
- src/emulator/shader/include/shader/usse_utilities.h
- src/emulator/shader/src/translator/data.cpp
- src/emulator/shader/src/usse_program_analyzer.cpp
- src/emulator/shader/src/usse_utilities.cpp
Fix Downwell. May fix other games involving MOVC.
How CMOV works in the nutshell:
```
compare_result = condition(src0, veczero)
for i = 0 to comp_count(compare_result):
if (compare_result[i]) dest[i] = src1[i]
else dest[i] = src2[i]
```
~~May introduce major framedrop but i have no choice right now. Will make static analyzation later if I can (like detect step pattern)~~
> shader/translator: Correctly implement CMOV

- src/emulator/config/include/config/functions.h
- src/emulator/config/src/config.cpp
Self-explanatory.
Had to change some of the logic around to make sure the home config path is not overwritten.
> config: Fix pref_path

- src/emulator/config/src/config.cpp
After a mention in Discord about the vpk loading not working, I realized that I forgot to add in the first three optional values and move it over to the main config. (*doh*)
> config: Move first three optional command line parameters

- .travis.yml
- .travis/linux/build.sh
- .travis/linux/docker.sh
- src/emulator/np/src/trophy/trp_parser.cpp
Replace docker image `ubuntu:18.04` by `gcc:8`
> travis: Use gcc docker image

- vita3k/config/include/config/config.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- Add Hardware Flip in news gpu tab.
- Move perfomance Overlay in emulator tab.
- Add save color surface missing in config.
- Performance Overlay
- Hardware Flip
> Change misc things in setting/config

- format.sh
- vita3k/CMakeLists.txt
- vita3k/app/src/app_init.cpp
- vita3k/config/src/config.cpp
- vita3k/features/include/features/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/renderer/src/gl/renderer.cpp
- Add gpu name on log info inside app init.
- fix startup project choice vita3k and no ALL BUILD with fix wrong path for project
- fix can allow change hardware flip without reboot emu before boot game.
- fix tab on setting dialog issue appear after update on 1.72 imgui. 
- fix missing change directory for format.sh
- Add on log backend render used
- fix vulkan render on gui working 
- fix command line for backend render
- GPU Name
- Startup project fixed by default.
> No name founded

- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
special thx to elad for help me with some things.
> gui: Replace hardcoded LLE module list with present dumped modules

- vita3k/app/src/app_init.cpp
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/game_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/include/host/state.h
- Add button for refresh game list.
- Refactor lot function.
- Refresh game list button
> Add refresh game list button and misc things

- .travis.yml
From @IllusionMan1212:
> It caused the releases to be untagged
> Revert "Playing Tag"

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/settings_dialog.cpp
Also run `clang-format` on project.
> gui: Fix LLE module list

- .gitmodules
- .travis/linux/docker.sh
- external/CMakeLists.txt
- vita3k/gui/CMakeLists.txt
- vita3k/gui/src/game_selector.cpp
- vita3k/gui/src/profiles_manager_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- Switch write path/user image background with using file explorer.
thx @IllusionMan1212 for help on nfd.
- Default Path :
- Open Explorer
- After
- Default
- File explorer : 
- After :
> Use file explorer for setting dialog

- vita3k/mem/src/mem.cpp
- vita3k/util/include/util/align.h
Hopefully fixes #597.
It fixes the crash on Windows, needs macOS + linux testing.
Edit:
fixes #584 too
> Fix memory regression ("10 Second Ninja", etc)

- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/game_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/interface.h
- Add install game dialog and popup for vpk/zip. (compatible with hb and maidump)
- ask reinstall game: 
- confirm game success installed:
> gui: Add install game with file explorer

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/settings_dialog.cpp
big thx to @kd-11 for help and time 
- Refactor module list and modules selected for merge all inside one value "vector pair string/bool"
- add refresh module list button.
- for can so add sort of modules enable listed in first.
> gui/setting: refactor modules list with using pair.

- vita3k/gxm/src/gxp.cpp
- vita3k/main.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
- vita3k/np/src/trophy/context.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/texture_format.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- vita3k/shader/src/usse_utilities.cpp
- vita3k/util/CMakeLists.txt
- vita3k/util/src/util.cpp
Part of an effort to get the emulator compiling clean with no warnings.
There are still a few left so I'll update this PR with more fixes once I figure the code out better.
> Fix warnings when compiling with Clang

- .gitmodules
- external/CMakeLists.txt
- vita3k/crypto/CMakeLists.txt
- vita3k/crypto/include/crypto/aes.h
- vita3k/crypto/src/aes.cpp
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/install_firmware_dialog.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/CMakeLists.txt
- vita3k/host/include/host/functions.h
- vita3k/host/include/host/pup_types.h
- vita3k/host/src/pup.cpp
- vita3k/host/src/pup_utils.cpp
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/util/include/util/string_utils.h
- vita3k/util/src/util.cpp
~~Draft PR for obvious reasons lol.~~
[TESTERS NEEDED] I still need people to test on ~~Mac~~ and linux to see if ~~A) it compiles~~ and B) it works as intended.
Thank you @pent0 for writing the fat16 lib
I wanted to get some feedback/opinions on a few things i did/didn't do here, so here goes:
- As you'll notice i took the liberty of adding the `nativefiledialog` submodule for file dialogs when installing the firmware, i've also made it from my own fork because it's the most updated one so far. If you feel that this is an unnecessary addition or have any feedback regards to it, please feel free to tell me.
- `pup_types.h` has some classes similar to the structs found in `vita-toolchain/src/self.h` **but they're not the same**. and i've basically rewrote a couple of ELF structs from …
> PUP decryption

- .gitmodules
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/game_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/kernel/src/relocation.cpp
- vita3k/modules/SceAudioIn/SceAudioIn.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- format: run clang format.
- small refactor firmware install dialog
- small refactor for game install dialog.
- button on setting dialog for download last firmware if it is missing.
- fix popup failed installation with correct typo 
- stub savedatadialogstatus
> few small refactoring

- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/game_install_dialog.cpp
- vita3k/host/src/pup.cpp
- vita3k/interface.cpp
- Add checkbox for popup dialog in firmware install and game install.
- Add firmware version on pop confirmation after install fw.
> gui/firmware and game install: add check for delete file after installed.

- vita3k/renderer/src/gl/sync_state.cpp
It need some testers. It works ok for Retroarch
> renderer/gl: Correct viewport formula again

- vita3k/cpu/src/cpu.cpp
- vita3k/kernel/src/thread/thread.cpp
Tells us specific error names plus register values.
velo was talking about tracking down which module the error might've happened in
that might be cool to add
> Better unicorn error reporting.

- vita3k/io/src/io.cpp
allows statting of directories on windows, something already supported on other platforms. stardew valley v1.00 would crash on windows because it tries to stat a directory.
> io: use _wstat instead of FindFirstFileW on windows for stat_file

- vita3k/modules/SceSysmem/SceSysmem.cpp
I forgot to look at travis builds...
> kernel/sysmem: Fix free mem on Linux

- vita3k/gui/src/common_dialog.cpp
- vita3k/host/include/host/app_util.h
- vita3k/io/include/io/functions.h
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
get access menu for some game.
- For more explain, is just actually it spam sce io open dlc file, because for it dlc is here, so actually it loop(depending game, reallity fighter don't loop) and block boot.
With this so i check if drm content is here, and said file is not here on this case and don't try open it after.
- ONE PIECE Unlimited World Red
> App util: stub sceAppUtilDrmOpen.

- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/gxp.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/shader/include/shader/usse_program_analyzer.h
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- vita3k/shader/src/usse_utilities.cpp
- vita3k/util/src/util.cpp
- implement sceGxmFragmentProgramGetProgram. (credit to @1whatleytay)
- run clang project format again
- Intro for sudoku and akiba and probably vbery lot more, see this function causing crash very lot time
> modules/SceGxm: implement sceGxmFragmentProgramGetProgram.

- vita3k/modules/SceDisplay/SceDisplayUser.cpp
credit to @frangarcj 
- Intro and check psn menu for High School DxD: New Fight
> module/sceDisplaySetFrameBuf: fix crash if pParam is null.

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- Implement sceClibStrlcat & sceClibStrlcpy & sceClibVsnprintf
- small refactor exist code
> implement sceClibStrlcpy/sceClibStrlcat /sceClibVsnprintf

- vita3k/io/src/io.cpp
Our io system returns ENOENT a lot for a bunch of different games. I see it a lot in logs and I have no idea what went wrong or how to start fixing it.
Wanted to add some logs so we are able to come up with an idea of what went wrong at a glance.
> io: add specific messages for ENOENT cases

- vita3k/app/src/app_init.cpp
- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
This option launches the emulator in fullscreen mode
> config/app: add --fullscreen command line option

- appveyor.yml
- gen-windows.bat
Format comments, remove useless ones.
Delete white space.
Use proper multi-line for cmd commands.
Remove verbosity since normal is the default.
Change slash to \ to be consistent with Windows.
Change Release to $env:CONFIGURATION
gen-windows.bat: Change default to Visual Studio 2019
> AppVeyor: Upgrade to Visual Studio 2019, Boost 1.71, other changes

- vita3k/interface.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.h
- Implement sceAppMgrLoadExec
- Retroarch, god of war collection working 
- On Snes9x 2010
> implement sceAppMgrLoadExec.

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
> gui: added a button to open pref path

- vita3k/gui/src/game_context_menu.cpp
> gui: add missing c_str()

- .gitignore
- CMakeLists.txt
- README.md
- building.md
- gen-linux.sh
- gen-macos.sh
- gen-windows.bat
- Update build instruction so that we can build locally on Linux and Mac OS.
- Fix missing headers for `ext-boost`.
This will help anyone who is interested in the project able to build locally on Linux and Mac OS.
> Update build instructions

- vita3k/interface.cpp
~`git blame watchful`~
i also added game patches just so they don't fall under the last else statement and overwrite the original game files
> emu: fix homebrew installation and add game patches

- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/game_context_menu.cpp
- vita3k/gui/src/game_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area_dialog.cpp
- vita3k/gui/src/manual_dialog.cpp
- vita3k/gui/src/reinstall.cpp
- vita3k/gui/src/settings_dialog.cpp
- Split theme pr for set update imgui submodule alone.
- fix size for app list if user don't have sao partition on firmware instaled.
- fix my mistake PopStyleColor missing.
- fix not show app selector with boot app on comment or vpk drop
.
> external: update imgui submodule

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/texture.cpp
- vita3k/util/include/util/align.h
- vita3k/util/src/util.cpp
thx @pent0 for your time and your code.
- implement  sceGxmTextureInitSwizzledArbitrary.
- God collection fix texture has null and show both loading screen
- Aw Phoenix fiesta
- fix select player screen
- fix information for battle mode (3d mode)
- fix crash this screen and get all after finjnaly showed for first time
- hack video playing and get menu works
> SceGxm: implement sceGxmTextureInitSwizzledArbitrary.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/gl/texture_formats.cpp
- fix video playing for time traveler, and lot other probably
- master
- pr
> Texture: Add support YUV/YVU(420P3).

- vita3k/host/src/pup.cpp
Increase the number of apps to test 🙂
> pup: Decrypt firmware apps

- vita3k/crypto/include/crypto/hash.h
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/private.h
- vita3k/main.cpp
- fix build on Visual Studio 2019 16.6.0.
- gui: set window title during app loading.
- gui: fix double view on app context.
> Some small fix.

- vita3k/config/include/config/config.h
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/game_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/host/include/host/pkg.h
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/io/src/io.cpp
- vita3k/main.cpp
- Add initial support curtum and offical playstation theme
(for now support only background and start screen)
- Add support install official vita theme with pkg or in nonpdrm.
- TODO for later:
can use sound music file.
- gui setting screen
- theme and background menu
- start screen menu
- background
- theme list
- select theme
- information theme
- deleting theme
- theme appy
- Start screen with default theme
- start screen with official theme
> gui: add initial themes support.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/renderer/CMakeLists.txt
- vita3k/renderer/include/renderer/pvrt-dec.h
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/gl/texture_formats.cpp
- vita3k/renderer/src/pvrt-dec.cpp
- implement PVRT texture support 
- Sackboy runner:
- Fort defense
- Salt and Sanctuary
blocked here, touch screen issue ? 
- Silent hill
> implement PVRT support decompress texture.

- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/modules/SceFiber/SceFiber.h
credit code to @frangarcj 
- fix implementation sceFiberGetSelf.
> modules/SceFiber: fix sceFiberGetSelf.

- vita3k/config/include/config/config.h
> config: Change default cross bind from "o" to "x"

- vita3k/dialog/include/dialog/state.h
- vita3k/gui/src/common_dialog.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
Implemented the substatus for the dialog which leads to a bunch of games progressing even more.
There's still a few other odd behaviors with how the dialog works and I'm currently lacking games to test how these work
> Savedata dialog fixes

- vita3k/app/src/app_init.cpp
- vita3k/host/CMakeLists.txt
- vita3k/host/include/host/import_var.h
- vita3k/interface.cpp
- vita3k/module/include/module/bridge.h
- vita3k/module/include/module/module.h
- vita3k/modules/ScePerf/ScePerf.cpp
- vita3k/modules/ScePerf/ScePerf.h
- vita3k/modules/module_parent.cpp
- vita3k/nids/CMakeLists.txt
- vita3k/nids/include/nids/functions.h
- vita3k/nids/include/nids/nid_vars.h
- vita3k/nids/include/nids/nids.h
- vita3k/nids/src/nids.cpp
- Change the hle vars interface to use factory function
- Give a pointer contains pointer to _pLibPerfCaptureFlagPtr
https://github.com/Vita3K/compatibility/issues/401
> Fix hle var import

- vita3k/app/src/app_init.cpp
- vita3k/interface.cpp
- vita3k/module/include/module/bridge.h
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
- vita3k/nids/src/nids.cpp
> Format #752

- vita3k/interface.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
- Fix a bug in HLE var exports
https://github.com/Vita3K/Vita3K/commit/52e41f3bd2f90c5fda2d48d39bb2d1d44710c4b7#commitcomment-39875184
> Fix initialization order bug of var_exports

- vita3k/modules/SceFios2Kernel/SceFios2Kernel.cpp
- vita3k/modules/SceFios2Kernel/SceFios2Kernel.h
- vita3k/modules/SceFios2Kernel/SceFios2Kernel02.cpp
- vita3k/modules/SceFios2Kernel/SceFios2Kernel02.h
- implement : _sceFiosKernelOverlayResolveWithRangeSync
- implement : _sceFiosKernelOverlayResolveWithRangeSync02
> Impelment two sceFiosKernelOverlayResolveWithRangeSync

- vita3k/gui/src/trophy_unlocked.cpp
- vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
- vita3k/np/include/np/functions.h
- vita3k/np/include/np/state.h
- vita3k/np/include/np/trophy/context.h
- vita3k/np/src/trophy/context.cpp
- Add install trophy conf.
- fix order for trophy grade with also change name + move on SceInt32
- Add group id count and trophy count by id on trophy user dat
- Add is_trophy_unlocked request for trophy manager and for one function implemented later.
- move copy_file_data_from_trophy_file inside context for install trophy conf file.
- fix trophy kinds value.
> np/trophy: Some refactor and prepare for trophy manager.

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/host/include/host/pkg.h
- vita3k/host/src/pkg.cpp
- vita3k/main.cpp
-  Refactor look design
- Add choice for can inpout zRIF key or select work.bin file for key with fix issue request #726
- Add info content installed. 
- Fix theme list not showed if fw not installed
> pkg: add mode choice for zRIF key.

- vita3k/app/src/app.cpp
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy.cpp
- vita3k/host/include/host/state.h
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/interface.h
- vita3k/main.cpp
- rename all named game to app
- Improve render on live area
- Get refactor bouton search/manual, using box with color like close on psvita
- Show selection on all icon clickable, ignore psn link
- on website link
> lot refactor and rename game to app.

- vita3k/gui/src/gui.cpp
> Fix "gui: Trim titles so that they order and show correctly"

- .github/format-check.sh
- .github/workflows/c-cpp.yml
If code is not formatted, stop the whole workflow.
Shout out to @Johnnynator
https://github.com/Johnnynator/Vita3K/pull/3
> Add fomat check github actions job

- README.md
* [Windows](https://github.com/Vita3K/Vita3K/actions?query=event%3Apush+is%3Asuccess+branch%3Amaster)
* [Visual C++ Redistributables](https://aka.ms/vs/16/release/vc_redist.x64.exe) (Install if not working.) 
* [Linux](https://github.com/Vita3K/Vita3K/actions?query=event%3Apush+is%3Asuccess+branch%3Amaster)
* [macOS](https://github.com/Vita3K/Vita3K/actions?query=event%3Apush+is%3Asuccess+branch%3Amaster)
Includes macOS, Linux and the C++ Runtime redistributables to avoid more vcruntime questions on the discord
> Update README.md to include a better downloads section

- vita3k/gui/src/themes.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceDbg/SceDbg.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/renderer/include/renderer/texture_cache_state.h
- renderer: small changes
- gui: small changes
> Small refactor: Change 1024 to KB(x)

- vita3k/gui/src/app_selector.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
Credit to @frangarcj for found fix.
- Fix first lbp crash on saevdata have null data
> modules/SceAppUtil: fix crash if data is null.

- vita3k/host/src/pup.cpp
- vita3k/interface.cpp
Split refactor kernel pr
- fw install/pup: decrypt full os0 and vs0 partiton
- interface/run app: load fw pre-load module if app don't have it.
> decrypt more firmware install and module loading change

- vita3k/gui/src/live_area.cpp
- vita3k/main.cpp
- gui/live_area: fix position on item if get outside frame.
- gui: fix flashing on boot if app no have background.
> Fix small gui issue.

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
> Implement sceKernelPollSema

- vita3k/shader/src/translator/alu.cpp
> Implement VF16DP

- vita3k/dialog/include/dialog/types.h
- vita3k/host/include/host/app_util.h
- vita3k/io/include/io/functions.h
- vita3k/io/include/io/state.h
- vita3k/io/src/io.cpp
- vita3k/io/src/state_functions.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- Added file truncation mode for SceAppUtilSaveDataDataSave
- Fixed passing in inverted arguments to `write()`
- Implemented system mode for the savedata dialog and added more checks which allow PlayStation Home Arcade to go ingame
> more savedata fixes

- vita3k/shader/include/shader/usse_program_analyzer.h
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/special.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- Implement kill instruction
It removes some glitches in lbp intro screen.
> shader: implement kill instruction

- vita3k/io/src/io.cpp
- vita3k/renderer/CMakeLists.txt
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/src/driver_functions.h
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/texture_cache.cpp
Based on https://github.com/Vita3K/Vita3K/pull/522 by @VelocityRa 
I elaborated logging and supported compressed texture dumping.
> renderer: add texture dumping

- vita3k/gui/src/live_area.cpp
- live area: small fix on Manual typo.
- live area: fix cursor on slider app list.
> Small fix on live area

- vita3k/gui/src/themes.cpp
- Add save and restore scroll pos for can resore it.
Very needed if you have very lot diferent theme in list for it not re go on 0 after set back.
> Add save/restore scroll pos for themes list.

- vita3k/io/src/io.cpp
credit code fix @frangarcj 
- Set read more correctly woth return same value.
- Fix value writed with get correct value.
> io: fix read/writen value.

- vita3k/io/src/io.cpp
- Fix mistake on read and write get regression on aqua kitty and maybe more.
> io: fix regression 

- vita3k/modules/SceNet/SceNet.cpp
- vita3k/modules/SceNetCtl/SceNetCtl.cpp
- Stub netctl callback correctly
- Return flight mode error in sceNetCtlInetGetResult
Improves booting of LBP.
> Wiser stub for netctl

- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/src/cpu.cpp
- vita3k/kernel/include/kernel/functions.h
- vita3k/kernel/src/kernel.cpp
- vita3k/modules/module_parent.cpp
> Log offset in memory watch

- vita3k/mem/include/mem/mem.h
- vita3k/shader/include/shader/usse_translator.h
> Minor edits

- vita3k/mem/include/mem/mem.h
> mem: revert std function commit

- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/themes.cpp
- vita3k/host/include/host/state.h
- vita3k/interface.cpp
I split my content manager pr
- Some refactor on globality gui
- Add get_app_index function
- rename apps to user_apps
> Gui: some refactor/fix.

- vita3k/config/include/config/config.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/module/include/module/load_module.h
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- Add new possible using default list on automatic mode. this list off course can change in future.
- Move log for hardware flip and module list inside load_app_impl.
- Auto mode
- Manual
> Add automatic module load list mode

- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/themes.cpp
- Add content manager
- move get app info inside content manager
- App Icon with theme
- App Live Area
- Content Manager home
- App list
- App Delete popup
- App info
- More App info with DLC installed
- Save Data List
- Empty save
- Save data delete popup
> Add Content manager

- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/src/cpu.cpp
- vita3k/host/src/load_self.cpp
- vita3k/kernel/src/thread/thread.cpp
- vita3k/modules/module_parent.cpp
- Add logging for lle function return value to keep track of their errors
- Several minor improvements related to logging
Set TRACK_IMPORT_CALL_RETURN to true.
Fix https://github.com/Vita3K/Vita3K/issues/798
> Add lle return logging

- vita3k/renderer/src/gl/renderer.cpp
- Refactor code move if to switch
- Fix regression on T@g with add color format request.
- Add color format request by Home arcade Ingame get fix it.
- Add color format request by gravity rush logo/menu.
> gl/renderer: Add more color format support for get_surface_data

- vita3k/audio/src/audio.cpp
- Fix sound get regressed with totaly disable it after #787
> audio: fix regression broken sound.

- vita3k/kernel/src/relocation.cpp
- Fix an issue in relocation type 2
Fix crash in LLE pvf
> kernel: fix relocation type 2

- vita3k/gui/src/common_dialog.cpp
I messed this one up back when i did some dialog fixes
> gui: fix save dialog substatus

- vita3k/interface.cpp
Fixes regression happen in debug build after https://github.com/Vita3K/Vita3K/pull/834.
> Correctly initialize struct in interface.cpp

- vita3k/app/src/app.cpp
- vita3k/gui/include/gui/imgui_impl_sdl_state.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/imgui_impl_sdl.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy.cpp
- vita3k/host/include/host/state.h
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/io/include/io/functions.h
- vita3k/io/include/io/state.h
- vita3k/io/src/io.cpp
- vita3k/main.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
Other split notice pr
- Fix crash if both theme folder is empty
- Create current title id and current app title
- Improve gui on trophy/theme/content
- Remove init background outside no console move for both can load it
- fix imgui_impl_sdl_state for using const, by @1whatleytay
> gui: some fix/refactor.

- vita3k/np/src/trophy/context.cpp
> np/trophy: fix writing trophies

- vita3k/app/src/app.cpp
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy.cpp
- vita3k/host/include/host/state.h
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/io/include/io/state.h
- vita3k/io/src/io.cpp
- vita3k/main.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
> app background: fix get and display good bg.

- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/usse_utilities.cpp
This implements full packing and unpacking of uint and int values. It can still pack and unpack the types supported before (uint8 and half)
> Implement unpack_one & pack_one of int and uint values

- vita3k/gxm/include/gxm/types.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- theyre functions, theyre precomputed
- @1whatleytay is an epic gamer who wrote most of this code
> Hitoashisaki

- vita3k/app/src/app_init.cpp
- vita3k/host/include/host/state.h
- vita3k/host/include/host/window.h
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
> host: Change window from shared_ptr to unique_ptr as it's never shared

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/condvars_dialog.cpp
- vita3k/gui/src/eventflags_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/mutexes_dialog.cpp
- vita3k/gui/src/semaphores_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy.cpp
Fix the second compilation error reported in #880
> gui: fix a compilation error and minor misc changes

- vita3k/gui/src/themes.cpp
- Add some background for default theme
> Osef works

- vita3k/shader/src/spirv_recompiler.cpp
It turned out the vita writes 0 when the program doesn't write anything to vertex outputs.
> Initialize vertex outputs to 0

- vita3k/shader/src/translator/alu.cpp
Improves rendering of chronovolt
> Implement dual frsq/frcp

- vita3k/modules/SceGxm/SceGxm.cpp
We should cast to non floats in this function. 
Look how VitaGL does: https://github.com/Rinnegatamante/vitaGL/blob/0d2110ac7b001e1e70688c6450a263b361a2b337/source/vitaGL.c#L1366
> Cast non float in sceGxmSetUniformDataF

- vita3k/shader/src/spirv_recompiler.cpp
This improves p4g rendering a lot.
I'm not sure whether this size is actually right. I'm going to confirm tomorrow.
> Correct the size and order of vertex outputs & fix some bugs in loading and storing them

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/modules/SceNgsUser/SceNgs.cpp
I observed stubbing ngs fixes danganronpa2.
We have quite a regressions caused by ngs support. But, there are also some progressions with ngs. I think having a gui option to toggle it is an ideal choice for now.
> Add gui option to disable ngs

- vita3k/app/src/app_init.cpp
- vita3k/config/src/config.cpp
- vita3k/glutil/src/shader.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/include/host/functions.h
- vita3k/host/include/host/sce_types.h
- vita3k/host/include/host/state.h
- vita3k/host/src/pup.cpp
- vita3k/host/src/sce_utils.cpp
- vita3k/io/include/io/device.h
- vita3k/io/include/io/functions.h
- vita3k/io/include/io/vfs.h
- vita3k/io/src/io.cpp
- vita3k/main.cpp
- vita3k/np/include/np/functions.h
- vita3k/np/include/np/trophy/context.h
- vita3k/np/src/trophy/context.cpp
- vita3k/renderer/src/batch.cpp
- vita3k/renderer/src/creation.cpp
- vita3k/util/src/util.cpp
*  [x] ~~CAN IT RUN CRYSIS?~~
*  [x] ~~CAN IT RUN CRYSIS?~~
*  [x] ~~CAN IT RUN CRYSIS?~~
#957 
#953 
#962 
* Thx to @Zangetsu38 for helping me fixing the PR history and merging this
> Add unicode path support

- external/CMakeLists.txt
> Update CMakeList to only download gamesdk once

- tools/usse-decoder-gen/autogen.py
> remove unnecessary import statement

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/state_set.cpp
This should remove most of the reported memory leaks when running games for a long time.
Fix https://github.com/Vita3K/Vita3K/issues/964
> renderer : fix mem leaks in data uploading commands

- vita3k/CMakeLists.txt
not sure if it's the same deal on macos
> vita3k: copy discord library and tell linker to look in working dir

- vita3k/module/include/module/vargs.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Fix https://github.com/Vita3K/Vita3K/issues/998
> modules: fix sceClibVsnprintf

- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/host/include/host/functions.h
- vita3k/host/include/host/pkg.h
- vita3k/host/src/pkg.cpp
- vita3k/host/src/pup.cpp
- vita3k/interface.cpp
- vita3k/interface.h
run game and firmware installation on a separate thread to avoid locking up the emulator and keep it responsive
> installation progress bar

- vita3k/renderer/src/gl/renderer.cpp
None blend function should just do normal rendering.
> renderer: fix none blend func

- vita3k/cpu/src/cpu.cpp
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- Implement cleareventflag
- Properly clear the flag in waiteventflag
This fixes the freeze at booting screen in puyo puyo tetris.
> kernel: improve eventflag

- vita3k/shader/src/translator/texture.cpp
Stub sb_mode 3.
This fixes black floor glitch in p4g when running vita3k with intel hd gpu.
> shader: implement sb_mode in smp

- vita3k/codec/src/mjpeg.cpp
- vita3k/codec/src/player.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/interface.cpp
- vita3k/modules/SceAppMgr/SceAppMgrUser.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/shader/src/usse_utilities.cpp
```
..\vita3k\codec\src\mjpeg.cpp(79): warning C4018: '<': signed/unsigned mismatch
..\vita3k\codec\src\player.cpp(166): warning C4018: '<': signed/unsigned mismatch
..\vita3k\codec\src\player.cpp(167): warning C4018: '<': signed/unsigned mismatch
..\vita3k\interface.cpp(206): warning C4244: 'argument': conversion from 'double' to 'float', possible loss of data
..\vita3k\gui\src\common_dialog.cpp(281): warning C4018: '<': signed/unsigned mismatch
..\vita3k\modules\SceAppMgr\SceAppMgrUser.cpp(480): warning C4018: '<': signed/unsigned mismatch
..\vita3k\modules\SceAppMgr\SceAppMgrUser.cpp(493): warning C4018: '<': signed/unsigned mismatch
..\vita3k\modules\SceCommonDialog\SceCommonDialog.cpp(975): warning C4018: '<': signed/unsigned mismatch …
```
> msvc: fix some compiler warnings

- vita3k/module/include/module/write_return_value.h
- vita3k/module/src/write_return_value.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
> SceGxm: implement some sceGxmDepthStencilSurface* functions

- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/modules/SceFiber/SceFiber.h
~~It helps A.O.T. Wings of Freedom and Grisaia no kajitsu spinout to proceed a bit further.~~
> SceFiber: add error checks

- vita3k/gxm/include/gxm/types.h
- vita3k/modules/SceGxm/SceGxm.cpp
> SceGxm: implement sceGxmPrecomputedVertexStateSetUniformBuffer

- vita3k/gui/src/app_selector.cpp
I have thinks add this like psvita after using tablet for control computer without mouse for scroll.
Psvita have "Page" view, but here i juste add scrol like one page by one page
> gui/app selector: Add arrow for scroll app list.

- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
i think this is how it should be, i tested a bunch of games and found no regressions
> SceCommonDialog: fix savedata dialog logic

- vita3k/shader/src/translator/texture.cpp
add case 0 request by game, fix regression  #1050
> shader: add sb_mode 0 in smp

- vita3k/renderer/src/gl/renderer.cpp
- Inspired by @scribam and @sunho commit but totaly changed
- based on scriban commit https://github.com/scribam/Vita3K/commit/4ca5c9328dc702dc3895c40f84bafb7d61239712  and refactored for more smart and logical, don't request any if with just using switch present
- fix regression see on  #1059
> Improve blending translation and fix font regression 

- vita3k/renderer/src/gl/renderer.cpp
- Fix shovel kinight color and render mirror
- Master
- PR
> Add color format U5U6U5_RGB

- vita3k/modules/SceCtrl/SceCtrl.cpp
>  SceCtrl: misc improvements

- vita3k/shader/src/translator/alu.cpp
Request by Blaze Blue, already approved by kd
> shader: Add Opcode ISUB16/ISUBU16.

- .github/workflows/c-cpp.yml
Addresses #985 
Merge https://github.com/Vita3K/ffmpeg-core/pull/2 first. I want to look at CI and see how it does with this new build under an older version of macOS (but it'll probably just have submodule issues).
> Fix for XCode 12

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Code from too old and difficult to merge pull request #796
> modules/SceLibKernel: sceKernelGetThreadExitStatus implemented

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/translator/ialu.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- vita3k/shader/src/usse_utilities.cpp
Improve rendering of Virtua Tennis 4
> shader: Fix typos and implement high/low modifier for IMAD32

- vita3k/kernel/src/thread/thread.cpp
Adds error check and error code for it
> kernel: Check if a thread is already running when starting it

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Didn't check carefully enough during my review of PR #1085, time to fix it
> SceLibKernel: Fix sceKernelGetThreadExitStatus

- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/interface.cpp
- vita3k/io/include/io/state.h
- vita3k/modules/SceNpCommon/SceNpCommon.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- some fix and split other pr for more small change on other
> gui: some fix/reworks.

- vita3k/config/include/config/config.h
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
Refactor config user and user management.
- add avatar
- move user name,  theme content id, start screen type, start screen path and backgrounds inside user xml file user id folder
- add struct for User with using std::map
- User xml
- Users list
- New User 
- Edit  User
- Delete User
> Bankai refactor user management

- vita3k/CMakeLists.txt
- vita3k/config/include/config/config.h
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/welcome_dialog.cpp
- Add welcome dialog with some information for first boot and new user.
-  gui/app context menu: fix glitch on render.
- emu: bump on version 0.1.2
> add welcome dialog on first boot and more.

- vita3k/modules/SceSysmem/SceSysmem.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/alu.cpp
- fix regressionon some game during check freeze memory size, credit @frangarcj 
-  improve render on some game with improve shader by @pent0.
- fix water effect
> Shader and fix free memrory

- vita3k/config/include/config/state.h
Fix crash on startup when a setting not found in config.yml
Also fix crash when new setting is added.
> config:state Fix crash on startup when a setting not found in config.yml

- .github/workflows/c-cpp.yml
I hope this one will be the last one
> ci: Attempt to fix move-tag job (2)

- vita3k/host/src/load_self.cpp
- vita3k/modules/module_parent.cpp
- vita3k/util/include/util/arm.h
- vita3k/util/src/util.cpp
- module: Patch imports when modules are loaded later
> module: Patch imports when modules are loaded later

- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/user_management.cpp
- Add french, italian, rusian, Spanish, korean, japanase, chinese trad and simpl language for some things in gui
- french
- Rusian
> init support some languague in gui

- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
- fix clock size
- Add clock for can select 24 or 12h mode, so with using AM/PM or just 24h
- add date format select
- start screen
- Setting:
> gui/settings: add date and clock format 

- vita3k/kernel/include/kernel/types.h
- Add missing field `changeCpuCount`
- Update fields types
> kernel: Update SceKernelThreadInfo structure

- vita3k/modules/SceGxm/SceGxm.cpp
thx to pent0 for help
- fix black screen on  some game
- fix madoka game blackscreen
- fix first logo/msg
> modules/SceGxm: Implement both DefaultUniformBuffer

- vita3k/modules/SceDisplay/SceDisplay.cpp
- vita3k/modules/SceDisplay/SceDisplay.h
check if 3 value resolution is invalide
> Add check resolution error

- vita3k/modules/SceGxm/SceGxm.cpp
reqsuest by wipeout 2048
- modules/SceGxm: implement both StateSetAllUniformBuffers.
> modules/SceGxm: implement both PrecomputedStateSetAllUniformBuffers.

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
create this pr for some game can get playable/ingame with bypass video player support not totally working.
- get akiba/diva f and more to ingame
> gui/settings dialog: Add option for disable video player.

- vita3k/kernel/include/kernel/state.h
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
This help to break throught dead pause on video player. It's very rough code and need to be restructured and reformatted. But it can help with big problem in many games.
I'm asking for help for good realisation of running callbacks. Now I can't pass more when 3 parameters and put garbage in threads list. Any advices how to realyse it right.
> AvPlayer event callback

- vita3k/modules/SceFiber/SceFiber.cpp
credit code by @sunho, with other dev i thinks it works fine with all app using it, and can good merged on master, add note inside if more check is needed later
> modules/SceFiber: implement _sceFiberAttachContextAnd(Run/switch)

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/texture.cpp
thx @kd-11 for help, i hop is good
- Implement both on GXM  and set glTexParameterf in gl/texture .
> implement LodBias and LodMin

- vita3k/modules/SceGxm/SceGxm.cpp
* Implement sceGxmProgramIsEquivalent
> gxm: Implement sceGxmProgramIsEquivalent

- vita3k/renderer/src/gl/sync_state.cpp
- fix or improve render on some game
-  Improve body and fix some transparante on Ff10 
- fix yellow screen
- fix character texture
> gl/sync_state: fix sync_cull.

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- refactor pkg install fr more close psvita result
- can now so showed all charachter like jap and other, so fix ???? issue on text
(yes is very old works)
> gui: refactor pkg install.

- vita3k/gxm/CMakeLists.txt
- vita3k/gxm/include/gxm/functions.h
- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/stream.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/include/renderer/gl/types.h
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/load_shaders.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/shader/include/shader/spirv_recompiler.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- Fix divekick and durara rendering
> Implement instancing and handle stripped symbols shader

- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/src/cpu.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Two functions for stack alloc / free inside hle modules
> cpu: use stack allocation

- vita3k/kernel/include/kernel/state.h
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
Clean code which is not used after @sunho callback pull request #1155
> modules/AvPlayer: clean unused code

- vita3k/renderer/src/gl/load_shaders.cpp
- is for can using title id folder for pre-compiler shader, prepare for future and i request it for some test here
> renderer/load_shaders: using title id folder for load exist shaders.

- vita3k/config/src/config.cpp
- vita3k/host/include/host/functions.h
- vita3k/interface.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- using better smart for separate argument with using simple split function but with split with ", " for separate argument.
> modules/SceAppMgr: reworks split in interface.

- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/trophy_unlocked.cpp
- notification for App installed
> gui: add indicator lang.

- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- fix position for app size icon
- fix typo on config.
> small fix.

- vita3k/kernel/include/kernel/thread/sync_primitives.h
- vita3k/kernel/include/kernel/types.h
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- based on other pr with only on finished works for merge ready
> modules/Sce(LibKernel/Threadmgr): Implement some event function.

- vita3k/shader/src/spirv_recompiler.cpp
> shader: Implement POINTCOORD

- vita3k/shader/src/spirv_recompiler.cpp
Fix dbz and ffX-2 shader crash, and probably more
> shader: expand out register bank size.

- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
Split other pr for can set this change only on this commit/pr 
- for can using date fomat like already set on other part
> gui: Move Date on date format for all.

- vita3k/gui/src/app_selector.cpp
- Can allow application filter by region, for can show only app correspond zone selected
- for jap
- for commercial only
- for hombrew only
> app selector: Add app filter by region and by type:

- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- fix video playing on drive girl.
> modules/SceAvPlayer: Stub GetVideoDataEx.

- vita3k/app/src/app.cpp
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/include/host/state.h
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
split again notice pr for remove some change on other pr/commit
- add content id.
- refactor change and reset path for improve it.
- fix using app path for update history.
- refactor delete app icon
- fix name on app filter for japan.
> gui: some small fix/refactor

- vita3k/kernel/src/thread/thread.cpp
Fix unicorn crash when callback is called from callback and both callbacks use stack (change sp register)
> kernel: callback from callback fix

- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/trophy_collection.cpp
- Add some lang support on text in trophy collection
- in french
> gui/trophy collection: add some lang support.

- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/dialog/include/dialog/state.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/trophy_unlocked.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- Add some text on common lang
- Add month in small format
- some boutton
> gui/lang: add some common text.

- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/host/include/host/state.h
- vita3k/interface.cpp
- vita3k/main.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
using execv previously implemented for can using this.
- Add ability to can switch/exit  game,  for moment, and like for LoadExec, it restart emu.
> emu: add can switch/exit game.

- vita3k/host/src/load_self.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/types.h
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Sync with https://github.com/vitasdk/vita-headers/blob/d36629f6afde94a11024ca1bae8bf7d5f32d8060/include/psp2/kernel/modulemgr.h
> kernel: Update SceKernelSegmentInfo/SceKernelModuleInfo structures

- vita3k/shader/src/translator/alu.cpp
fix regression get crash shader
> shader/alu: Fix maximum bits allowed on decode_dest

- vita3k/gxm/src/textures.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/gl/texture_formats.cpp
> gxm: Improve cube textures

- lang/en.xml
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- vita3k/modules/SceNgsUser/SceNgs.cpp
- add ability can change some setting app by app.
- fix typo error on lang en.
> gui/settings dialog: Add custom config by apps.

- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
on some game, it give wrong path for video file, like also if video is inside archive, so get wrong path, with get so MC_INVALID, here code so extract data of video for write it inside cache folder for can normally open it.
- can fix video playing on some game like on angry bird stars wars, AOT and more
- fix also two compile warning. 
- on aot wing of freedom menu
- fix digimon to go ingame (video is skiped no idea why, some game like stane gate have this too
> modules/SceAvPlayer: Fix open video file if path is wrong.

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/src/scheduler.cpp
- Improve sound on very some game, also fix some video usm playing.
- Sound + video fixed on SAO lost song
- same for it
- some sound + video playing fixed
- fix sound on stardrew valley for can fix crash and get menu
- fix video playing + some sound too
- fix also crash for can get menu/ingame
- fix video playing + some sound and music in ingame/menu
- fix video playing + some sound, fix also music playing
And  on very more
> ngs/sheduler: fix some sound playing.

- vita3k/gui/src/live_area.cpp
- some game have demo mode, so get can using retail mode.
> gui/live area: enable can read retail live area version if exist.

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/private.h
- vita3k/host/CMakeLists.txt
- vita3k/host/include/host/app_util.h
- vita3k/host/include/host/functions.h
- vita3k/host/include/host/state.h
- vita3k/host/src/license.cpp
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- alow can unlock full game for game using this.
For moment, request drag and drop work.bin or zif key on window emu
- for coconut, drag drop work.bin
and so before
after
> modules/SceAppUtil: Implement AppParamGetInt.

- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/host/include/host/pkg.h
- vita3k/host/src/license.cpp
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
-  main & live area: fix crash on live area/hb with check license only for ps app.
- fix ime dialog string sended.
- fix one typo for license install dialog.
- remove double code on license.
> gui: few small fix.

- vita3k/gxm/include/gxm/types.h
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/include/renderer/gl/types.h
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/renderer.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/shader/include/shader/usse_translator_entry.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- fix black screen or flashing on some game.
- fix black screen for Asphalt ingame render
- fix UNCHARTED black screen, ah no wait is other game😎  😂 
- fix flashing screen/.hide render on some game like it
- fix Super Stardust logo Black Screen 
- fix black screen on ingame render for Call of Duty, it request transfert copy
> gxm: Handle front/back fragment disable.

- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/kernel/src/thread/thread.cpp
Fixes to love ru visual novel game booting.
> Fix eventflag wait

- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/gxp.cpp
- vita3k/io/src/io.cpp
- vita3k/kernel/src/thread/thread.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/shader/include/shader/usse_translator_types.h
- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
Not sure in "app/screen_render: add stensil clear before draw"
and "TLS init fix" but tls init fix is better then before (but may be still buggy)
> Some very minor refactorings, improvements and compiler warnings fixes

- vita3k/shader/src/usse_utilities.cpp
- fix shader crash on god of war 1 & 2 for can get ingame on both
- fix other shader crash with fix generate shader all on atelier game, MS RC, Accel >World vs Sao and more
- God of war 1
- God of war 2
> Shader fix

- vita3k/gui/src/condvars_dialog.cpp
- vita3k/gui/src/eventflags_dialog.cpp
- vita3k/gui/src/mutexes_dialog.cpp
- vita3k/gui/src/semaphores_dialog.cpp
- vita3k/kernel/CMakeLists.txt
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/include/kernel/thread_data_queue.h
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- Fix cond var signal specific
- Add ThreadDataQueue class that replaces WaitingThreadQueue
- ThreadDataQueue class uses std::list for FIFO queue and std::multiset for priority queue
- Cleanly traverse waiting thread queue in event flag wait
> Sync primitives 1

- vita3k/app/src/app_init.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/ime.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/host/include/host/state.h
After have see some strange things, like font is set for scale on dpi but ,after divide on this dpi get so no scaled, i have so reworks it completely.
- settings dialog: fix lle kernel for custom config.
Arrow added in app selector/live area + texte centered on column
> gui: fix and refactor dpi scale/font scale.

- .gitmodules
- external/CMakeLists.txt
- vita3k/app/src/app_init.cpp
- vita3k/cpu/CMakeLists.txt
- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/include/cpu/dynarmic_cpu.h
- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/include/cpu/interface.h
- vita3k/cpu/include/cpu/state.h
- vita3k/cpu/include/cpu/unicorn_cpu.h
- vita3k/cpu/src/cpu.cpp
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
- vita3k/kernel/include/kernel/thread/thread_functions.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread/thread.cpp
- vita3k/mem/include/mem/state.h
- vita3k/mem/src/mem.cpp
- vita3k/modules/SceFiber/SceFiber.cpp
- vita3k/modules/SceFiber/SceFiber.h
- vita3k/util/CMakeLists.txt
1. CPU Abstraction
2. More readable, accurate, intuitive thread execution loop
3. Eliminate weird unintuitive callback flag in thread function
4. Use halt instruction to return control to host
5. More accurate context
6. Correctly implement float registers
7. Add basic dynarmic cpu implementation
> Rework cpu & thread base to support dynarmic

- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/sync_primitives.h
- vita3k/kernel/include/kernel/types.h
- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/kernel/src/thread/thread.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- Implement basic functionalities of MsgPipe
I haven't really verified the implementation. Needs some testing.
> kernel: Implement MsgPipe

- vita3k/gui/src/live_area.cpp
- fix stupid fail on my preview pr, fix text big size if app using default size value for texte
| Before | After |
| --- | --- |
| <img  src="https://user-images.githubusercontent.com/5261759/117029503-037b9200-acff-11eb-860c-a5ab3ef0942e.png"> | <img src="https://user-images.githubusercontent.com/5261759/117029424-ea72e100-acfe-11eb-955e-b706c13b0ea5.png"> |
> gui/live area: fix font size of texte.

- .github/workflows/c-cpp.yml
For outsiders not confusing about it
> ci/workflows: Add note about release date

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/interface.cpp
stupid fail lol 
- Add license path for open/delete in app context menu
> gui/license install dialog: fix typo for rif file.

- external/CMakeLists.txt
Now folder shows up like this.
> Group external projects

- vita3k/kernel/src/thread/thread.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Fix regression in Dungeon Hunter: Alliance
> kernel: Add null checks

- vita3k/modules/SceNgsUser/SceNgs.cpp
asked by tester, and i have try found where is probleme also recently.
> SceNgs: fix crash if it is disable.

- vita3k/shader/src/usse_utilities.cpp
- fix regression black render on Downwell
> shader: Fix int to float reinterpret casting missing cases.

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/src/load_self.cpp
- vita3k/host/src/sce_utils.cpp
- vita3k/util/include/util/log.h
Dump elfs by turning on "Elf dump" in debugger setting dialog. Elfs contain relocated code.
> Add elf dumping

- vita3k/kernel/src/thread/sync_primitives.cpp
- vita3k/modules/SceCodecEngine/SceCodecEngineUser.cpp
This was causing race condition in gravity rush. The specified signal was not respected well.
> Fix semaphore

- vita3k/config/include/config/state.h
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/kernel/src/kernel.cpp
- vita3k/main.cpp
- Simply add possibility change cpu backend for custom config.
- remove set value in kernel, value is already set in app init, so no need re set again.
> settings_dialog: Add support cpu backend for custom config.

- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- fix search link with correct title name.
- fix savee config for ngs and video playing in global.
- little move column for no hide arrow in trophy collections.
> gui: fix some small things.

- external/CMakeLists.txt
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/include/cpu/impl/dynarmic_cpu.h
- vita3k/cpu/src/cpu.cpp
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/functions.h
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
For debugging purposes, CPU optimizations can be disabled.
> Configuration option to enable/disable CPU JIT optimizations

- vita3k/gui/src/settings_dialog.cpp
- fox can fix height size too big for Core tab.
- Core
- CPU
> gui/settings dialog: Add cpu tab.

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
I want to get as far away as possible from unicorn. Yet, fallback is still useful.
> Fix unicorn fallback

- vita3k/modules/SceGxm/SceGxm.cpp
- fix black screen for Yakuza game serie
> modules/SceGxm: Fix ProgramFindParameterBySemantic implementation.

- vita3k/interface.cpp
- fix my old fail with confounding this both value.
> gui: fix toggle gui state after change controller mapping.

- vita3k/renderer/src/gl/renderer.cpp
- Add color format SCE_GXM_COLOR_FORMAT_U16_R request by littlebigplanet.
> renderer: Add color format U16_R.

- vita3k/shader/src/spirv_recompiler.cpp
This fixes atlier black background flowers.
> shader: Disable early fragment test in non-nativecolor shaders

- vita3k/shader/src/translator/data.cpp
> shader/vpck: Correct no cycling

- vita3k/shader/src/usse_utilities.cpp
Fix  texture on environement in gravity rush
> shader: Eliminate bias for normalize

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_disasm.cpp
- vita3k/shader/src/usse_utilities.cpp
These fix atlier partial character render.
VTSTMSK implementation is fragile in edge cases and repeat mode is not implemented yet. I'll pr a complete version shortly.
> Implement vtstmsk & fix vdual swizzle

- vita3k/gui/src/settings_dialog.cpp
I have totaly forget move it in other child after create this new tab
- enable gui state on open settings dialog
> custom config: move cpu settings in cpu child.

- tools/usse-decoder-gen/autogen.py
- tools/usse-decoder-gen/grammar.yaml
- vita3k/renderer/include/renderer/types.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/texture.cpp
- vita3k/shader/src/usse_translator_entry.cpp
Should fix another game display unimplemented sop3 before. 
Rayman Legends still black screen, investigating later.
> Attempt to fix Rayman Legends black

- vita3k/config/include/config/config.h
- vita3k/config/src/config.cpp
- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/src/cpu.cpp
- vita3k/gdbstub/src/gdb.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/src/load_self.cpp
- vita3k/kernel/include/kernel/cpu_protocol.h
- vita3k/kernel/include/kernel/debugger.h
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/cpu_protocol.cpp
- vita3k/kernel/src/debugger.cpp
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/sync_primitives.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
Some rtc functions should return time since process started.
> Debugger improvement + rtc fix

- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/ngs/include/ngs/modules/atrac9.h
- vita3k/ngs/include/ngs/modules/equalizer.h
- vita3k/ngs/include/ngs/modules/master.h
- vita3k/ngs/include/ngs/modules/null.h
- vita3k/ngs/include/ngs/modules/passthrough.h
- vita3k/ngs/include/ngs/modules/player.h
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/equalizer.cpp
- vita3k/ngs/src/modules/master.cpp
- vita3k/ngs/src/modules/null.cpp
- vita3k/ngs/src/modules/passthrough.cpp
- vita3k/ngs/src/modules/player.cpp
- vita3k/ngs/src/scheduler.cpp
This fixes the hang in saenai chapter 2.
> Transition state after ngs voice finished + random kernel fixes

- vita3k/gui/src/settings_dialog.cpp
show apply button only if app current run is same on this current custom dialog open.
- small refactor of set cpu backend
> settings dialog: using apply only for current running app.

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/include/cpu/functions.h
- vita3k/cpu/include/cpu/impl/dynarmic_cpu.h
- vita3k/cpu/include/cpu/impl/unicorn_cpu.h
- vita3k/cpu/src/cpu.cpp
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgrCoredumpTime.cpp
- vita3k/modules/SceLibDbg/SceDbg.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- rename, move, and cleanify many kernel functions.
- remove thumb address check logic from load_context
- remove sp, lr parameters from init_cpu
- fill initial cpu context manually  from kernel module not relying on internal cpu implementation
> Refactor kernel

- vita3k/renderer/src/gl/renderer.cpp
Add color format U4U4U4U4_ARGB usd by time traveler.
> renderer: Add color format U4U4U4U4_ARGB.

- vita3k/kernel/src/thread.cpp
Fix regression in Bentley's Hackpack
> kernel: Fix waitthread regression

- vita3k/gdbstub/src/gdb.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/thread/thread_state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
> Implement stack arguments in guest function job

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/cpu/src/unicorn_cpu.cpp
- vita3k/modules/module_parent.cpp
> kernel: Fix cpsr regression

- vita3k/gui/src/app_selector.cpp
fix my proper mistake with forget it check value only one time and so after uisng same index, so it delete because found but after no re insert in first pos because for it already exist
- set limit to 14.
> gui/main menu bar: fix save app if already exist.

- vita3k/gui/src/license_install_dialog.cpp
- vita3k/host/include/host/state.h
- vita3k/host/src/license.cpp
split other part pr for this fix, with create value dedied on license.
> notice: fix notice update for addcont.

- vita3k/shader/src/spirv_recompiler.cpp
- Shader improvement for get improvement on color issue in gravity rush.
I thinks is good using it in maste,r no regression, only improvement on gravity rush for color issue in shader.
Using only one hack on vertex shader for body explosed
some color keep wrong but Very better and good buy red
- some color keep fluo/flashy but very more better
> shader: Support copy non aligned buffer

- vita3k/CMakeLists.txt
Just bump version on 0.1.3 after this all crazy improvement on this month.
> vita3k: bump version on 0.1.3.

- vita3k/app/include/app/functions.h
- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/interface.cpp
- vita3k/interface.h
- vita3k/main.cpp
- vita3k/util/include/util/overloaded.h
With this, for moment, you can just with open emu, drag & drop any one or few content, but that works also if you drag & drop one folder with inside 200 content like dlc/app
> install content folder and some refactor

- vita3k/kernel/include/kernel/state.h
- vita3k/modules/SceSysmem/SceSysmem.cpp
- vita3k/modules/SceSysmem/SceSysmem.h
- vita3k/modules/include/modules/library_init_list.inc
I need this to do unpredictable instruction testing.
> Implement sceKernelSyncVMDomain

- vita3k/mem/include/mem/allocator.h
- vita3k/mem/src/allocator.cpp
- vita3k/mem/src/mem.cpp
- vita3k/mem/tests/allocator_tests.cpp
Fix allocate_at and some bugs in edge cases
> Fix memory allocator

- vita3k/mem/include/mem/functions.h
- vita3k/mem/src/mem.cpp
- vita3k/renderer/include/renderer/functions.h
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/texture_cache.cpp
- vita3k/renderer/src/texture_format.cpp
Add validity check to prevent invalid access.
> Fix random texture cache crash

- vita3k/gui/src/settings_dialog.cpp
fix title writed ????? in debug build with using custom config.
remove old code useless.
> setting dialog: fix title for custom config in debug.

- vita3k/interface.cpp
fix my fail, totaly forget addcont request create 2 directories and no one
> interface: fix copy directories for addcont content.

- vita3k/gui/src/information_bar.cpp
Smal reworks after see on install contents can get same second epoch if is small content and so that causing some issue with push id.
- using millisecond for no can get double same value causing problem.
- using app icon if is available when no found content icon.
> notice: small refactor for time and icon.

- vita3k/gui/src/settings.cpp
-  Add content id for theme selected in information.
Also, i see some wrong things on position for text and button and on text wrapper, (text go outside window)  
- little clean old code no needed.
> settings: Add content id on theme information.

- vita3k/gui/src/settings.cpp
is same like for app list
Is very useful for can scroll without wheel, without mouse, iwht just keyoard and click on arrow
> gui/settings: add arrow for scroll in theme list.

- lang/fr.xml
- lang/it.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/live_area.cpp
thx @Croden1999 for help for both chinese languague
> lang: update some missing string.

- vita3k/host/src/license.cpp
- vita3k/host/src/pkg.cpp
- vita3k/interface.cpp
- also prevent crash if try copy same license file.
> interface: fix patch install.

- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
PCSE01332 [London Detective Mysteria Demo] can go ingame with this change
> modules/SceAvPlayer: returns false when sceAvPlayerIsActive is called with an invalid handle

- vita3k/ctrl/include/ctrl/state.h
- vita3k/main.cpp
- vita3k/modules/SceCtrl/SceCtrl.cpp
Fix regression on rumble for xinput and add rumble suport on DS4 and DS
thx @german77 for help
> input: fix rumble support.

- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/gxp.cpp
- vita3k/shader/src/gxp_parser.cpp
Also tidied up get_fragment_inputs.
> Name last missing fields in SceGxmProgram

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/welcome_dialog.cpp
refactor code for using only one function for all
fix https://github.com/Vita3K/Vita3K/issues/1423
- fix open folder when using space.
> gui: refactor open path.

- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/user_management.cpp
Fix hang on first boot for create apps cache.
- gui: refactor create user apps cache.
- user management: fix hide button back when user no init.
> gui: refactor create user apps cache.

- vita3k/gui/src/trophy_collection.cpp
> trophy collection: fix one translate string missing.

- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/pt-br.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/trophy_collection.cpp
fix some wrong place caused by bad format on xml file
credit to @Croden1999 for have founded this
inspired by #1439 with set in in proper without broken xml file
> lang: fix wrong format for double line string.

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/live_area.cpp
for fix ch/zh used in live area template, have different name compare translate gui.
thx to @sunho & @pent0 for some help :)
> live area: refactor user lang variable.

- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings_dialog.cpp
It's a lot easier to read now. I've also added a tooltip for one of the sliders in GUI. I'd like to add more but some of them I'm not entirely sure of their functions.
> Clean up English, grammar and add tooltip

- vita3k/kernel/src/sync_primitives.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/usse_utilities.cpp
I don't have a fancy name no more
The third commit still awaits for conformation from sunho
> Some small fixes

- vita3k/cpu/include/cpu/common.h
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- vita3k/renderer/src/gl/draw.cpp
I'm not sure if I fix this warnings properly, but original code looks strange for me.
@sunho please, check this. The most strange moment for me is float registers in Dynarmic and Unicorn.
> Warning fixes

- vita3k/config/include/config/config.h
- vita3k/kernel/include/kernel/types.h
- vita3k/modules/CMakeLists.txt
- vita3k/modules/SceKernelModulemgr/SceModulemgr.cpp
- vita3k/modules/SceKernelModulemgr/SceModulemgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceShellSvc/SceShellSvc.cpp
- vita3k/modules/SceShellSvc/SceShellSvc.h
- vita3k/nids/include/nids/nids.inc
- request by some unity game.
- get game more boot.
- modules: register nid and function of SceShellSvc libary.
- with my sysmem revert pr
> modules/SceKernelModulemgr: Implement sceKernelStartModule.

- vita3k/kernel/src/kernel.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Without deadlock fix almost all games stops almost immediately.
Sorry for lack of review in #1485 PR
> modules/SceKernelThreadMgr: fix mutex deadlock and clean code of callback implementation

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- vita3k/main.cpp
Update sdl on stable 2.0.0.16.
- Add support of Nintendo Switch controller.
- add player led position on DualSense (Depending order on controller detected
> external: update SDL to 2.0.16

- vita3k/modules/SceGxm/SceGxm.cpp
fix print double texture, fix flickering.
> modules/SceGxm: Improve sceGxmMidSceneFlush.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/texture_format.cpp
i split stuff of @pent0 with is already ready for master, other need more stuff
> renderer: some few fix ready

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/include/ngs/modules/atrac9.h
- vita3k/ngs/include/ngs/modules/player.h
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/player.cpp
implement function used by very some game for can set auddio effect (DSP Effect)
- fix sound missing on Metal Gear Solid 2 HD Menu (Need fix black screen on video and menu now  😂, it crash on start ingame )
thx @pent0  for time and explain
> modules/SceNgs: implement sceNgsVoiceSetParamsBlock.

- vita3k/shader/src/translator/branch_cond.cpp
> shader: Correct src2_vscomp apply condition

- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_utilities.cpp
- fix black and with color on Gintama
> shader: Try correct address of non-fetch load/store.

- vita3k/features/include/features/state.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- persona 4 limbo background no longer blocky.
> renderer: fix interlock missing.

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
#about: 
- move cache of apps list insit pref path ux0/temp, fix problem when you have diferent folder of exe.
> gui: move apps cache inside pref path.

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/themes.cpp
- Start refactor my old code for move variable inside struct and enum.
- get more clear with this and with set value default for all for not set double code of set default value.
> gui/themes: start move variable inside struct and enum.

- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy_collection.cpp
- fix little fail on Date Layout.
- move DateTime in enum too.
> gui: move DateTime in enum.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/include/renderer/texture_cache_state.h
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/texture.cpp
- vita3k/renderer/src/texture_cache.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/texture.cpp
- first setp on cube texture support.
> modules/SceGxm: Add first step cube texture support.

- vita3k/renderer/src/batch.cpp
- vita3k/threads/include/threads/queue.h
- Current code lock game in very low speed, have request some thinks and lot of testing. 
- should fix speed on game locked in low framespeed.
> renderer/batch: fix process queue of command list.

- vita3k/glutil/include/glutil/object_array.h
- vita3k/renderer/CMakeLists.txt
- vita3k/renderer/include/renderer/gl/surface_cache.h
- vita3k/renderer/include/renderer/gl/types.h
- vita3k/renderer/include/renderer/surface_cache.h
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/scene.cpp
- fix some game with ingame black screen or with one things hide render 
- Accel world vs SAO
- ben 10 
- blue reflection
- all atelier can already go ingame
- wipeout 2048 menu
> Implement surface cache

- external/CMakeLists.txt
> Fix Linux CI build issue related to libatrac9

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- add Automatic & Manual mode
-  fix stupid fail forget inside sysmodule with look cfg and no crurent config 🤦 
- refactor is enable module for no repeat code
- change automatic module, ssl/https is no working
> config: Add modules mode Auto & Manual.

- vita3k/CMakeLists.txt
- fix detection for build download in github.
> vita3k: fix master detection from github action.

- vita3k/renderer/src/gl/sync_state.cpp
Split WIP PR #1462 with things already ready for master
- fix black screen on some game like Joe danger
> renderer: correct untyped attribute check

- vita3k/host/src/pkg.cpp
- vita3k/interface.h
- vita3k/io/include/io/filesystem.h
- update psvpfstools for fix compile in linux spoted by @hobyst
- update few file for fix compile inside project.
> external: update psvpfstools.

- .github/workflows/c-cpp.yml
Update release date on each new release
> GHA: Update release date

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- vita3k/ctrl/include/ctrl/functions.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/modules/SceCtrl/SceCtrl.cpp
Update sdl to 2.0.18
- move get type from name to type get.
- remove one things no needed.
thx agan tyo @qurious-pixel  for help to linux build again
> external: update sdl to 2.0.18

- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/gui.cpp
- vita3k/main.cpp
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/gl/draw.cpp
- sugested and based on idea by @1whatleytay  after see is not possible display in real time compiling shaders message
- display in down left corner message for said have compiled one/few shaders.
- delay for display dialog is 2 sec.
> gui: display draw shader compiled.

- .github/workflows/c-cpp.yml
> update TAG name

- CMakeLists.txt
deletes a t, solving the typo kekW
> vita3k: Fix typo on CMakeLists.txt

- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
This is the second part of fixing compilation problems in the Arch AUR, turns out that there were more errors than the string literal one, they look to be the same error as before but in different places, they do make sense tho, hopefully this is the last one. If possible i will try to get ownership of it if its a PKGBUILD error, but in the meantime, we should fix these inconsistent strings of the gui
> vita3k: Fix compilation errors on the Arch AUR

- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_unlocked.cpp
Probably last batch of compilation errors from the arch aur, i checked every single line that uses ImGui for string literals and everything seems fine now. This time there were only 2, that's a good sign c:
* i don't want to make more PRs about this anymore, it feels scuffed
> vita3k: Fix next batch of compilation errors on AUR

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/main.cpp
- vita3k/renderer/include/renderer/gl/functions.h
- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/load_shaders.cpp
- add option for can disable load and precompile shaders cache, can help debuger/developer if no want clean all time shader cache before test code change 👌
> settings dialog: Add option for can disable pre-compile shaders cache.

- vita3k/modules/ScePgf/ScePgf.cpp
* Add function parameters for the module ScePgf
> ScePgf: Implement function params

- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
Cleans up and abstracts some ranged-for loops for their standard library equivalent.
Happy to condense / squash into one commit. :smile_cat: 
Currently PR is in this commit form to show changeset history (before squash / merge).
> gui: Prefer standard library algorithms

- vita3k/io/src/io.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
should fix crash when save data try delete folder.
> modules/SceAppUtil: fix delete savedata when try delete folder.

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/interface.cpp
thx to @iWumboUWumbo2 for detect issue in very special case.
fix crash on very special case and fix good order for no run 2 time init home
> gui: fix boot of init home.

- vita3k/app/src/app.cpp
- vita3k/config/include/config/config.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/host/include/host/state.h
- vita3k/main.cpp
- add avg, min abd max fps and line for statistic of fps
> gui: add avg and max value with statistic of fps.

- vita3k/gui/src/user_management.cpp
- fix issue reported by few user.
> gui/user management: fix init avatar when path is unicode.

- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_selector.cpp
- vita3k/gui/src/welcome_dialog.cpp
- Add developers and contributors list.
- delete patreon outdated
- little refactor
> gui/about dialog: Add developers and contributors list.

- lang/ko.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/initial_setup.cpp
> gui/initial setup: fix some string.

- .gitmodules
- external/CMakeLists.txt
- vita3k/codec/include/codec/state.h
- vita3k/ngs/CMakeLists.txt
- vita3k/ngs/include/ngs/dsp/playback_rate.h
- vita3k/ngs/include/ngs/modules/player.h
- vita3k/ngs/src/dsp/playback_rate.cpp
- vita3k/ngs/src/modules/player.cpp
Implement playback rate scaling
> codec & ngs: Implement playback rate scaling

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/interface.cpp
- vita3k/interface.h
- vita3k/main.cpp
- can install inside one zip App/Addcont/path etc in one time.
- archive of nonpdrm contents
- achive of custom theme
> gui/archive install dialog: add support of multiple install content.

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/atrac9.cpp
- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/player.cpp
Fix ngs crash on ar nosurge game.
Also fix a compiler warning
> ngs/player: fix ngs crash and move outpout format in short for atrac9

- vita3k/codec/src/pcm.cpp
fix ngs error in RIDGE RACER and other games, which use adpcm codec
> codec/pcm: fix intermediate buffer size calculation for adpcm decoder

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/host/include/host/functions.h
- vita3k/host/src/pkg.cpp
- vita3k/host/src/sfo.cpp
- vita3k/interface.cpp
- add support of path app, using same method of  repatch for now
> add patch support

- vita3k/gui/src/settings.cpp
Remove space contourn popup select, get better result.
> settings: improve dialog selet lang/time format.

- vita3k/modules/SceGxm/SceGxm.cpp
Also implement sceGxmShaderPatcherSetUserData
Callbacks usage is not the same as in original module, many more callbacks should be used.
Fix crash after first door in ar nosurge
> modules/SceGxm: use host callbacks to alloc mem in ShaderPatcher.

- vita3k/io/src/io.cpp
- vita3k/io/src/state_functions.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- fix some game in boot.
- nothing to menu
- nothing to ingame
- nothing to ingame
> io/stat file: Increment size of value, with using _wstati64.

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/user_management.cpp
- vita3k/lang/include/lang/state.h
- thx Mr. @Zangetsu38 help me.
- this is before pull request [#1627](https://github.com/Vita3K/Vita3K/pull/1627).
> gui/lang: update user management lang string.

- vita3k/gui/src/gui.cpp
- vita3k/lang/src/lang.cpp
- fix title of ninja gaiden
- master have ?
> gui/font: add glyph of Greek and Coptic.

- tools/usse-decoder-gen/grammar.yaml
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- implement LIMM.
- fix Diva X hair missing
- fix DIva F texture of environment missing
> shader: Implement LIMM

- vita3k/cpu/src/unicorn_cpu.cpp
- vita3k/gdbstub/src/gdb.cpp
- vita3k/glutil/include/glutil/gl.h
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/themes.cpp
- vita3k/host/src/sfo.cpp
- vita3k/mem/include/mem/mempool.h
- vita3k/mem/include/mem/ptr.h
- vita3k/mem/src/allocator.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/module_parent.cpp
- vita3k/np/src/trophy/context.cpp
- vita3k/renderer/src/gl/draw.cpp
- vita3k/shader/src/translator/branch_cond.cpp
I fix some compiler warnings (and one very annoying) and some minor and almost impossible errors
> fix compiler warnings, clean code a little

- vita3k/shader/include/shader/usse_types.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/ialu.cpp
- vita3k/shader/src/translator/utils.cpp
- vita3k/shader/src/usse_disasm.cpp
- vita3k/shader/src/usse_utilities.cpp
Minor fixes to `shader/`. See individual commits.
> shader: minor fixes

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/branch_cond.cpp
- vita3k/shader/src/usse_utilities.cpp
- fix vertex explos in gravity rush
> shader: fix vertex explos on gravity rush

- vita3k/gui/src/settings_dialog.cpp
- Add buton for can clean all shaders cache and log in one click.
> gui/settings dialog: Add buttons for can clean shaders cache/log.

- vita3k/shader/src/usse_utilities.cpp
- For Gravity rush texture (japan studio/skin/cloth)
> shader: Fix normalize signed type.

- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
- vita3k/ngs/src/ngs.cpp
Fix crashes on some games, using thread local storage in SceGxmShaderPatcher callbacks
> kernel\thread, modules: fix TLS in callback calls

- vita3k/kernel/include/kernel/callback.h
- vita3k/kernel/src/callback.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Try to fix callback execution
run_guest_function of thread shouldn't be called in the hle handler of that thread.
> kernel: Fix callback execution

- vita3k/display/include/display/functions.h
- vita3k/display/include/display/state.h
- vita3k/display/src/display.cpp
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceDisplay/SceDisplay.cpp
- implement both unction registervblankcallback.
- add support of cb vblank function.
- refactor vblank_sync_thread
> modules/SceDisplay:  Implement (Un)RegisterVblankStartCallback.

- vita3k/display/src/display.cpp
- fix vblank count with incremental in anyframe
- fix Wipoeut/lego harry potter/etc... boot
> display: fix vblank count in vblank_sync_thread.

- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/translator/texture.cpp
> shader: Implement gradient LOD mode for smp.

- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/src/sync.cpp
- This fix durara, f1 2011, tearaway, ffx(2), knyt underground and more...
- playable again
- fix crash in boot and playable
- fix spam error and Go menu for first time without hack
- fix infinite wait and get ingame
> Fix notification value being passed as pointer instead of copy.

- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
Not sure if we need to use free or available :eyes: 
but this should be enough
> io: Add sceAppMgrGetDevInfo

- vita3k/renderer/src/sync.cpp
fix lost refresh render on all atelier serie, jet set radio, and more...
- get ingame corectly visible for first time
> renderer/sync: Fix sync wait not wait all

- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/texture.cpp
- vita3k/shader/src/usse_utilities.cpp
It looks like we update dependencies, so why not to update glslang and SPIRV-Cross.
It's not the last version of glslang, but it's last version I can make working here.
Changes are precision, discard and spirv-version (if version is newer, then spirv-cross does not emit global variables)
> Update version of SPIRV-Cross and glslang

- vita3k/modules/SceNpCommon/SceNpCommon.cpp
Fix PCSG00455 [Ar nosurge PLUS: Umareizuru Hoshi e Inoru Uta] (only the Japanese version)
Without stubbing this function, game freeze on start screen.
> modules/SceNpCommon: stub implementation of sceNpAuthCreateStartRequest

- vita3k/kernel/src/sync_primitives.cpp
`SCE_KERNEL_ATTR_TH_FIFO` is defined as `0x00000000U`, therefore `is_fifo` is always set to false, even when the bit corresponding to `SCE_KERNEL_ATTR_TH_PRIO` (`0x00002000U`) is set.
Moreover the way the thread queue for events is considered as a priority or fifo queue is different compared to what is done for semaphores and mutexes. This pull request changes the code so that it is done the same way.
I don't know if this fix improves the state of any game.
> kernel: Fix fifo event thread queue treated as a priority queue

- vita3k/codec/CMakeLists.txt
- vita3k/codec/include/codec/state.h
- vita3k/codec/src/aac.cpp
- vita3k/codec/src/decoder.cpp
- vita3k/codec/src/h264.cpp
- vita3k/codec/src/mjpeg.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
Fixes #805
Some other things I want to do in this PR:
> Start init Implement Aac for sceAudioDec

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/aac.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- fix rebase mistake for compuile build when aac is enable.
- Add two parameter from aac.
> modules/SceAudiodecUser: fix build when aac is enable.

- external/CMakeLists.txt
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- Add lock guard inside all mspace function, fix crash on mp4 lle.
> kernel: add mutex lock guard on mspace func.

- vita3k/gui/src/about_dialog.cpp
- Move @bookmist to dev list.
- Add @Croden1999, @Macdu, @xerpi  in contributor list
> gui/about dialog: Update developers and contributors list.

- vita3k/kernel/src/sync_primitives.cpp
Debug builds have been broken since #1496 was merged.
> kernel: fix debug build

- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
Fix small memory leak in SceAudiodec: handles are not removed from state->codecs[codec] when sceAudiodecDeleteDecoder is called.
> modules/SceAudiodec: fix small memory leak while deleting decoders

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/decoder.cpp
- vita3k/modules/SceVideodec/SceVideodecUser.cpp
- game request incrtement numOfOutput only when play frame success.
- fix black screen onvideo when first frame failed.
> modules/SceVideodec: increment numOfOutput only when success play frame.

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/aac.cpp
- vita3k/codec/src/atrac9.cpp
- vita3k/codec/src/decoder.cpp
- vita3k/codec/src/mp3.cpp
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/module/src/load_module.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- vita3k/modules/SceAvPlayer/SceAvPlayer.cpp
- modules/SceAudiodecUser: enable AAC codec.
- codec/aac: fix aac implement.
- enable lle of mp4 and avplayer in auto mode.
- delete obsolete setting.
- fix lbp video
- tales of serie
- wipeout
- PSBAR
and more....
> fix implement of aac and enable it.

- vita3k/mem/include/mem/functions.h
- vita3k/mem/include/mem/state.h
- vita3k/mem/include/mem/util.h
- vita3k/mem/src/mem.cpp
- vita3k/renderer/src/texture_cache.cpp
I start split graphics branch with commit already good for master 👌 
- mem: Refactoring protect functions.
- Add way to lock protection and unprotect a callback region.
> mem: Refactoring protect functions.

- vita3k/renderer/src/texture_format.cpp
Another split graphics ready for master
> renderer: Correct texture size of PVRT format.

- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
Along with PR #1727, this fixes sound effects and cutscene softlocks in Tales of Hearts R. This should fix audio in games using this function.
> modules/SceAudiodec: Implement sceAudiodecDecodeNFrames

- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/sync_primitives.h
- vita3k/kernel/src/sync_primitives.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Used by a few games like Tearaway or Killzone.
> kernel: Implement RWLock

- vita3k/modules/SceAudio/SceAudio.cpp
Implement `sceAudioOutGetAdopt` , `sceAudioOutGetRestSample` and  `sceAudioOutReleasePort`.
This fixes the fmv issues in God of War.
> modules/SceAudio: Implement SceAudio functions

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/modules/equalizer.cpp
- vita3k/ngs/src/ngs.cpp
- vita3k/ngs/src/scheduler.cpp
Implement `sceNgsVoiceSetPreset`, `sceNgsVoiceInit`, `sceNgsVoiceGetModuleBypass`, `sceNgsVoiceBypassModule`, `sceNgsVoiceSetFinishedCallback`.
> ngs: Implement new functions

- vita3k/ngs/CMakeLists.txt
- vita3k/ngs/include/ngs/definitions/scream.h
- vita3k/ngs/src/definitions/scream.cpp
- vita3k/ngs/src/ngs.cpp
- Is stuff of voice definition scream at9/player, get sound on more 200 300 game, juste nheed more check and veify it
https://user-images.githubusercontent.com/5261759/142975247-e9779aff-756f-4390-ac18-6fa55b0a6f13.mp4
https://www.youtube.com/watch?v=38ZSOHCSerI
> ngs: stub voice definition of Buss Scream(Player/At9).

- vita3k/host/include/host/app_util.h
- vita3k/io/src/io.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
Current code have big fail on open file, with can allow create file on write or append flag, only create flag can create file. 
modules/SceAppUtil: fix open file flag.
fix also one function why wrong flag set, and with fix bellow, can so finnaly said file no exist and return error.
> io: fix open file when create flag is not here.

- vita3k/io/src/io.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- small refactor on my recent stuff of safe memory
- io: clean code unneeded in open file.
> modules/SceAppUtil: small refactor of SafeMemory func.

- vita3k/shader/src/translator/ialu.cpp
- vita3k/shader/src/usse_utilities.cpp
fix compile shader erorr on some game using i16mad
> shader: Fix i16mad.

- vita3k/gxm/include/gxm/state.h
- vita3k/modules/SceGxm/SceGxm.cpp
- modules/SceGxm: Correct implement sceGxm(Un)MapMemory.
- fix calcule upload size on gxmSetUniformBuffers.
> modules/SceGxm: Correct implement sceGxm(Un)MapMemory.

- vita3k/shader/src/translator/alu.cpp
This fixes the graphical glitches in Tales of Hearts R:
> shader: Fix VMAD dest repeat

- vita3k/renderer/src/gl/surface_cache.cpp
- And add some glparam.
- should fix black screen of gravity rush.
> renderer/surface cache: move order of write surface stored.

- vita3k/shader/src/translator/alu.cpp
This fixes the graphics in Tales of Hearts.
> shader: Fix multipliers in SLMSI mode for vmad

- vita3k/touch/src/touch.cpp
Give a few improvements to `peek_touch`.
This allows Run Sackboy and Table Top Racing to go ingame, for some reason they don't like having a touch id set to 0.
> Touch: Give more accurate timestamp, number of buffer used and non-zero id

- vita3k/modules/SceSysmem/SceSysmem.cpp
It looks like the ps vita is more lenient than I thought it would be when passing what is supposed to be invalid arguments to  `sceKernelAllocMemBlock`, remove checks to take this into account.
This fixes regressions from #1784 in many games like Uncharted.
> modules/SceSysmem: Remove checks in sceKernelAllocMemBlock

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/include/ngs/scheduler.h
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/ngs.cpp
- vita3k/ngs/src/scheduler.cpp
Implement `sceNgsRackRelease` and `sceNgsSystemRelease`, also add some setup for `sceNgsSystemLock` and `sceNgsSystemUnlock` functions (not implemented).
This allows Catherine Full Body to go ingame.
> modules/SceNgsUser: Implement release functions

- vita3k/modules/SceNgsUser/SceNgs.cpp
- Add check when ngs is disable for fix crash.
> modules/SceNgs: Add missing check for voice and ngs disable option.

- vita3k/renderer/src/gl/surface_cache.cpp
When looking if a texture belongs to a surface, if no one is found in the cache let the texture cache handle it instead of creating a new surface only for it.
This fixes the random black textures that could happen in a few games like Tales of games.
A part of this pr is from #1770 .
> renderer: Do not return a surface handle when it is a texture

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
issue is now fixed, no needed anymore
> config: remove option disable AT9 decoder.

- vita3k/mem/src/mem.cpp
> mem: Try to allocate the guest memory at a fixed location

- lang/ru.xml
> Update Russian (100%)

- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/gl/surface_cache.cpp
Improve the support of raw textures in surface sync. This removes half of the opengl errors that happen when running Uncharted (the other half can't be removed without graphic regressions).
> renderer: More support for raw textures

- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
Implement `sceAudiodecPartlyDecode`.
This allows the 50 games which rely on libatrac to have sound.
> modules/SceAudiodec: Implement sceAudiodecPartlyDecode

- vita3k/modules/SceNpTrophy/SceNpTrophy.cpp
- should fix log of id for create context and for set notice of trophy.
> modules/SceNpTrophy: fix data of np com id when get overflow.

- vita3k/kernel/include/kernel/sync_primitives.h
- vita3k/kernel/src/sync_primitives.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.h
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- Add execute callback on all cb function.
> modules/SceLibKernel: add process callbacks on cb function.

- vita3k/app/src/app.cpp
Display the real internal resolution used by the game in the window title.
> app: Display real internal resolution in window title

- vita3k/gui/src/information_bar.cpp
- vita3k/shader/src/translator/alu.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/translator/special.cpp
- update fmt submodule on last tag verison 8.1.1
- should fix compile issue on some compiler
> external: update fmt to 8.1.1

- vita3k/gui/src/settings_dialog.cpp
I found some problems in here with the grammar in the configuration menu and it might need to be fixed
> vita3k: Fix settings grammar

- vita3k/renderer/src/gl/screen_render.cpp
Fix flashing yellow screen in Ar nosurge
> renderer/screen_render: improve save/restore OpenGL state is screen renderer

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/compile_shaders.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/interface.cpp
- vita3k/main.cpp
- add new devs and contributors.
- delete driver user of settings dialog.
- re set style in setting dialog of button and title.
- rename app selector to home screen like from vita.
- reduce size of button font in home screen.
- fix pos of window of  comping shaders.
- reduce size of font in app context menu.
- reduce size font of app context menu.
- in list
- in grid
> gui: Some small fix and refactor

- vita3k/display/CMakeLists.txt
- vita3k/display/include/display/functions.h
- vita3k/display/include/display/state.h
- vita3k/display/src/display.cpp
- vita3k/interface.cpp
- vita3k/modules/SceDisplay/SceDisplay.cpp
- vita3k/modules/SceTouch/SceTouch.cpp
- vita3k/touch/include/touch/functions.h
- vita3k/touch/src/touch.cpp
Improve the accuracy of the touch functions with regard to how they should behave on a real ps vita.
This should help games having issues with the touch screen.
> touch: Improve accuracy of SceTouch functions.

- vita3k/modules/SceGxm/SceGxm.cpp
Allocate the deferred command in the host memory instead of the guest memory which is too small (our commands are bigger than the one generated by the PS Vita). We just need to track where the command list are allocated in order to be able to free them when they are overwritten.
This allows Valkyria Revolution to go ingame and should fix the games displaying a VDM out of memory error.
> modules/SceGxm: Make deferred contexts use host memory

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/lang/include/lang/state.h
update lang strings for the Thophy Collection, and fixed missing lang strings part of the "CalcTextSize" position for the User Management, fix my mistake in [#1635](https://github.com/Vita3K/Vita3K/pull/1635), plz Mr. @Zangetsu38  review this pr again, thx a lot.
> gui/lang: Fix position and update lang strings.

- vita3k/app/src/app.cpp
- vita3k/gui/src/settings_dialog.cpp
- settings dialog: Improve and clean code of set AF.
delete some value not needed for init config.
fix set config of aniso and fxaa with using current config.
- app: set AF level used in title.
> settings dialog: Improve and clean code of set AF.

- vita3k/ngs/src/modules/atrac9.cpp
Some games send the atrac9 header along with the data, Vita3K needs to skip it in order not to crash.
This (partially) fixes the audio in Muramasa.
> ngs: Fix Atrac9 crash when data sent has header

- vita3k/shader/src/spirv_recompiler.cpp
Support of the `GL_EXT_shader_framebuffer_fetch` extension was completely broken. Fixing it allows all GPUs supporting this extension (i.e all Intel iGPUs) to work on games using blending (like Persona 4 dancing).
> shader: Fix support of LastFragData

- vita3k/app/src/app.cpp
> app: add backend render used in title bar.

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/src/gl/renderer.cpp
- settings dialog: add option for can disable v-sync.
should fix speed issue on lot game.
> settings dialog: add option for can disable v-sync.

- vita3k/CMakeLists.txt
- vita3k/script/update-linux.sh
- vita3k/script/update-windows.bat
- Add a batch to the root of the emulator folder to be able to download and automatically extract the new builds
Based of works of hiroshiyuri and reworked.
- linux
-windows
> vita3k: create batch for download and extract last build automatically.

- .github/workflows/c-cpp.yml
- vita3k/CMakeLists.txt
- vita3k/Vita3K.rc
- vita3k/resource.h
- Add info of build priority
- Add build count on release page
> Vita3k: Add version of file.

- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/pt-br.xml
- lang/ru.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/gui.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
Improve date format in other languages (e.g. ru, jp, ko, zh and ch), looks like same the PS Vita. The code should be checked to ensure that it correctly recognizes the correct date.
> gui: Improve date format.

- vita3k/gui/src/themes.cpp
- fix the ''Content Manager'' other themes missing icon.
> gui/theme: fix missing other themes icon.

- lang/en.xml
- lang/fr.xml
- vita3k/CMakeLists.txt
- vita3k/codec/src/pcm.cpp
- vita3k/config/include/config/version.h
- vita3k/config/src/version.cpp.in
- vita3k/gui/CMakeLists.txt
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- vita3k/script/update-linux.sh
- vita3k/script/update-windows.bat
- vita3k: Add vita3k update.
- Improvement of update script.
Special credit and thx to @qurious-pixel & @EXtremeExploit  for help on linux code
> vita3k: Add vita3k update.

- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- update lang strings for the pkg/archive Install dialog, Content Manager, Settings, the “Version” of Update History (i did not sort it) etc., some language are based on psvita, and also fix some lang.
- fixed the wrong strings in Settings.
- Content Manager
- Home Screen button
- Install Dialog
- Settings (Theme & Home Screen Background)
> gui/lang: Update more lang strings.

- lang/pt.xml
- vita3k/gui/src/pkg_install_dialog.cpp
my bad, plz Mr. @Zangetsu38 check it.
> pkg install dialog: fix the check log position.

- vita3k/shader/src/spirv_recompiler.cpp
Fix some errors in the spir-V generated code that I found while making the shaders work with Vulkan. SpirV-Cross is lenient enough not to care about it but I'm surprised the SpirV shaders were able to work in OpenGL.
> shader: Fix Spir-V validation errors

- vita3k/main.cpp
works on windows :+1: . tested and it works on linux
> vita3k: Check for admin privileges at startup

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
Improve some strings with reasonablity.
> gui/lang: improve some strings.

- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/settings.cpp
there is display "KB", is not display "KiB" in psvita, so i revert them.  #1971
> gui: revert display size.

- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/nl.xml
- lang/pt-br.xml
- lang/ru.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/controls_dialog.cpp
- vita3k/lang/include/lang/state.h
correct lang typo and translation, and also add the "Full Screen" tip in control dialog (someone need this). if someone need me change some things, i'll check it.
plz Mr. @Zangetsu38 check this code.
> gui/lang: correct lang typo and translation.

- lang/da.xml
- lang/es.xml
- lang/fi.xml
- lang/it.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- vita3k/lang/include/lang/state.h
here is finished this pr #2005 .
> lang: update translation.

- lang/en-gb.xml
my fault, i'am so sorry forgot it, plz Mr. @Zangetsu38 check it.
> lang: revert a small issue for lang.

- README.md
[`vita3k`](https://scoop.sh/#/apps?q=vita3k&s=0&d=1&o=true) is available in the games bucket in Scoop.
> readme: Add Scoop in download section

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
> libkernel: Fix crash on SceIoDevctl

- vita3k/app/src/app_init.cpp
should fix the complaint from #2029
> opengl: Update OpenGL version when it can't create context

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- CMakePresets.json
- building.md
Makes linking with Clang much faster.
> CMake: Use LLD linker with Clang

- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/vulkan/pipeline_cache.cpp
- vita3k/shader/src/spirv_recompiler.cpp
Assassin creeds 3 uses matrices as vertex attributes, which was previously not supported by the shader recompiler or the renderer.
Implement this feature, however I only implemented it for matrices with regformat enabled (which is the case for assassin creeds 3) as it is a bit harder to do so for fields which are not 32-bit wide.
> renderer, shader: Allow matrices to be passed as vertex attributes

- vita3k/renderer/src/vulkan/surface_cache.cpp
Games using a gbuffer (like uncharted), will read the normal computed using a texture with a 4 bytes (32-bit component) offset from the start of the surface. Implement it to correctly render lighting.
> renderer: Implement typeless copy with offset in vulkan

- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/settings_dialog.cpp
- settings dialog: fix typo of ngs option for custom config.
- perf overlay: fix hide overlay when menu bar enable.
> settings dialog: fix typo of ngs option for custom config.

- vita3k/kernel/src/sync_primitives.cpp
Lock the kernel mutex instead of the object mutex to prevent a race condition during sync object deletion.
Also, locking the object mutex during deletion is not wrong because of the use of shared ptrs and object destruction order inside a function, however they don't solve the underlying issue, so remove them.
This solves the possible random in littlebigplanet.
> kernel: Fix race conditions during sync object deletion

- vita3k/renderer/src/vulkan/screen_renderer.cpp
Some modifications to the vulkan screen renderer, this fixes screen resizing on Intel iGPUs (and hopefully AMD too).
Also don't render anything to the swapchain when the window is minimized. This fixes the crash that happens when minimizing the window on Vulkan.
> renderer/vulkan: Fix screen resizing and minimizing

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- vita3k/np/include/np/state.h
makes bitrip go ingame instead of intro
> psn: Add PSN State option

- vita3k/config/CMakeLists.txt
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/kernel/src/load_self.cpp
- vita3k/util/include/util/elf.h
- fix save psn status in config.
- small refactor dessign of network tab 
- fix some other format
> settings dialog: fix save PSN status.

- vita3k/config/include/config/state.h
- vita3k/modules/CMakeLists.txt
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- vita3k/modules/include/modules/tracy.h
I try to make universal macro, which can be used to log function parameters with tracy. Now this PR is only a demo, with one module as example.
> modules: Universal tracy macros (SceAudiodecUser as example)

- vita3k/config/include/config/state.h
- vita3k/modules/ScePower/ScePower.cpp
- vita3k/util/include/util/vector_utils.h
Also of adding ScePower, turn the available tracy list into a set so its always in order and add a missing include in vector_utils
> tracy: Implement ScePower

- vita3k/gui/src/firmware_install_dialog.cpp
tested by the nice people from nixpkgs
> gui: Fix crash when installing firmware

- lang/ru.xml
Looks like machine translation was used for ru. This commit updates it and fixes some typos.
> fix and update translation in ru.xml

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/lang/include/lang/state.h
improve some lang strings and format them, correcting zh/ch language translation, and also add the `Title ID` in app information (can find in devkit/testkit).
> gui/lang: improve some lang strings.

- vita3k/host/dialog/src/filesystem.cpp
Fixes #2120 (tested).
Also fix a dangling pointer issue.
> host: Handle correctly utf8 paths

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/compile_shaders.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
add lang strings for compile_shaders.cpp, and corrected small zh/ch translation.
> gui/lang: add lang strings for compile_shaders.cpp.

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/settings.cpp
- vita3k/lang/include/lang/state.h
fix a missing string of image in settings, plz Mr. @Zangetsu38 check it.
> gui/settings: fix a missing string of image

- vita3k/util/src/util.cpp
The float_to_half_AVX_F16C function had two issues:
- _mm256_load_ps requires the data to be aligned, however that was not necessarily the case
- This function would do out of bound writes if the size was not a multiple of 8
This PR fixes these issues.
> util: Fix float_to_half_AVX_F16C

- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix crash in Ar Nosurge using vulkan renderer
> renderer/vulkan/surface_cache: fix crash

- vita3k/config/include/config/state.h
- vita3k/modules/CMakeLists.txt
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/SceAtrac/SceAtrac.cpp
- vita3k/modules/SceAudio/SceAudio.cpp
- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- vita3k/modules/SceCtrl/SceCtrl.cpp
- vita3k/modules/SceHttp/SceHttp.cpp
- vita3k/modules/SceLibc/SceLibc.cpp
- vita3k/modules/ScePower/ScePower.cpp
- vita3k/modules/SceRtc/SceRtc.cpp
- vita3k/modules/SceSsl/SceSsl.cpp
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- vita3k/modules/SceTouch/SceTouch.cpp
- vita3k/renderer/CMakeLists.txt
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/scene.cpp
- vita3k/renderer/src/state_set.cpp
- vita3k/renderer/src/sync.cpp
- vita3k/util/CMakeLists.txt
- vita3k/util/include/util/tracy.h
had to add a new define specifically for commands, hope bookmists approves it and macdu the commands part
> renderer: Add tracy support to all commands

- vita3k/kernel/src/load_self.cpp
- vita3k/kernel/src/relocation.cpp
Update the code for relocation based on VitaSDK.
> kernel: Update and improve relocation code

- vita3k/modules/SceGxm/SceGxm.cpp
PR #2151 caused a regression as the code for going back to the beginning in a ring buffer had an issue: the last allocated uniform buffer could map to memory after the ring buffer and corrupt other gxm structures.
This should fix the regression in Soul sacrifice.
> modules/SceGxm: Fix out of bound write in ReserveDefaultUniformBuffer

- external/CMakeLists.txt
- vita3k/audio/src/audio.cpp
- vita3k/kernel/src/kernel.cpp
- vita3k/main.cpp
- vita3k/module/include/module/bridge.h
- vita3k/renderer/include/renderer/profile.h
- vita3k/shader/include/shader/profile.h
- vita3k/util/include/util/tracy.h
new tracy update looking lit frfr:fire:
> tracy: Update to v0.9

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/common_dialog.cpp
- vita3k/lang/include/lang/state.h
add lang in "Submit" button, and also revert "macOS" of the about and welcome dialog, plz Mr. @Zangetsu38 check it.
> gui/lang: update lang strings.

- vita3k/gui/src/app_context_menu.cpp
Makes it easy to create compatibility reports with copy and paste:sunglasses:
> gui: update copy app info

- vita3k/http/include/http/state.h
- vita3k/modules/SceHttp/SceHttp.cpp
> modules/SceHttp: fix memory errors in sceHttpUriParse

- vita3k/script/update-windows.bat
bump to v0.1.6 correct get update version. (windows)
> vita3k/updater: bump to v0.1.6

- vita3k/CMakeLists.txt
- vita3k/gui/src/vita3k_update.cpp
- vita3k/script/update-macos.sh
This will download `macos-latest.dmg` to user's home directory(a.k.a. `~/`) and try to update.
> vita3k/updater: Properly implement updater for macOS

- vita3k/gui/src/live_area.cpp
> gui: Fix help dialogue

- vita3k/gui/src/live_area.cpp
i am sorry, my fault, i ignored it, i should have check more.
> gui/live_area: fix a minor bug

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
- gui: move get modules list in boot emu.
should fix help dialog in live area for detect fw.
> gui: move get modules list in boot emu.

- vita3k/main.cpp
This may solve issues related to non-ASCII characters in paths.
> vita3k: Make sure pref_path is seen as utf8

- vita3k/gui/src/vita3k_update.cpp
- vita3k/script/update-windows.bat
As the title says it fixes the auto updater on Windows by starting the batch file on it's own process.
> vita3k updater: fix the auto updater on Windows

- vita3k/audio/src/impl/sdl_audio.cpp
> audio: Fix assert compilation error on debug

- vita3k/gui/src/vita3k_update.cpp
- vita3k/script/update-windows.bat
When I last time I wrote it it was 3 am so there was bound to be some mistake it worked fine on my local machine but now it doesn't work at all...
> Improve the Windows update script yet again.

- vita3k/gui/src/vita3k_update.cpp
- vita3k/script/update-windows.bat
> Revert "Improve the Windows update script yet again."

- vita3k/gui/src/vita3k_update.cpp
- vita3k/script/update-windows.bat
These commits broke the updater, revert them until it is fixed.
> updater: Revert commits related to updater

- vita3k/renderer/src/vulkan/renderer.cpp
Add (optional) support for the VK_EXT_global_priority to tell the GPU Vita3K should be considered as high priority. This may improve performance.
> renderer/vulkan: Add support for VK_EXT_global_priority

- vita3k/gui/src/app_context_menu.cpp
Macdu's advice helped me fix it.
Japanese and other languages(like chinese) can be handled.
> gui: Use SDL_OpenURL in search

- vita3k/compat/src/compat.cpp
- vita3k/gui/src/vita3k_update.cpp
- Add timeout 2 second for check version.
- fix error on download compat db when path have space.
- little reworks code for fix some strange issue and add check if command is successfully executed.
> compat: add timeout for check and download update.

- vita3k/CMakeLists.txt
- fix GIT_BRANCH and GIT_REPO value when is PR
> cmake: fix value of VITA3K_GIT_REV when is PR.

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- vita3k/CMakeLists.txt
- vita3k/gui/src/app_context_menu.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- lang: Add french for compatibility
- cmake: remove repetitive execute process for GIT_REPO.
> lang: Add french for compatibility & cmake clean

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
> gui: load compatibility db in background thread on app startup

- .gitmodules
- external/CMakeLists.txt
- vita3k/cpu/CMakeLists.txt
- vita3k/renderer/src/gl/draw.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/vulkan/scene.cpp
- vita3k/shader/include/shader/usse_utilities.h
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/special.cpp
- vita3k/shader/src/usse_translator_entry.cpp
- vita3k/shader/src/usse_utilities.cpp
Update many dependencies.
For each dependency, I choose the the latest release version with a tag. The exception being xxHash, which is still actively developed, but its last official release was 2 years ago. Given how much we use it, I think taking the latest version for better performance would be better.
I also forked and slightly modified the libAtrac9 dependency so that it is not required anymore to put it in its own dll.
Glslang had many breaking changes, so I'm putting it in its own commit.
> external: Update dependencies

- vita3k/compat/src/compat.cpp
- vita3k/config/include/config/config.h
- vita3k/gui/include/gui/functions.h
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/shader/src/usse_utilities.cpp
- gui: Add first message information replace log for android user.
is also better for other OS. vita3k updater: set init update inside thread, fix freeze in boot.
- vita3k updater: set init update inside thread, fix freeze in boot.
> gui: Add first info message replace log for android user.

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/compat/src/compat.cpp
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/lang/src/lang.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- [ang: fix forget change id of Compatibility State.
- compat: fix sort app after update database.
- fix format.
> lang: fix forget change id of Compatibility State.

- external/CMakeLists.txt
- vita3k/cpu/CMakeLists.txt
- vita3k/cpu/src/dynarmic_cpu.cpp
- vita3k/mem/src/mem.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/modules/SceLibc/SceLibc.cpp
- vita3k/util/src/instrset_detect.cpp
- vita3k/util/src/util.cpp
Backport some of the changes I made for the android version to the PC version.
With these changes, adding support for arm64 Linux, Macos and/or Windows should be quite straightforward. 
A lot of the content of this PR is similar to what @KhoraLee did in #2166.
> external, vita3k: Update dynarmic and add initial support for aarch64

- vita3k/compat/CMakeLists.txt
- vita3k/compat/include/compat/state.h
- vita3k/compat/src/compat.cpp
- vita3k/gui/include/gui/state.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- compat: move from curl and powershell to openssl.
should fix problem for some users.
> compat: move from curl and powershell to openssl.

- external/CMakeLists.txt
- vita3k/io/src/io.cpp
- vita3k/mem/src/mem.cpp
Adding macOS specific changes for aarch64 build.
Still need aarch64 binary of ffmpeg and psvpfstools's libtomcrypt.
> vita3k: Support building for aarch64 macOS

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/https/include/https/functions.h
- vita3k/https/src/https.cpp
- Add progress bar on download new build.
- https: Add check for null result from getaddrinfo when resolving host address.
should fix crash when internet is no available.
> vita3k update: Add progress bar on download new build.

- vita3k/renderer/src/vulkan/renderer.cpp
> Fix syntax error on debug build for addr align mem map

- vita3k/compat/src/compat.cpp
- vita3k/gui/src/gui.cpp
- vita3k/https/src/https.cpp
- https: Add check of file size dowloaded
- compat: smal improvement in log info.
- gui: no display dialog info when app already running.
- fix one mistake in pos of dialog info.
- move vita3k update init after init home, should fix transparency issue in boot when update is available.
> https: Add check of file size dowloaded and little more.

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/reinstall.cpp
- vita3k/lang/include/lang/state.h
> lang: Update language strings

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- gui: improve size and positon of some window for keep proportion.
fix window abd icon size deformed when when vita3k window is resized.
> gui: improve size and positon of some window for keep proportion.

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
Follow with https://github.com/Vita3K/Vita3K/pull/2399, please Mr.@Zangetsu38 review it.
> lang: Complements missing the 'nospace' lang

- vita3k/renderer/src/vulkan/renderer.cpp
Small fixes while creating a mapping:
- Make sure the buffer host address is page aligned when creating the buffer
- Between a memory that is only cached and another one only coherent, choose the one only cached.
> renderer/vulkan: small fixes when creating a mapping

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/gl/screen_render.h
- vita3k/renderer/include/renderer/gl/state.h
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/include/renderer/vulkan/screen_renderer.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/gl/renderer.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- vita3k/renderer/src/vulkan/screen_renderer.cpp
- settings dialog: Add option to allow disable linear filter in screen surface.
- config: fix options of using shaders cache.
Delete inside command line.
> gui/settings dialog: add option allow disable linear filter

- lang/en-gb.xml
- lang/en.xml
- lang/ja.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/lang/include/lang/state.h
Japanese update after a long time.
- update Japanese
- small fixes
> lang: update Japanese and small fix

- vita3k/util/src/util.cpp
I hope it should works correctly now. No problems with handled c++ exceptions.
> util: Fix log craches. Log unhandled C++ exceptions on all platforms

- vita3k/gui/src/vita3k_update.cpp
- Add author column on commit description.
> gui/vita3k update: Add author column in commit description list.

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/vita3k_update.cpp
- gui/app context menu: Fix url encoding when create compatibility issues.
should fix encoding url when title app contains (#, & or +).
> gui/app context menu: Fix url encoding when create compatibility issues.

- vita3k/gui/include/gui/state.h
- vita3k/gui/src/settings_dialog.cpp
> gui: Update LIST_SYS_LANG

- vita3k/app/src/app_init.cpp
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/welcome_dialog.cpp
- gui: Add more keep aspect ratio and scaling font.
should fix size of font in full screen.
- app/app init: enable calculate dpi for linux and windows only.
> gui: Add more keep aspect ratio andd scaling font.

- vita3k/https/src/https.cpp
- https: fix crash during a simultaneous call of init.
fix crash when call few instance in same time of init, like for update compat and check update on vita3K
> https: fix crash during a simultaneous call of init.

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/it.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/install dialog: Optimize text again
- lang: update other lang of vita3k_update
based on psvita lang and used psvita check again
Optimized #2432 , should be display failed install and check, please Mr.@Zangetsu38 check this code
> gui/install dialog: Optimize text again

- vita3k/io/src/io.cpp
Fios overlay paths are not standardized (app0 paths should start with app0:/), which leads to overlays not matching standardized paths later.
Fixing this allows killzone to get to the menu.
> io: Standardize path of overlays

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/settings.cpp
- vita3k/lang/include/lang/state.h
- gui/settings: fix theme selectable menu size.
update link and name of custom website.
> gui/settings: fix theme selectable menu size

- lang/en-gb.xml
- lang/en.xml
- lang/nl.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/perf_overlay.cpp
- vita3k/lang/include/lang/state.h
> gui/pref overlay: revert minor changes

- vita3k/script/update-macos.sh
> vita3k/updater: Fix broken updater script for macOS

- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/vita3k_update.cpp
- gui/vita3k update: fix run script of update when path have space.
- gui/live area: enable and correct value of frame for psmobile template.
- gui/home screen: fix sort app list for update compat db when user is not open.
> few small fix

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/ja.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/config/include/config/config.h
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/interface.cpp
- vita3k/lang/include/lang/state.h
* better align in controls_dialog and live area help page and more
* make GUI controls configurable
* some optimization and refactoring
> gui: better align in controls_dialog and live area help page and more

- vita3k/renderer/src/gl/color_formats.cpp
> renderer/ogl: Implement F16 base color format

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/ja.xml
- vita3k/gui/src/about_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/about dialog: Add first supporter.
reworks list move to column to table.
> gui/about dialog: Add first supporter.

- vita3k/modules/SceGxm/SceGxm.cpp
helps with https://github.com/Vita3K/compatibility/issues/1023
> modules/gxm: Add a check for nullptr on execute command list

- vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
thanks macdu for help :pray: 
on linux systems tm has 2 more members, which when sending it to mktime or any other time function it sets them to 0, causing a stack corruption cause those members aren't actually there in real hardware.
> modules/processmgr: Replace uses of os tm to defined vita tm

- lang/ru.xml
Translation improved, added more lines
> lang: Russian translation 

- vita3k/kernel/src/sync_primitives.cpp
Implement the SCE_KERNEL_MSG_PIPE_MODE_DONT_WAIT flag.
This allows audio to work in Trails Evolution games.
> kernel: Implement DONT_WAIT flag for msg pipes

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- gui/manual: Improve D-pad in slider
- gui/live area: Remove the zoom instructions
- gui/settings dialog: Add lang to main buttons
> gui: Some improve for gui

- vita3k/gui/src/live_area.cpp
> gui/live area/help: fixed crash

- vita3k/app/include/app/functions.h
- vita3k/app/src/app_init.cpp
- vita3k/audio/include/audio/impl/cubeb_audio.h
- vita3k/audio/include/audio/impl/sdl_audio.h
- vita3k/audio/include/audio/state.h
- vita3k/audio/src/audio.cpp
- vita3k/audio/src/impl/cubeb_audio.cpp
- vita3k/audio/src/impl/sdl_audio.cpp
- vita3k/display/src/display.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/interface.cpp
- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/src/kernel.cpp
- vita3k/main.cpp
- Implement pause and resume app when you open live area like one real hw
https://user-images.githubusercontent.com/5261759/236638040-e50b5637-34d0-43f8-bd1c-155576c1d95e.mp4
> vita3k: implement Pause/resume app.

- vita3k/compat/include/compat/state.h
- vita3k/cpu/include/cpu/disasm/functions.h
- vita3k/crypto/include/crypto/hash.h
- vita3k/np/include/np/trophy/trp_parser.h
- vita3k/np/src/trophy/trp_parser.cpp
- vita3k/renderer/include/renderer/shaders.h
explanation: linux compiler update, need merge so building vita3k-git actually builds
> vita3k: Add missing cstdint includes

- vita3k/codec/include/codec/state.h
- vita3k/codec/src/mjpeg.cpp
- vita3k/kernel/include/kernel/state.h
- vita3k/modules/SceJpeg/SceJpegUser.cpp
- modules/SceJpegUser: Implement sceJpegDecodeMJpeg function.
based of @1whatleytay stuf. https://github.com/1whatleytay/Vita3K/commit/1948318f74f289749c887a779632d52564b6658c
- codec/mjpeg: Add support of format AV_PIX_FMT_YUVJ420P.
- kernel: set variable paused_threads_status in private.
- fix display image on boot in BSBAR
- fix dialog image in graviity rush
> modules/SceJpegUser: Implement sceJpegDecodeMJpeg function.

- vita3k/renderer/src/vulkan/renderer.cpp
This should fix the IncompatibleDriver error occuring on Apple devices with MoltenVK.
> renderer/vulkan: Enable portability extension on Apple

- vita3k/mem/src/mem.cpp
Thanks dima-xd for noticing it.
> mem: Fix bug when adding protection

- vita3k/renderer/src/vulkan/context.cpp
- vita3k/renderer/src/vulkan/texture.cpp
> vulkan: Fix nodiscard warnings

- external/CMakeLists.txt
- external/MoltenVK/mvk_config.h
- vita3k/renderer/src/vulkan/renderer.cpp
> external, renderer/vulkan: Enable full swizzle on MoltenVK

- vita3k/kernel/src/sync_primitives.cpp
Fix the way the auto-reset flag works. I thought we only had to clear one bit in common whereas all bits in common needed to be cleared.
This fixes Deception 4 games.
> kernel: Fix simple event auto reset

- lang/ja.xml
- vita3k/gui/src/gui.cpp
- vita3k/interface.cpp
- update japanese
~~PS TV is Vita TV in jpn~~
- fix small about gui
`※` is not in ltn, makes display
> lang: update japanese

- vita3k/gui/src/user_management.cpp
- vita3k/shader/src/translator/special.cpp
- fix text get outside bgoutton in no english language.
because like french some have long string.
- fix texture broken after click on edit user.
> gui/user management: Improve and fix text outside for button.

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/user_management.cpp
- Allow can using avatar with all aspect ratio without deform image.
> gui/user management: Allow using avatar with keep aspect ratio.

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/controllers dialog: Align text in controllers dialog
- lang: a few of lang strings improve
please Mr.@Zangetsu38 and Mr.@bookmist check this PR
> gui/controllers dialog: Align text in controllers dialog

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/user_management.cpp
- vita3k/lang/include/lang/state.h
- gui/user management: Fixed typos.
based on ps4 settings lang
> gui/user management: Fixed typos

- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/main.cpp
- vita3k/modules/SceNpCommon/SceNpCommon.cpp
- vita3k/modules/SceNpManager/SceNpManager.cpp
- vita3k/np/include/np/common.h
- gui/user management: Big Refactor for more close to PS4.
reworks size and position of avatar.
Add box for avatar and user name.
reworks user name position.
limit input to 16 letter.
move menu from string to enum with switch.
> gui/user management: Big Refactor for more close to PS4. 

- vita3k/script/update-windows.bat
- vita3k/script/update-windows: Fix number of current build.
Add 1 sec timeout for fix display begin of batch.
> vita3k/script/update-windows: Fix number of current build.

- vita3k/gui/src/user_management.cpp
> gui: Fix default avatar path on linux

- vita3k/gui/src/settings_dialog.cpp
This commit will fix surface sync since in the previous commit it was broken.
latest
my commit
the visual artifacts only happen on my system so don't worry about those.
> vita3k/gui: fix surface sync

- vita3k/shader/src/translator/alu.cpp
This opcode is used by a few games, including need for speed.
> shader: Implement SUBFLR dual op

- vita3k/config/include/config/config.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/renderer/include/renderer/vulkan/functions.h
- vita3k/renderer/include/renderer/vulkan/state.h
- vita3k/renderer/src/creation.cpp
- vita3k/renderer/src/vulkan/renderer.cpp
- config: Add option of vulkan validation layer.
Allow can disable it for no impact performance of game if sdk is installed.
> config: Add option of vulkan validation layer.

- vita3k/kernel/src/sync_primitives.cpp
Not exactly correct implementation, but a bit better. Fix crash in Sword Art Online -Hollow Fragment-
> kernel/sync_primitives: more accurate implementation of message pipes

- vita3k/CMakeLists.txt
- fix my forget mistake change also this on path.
> vita3k/CMakeLists: fix path of openssl on copy command.

- vita3k/renderer/src/gl/surface_cache.cpp
- Fixed an issue with initializing textures when the width or height of the Surface cache is extented
Clones the contents of the existing texture to the exptented texture if the width or height is extented from the original.
If either width or height is less than it was before, it will simply reassign and initialize the new texture as it was before.
> renderer/gl: Fix issue when Surface cache is extented

- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/gui/src/welcome_dialog.cpp
- gui: Update the firmware website of regions
and another reason is the firmware website (US) is not accessible in China, because it is blocked by the network wall of China
> gui: Update the firmware website of regions

- vita3k/renderer/src/vulkan/surface_cache.cpp
Handle when we read the stride of a surface.
Also remove a TODO comment I implemented a while ago.
This fixes the photos in PhotoKano Kiss.
> renderer/vulkan: Handle when reading a surface with its stride included

- vita3k/renderer/src/vulkan/gxm_to_vulkan.cpp
- renderer/vulkan/gxm to vulkan: Stub fmt U8U3U3U2.
Should fix crash on app using it.
> renderer/vulkan/gxm to vulkan: Stub fmt U8U3U3U2.

- vita3k/gui/src/live_area.cpp
used screenshot from my vita
Result (updated)
> gui/live_area: add browser template

- vita3k/gui/src/user_management.cpp
- gui/user management: Small reworks and improvement.
Remove scroll bar.
automatic scrol in center pos when click on element if is not centered.
> gui/user management: Small reworks and improvement.

- vita3k/modules/SceNet/SceNet.cpp
- vita3k/net/include/net/state.h
- Fix regression on some game when calling this when Control function try look this id inside map
> modules/SceNet: Stub SceNetResolverCreate with fake id.

- vita3k/modules/SceLibKernel/SceLibKernel.cpp
Because why not. And it's used in some games (A-men [PCSB00056]; Assault Army [PCSG90030]; Tokushu Houdoubu [PCSG00087]; ...)
> modules/SceLibKernel: implement sceClibVprintf

- vita3k/gui/src/live_area.cpp
- gui/live area: Some small refactor and improvement.
Add search in navigate by controller/kb.
Fix navigate when press right if have nothing available on it.
Refactor and improve position and size of gate/frames for all style.
Respect aspect ratio for position and size.
- Compare master/pr for respect aspect ration, for keep good position and size
> gui/live area: Some small refactor and improvement.

- vita3k/gui/src/live_area.cpp
This reverts commit 0a3c9d5b2d73d05329507ac97f59049ee74c013f.
This previous PR was approved by ExtremeExploit who did not see the message history on it and that I disagreed with its content. Zangetsu also asked someone else to review this PR knowing I was disagreeing with it.
> Revert "gui/live area: Some small refactor and improvement."

- vita3k/modules/SceGxm/SceGxm.cpp
Implement sceGxmShaderPatcherForceUnregisterProgram.
This allows World of Final Fantasy to boot a bit further and even go ingame if ngs is disabled.
> modules/SceGxm: Implement sceGxmShaderPatcherForceUnregisterProgram

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/compat/src/compat.cpp
- vita3k/gui/src/gui.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- gui/compat: Add lang to info message.
Please Mr.@Zangetsu38 check this PR.
> gui/compat: Add lang to info message.

- vita3k/gui/src/settings_dialog.cpp
>  gui/settings_dialog: fix small (tiny) typo

- vita3k/shader/src/translator/ialu.cpp
This is used by some shader in the overworld of World of Final Fantasy to compute some buffer adresses.
This allows World of Final Fantasy not to crash anymore on the World map with the Vulkan renderer and memory mapping enabled. Moreover, it should fix some graphics (I don't know what).
> shader: Implement repeat for IMAD opcode

- vita3k/gui/src/information_bar.cpp
> gui/information bar: Fix tiny typo of platinum trophy.

- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
🤦  gosh, i have forget push after change commit....
> modules/SceAppMgrUser: Fix slash missing of sceAppMgrWorkDirMount.

- vita3k/io/include/io/functions.h
- vita3k/io/src/io.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- Implment SceIoRename
Tested in both case, rename in same folder, and rename to other folder, is fine.
> modules/SceLibKernel: implement SceIoRename.

- vita3k/config/include/config/config.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
Request by lot user
- Add option in setting dialog for can disable display dialog of compile ;shaders
> gui: Add option to allow disable display compile shaders dialog.

- vita3k/modules/SceAudiodec/SceAudiodecUser.cpp
- Implement some errors in sceAudiodecClearContext
This update fixes Kiss Ato [Vita3K/compatibility#1823] (https://github.com/Vita3K/compatibility/issues/1823) to make it runnable.
Even with this update, Kiss Ato still not fully playable because of sound issues.
> modules/SceAudiodecUser: Implement some errors in ClearContext

- vita3k/modules/SceRegistryMgr/SceRegMgr.cpp
- vita3k/modules/SceRegistryMgr/SceRegMgrForGame.cpp
- vita3k/modules/SceRegistryMgr/SceRegMgrForSDK.cpp
- vita3k/regmgr/include/regmgr/functions.h
- vita3k/regmgr/include/regmgr/state.h
- vita3k/regmgr/include/regmgr/types.h
- vita3k/regmgr/src/regmgr.cpp
- regmgr: Move value from string to vector char.
reworks GetBin
- Stub sceRegMgrGetKeysInfo.
> regmgr: Move value from string to vector char.

- vita3k/main.cpp
> vita3k: Use config pref path for command line commands

- vita3k/regmgr/src/regmgr.cpp
> regmgr: add missing id

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/renderer/include/renderer/vulkan/surface_cache.h
Looks better to me
The higher the version number, the higher position it should be (inversed now) 🤔
> gui: small change for update_history

- vita3k/interface.cpp
> gui: allow circle for confirm in app close dialogue

- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
Allow debug builds to compile again.
> modules/SceThreadmgr: Remove assert

- vita3k/kernel/include/kernel/state.h
- vita3k/kernel/include/kernel/types.h
- vita3k/module/include/module/load_module.h
- vita3k/modules/SceSysmodule/SceSysmodule.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
- Implement sceSysmoduleLoadModuleInternal(WithArg) 
Original commit by @Macdu 
fixed commit after load module reworks by @bookmist 
Some small change by me: Add more module and add list of module success loaded in vector (Like other), for futur implement check internal module is loaded
> kernel, modules: Implement sceSysmoduleLoadModuleInternal(WithArg)

- vita3k/modules/SceGxm/SceGxm.cpp
This is an improved version of a performance fix I did for the Android version.
Basically, a bitmap allocator is really easy to use and support multiple operations but it is often far from efficient.
For gxm command allocations, where we have only one contiguous buffer, the commands have all the same size and are destroyed in the same ordered they are created and one consumer/producer, a simple lock-free data structure is way better and far more efficient for this task.
In my testings, this easily gave a 15-20% speed increase in many games.
Also erase a debug memset I forgot to remove.
> modules/SceGxm: Improve context command allocation performance

- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/perf_overlay.cpp
- vita3k/gui/src/user_management.cpp
- Enlarged buttons for Japanese
- Other small fixes
> gui: small fix for japanese

- vita3k/gui/src/home_screen.cpp
- vita3k/module/include/module/load_module.h
- Add compat color in app filter
> gui/home screen: Add color of compat state in filter.

- lang/en-gb.xml
- lang/en.xml
- lang/ru.xml
- lang/zh-t.xml
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/settings dialog: small typo fix.
- gui/initial setup: small lang strings update.
> gui/settings dialog: small typo fix.

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/ja.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/manual.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/interface.cpp
- vita3k/lang/include/lang/state.h
- gui: Add the IsKeyPressed control to the buttons
- gui/live area: Correct the description in live area help
thx Mr. @Zangetsu38 help me 🙏.
> gui: Add the IsKeyPressed control to the buttons

- vita3k/packages/src/pup.cpp
- Add missing include for fix compile with last Visual Studio 17.7.
> packages/pup: Add missing include algorithm.

- vita3k/gui/src/settings.cpp
- gui/settings: Fix respect aspect ratio.
remove rounding and padding of main window.
> gui/settings: Fix respect aspect ratio.

- vita3k/gui/src/trophy_collection.cpp
- gui/trophy collection: Fix respect aspect ratio.
fix pos of both text for delete trophy.
> gui/trophy collection: Fix respect aspect ratio.

- vita3k/gui/src/content_manager.cpp
- gui/content manager: Fix respect aspect ratio.
fix missing scroll bar in list.
> gui/content manager: Fix respect aspect ratio.

- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy_collection.cpp
- gui/information bar/Notice: Fix Respect aspect ratio.
- gui/(content manager/trophy collection): Fix pos of search.
- gui/themes: Fix size of theme background.
> gui/information bar/Notice: Fix Respect aspect ratio.

- lang/en-gb.xml
- lang/en.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/lang/include/lang/state.h
- gui/lang: Move search to common.
> gui/lang: Move search to common.

- vita3k/gui/src/trophy_collection.cpp
> gui/trophy collection: Fix the missing text.

- vita3k/config/include/config/config.h
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/shader/include/shader/usse_translator_types.h
- config & gui/setting dialogs: Add Option to display system apps.
For can allow disable disable display system apps from the home screen to the main menu bar only.
> config & gui/settings dialog: Add Option to display system apps.

- lang/en-gb.xml
- lang/en.xml
- lang/ja.xml
- lang/ru.xml
- vita3k/gui/src/ime.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/ime: Fix the tiny punctuation and add IsKeyPressed to the buttons.
- gui: Adjust the text length.
The dp and screen ratio on Android devices affect the font size display of the gui, some text are out of the screen range.
please Mr.@Zangetsu38 and Mr.@Macdu check it.
> gui: Some fixes for gui.

- lang/en-gb.xml
- lang/en.xml
- lang/ja.xml
- lang/ru.xml
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/firmware install dialog: improve dialog window.
please Mr. @Zangetsu38 check this pr.
> gui/firmware install dialog: improve dialog window.

- lang/en-gb.xml
- lang/en.xml
- lang/pt-br.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/controllers: Update tiny lang strings.
- lang: Update pt-br translation (based on #2360).
> gui/controllers: Update tiny lang strings.

- vita3k/config/include/config/config.h
- vita3k/ctrl/include/ctrl/functions.h
- vita3k/ctrl/include/ctrl/state.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/interface.cpp
This is the continiuation of https://github.com/Vita3K/Vita3K/pull/2735 (Thanks to @nn9dev ).
The implementation is not great, so I need opinions what can be done better or what can be also added.
> ctrl: Implement controller remapping

- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/lang/include/lang/state.h
It would be useful to be able to select rif file when installing updates.
> gui/pkg_install_dialog: Allow rif license for pkg installation.

- vita3k/modules/SceGxm/SceGxm.cpp
As found out by xerpi, calling multiple times sceGxmReserve*DefaultUniformBuffer should not create multiple buffers but instead always return the same buffer.
This should fix any game calling multiple time sceGxmReserve*DefaultUniformBuffer before a draw.
> modules/SceGxm: Improve accuracy of sceGxmReserve*DefaultUniformBuffer functions

- vita3k/modules/module_parent.cpp
When a function with an unknown NID is encountered, nothing is done, which means the returned value will be the first arg given to the function if it accepts at least one argument (and otherwise kinda random).
It's better to make them return 0, so that it matches the behavior of stubbed functions.
Should remove the need for #2909 (at least while the function behavior (or at least name) is not reversed engineered, or that returning 0 is found out to be not enough)
> modules: Return 0 for unknown NIDs

- lang/en-gb.xml
- lang/en.xml
- lang/ja.xml
- lang/ru.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/lang/include/lang/state.h
- gui/license_install_dialog: Changed work to license.
- lang: Minor update.
> gui/license_install_dialog: Changed work to license.

- lang/en-gb.xml
- lang/en.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/main_menubar.cpp
- vita3k/lang/include/lang/state.h
- gui/main_menubar: Add the exit button.
please Mr. @Zangetsu38 check it.
> gui/main_menubar: Add the exit button.

- README.md
- lang/da.xml
- lang/de.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-t.xml
Using language from PPSSPP https://github.com/hrydgard/ppsspp/tree/master/assets/lang.
> lang: Update xml

- vita3k/renderer/src/vulkan/scene.cpp
MoltenVK 1.2.5 added support for the triangle fan primitive topology, so the workaround we are currently doing is no longer needed.
> renderer/vulkan: Remove triangle fan workaround on Mac

- vita3k/shader/src/translator/texture.cpp
Implement texture projection with a texture viewport, this fixes graphical issues occuring with renderer accuracy set to standard in the game flower.
> shader: Implement texture viewport for texture projection

- CMakeLists.txt
- external/CMakeLists.txt
This changes were inspired by this https://github.com/Vita3K/Vita3K/issues/1418#issuecomment-1267773600 comment
I'm not sure if link time optimization is worth it, but it seems to have no problems.
> cmake: some refactor and set on link time optimization

- vita3k/https/src/https.cpp
- https: Add MD5 checksum verification file using Content-MD5 header.
should fix corrupted file download with checksum integrity before try using it.
> https: Add MD5 checksum verification file using Content-MD5 header.

- vita3k/compat/include/compat/functions.h
- vita3k/compat/src/compat.cpp
- vita3k/gui/src/home_screen.cpp
- compat: Check if app compat db is outdated before load.
Get load compat db more speed without full load db two time when have new update.
fix function name.
> compat: Check if app compat db is outdated before load.

- vita3k/config/include/config/state.h
- vita3k/config/src/config.cpp
- vita3k/main.cpp
Allow firmware files to be installed using the command line (--firmware argument).
I also cleanup up some inconsistencies and bad english for the command line arguments description.
> config, main: Allow firmware files to be installed using the commandline

- vita3k/main.cpp
Defer the pref path check after the config file has been read (up to this point nothing in the preference path should have been read).
This should fix issues where the preference path cannot be created. Also this prevent a useless directory from being created if you don't use it.
I also fixed the firmware installation command to use the correct pref path in this PR.
> main: Defer pref path check

- lang/da.xml
- lang/de.xml
- lang/en-gb.xml
- lang/en.xml
- lang/es.xml
- lang/fi.xml
- lang/fr.xml
- lang/it.xml
- lang/ja.xml
- lang/ko.xml
- lang/nl.xml
- lang/no.xml
- lang/pl.xml
- lang/pt-br.xml
- lang/pt.xml
- lang/ru.xml
- lang/sv.xml
- lang/tr.xml
- lang/zh-s.xml
- lang/zh-t.xml
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/reinstall.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
Add lang strings in time_used of app context menu, fixed the description and small lang strings improve.
> gui/app context menu, lang: Add lang strings in time_used and small refactor.

- vita3k/renderer/src/vulkan/surface_cache.cpp
Fix a memory leak caused by my previous PR.
> renderer/vulkan: Fix memory leak

- vita3k/shader/src/translator/alu.cpp
The result of vcomp was only stored in the first possible component, even when the mask had multiple components.
This fixes the menu of flower
> shader: Fix vcomp with multiple dest components

- vita3k/gui/src/themes.cpp
- vita3k/interface.cpp
- gui: Refactor UI navigation code in interface.
Optimize code by creating lambda to remove duplicate code
> gui: Refactor UI navigation code in interface.

- vita3k/gui/src/app_context_menu.cpp
fixed PR #3017, sorry, my bad.
> gui/app context menu: Fixed the missing open folder or delete shaderlog menuItem.

- vita3k/modules/SceGxm/SceGxm.cpp
Rewrite sceGxmSetUniformDataF so that it is closer to the function on the real hardware.
There are a few things that I didn't understand (in particular why is the offset divided by 3 when the component count is 3 ??), but this should be more accurate.
> modules/SceGxm: Rewrite sceGxmSetUniformDataF

- vita3k/motion/src/motion.cpp
The steam is using SDL 2.24 while Vita3K relies on SDL_GameControllerGetSensorDataWithTimestamp which is only implemented in SDL 2.26. 
As a workaround, detect at runtime the SDL version and only use this function when it is possible.
Should fix #3019
> motion: Workaround for steam deck

- vita3k/modules/SceGxm/SceGxm.cpp
This reverts commit b083094cc3a258a0d3a4d5ab160847fbc8da757a.
It appears I shouldn't trust too much ghidra's generated decompiled code.
> modules/SceGxm: revert "Rewrite sceGxmSetUniformDataF"

- lang/es.xml
I will probably translate more things, but I wanted to open the PR already. You can accept it now if you want, and later I will open another one with more translations, no problem.
Please leave me comments correcting everything, it's my first time doing a PR for a serious repo.
> welcome message translated to spanish

- vita3k/modules/SceJpeg/SceJpegUser.cpp
Improve sceJpegGetOutputInfo, add a lot more warnings and errors when games are doing things which are not implemented.
This is necessary for Gravity Rush not to crash with my next PR (right now when decoding a JPEG, the pitch ends up being an undefined value).
> modules/SceJpeg: Improve Jpeg decoding

- vita3k/renderer/src/texture/replacement.cpp
Fix a typo causing texture dumping not to work anymore.
> renderer/texture: Fix texture dumping

- .github/workflows/c-cpp.yml
@Macdu CI is failing to create release due to file name change.
> ci: fix failing create-release

- vita3k/renderer/src/gl/screen_render.cpp
> shader/ogl: Fix typo between frag and vert

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/main.cpp
Eliminate the need to remove NPXS from folder name as currently
> gui: add welcome_park as a commercial_app

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/ngs/include/ngs/modules/atrac9.h
- vita3k/ngs/include/ngs/modules/player.h
- vita3k/ngs/include/ngs/scheduler.h
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/modules/atrac9.cpp
- vita3k/ngs/src/modules/player.cpp
- vita3k/ngs/src/ngs.cpp
- vita3k/ngs/src/route.cpp
- vita3k/ngs/src/scheduler.cpp
First commit should improve the accuracy of the atrac9 / player ngs modules. In particular, it fixes the audio repeating itself in Disney Epic Mickey 2 / Valhalla Knight 3 / Borderlands 2. It also fixes the softlock in Borderlands 2.
Second commit should hopefully prevent some random ngs crashes.
> Ngs player fix

- lang/user/id.xml
- lang/user/ms.xml
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/src/lang.cpp
- lang: Add two static user languages.
Indonesia and Malaysia.
- Add current language system set.
special credit to @Kitakatarashima both languages translate.
> lang: Add two static user languages.

- vita3k/shader/src/translator/data.cpp
The test condition on conditional moves can be done on u8, floating point but also any signed or unsigned integer, so handle this case.
This fixes validation errors in fifa.
> shader: Improve conditional move with integers

- vita3k/modules/SceGxm/SceGxm.cpp
This is needed in case the command buffer location is mapped/unmapped after the context was created.
This allows FIFA to run while using the page table mode, useful when using renderdoc or on android.
> modules/SceGxm: Use guest pointer for gxm alloc space

- vita3k/gxm/include/gxm/functions.h
- vita3k/gxm/include/gxm/types.h
- vita3k/gxm/src/gxp.cpp
- vita3k/modules/SceGxm/SceGxm.cpp
- vita3k/renderer/include/renderer/state.h
- vita3k/renderer/src/gl/surface_cache.cpp
- vita3k/renderer/src/gl/sync_state.cpp
- vita3k/renderer/src/texture/cache.cpp
- vita3k/renderer/src/vulkan/screen_filters.cpp
- vita3k/renderer/src/vulkan/surface_cache.cpp
- vita3k/shader/include/shader/usse_translator.h
- vita3k/shader/src/gxp_parser.cpp
- vita3k/shader/src/spirv_recompiler.cpp
- vita3k/shader/src/translator/data.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
More consistent code, set enum types if needed, fix warnings and so on.
Fix something that looks like bug in vita3k/shader/src/usse_program_analyzer.cpp
> Some refactoring of gxm

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings_dialog.cpp
It is undefined behavior to compare iterators of two different vectors.
It is undefined behavior to use the content of a variable outside of its living scope.
> gui: fix undefined behavior

- vita3k/shader/src/usse_program_analyzer.cpp
The function get_predicate had some inaccuracies where it was returning the wrong predicate for some opcodes.
This fixes it, this allows the character in Child of Light to be displayed on Nvidia GPUs.
> shader: Improve get_predicate

- .github/labeler.yml
- .github/workflows/labeler.yml
No one is putting any effort into labeling, and this will continue to be the case.
Bots may make mistakes, but it is better than no labels at all.
> .github: Add bot labeler

- lang/user/id.xml
- lang/user/ms.xml
- Indonesia translation by @Kitakatarashima & @darkash .
- Malaysia translation by @Kitakatarashima .
Not me translate, I only fixed the format, please devs review this pr.
> lang: Update Indonesia and Malaysia translations.

- vita3k/modules/SceNgsUser/SceNgs.cpp
- vita3k/modules/SceProcessmgr/SceProcessmgr.cpp
- vita3k/modules/SceProcessmgr/SceProcessmgr.h
- vita3k/ngs/include/ngs/system.h
- vita3k/ngs/src/modules/atrac9.cpp
sceNgsAT9GetSectionDetails's behavior depends on the main module sdk version, moreover it does a few weird things. Modify this function to be more accurate.
> modules/SceNgs: Improve sceNgsAT9GetSectionDetails

- .github/labeler.yml
- .github/workflows/labeler.yml
> .github/labeler: small fixes

- lang/system/ja.xml
Translations added against the settings dialog for Japanese.
> gui/lang: update japanese for settings dialog

- lang/system/da.xml
- lang/system/de.xml
- lang/system/en-gb.xml
- lang/system/en.xml
- lang/system/es.xml
- lang/system/fi.xml
- lang/system/fr.xml
- lang/system/it.xml
- lang/system/ja.xml
- lang/system/ko.xml
- lang/system/nl.xml
- lang/system/no.xml
- lang/system/pl.xml
- lang/system/pt-br.xml
- lang/system/pt.xml
- lang/system/ru.xml
- lang/system/sv.xml
- lang/system/tr.xml
- lang/system/zh-s.xml
- lang/system/zh-t.xml
- lang/user/id.xml
- lang/user/ms.xml
- vita3k/gui/src/content_manager.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- gui/settings_dialog: Update lang strings and adjust debug options.
- gui/content_manager: Fixed small issue about missing addcont (DLC) title. 
- lang: Fixed pl.xml and ms.xml load error.
> gui/settings_dialog: Update lang strings and adjust debug options.

- .github/ISSUE_TEMPLATE/1-bug_report.yml
- .github/ISSUE_TEMPLATE/2-feature_request.yml
- .github/ISSUE_TEMPLATE/3-blank_template.md
- .github/ISSUE_TEMPLATE/config.yml
Created with reference to other emulators.
You can check here https://github.com/nishinji/Vita3K/issues/new/choose.
> .github: Create GItHub issue templates

- vita3k/gui/src/settings_dialog.cpp
> gui: Fix audio parameter

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
> workflows: Update actions

- lang/system/en-gb.xml
- lang/system/en.xml
- vita3k/app/src/app_init.cpp
- vita3k/audio/include/audio/state.h
- vita3k/audio/src/audio.cpp
- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/lang/include/lang/state.h
- vita3k/lang/src/lang.cpp
- Add audio tab & small refactor on settings dialog.
- Remove double init of global volume value.
> gui/settings dialog; Add audio tab & small refactor.

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
- vita3k/lang/src/lang.cpp
- build: fix openssl pre-build path.
- lang: fix typo of audio settings.
> build: fix openssl pre-build path.

- vita3k/modules/SceHttp/SceHttp.cpp
This bug can be seen only on vcpkg build
> modules/SceHttp: fix crash on HLE of creating https connection

- vita3k/gui/src/information_bar.cpp
- implement feature request in #3224
> gui/information bar: Add support of read battery level.

- lang/system/pl.xml
Fully updated Polish localization basing on English xml.
- Added and translated missing strings
- Corrected eventual mistakes
> lang: Improve Polish localization.

- external/CMakeLists.txt
- external/CppCommon/LICENSE
- external/CppCommon/README.md
- external/CppCommon/include/cpu.h
- external/CppCommon/include/environment.h
- external/CppCommon/include/resource.h
- external/CppCommon/source/cpu.cpp
- external/CppCommon/source/environment.cpp
- vita3k/CMakeLists.txt
- vita3k/gui/CMakeLists.txt
- vita3k/gui/src/app_context_menu.cpp
- vita3k/main.cpp
I implemented this based on information from bookmist.
It works on my PC. But Android and Arm are not supported.
Macdu said that is not very useful, but it is useful for state_report (that's why I'm implementing this).
> external: Import CppCommon to detect CPU and OS

- vita3k/vkutil/include/vkutil/vkutil.h
Fix a regression causing the vulkan renderer to crash from #3236 .
Sorry, this one is entirely my bad.
> vkutil: Fix regression

- vita3k/gui/src/live_area.cpp
- gui/live area: Fix transparency of Info bar.
small reworks for separe window to info bar.
> gui/live area: Fix transparency of Info bar.

- vita3k/gui/src/settings_dialog.cpp
- fix one mistake causing imposible enable surface sync in ogl.
> gui/settings dialog: Fix allow using surface sync on ogl.

- vita3k/compat/src/compat.cpp
- Fix issue detected by @nishinji, causing issue count is all time on 0 when update it.
> compat: Fixed issue count discrepancy after update.

- .github/ISSUE_TEMPLATE/2-feature_request.yml
- vita3k/codec/src/player.cpp
- vita3k/gui/src/about_dialog.cpp
- vita3k/gui/src/allocations_dialog.cpp
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/common_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/ime.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/gui/src/main_menubar.cpp
- vita3k/gui/src/settings.cpp
- vita3k/gui/src/themes.cpp
- vita3k/gui/src/trophy_collection.cpp
- vita3k/gui/src/trophy_unlocked.cpp
- vita3k/gui/src/user_management.cpp
- vita3k/gui/src/vita3k_update.cpp
- vita3k/io/include/io/util.h
- vita3k/kernel/src/load_self.cpp
- vita3k/modules/SceCommonDialog/SceCommonDialog.cpp
- vita3k/shader/src/translator/texture.cpp
Take over #2097 and use constexpr for ROMable values
> Minor optimize, code refactor v2

- external/CMakeLists.txt
- vita3k/CMakeLists.txt
- see this night curreent link is dead and no can compile anymore from draft so.
using so last link
> build: fix openssl link with update to 3.3.1.

- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/gui/src/controls_dialog.cpp
- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/initial_setup.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- vita3k/gui/src/private.h
- vita3k/gui/src/settings_dialog.cpp
It's sometimes useful on long translated texts
> gui: wrap tooltips on window border

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- https://github.com/illusion0001/Vita3K/actions/runs/9537608114/job/26286287306
- https://github.com/illusion0001/Vita3K/actions/runs/9537608116/job/26285910768
> CI: skip releases on forks

- vita3k/io/src/io.cpp
- vita3k/modules/module_parent.cpp
Allows Sir Eatsalot to go a bit further on linux, still nothing tho, so its now on par with windows.
Also added vs0 support for finding case sensitive paths
> io/modules: Make modules load the case sensitive file found in fs

- vita3k/config/include/config/config.h
- vita3k/ctrl/include/ctrl/state.h
- vita3k/ctrl/src/ctrl.cpp
- vita3k/gui/src/controllers_dialog.cpp
- vita3k/gui/src/settings_dialog.cpp
- vita3k/interface.cpp
- vita3k/modules/SceDriverUser/SceMotion.cpp
- vita3k/util/src/string_utils.cpp
Changes to improve my personal QoL.
PS5 and PS4 replace special characters with `_`.
I could not test controller part because I do not have a motionless controller.
> Small QoL improvement

- vita3k/gui/src/perf_overlay.cpp
- vita3k/main.cpp
- gui/perf overlay: Refactor calcul window size.
Fix Window size when using scaling.
> gui/perf overlay: Refactor calcul window size.

- lang/system/da.xml
- lang/system/de.xml
- lang/system/en-gb.xml
- lang/system/en.xml
- lang/system/es.xml
- lang/system/fi.xml
- lang/system/fr.xml
- lang/system/it.xml
- lang/system/ja.xml
- lang/system/ko.xml
- lang/system/nl.xml
- lang/system/no.xml
- lang/system/pl.xml
- lang/system/pt-br.xml
- lang/system/pt.xml
- lang/system/ru.xml
- lang/system/sv.xml
- lang/system/tr.xml
- lang/system/zh-s.xml
- lang/system/zh-t.xml
- lang/user/ms.xml
- lang/user/ua.xml
- vita3k/gui/src/vita3k_update.cpp
- vita3k/lang/include/lang/state.h
- vita3k/util/include/util/net_utils.h
- vita3k/util/src/net_utils.cpp
util/net utils: Implement file download resume.
gui/vita3k update: Restore resume download new build.
> util/net utils: Implement file download resume.

- vita3k/gui/src/pkg_install_dialog.cpp
This is useful when installing updates.
> gui/pkg_install_dialog: Allow license files to be automatically selected if it is already exist

- vita3k/gui/src/controllers_dialog.cpp
- gui/controllers dialog: Implement swap for controller ports.
Implement featur request by https://github.com/Vita3K/Vita3K/issues/3244
> gui/controllers dialog: Implement swap for controller ports.

- vita3k/interface.cpp
- interface: Fix load app when module is missing.
> interface: Fix load app when module is missing in auto mode.

- vita3k/modules/SceGxm/SceGxm.cpp
This PR implements improvements and refactoring for the viewport update logic. The main changes are as follows:
1. Modified the logic to prevent viewport updates outside of the Scene.
2. Integrated duplicate viewport update code into a single function, enhancing code readability and maintainability.
These modifications have resolved an issue where certain games would crash due to attempting viewport updates before Scene initialization. (Reference: [Vita3K/compatibility#212](https://github.com/Vita3K/compatibility/issues/212))
> modules/SceGxm: Prevent viewport updates outside of the scene

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/app_context_menu.cpp
- vita3k/gui/src/archive_install_dialog.cpp
- vita3k/gui/src/home_screen.cpp
- vita3k/gui/src/information_bar.cpp
- vita3k/gui/src/pkg_install_dialog.cpp
- gui/information bar: Small refactor of notice.
Switch to select app from open it for go to new app installed.
Add erase app notice for erase notice of app when delete app corresponding.
Refactor both structure for remove double variable.
> gui: Refactor notice handling and app selection. 

- vita3k/gui/src/settings.cpp
- gui/settings: Skip theme list refresh if no recent updates detected.
Split other pr, no relate directly bgm player
> gui/settings: Skip theme list refresh if no recent updates detected.

- vita3k/shader/src/translator/texture.cpp
Fix for an assertion in debug mode.
> vulkan: fix assertion in Instruction::addIdOperand

- vita3k/modules/SceAppMgr/SceSharedFb.cpp
- vita3k/modules/include/modules/library_init_list.inc
- modules/SceSharedFb: Implement few functions.
Add more functions request by vsh and system app.
> modules/SceSharedFb: Implement few functions.

- vita3k/kernel/include/kernel/types.h
- vita3k/kernel/src/thread.cpp
- vita3k/modules/SceKernelThreadMgr/SceThreadmgr.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/modules/SceLibc/SceLibc.cpp
- vita3k/modules/SceNet/SceNet.cpp
also stub ThreadVfpException functions
used mostly for lle libkernel
> kernel: more correct thread local storage emulation

- vita3k/modules/SceDriverUser/SceDisplayUser.cpp
- vita3k/modules/SceGxm/SceGxm.h
- vita3k/modules/SceGxm/SceGxmInternal.cpp
- modules/(SceDisplay&GxmInternal): Stub some function.
Get wave viewer and safe mode working.
used for vsh and any app using paf etc..
> modules/(SceDisplay&GxmInternal): Stub some function.

- vita3k/gui/src/initial_setup.cpp
- vita3k/packages/CMakeLists.txt
- vita3k/packages/include/packages/exfat.h
- vita3k/packages/src/exfat.cpp
- vita3k/packages/src/pup.cpp
- package: Add support installation of Preinstalled firmware. 
Add support of exfat partition for installing it.
- gui/initial setup: Add button for download Preinstalled Firmware.
Get usefull for later with vsh and also with my other pr of bgm support
> package: Add support installation of Preinstalled firmware.

- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.h
- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
About
- modules/SceAppMgr: Stub sceAppMgrMmsMount.
using by shell and system app
> modules/SceAppMgr: Stub sceAppMgrMmsMount.

- vita3k/modules/SceDriverUser/SceErrorUser.cpp
- vita3k/modules/SceError/SceError.h
- modules/SceError: Implement GetExternalString.
used by vsh
> modules/SceError: Implement GetExternalString.

- vita3k/gui/src/app_context_menu.cpp
- Improved code readability.
- Fixed so that the latest update is at the top in the update history.
> gui/app_context_menu: Improvements to update_history

- lang/system/ru.xml
Now it's ready for review. Big thanks to Kane
> lang: better ru translation

- lang/system/en.xml
- vita3k/gui/src/trophy_collection.cpp
- vita3k/lang/include/lang/state.h
Allow the hidden trophy to be displayed.
> gui/trophy_collection: Allow to display hidden trophy

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/home_screen.cpp
- vita3k/interface.cpp
- gui/home screen: refactor App filtered, moving to string.
Is better code more cleaner.
Usefull for my current workis, and more cleaner code
> gui/home screen: refactor App filtered, moving to string.

- .github/workflows/c-cpp.yml
- .github/workflows/codeql-analysis.yml
- CMakePresets.json
- Back linux CI tu using last clang available for fix build.
> .github/workflows: Back linux CI to the last clang

- vita3k/shader/src/translator/texture.cpp
Add support for the lod bias sample instruction.
Supersedes #3486.
Note that I haven't tested it, please do so before approving.
> shader: Add sample lod bias support

- vita3k/modules/SceDriverUser/SceMotion.cpp
- vita3k/motion/include/motion/motion.h
- vita3k/motion/include/motion/state.h
Makes sure we return the same error codes as the console
> motion: Return proper error codes

- vita3k/emuenv/include/emuenv/state.h
- vita3k/emuenv/src/emuenv.cpp
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/gui/src/live_area.cpp
- vita3k/interface.cpp
- vita3k/io/include/io/state.h
- vita3k/main.cpp
- vita3k/modules/SceAppUtil/SceAppUtil.cpp
- vita3k/modules/module_parent.cpp
- vita3k/packages/CMakeLists.txt
- vita3k/packages/include/packages/functions.h
- vita3k/packages/include/packages/license.h
- vita3k/packages/include/packages/sce_types.h
- vita3k/packages/src/license.cpp
- vita3k/packages/src/pkg.cpp
- vita3k/packages/src/pup.cpp
- vita3k/packages/src/sce_utils.cpp
- package: Implement decrypt fself in a fly.
Request by @Princess-of-Sleeping for obligatory things with vsh support
Should help for improve it https://github.com/Vita3K/Vita3K/pull/3432
> package: Implement decrypt fself in a fly.

- .github/workflows/c-cpp.yml
- fix small mistake inside last commit https://github.com/Vita3K/Vita3K/pull/3495 for find artefact build during create release
> ci: fix create release find linux artefact.

- vita3k/gui/src/initial_setup.cpp
- vita3k/main.cpp
Split my other pr for separe Fix aspect ratio of other.
- gui/initial setup: Add two gui setting and little more
Fix size of column of select language.
Save config any time press on next.
Small clean code.
Change bg color
> gui/initial setup: Add two gui setting and little more.

- vita3k/gui/src/firmware_install_dialog.cpp
- vita3k/interface.cpp
- vita3k/packages/include/packages/functions.h
- vita3k/packages/src/pup.cpp
- interface: Adding support of drag and drop pup file.
Request by one user fo bypass issue on native dialog in linux.
> interface: Adding support of drag and drop pup file.

- vita3k/gui/src/initial_setup.cpp
- gui/initial setup: Fix path of serialize config.
should fix issue on linux and in portable mode.
> gui/initial setup: Fix path of serialize config.

- lang/system/sv.xml
- lang: revert some wrong string of sv.
using official translation for it.
- fix get broken by last commit #3517
> lang: revert some wrong string of sv.

- external/CMakeLists.txt
- gen-windows.bat
- external: Fix link to pre-built OpenSSL by updating it to 3.4.
- gen-windows: Set title for generating Vita3K project files.
> external: Fix link to pre-built OpenSSL by updating it to 3.4 and small more.

- vita3k/gui/src/vita3k_update.cpp
- gui/vita3k updater: Refactor and fix get commit descriptions.
Refactored page count calculation for clarity and efficiency.
Improved and fix per-page commit handling to correctly display remaining commits when exceeding 100.
> gui/vita3k updater: Refactor and fix get commit descriptions.

- vita3k/audio/include/audio/state.h
- vita3k/gui/src/license_install_dialog.cpp
- vita3k/ngs/include/ngs/system.h
- vita3k/renderer/src/texture/pvrt-dec.cpp
- vita3k/util/include/util/pool.h
- Use `default` `delete` to define.
- Use `empty` method to check for emptiness.
- Use bool literal to avoid converting integer literal to bool.
> audio/gui/ngs/renderer/util: Optimize some code

- vita3k/interface.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.cpp
- vita3k/modules/SceAppMgr/SceAppMgr.h
- vita3k/modules/SceDriverUser/SceAppMgrUser.cpp
- vita3k/packages/src/sfo.cpp
- modules/SceAppMgr: fix Sfo loading and improve AppParamGetString.
- packages/sfo/get data by id: Set key corresponding id.
- interface: load sfo in boot app.
Fix call of getstring used by adhoc mode in app and on vsh too
> modules/SceAppMgr: fix Sfo loading and improve AppParamGetString.

- vita3k/gui/src/ime.cpp
- gui/ime: Fix respect aspect ratio.
Improve Grab size.
> gui/ime: Fix respect aspect ratio.

- vita3k/modules/SceDisplay/SceDisplay.h
- vita3k/modules/SceVshBridge/SceVshBridge.cpp
- modules/SceVshBridge: Stub vshDisplayRegisterFrameBufCallback.
> modules/SceVshBridge: Stub vshDisplayRegisterFrameBufCallback .

- vita3k/modules/module_parent.cpp
Avoid copying a function object and memory allocation on this process.
I run profiler and this copying use about 4% of whole Vita3K CPU consumption.
> modules/module_parent: optimise HLE calls

- vita3k/modules/SceGxm/SceGxm.cpp
- modules/SceGxm: Add fallback for sceGxmGetPrecomputed*StateSize.
Return default size when computed result is zero.
Some games expect a non-zero return value from sceGxmGetPrecomputed{Fragment,Vertex}StateSize.
This fallback avoids crashes or invalid behavior.
- Get it and maybe more other precomputed game works again.
> modules/SceGxm: Add fallback for sceGxmGetPrecomputed*StateSize.

- vita3k/renderer/src/gl/compile_program.cpp
- vita3k/util/include/util/log.h
- vita3k/util/src/logging.cpp
> util/log.h: Make log_hex available to uint8_t

- vita3k/config/include/config/config.h
- vita3k/config/include/config/state.h
- vita3k/gui/src/settings_dialog.cpp
- vita3k/modules/SceLibKernel/SceLibKernel.cpp
- vita3k/shader/src/usse_program_analyzer.cpp
- shader/usse program analyzer: Implement call stack analysis support.
Some games may require calling functions, implements support for handling these function calls and returns.
Ensuring correct analysis of the shader/USSE programs.
- Add file loading delays options for fix file loading too speed before acces loading screen on silent hills.
- Silent hill get ingame for first time with complet HUD and perfectly playable.
> shader/usse program analyzer: Implement call stack analysis support.

- lang/system/en.xml
- lang/system/zh-s.xml
- lang/user/id.xml
- vita3k/app/src/app_init.cpp
- vita3k/lang/include/lang/state.h
- vita3k/renderer/src/vulkan/screen_filters.cpp
- Fix error in id.xml.
- Replace bitwise "&" used for Boolean with logical "&&".
> lang/app/renderer: Update Simplified Chinese translation

- vita3k/module/src/load_module.cpp
- module/load module: Add SQLITE module in auto-load list.
Reorder the auto list to match the enum order
> module/load module: Add SQLITE module in auto-load list.

- vita3k/gui/include/gui/functions.h
- vita3k/gui/src/gui.cpp
- vita3k/gui/src/manual.cpp
- gui/manual: Refactor, add book mode and scroll animation.
Start
- Book mode like from real hw
> gui/manual: Refactor, add book mode and scroll animation.

- vita3k/modules/SceSysmem/SceSysmem.cpp
- modules/SceSysmem: Handle memory using SFO and pool info.
Fix crash and prevent memory over-commitment in sceKernelGetFreeMemorySize.
Support +29MiB, +77MiB, and +109MiB memory expansion modes via ATTRIBUTE2 in SFO.
Adjust max usable memory (max_user) dynamically based on selected expansion mode.
Account for all memory pools: normal, CDRAM, and phycont, for accurate memory tracking.
Ensure proper scaling and alignment of memory size when memory is limited.
thx to @bookmist for lot information and explain.
- Get playable for first time
- Move from nothing to Intro for first time
> modules/SceSysmem: Handle memory using SFO and pool info.

- vita3k/modules/SceIpmi/SceIpmi.cpp
- vita3k/modules/SceShellSvc/SceShellSvc.cpp
- vita3k/modules/include/modules/module_parent.h
- vita3k/modules/module_parent.cpp
- Stub sceShellSvcGetSvcObj.
request by initialsetup.
> modules/SceShellSvc: Stub sceShellSvcGetSvcObj.

- vita3k/ctrl/src/ctrl.cpp
> ctrl: fix crash on gamepad disconnect when game started
